### ISSUE TITLE
[Feature Request] Tasks & Debts listing

### ISSUE THREAD

**Issue by xJMV** [monicahq/monica#1001]
Create two new pages (like dashboard, contacts, journal) where tasks and debts are listed ordered by contacts.

This way, it is easy to keep tracks of tasks or debts when you can't remember the name of the person attached to a certain task or debt. 

It would also empower users to be more efficient by allowing them to be more efficient. For example, having a single page to review all tasks in one place make less navigation in the portal, make sure you do not forget you assigned something to someone and it should also allows to check a done task right from there. Same for debts.

**Comment by djaiss** [comment]
I agree. This was actually part of the first version of Monica (version that was never made public) 😀

**Comment by djaiss** [comment]
Tasks have also been added #1909 and will be available in the next release.
