### ISSUE TITLE
Possible API issue for some GETs (code sample included)

### ISSUE THREAD

**Issue by mattdp** [monicahq/monica#1008]
Hi Regis, thanks a ton for implementing [the additional tag features via API](https://github.com/monicahq/monica/issues/658)! I'm trying to use that now, and getting some odd behavior—for the following code sample, it's returning correctly for one GET request (test data provider, /tags) but not for others (/contacts, /activities, /contacts/<ID>). I also tried playing with the limit and page parameters in case pagination was required. Is there a possible issue with the API code here? Thanks!

Code sample is Ruby, and has some working and non-working URLs.

```
require 'net/http'
require 'open-uri'
require 'json'

#WORKING!
destination = "https://app.monicahq.com/api/tags"
#destination = "https://jsonplaceholder.typicode.com/posts/1"

#NOT WORKING
#destination = "https://app.monicahq.com/api/tasks"
#destination = "https://app.monicahq.com/api/activities"
#destination = "https://app.monicahq.com/api/contacts"
#destination = "https://app.monicahq.com/api/contacts/"
#destination = "https://app.monicahq.com/api/contacts/<one of my contact ids>"

api_key = "<my api key>"
uri = URI.parse(destination)
request = Net::HTTP::Get.new(uri)
request["Content-Type"] = 'application/json'
request["Authorization"] = "Bearer #{api_key}"

req_options = {
  use_ssl: uri.scheme == "https",
}

response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
  http.request(request)
end

puts response
puts response.body
```

**Comment by djaiss** [comment]
Thanks @mattdp 

I will check this issue in the coming days. I'm really sorry for my silence, but #971  is taking all my time right now.

**Comment by djaiss** [comment]
Do you still have a problem with this @mattdp ?

**Comment by mattdp** [comment]
Hi Regis, I went to revisit this today now that you have nice tag helper methods (thanks!), but my formerly working code isn't authenticating correctly - I'm getting a 302, but it's "Redirecting to https://app.monicahq.com/login". 

Following [documentation from here](https://www.monicahq.com/api/overview), and attempting to simplify matters for troubleshooting, I found I'm getting the same result in a terminal with:

`curl -H "Authorization: Bearer $MONICA_API_KEY" https://app.monicahq.com/api/tags`

It's very possible I'm making a silly mistake here (double-checked variable bound correctly), but could you please verify the auth is working as expected for sharing tokens in the header (not key/secret)?

Thanks @djaiss

**Comment by mattdp** [comment]
This worked, thanks! And unlike before these 

```
#NOT WORKING
#destination = "https://app.monicahq.com/api/tasks"
#destination = "https://app.monicahq.com/api/activities"
#destination = "https://app.monicahq.com/api/contacts"
#destination = "https://app.monicahq.com/api/contacts/"
#destination = "https://app.monicahq.com/api/contacts/<one of my contact ids>"
```

are returning fine. Thanks for the fix!!
