### ISSUE TITLE
Feature Request: Better date formatting

### ISSUE THREAD

**Issue by AdamIsrael** [monicahq/monica#102]
It's not immediately clear, when entering a date, that it's formatted as DD/MM/YYYY.

- Allow the user to choose their default date format, i.e., MM/DD/YYYY or DD MMM YYYY.
- Improve the date input UI to make it more intuitive.

**Comment by errogaht** [comment]
Hello! i can code to switch date format. I need to known - somebody is not make this thing too.
@djaiss Please tell me that i can implement date format. i think this way https://goo.gl/Aoj2FJ may be you can say something about, because im not detailed uderstand all app, may be there is many date formats ind we need more than 1 input for date format

**Comment by Nebucatnetzer** [comment]
It would probably make sense to allow multiple formats.
E.g. MM/DD/YYY, MM.DD.YYYY, YYYY-MM-DD, etc

**Comment by djaiss** [comment]
@errogaht that'd be awesome. It might be tricky because I'm using the default HTML5 datepicker, but if we can find something simple, let's do it!

**Comment by djaiss** [comment]
We've switched away from the default HTML5 datepicker in 1.4.0 for 
* birthdates
* first met date
* deceased date

We'll have to change it for reminders, activities as well.

**Comment by pqhf5kd** [comment]
Taking this a little further, it would be nice to be able to choose between US/EU formats in the 'Account settings', next to 'Currency' and 'Temperature scale'. It's surprisingly frustrating entering dates 'the wrong way'.

**Comment by djaiss** [comment]
This is something we should do indeed.

**Comment by asbiin** [comment]
Date are now right formatted.

**Comment by jacobmulquin** [comment]
Did any changes come of this? I just installed and birthdays are forced in MM/DD/YYYY with no obvious way to modify the format
