### ISSUE TITLE
Relationships should be People entities too

### ISSUE THREAD

**Issue by jbrooksuk** [monicahq/monica#103]
For example, I'm friends with someone and their significant other, so I should be able to existing people together.

Likewise, kids should be a manageable person. Other relationships could include:

- Brother, Sister
- Parent
- Uncle/Auntie
- Grand-parent
- Niece/Nephew

**Comment by adrum** [comment]
Dupe of probably #19, #35, and #41

**Comment by jbrooksuk** [comment]
My search didn't do a good job. Thanks
