### ISSUE TITLE
Adding Contact Information gives bogus link

### ISSUE THREAD

**Issue by fiosmiles** [monicahq/monica#1030]
I added a contact information piece and it automatically added a link to:
https://app.monicahq.com/people/whateverIhadinthecontactinfo

Which doesn't make sense.

**Comment by asbiin** [comment]
I can't reproduce this problem. What is the scenario to reproduce it ?

**Comment by fiosmiles** [comment]
Open a person.
Go to contact information
Click edit
Add Twitter or other
Enter username
Save

See the link generated to the username entered, this refers back to Monica website which doesn't make sense.

**Comment by tullyhansen** [comment]
Same issue here:

1. Add a new Twitter profile to a contact under Contact Information by typing their Twitter handle (`handle`, say).

**Expected**

Twitter handle appears under Contact Information section of sidebar and links to https://twitter.com/handle

**Actual**

Twitter handle appears under Contact Information section of sidebar but links to https://app.monicahq.com/people/handle
