### ISSUE TITLE
Not sure if the instructions are complete for generic installtion

### ISSUE THREAD

**Issue by EricSlusarz** [monicahq/monica#1040]
Tired to install Monica following all the instructions but I come up with a 403 error on the root.

I can get them a basic HTML login form on localhost/public/ but it doesn't go anywhere when the correct credentials are entered. 

Here is the site I installed Monica to: http://vagabondlogic.com

I'm new to programming, PHP, Laravel, etc

**Comment by asbiin** [comment]
Hi.
Is it a problem with apache/nginx installation, or with monica itself ? What instructions did you followed ?

**Comment by asbiin** [comment]
If you can describe more precisely your issue, we can help you, but there is not enough information here to improve generic installation instruction.
