### ISSUE TITLE
CSS bug when using contact images

### ISSUE THREAD

**Issue by HugoGerritsen** [monicahq/monica#1047]
When using contact images, they get squeezed on smaller viewports. Should be an easy CSS fix 👍  

![image](https://user-images.githubusercontent.com/20877292/37864945-b6f8ec20-2f75-11e8-8c53-833008abf2e8.png)

**Comment by djaiss** [comment]
Ouch. Looks bad. I don't have this problem, so I'll have to see why.

**Comment by cruzken** [comment]
It seems that the images want to be responsive to its container regardless of the width css-class its using (in this case `w3`.)

@djaiss I'd like to submit a pr to fix this issue by adding the css-class `mw-none` to avatar images if that's ok?

![monica-avatar-css-mwnone](https://user-images.githubusercontent.com/11887494/39885477-b6129cfc-545a-11e8-9093-d7461908a918.png)

**Comment by tomzx** [comment]
I can't reproduce this issue on master @ commit:a0710ff924241100895ab0ca3a7192760e41a9fa.

@HugoGerritsen Can you still reproduce the issue?

**Comment by asbiin** [comment]
This is fixed now
