### ISSUE TITLE
working nginx configuration

### ISSUE THREAD

**Issue by cmatera** [monicahq/monica#1050]
Would anyone be willing to share a working nginx configuration for monica rather than using apache?

Thanks

**Comment by mbuc** [comment]
I'm also completely unable to get it to work in nginx.  Other laravel apps work just fine.

**Comment by cruisemaniac** [comment]
@cmatera, @mbuc This is mine:

```
$ cat /etc/nginx/sites-enabled/monica.conf
server {
    server_name  monica.flatty.co;

    root         /var/www/monica/public/;
    index        index.php;
    charset      utf-8;

    add_header Strict-Transport-Security max-age=31536000;

    location ^~ /storage {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~* \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include       fastcgi_params;
        fastcgi_pass  unix:/var/run/php/php7.2-fpm.sock;
	include snippets/fastcgi-php.conf;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
   }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/monica.flatty.co/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/monica.flatty.co/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = monica.flatty.co) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen      80;
    server_name  monica.flatty.co;
    return 404; # managed by Certbot


}
```

**Comment by zaroth** [comment]
Here's mine. Monica is hosted via official docker container on port 13001.

```
# vi:syntax=nginx

server {
  listen 80;
  deny all;

  location = /robots.txt {
    allow all;
    alias /var/www/robots-deny.txt;
  }

  # certbot places token files under /.well-known/acme-challenge/ to verify domain and get SSL cert
  location /.well-known/acme-challenge/ {
    root /var/www/certbot/;
    allow all;
    if (!-d "/var/www/certbot/.well-known/acme-challenge") {
      return 403;
    }
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name monica.example.com;

  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

  ssl_certificate /etc/letsencrypt/live/monica.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/monica.example.com/privkey.pem;

  include ssl_params.conf;

  location / {
    proxy_pass  http://127.0.0.1:13001;
    proxy_redirect     off;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;
  }
}
```

**Comment by croulibri** [comment]
Hello,
People using Monica on Yunohost server (https://github.com/YunoHost-Apps/monica_ynh ) have trouble in using the Android App (see https://github.com/monicahq/chandler/issues/239#issuecomment-401910302 )
We believe it could be linked to yunohost nginx configuration.

Have you tried to connect through Android App ?
If yes, does your nginx configuration allow this connection ?

Thanks for your help !

**Comment by croulibri** [comment]
Hello @zaroth and @cruisemaniac !

People using Monica on Yunohost server (https://github.com/YunoHost-Apps/monica_ynh and https://forum.yunohost.org/t/monica-v2-7-1-personal-relationship-manager/3041/50 ) have trouble in using the Android App (see monicahq/chandler#239 (comment) ), we always get the `bad credential` message.
We believe it could be linked to yunohost nginx configuration.

Have you tried to connect through Android App ?
If yes, does your nginx configuration allow this connection ?

Thanks for your help !

**Comment by zaroth** [comment]
@croulibri I wasn't even aware Monica has an android app, will try it when I have a moment, thanks.

**Comment by djaiss** [comment]
The app is extremely, extremely limited right now, and has been for a while.

**Comment by callmesoul** [comment]
I use nginx and copy  them

> 这是我的。Monica通过端口13001上的docker容器托管（来自集线器的官方码头图像）。
> 
> ```
> # vi:syntax=nginx
> 
> server {
>   listen 80;
>   deny all;
> 
>   location = /robots.txt {
>     allow all;
>     alias /var/www/robots-deny.txt;
>   }
> 
>   # certbot places token files under /.well-known/acme-challenge/ to verify domain and get SSL cert
>   location /.well-known/acme-challenge/ {
>     root /var/www/certbot/;
>     allow all;
>     if (!-d "/var/www/certbot/.well-known/acme-challenge") {
>       return 403;
>     }
>   }
> 
>   location / {
>     return 301 https://$host$request_uri;
>   }
> }
> 
> server {
>   listen 443 ssl;
>   server_name monica.example.com;
> 
>   add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
> 
>   ssl_certificate /etc/letsencrypt/live/monica.example.com/fullchain.pem;
>   ssl_certificate_key /etc/letsencrypt/live/monica.example.com/privkey.pem;
> 
>   include ssl_params.conf;
> 
>   location / {
>     proxy_pass  http://127.0.0.1:13001;
>     proxy_redirect     off;
>     proxy_set_header   Host $host;
>     proxy_set_header   X-Real-IP $remote_addr;
>     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header   X-Forwarded-Host $server_name;
>   }
> }
> ```

but monica server not start . how start minica start

**Comment by callmesoul** [comment]
I use nginx and copy  them

> 这是我的。Monica通过端口13001上的docker容器托管（来自集线器的官方码头图像）。
> 
> ```
> # vi:syntax=nginx
> 
> server {
>   listen 80;
>   deny all;
> 
>   location = /robots.txt {
>     allow all;
>     alias /var/www/robots-deny.txt;
>   }
> 
>   # certbot places token files under /.well-known/acme-challenge/ to verify domain and get SSL cert
>   location /.well-known/acme-challenge/ {
>     root /var/www/certbot/;
>     allow all;
>     if (!-d "/var/www/certbot/.well-known/acme-challenge") {
>       return 403;
>     }
>   }
> 
>   location / {
>     return 301 https://$host$request_uri;
>   }
> }
> 
> server {
>   listen 443 ssl;
>   server_name monica.example.com;
> 
>   add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
> 
>   ssl_certificate /etc/letsencrypt/live/monica.example.com/fullchain.pem;
>   ssl_certificate_key /etc/letsencrypt/live/monica.example.com/privkey.pem;
> 
>   include ssl_params.conf;
> 
>   location / {
>     proxy_pass  http://127.0.0.1:13001;
>     proxy_redirect     off;
>     proxy_set_header   Host $host;
>     proxy_set_header   X-Real-IP $remote_addr;
>     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header   X-Forwarded-Host $server_name;
>   }
> }
> ```

but monica server not start . how start minica start?

**Comment by asbiin** [comment]
This is not a Monica issue related, and more a support for ngnix configuration.

**Comment by anmol26s** [comment]
If there an example of the Apache or Nginx configuration? I am not able to fix the dav on Yunohost for Monica. The Dav redirects to the api page.
