### ISSUE TITLE
Add a view of contacts who do not have tags associated with them

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1056]
Feedback from one of our user:

Would you consider adding a "untagged" view of contacts, so we can see the list of contacts we haven't added tags to yet?

**Comment by turtles2** [comment]
@djaiss I propose that we implement this by adding a new method on the Contact class which takes an array of tags or null for none and returns all the users that have all of those tags. This will allow use to clean up the index method on the Contact Controller as well. I am going give this a try.
