### ISSUE TITLE
[Feature Request] Add a "Today" option to the date picker for "How I met X" page

### ISSUE THREAD

**Issue by heliostatic** [monicahq/monica#1059]
I usually add contacts the day I meet them, so it would be great to have "Today" as a shortcut on the "How I met X" screen:
 
<img width="449" alt="screenshot 2018-03-26 08 57 00" src="https://user-images.githubusercontent.com/70898/37907700-d4ebe5de-30d3-11e8-8409-1e218851ad05.png">

**Comment by asbiin** [comment]
Closed by #1256
