### ISSUE TITLE
Turn "phone calls" into generic "chats"

### ISSUE THREAD

**Issue by jonasvp** [monicahq/monica#1062]
I'm not sure if there's a reason but currently "phone calls" seem to have a special status within Monica in order to record chats with people. This doesn't work for me - and I'm sure many others - since I practically never talk over the phone.

I usually IM with people or meet them for coffee for chats. My workaround is obviously that I take a note with that heading but it would be nice to have generic "chats" and a "type" field, where I could write "IM", "Phone call", "Coffee date" or such.

**Comment by DivineOmega** [comment]
I've also got this issue. I mostly talk to people via instant messaging. A simple solution would be to change 'Phone calls' to a more generic term such as 'Conversations'.

**Comment by djaiss** [comment]
Done 😀with the conversation feature in production since 2.7.0.
