### ISSUE TITLE
Make debt currency agnostic

### ISSUE THREAD

**Issue by ssx** [monicahq/monica#108]
It would be better to have the currency amounts be selectable or removed so that dollars are not forced.

**Comment by DRogue1337** [comment]
Would go for selectable. Maybe some people owe you dollars and others some euros. Worst case is, they owe you 5 $ and 3 €. Then you'd need more debt fields. 😄

**Comment by djaiss** [comment]
Yep. Totally agree. I think we should have a currency dropdown in the Settings, and use it everywhere.

The currency should be a dedicated table so we can add more easily in the database.

**Comment by webdistortion** [comment]
I've added a pull request for this here: #188

**Comment by djaiss** [comment]
This is done and pushed to production. Thanks a lot!
