### ISSUE TITLE
Creation of reminder about a birthday shouldn't be automatic

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1081]

**Comment by mattdp** [comment]
I'd love if this came with a way to disable all reminders by default for those of us with a lot of existing birthday data. Thanks for considering!

**Comment by djaiss** [comment]
This is bothering me as well, so this is probably one of the next features I'm going to work on.

**Comment by djaiss** [comment]
This has been done in https://github.com/monicahq/monica/pull/1275

Will be in production soon.
