### ISSUE TITLE
Indicate age at death for deceased people

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1099]
Feedback from user:

For contacts who are deceased, wouldn’t it be better to indicate their age at death versus the age they would be if they were still alive?  As cool as it is to see what they would be, IMHO I think age at death is probably more useful.

**Comment by GjjvdBurg** [comment]
I'm not sure if I should comment here or open a new issue, but I think the age is still calculated wrongly for deceased people when shown in a relationship with another person. For instance, if A is deceased and is in a love relationship with B, then when viewing B it says under love relationship: ``A (x)`` where x is the age they are today. Here's an example where A lived from 1900 - 2000 (so x should be 100):

![screenshot from 2018-10-19 22-00-43](https://user-images.githubusercontent.com/3286696/47243629-88755900-d3ea-11e8-9a6f-34887b2a5897.png)

Based on the merged PR, I think the patch is something like this (untested):

```
diff --git a/resources/views/people/relationship/_relationship.blade.php b/resources/views/people/relationship/_relationship.blade.php
index 7fa9122c..6379158f 100644
--- a/resources/views/people/relationship/_relationship.blade.php
+++ b/resources/views/people/relationship/_relationship.blade.php
@@ -10,10 +10,14 @@
     @endif
 
     {{-- AGE --}}
-    @if ($relationship->ofContact->birthday_special_date_id)
+    @if ($relationship->ofContact->birthday_special_date_id && !($relationship->ofContact->is_dead))
       @if ($relationship->ofContact->birthdate->getAge())
         <span class="{{ htmldir() == 'ltr' ? '' : 'fr' }}">({{ $relationship->ofContact->birthdate->getAge() }})</span>
       @endif
+    @elseif ($relationship->ofContact->is_dead)
+      @if (! is_null($relationship->ofContact->deceasedDate))
+        <span class="{{ htmldir() == 'ltr' ? '' : 'fr' }}">({{ $relationship->ofContact->getAgeAtDeath() }})</span>
+      @endif
     @endif
 
     {{-- ACTIONS: EDIT/DELETE --}}
```

Please let me know if I should open a separate issue/PR for this.
