### ISSUE TITLE
In edit page of personal information, country list is not in alphabetical order

### ISSUE THREAD

**Issue by Kristis** [monicahq/monica#110]
Hi,

As title described it would be nice to have countries in order. Easier to read and found countries. 
Should be an easy fix.

Thanks!

K.

**Comment by grawlinson** [comment]
Also encountering this bug. An alphabetical sort should fix it right up.

**Comment by webdistortion** [comment]
pull request #130 should help sort this out.

**Comment by Nebucatnetzer** [comment]
Yes this seems to be fixed.

**Comment by djaiss** [comment]
This is indeed fixed. Thanks all!
