### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by Ben11loper** [monicahq/monica#1104]
This thing is great, but I noticed versus the primary deployed app, when I pushed my own through Heroku, the marriage/child changed to love interest, family, and other, but when selected, the page does not yield the contents of the add relationship blade. It will just show top/bottom bar with no middle content to add user relationship. 

For example, .../people/21/relationships/new?type=171 will yield nothing. 

Any thoughts here, hopefully I'm not just missing something but I can't seem to find where it's trying to pull the new.blade.php within the relationship folder.

**Comment by Ben11loper** [comment]
This was the current version on Heroku where I was seeing it.

**Comment by asbiin** [comment]
This is not preset anymore
