### ISSUE TITLE
Feature request: Use Markdown in activity comments

### ISSUE THREAD

**Issue by alexwlchan** [monicahq/monica#1109]
I’m using activities as mini-journal entries, because I can attach them to specific people. Then I’m putting in the detail in the comment, which is often quite long – multiple paragraphs or bulleted lists.

Problem is, when I go to view that comment, all the whitespace is lost – it’s collapsed onto a single line, which makes it harder to read.

It would be nice if the comments field either:

* Supported Markdown formatting (or some other markup that’s used in the rest of Monica)
* At least respected line breaks in the original source

**Comment by djaiss** [comment]
Thanks a lot for caring and submitting an issue.

This will be addressed here https://github.com/monicahq/monica/pull/1145 which will be merged before the end of this week.
