### ISSUE TITLE
The "Edit contact information" page hangs Safari

### ISSUE THREAD

**Issue by kstrauser** [monicahq/monica#111]
I added a contact. When I visit their page, then press "Edit contact information", Safari (10.1.1 on macOS 10.12.5 - both the latest versions) hangs indefinitely until I have to force quit it.

**Comment by djaiss** [comment]
This is because of the hugggeeeeeee amount of countries that were present in the dropdown. It is now fixed. Sorry about that.

**Comment by kstrauser** [comment]
Verified fixed. Thanks!
