### ISSUE TITLE
Links to added gifts in "Latest actions" fails.

### ISSUE THREAD

**Issue by kstrauser** [monicahq/monica#113]
I added a gift for a contact. When I see it listed in the "Latest actions" tab on the dashboard, I can't click on the link to view it.

To repeat, I go to: Dashboard > Latest actions > "You added a gift for ..." and get a 404. It links to https://app.monicahq.com/people/[personID]/gifts.

The entry before it, "You added ... as a contact", links to https://app.monicahq.com/people/[personID] and succeeds.

**Comment by djaiss** [comment]
This is fixed and in production. Thanks for the bug report!

**Comment by kstrauser** [comment]
Verified fixed. Thanks!
