### ISSUE TITLE
Wrong "new version available" message just after update

### ISSUE THREAD

**Issue by asbiin** [monicahq/monica#1161]
When upgrading an instance of Monica to the latest version, the current available version should be updated as well:
![image](https://user-images.githubusercontent.com/25419741/38729233-9159ebde-3f12-11e8-8229-ac3abc2b95f2.png)

**Comment by djaiss** [comment]
That's because we need to run `php artisan monica:ping`. We probably can automate this part as well.

**Comment by asbiin** [comment]
Or to be integrated in `monica:update` command!
