### ISSUE TITLE
PHP Syntax Error on 2.0

### ISSUE THREAD

**Issue by doodlemania2** [monicahq/monica#1165]
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /app/cod
e/vendor/symfony/http-kernel/Exception/HttpException.php on line 24

New install and upgrades.

**Comment by turtles2** [comment]
Which PHP version? Can you set APP_DEBUG=true in .env and display the output?

**Comment by djaiss** [comment]
Indeed we need more details. Does this happen during installation? When you load a specific page? Which one?

**Comment by asbiin** [comment]
This error might be due to a wrong php version. We rely on Laravel 5.6 now, which need php >= 7.1

**Comment by doodlemania2** [comment]
Apologies, wasn't sure where to even start - this happens when I start up the app with Apache.ls   The Migrate completed okay. Also getting this error when debug is set to true:

[Mon Apr 16 00:52:44.808212 2018] [:error] [pid 37] [client 172.18.0.1:47966] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[Mon Apr 16 00:52:44.813386 2018] [:error] [pid 37] [client 172.18.0.1:47966] PHP Parse error:  syntax error, unexpected '?' in /app/code/vendor/symfony/http-foundation/
Response.php on line 499

PHP is 7.2

**Comment by asbiin** [comment]
The line on Response.php file of symfony/http-foundation use a nullable type https://wiki.php.net/rfc/nullable_types
It has been introduced in PHP 7.1 http://php.net/manual/en/migration71.new-features.php

Could you check your php version by runing a `phpinfo();` in your instance ?

**Comment by doodlemania2** [comment]
Any thoughts most appreciated! Going to try with 2.0.1 today to see if it magically fixed itself.

**Comment by turtles2** [comment]
May I suggest shutting down apache and running php artisan serve which will start it using PHP at http://localhost:8000. This may or may not work with Monica. I don't have access to my server to test. But if it does we will at least know where the issue is.

**Comment by doodlemania2** [comment]
interesting! i get a render on php artisan serve - this seems to point towards an issue with apache me thinks. Where to start? My site config couldn't be more boring:
<VirtualHost *:8000>
    # The ServerName directive sets the request scheme, hostname and port that
    # the server uses to identify itself. This is used when creating
    # redirection URLs. In the context of virtual hosts, the ServerName
    # specifies what hostname must appear in the request's Host: header to
    # match this virtual host. For the default virtual host (this file) this
    # value is not decisive as it is used as a last resort host regardless.
    # However, you must set it for any further virtual host explicitly.
    #ServerName www.example.com

ServerAdmin webmaster@localhost
    DocumentRoot /app/code/public

    # For most configuration files from conf-available/, which are
    # enabled or disabled at a global level, it is possible to
    # include a line for only one particular virtual host. For example the
    # following line enables the CGI configuration for this host only
    # after it has been globally disabled with "a2disconf".
    #Include conf-available/serve-cgi-bin.conf

<Directory /app/code/public>
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
    </Directory>
</VirtualHost>

Other places to peak? I wonder if my Dockerfile isn't setting up things correctly in Apache (see comment above about 
RUN a2enmod php7.2
RUN a2enmod rewrite

Everything succeeds on run.

**Comment by turtles2** [comment]
I would tend towards your server being the problem per your last post. Per laravel docs try this in apache. 

> Options +FollowSymLinks
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]

**Comment by asbiin** [comment]
Instead of building your own docker image, you can use the pre-built docker image, see:
https://github.com/monicahq/monica/wiki/Installing-Monica-on-Docker#use-docker-compose-to-run-a-pre-built-image

**Comment by doodlemania2** [comment]
@asbiin am working on packaging the app for a most excellent tool called Cloudron so the default Docker image won't work but it has provided tons of useful pointers along the way!

@turtles2  am trying that now - will report back.

**Comment by doodlemania2** [comment]
Very much appreciate the assistance. I've gotten the errors to go away from the PHP side with @turtles2 's suggestion but now just getting a raw 400 error from the server. Debug=true doesn't seem to produce anything as well. Here's my new Apache file. Things in the right spot?

<VirtualHost *:8000>

ServerAdmin webmaster@localhost
    DocumentRoot /app/code/public
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

<Directory /app/code/public>
Options +Indexes +FollowSymLinks
AllowOverride All
Require all granted
    </Directory>
</VirtualHost>
~

**Comment by turtles2** [comment]
May I suggest not install Monica but instead just get laravel to work then
install Monica in it's place? Laravel has allot of resources to help guide
you as I feel it's a config problem not realted to Monica.

**Comment by doodlemania2** [comment]
That's fair - only opened it as an issue as it cropped up in latest builds but didn't in previous. Thanks all for the help!
