### ISSUE TITLE
Setting relationship errors, and breaks both parties profile pages

### ISSUE THREAD

**Issue by mattdp** [monicahq/monica#1169]
On the site, I tried using the new relationships to tie together two people as spouses (the new page loads SO much faster with many contacts, thanks!). 

It errored, and now causes errors when I try to view either of the people's pages as well, which were working before (https://app.monicahq.com/people/h:G1V5ZebQwjBgr6XOzo and https://app.monicahq.com/people/h:L1o2g0W4ynDdrJz7Ye).

Big fan of the new personalization as well, thanks for the great updates.

**Comment by djaiss** [comment]
Thanks a lot for the feedback.

I'll fix this asap.

**Comment by djaiss** [comment]
I understand what happened. There is a problem when you edit a contact (whether it's through a relationship) - sometimes the gender id is not set.

@mattdp which browser are you using?

**Comment by djaiss** [comment]
@mattdp this _should_ be fixed now. Could you try and test? Thanks a lot and sorry for this error.

**Comment by mattdp** [comment]
@djaiss thanks for the quick response! works well now :)

i think because 98% of my contacts are API imports it's very common for them not to have genders set yet.
