### ISSUE TITLE
Add activity that includes multiple people

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#118]
Feedback from the community ([source](https://news.ycombinator.com/reply?id=14507921&goto=item%3Fid%3D14497295%2314507921)):

It would be great if there would be a place to set up a new activity that includes multiple people. So entering a birthday party with 15 people is a bit more practical than it is now. I first thought that's what the journal is about, but it doesn't seem have this feature (yet?). Like it is now, the journal seems not very useful at all to be honest.

**Comment by erdmenchen** [comment]
Just merge the journal and activities.
From a workflow point and usability, I want to create an activity and then decide on (or add) people.
I would not search for a person and enter the details and scroll down for acrivities, just change the journal to a place of activities and let me quickly create a new one and then add people to it.

**Comment by delaaxe** [comment]
+1 for this

**Comment by psteinweber** [comment]
What @erdmenchen says would make things easier indeed. And it would give a true purpose to the journal.

**Comment by djaiss** [comment]
I agree that the current goal of the journal is pointless in its current form.

**Comment by djaiss** [comment]
This will go in production very soon!
