### ISSUE TITLE
Translating genders leads to wrong gender in relationships

### ISSUE THREAD

**Issue by jonasvp** [monicahq/monica#1182]
Thanks for Monica! I recently rediscovered it and it's really helpful.

One thing I ran across: I translated the genders to german ("man" -> "männlich", "woman" -> "weiblich") using the personalization feature in my instance of Monica. However, apparently this leads to all relationships displayed as "male". For instance, my daughters have "son" beside them in the sidebar. My wife has "father" on the side. This is due to [`getLocalizedName()`](https://github.com/monicahq/monica/blob/ae521f52266d194094863c49c534cdc51dec3057/app/RelationshipType.php#L77) testing for the strings "man" or "woman" directly.

I would propose adding an attribute on the custom genders defining which pronoun to use. This attribute should be used in `getLocalizedName()` for deciding which gender to use. I'll be happy to try to create a PR for this (even though I'm not really fluent in PHP, if someone else would like to do it, I'd rather defer).

**Comment by djaiss** [comment]
I can't reproduce the fact that the genders are not the right ones, despite having tried :-/ How can I reproduce the case where genders are wrong?

**Comment by jonasvp** [comment]
I tried to reproduce it and could actually do it from a completely new, blank account:

1. Set browser language to German
2. Sign up to Monica (this creates genders called "Männlich" and "Weiblich" instead of "Male" and "Female")
3. Add a female family connection to a person (daughter, wife)
4. Have the new family connection show up as "Son" or "husband":

![](https://user-images.githubusercontent.com/117138/39686755-3721b0e0-51cb-11e8-8386-754e7b4f2cfa.png)

**Comment by jonasvp** [comment]
PS: I don't think it's a bug, it's a consequence of an earlier design decision interacting with a new feature (configurable genders).

**Comment by djaiss** [comment]
Thanks @jonasvp 
I'm going to fix this.

**Comment by djaiss** [comment]
The entire way of how genders are handled in Monica is crap. Values are hardcoded - why on earth did I do that 😀

I need to change the entire system to make it better.

**Comment by jonasvp** [comment]
I actually don't think this is all that broken - what do you think of my suggestion? Shouldn't be too hard to implement:

> I would propose adding an attribute on the custom genders defining which pronoun to use. This attribute should be used in getLocalizedName() for deciding which gender to use.

**Comment by Skaronator** [comment]
Just run in the same issue (using German language as well). Apparently I've 2 fathers and no mother.

![image](https://user-images.githubusercontent.com/2886913/44084468-12a04db4-9fb7-11e8-849a-80e23f70787d.png)

**Comment by trwnh** [comment]
Perhaps a more generic terminology should be adopted? Instead of "son/daughter", the badge could simply read "child". Instead of "father/mother", the badge could simply read "parent". Alternatively, the relationship itself could be reworked to simply be a freeform entry instead of a dropdown list with 25 different entries... To be honest, having a 25-option list is already too overwhelming if e.g. you wish to disable certain options like "protege" or "secret lover" or "godson".

**Comment by gamesme** [comment]
Replace `strtolower($gender) == 'female'` 
with
 `strtolower($gender) == trans('app.gender_female')
`
in RelationshipType.php

Solved. (if you use default Gender option)

**Comment by LukasRos** [comment]
+1 As someone who uses Monica in German it's also annoying that there are only fathers and sons but no mothers and daughters.

**Comment by asbiin** [comment]
The main issue #1981 will resolve this.
