### ISSUE TITLE
Add an option to confirm email address on signup

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1183]
Europe is launching a new law in May, called GDPR, which is great, but comes with a lot of constraints for anyone having a webservice.

One of the thing we need to do to be compliant is:

_With e-mail double opt-in, a new user first needs to verify their e-mail address before completing the sign-up process._

I've tried to prevent doing this on Monica since the beginning - not because I wanted to collect your email address and do nasty thing with it, but because I wanted people to sign up with fake email addresses if they wanted to.

This law will force us to confirm email addresses on signup.

We will create a new `.env` variable, called `SIGNUP_DOUBLE_OPTIN`, which will default to `TRUE`. On our hosted version, it will be set to true, but you will do whatever you want on your own instance.

Note: to be clear, we do have an email newsletter, but we only contact people who have subscribed manually and specifically to receive this newsletter. The email address used on signup is never used otherwise, other than sending reminder emails.

Changes to do:
- [ ] Create a email confirmation process
- [ ] Keep track of when the user has validated his email address
- [ ] Display this information in the Settings panel under a new section (called `Compliance`)
- [ ] Add a method in the User object, something like `isCompliant`, that will tell if users have confirmed emails and accepted Terms & Privacy. If not, we should block email sending (reminders, notifications,...) automatically. This will be done in https://github.com/monicahq/monica/issues/1184 so you don't have to do it here.

cc @asbiin @Mokto

**Comment by Mokto** [comment]
*With e-mail double opt-in, a new user first needs to verify their e-mail address before completing the sign-up process.*

Don't we have to force the users to confirm their email before accessing their account ?

**Comment by djaiss** [comment]
We don't currently, but we have to from now on.

**Comment by turtles2** [comment]
@djaiss Why reinvent the wheel with this. I found this package [laravel-email-confirmation](https://github.com/bestmomo/laravel-email-confirmation) from my reading it should allow the project to comlpy with GDPR on the email side

**Comment by djaiss** [comment]
@turtles2 thanks! This will be valuable.

**Comment by asbiin** [comment]
OK I'm working on it.
Problem: if a user is logged out, and has registered with a fake email ... it will not be able to validate the email, nor to change it, because he will not be able to log in after that.
Any idea ?

**Comment by turtles2** [comment]
Why not allow a user to only log in to change there email? As in if they have not yet confirmed there email and they log in they go to a page that allows them to re-send confirm or change there email?

**Comment by djaiss** [comment]
Here are how we should do. This will work for both new users and existing ones.
- We should add a `email_confirmed` boolean to User object that defaults to false
- User signs up or signs in
- User clicks on OK button
- The next page depends on the state of the user:
  - If new user:
    - display "We've sent you an email" screen - this can't be bypassed
    - send email
    - click on email, display dashboard with a success message at the top "Thanks for confirming your account"
    - set `email_confirmed` to true
  - If existing user:
    - when user signs in, check `email_confirmed` value.
    - if false: display "We've sent you an email" screen - this can't be bypassed
    - then do the same as above


Other things to consider:
- reminders and notifications should not be sent if email is not confirmed
