### ISSUE TITLE
Terms and privacy opt-in

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1184]
Europe is launching a new law in May, called GDPR, which is great, but comes with a lot of constraints for anyone having a webservice.

With GDRP, it is now required to actively opt-in to the terms and privacy when signing up. So something like: "By clicking the button above you'll agree to our TOC" is no longer allowed. ([source](https://blog.fortrabbit.com/fortrabbit-is-gdpr-ready))

We need to make those ones opt-in, and also keep a trace of 

- when users have accepted those terms of conditions and privacy policy
- which versions of the privacy policy users have accepted
- keep the IP address of the user who accepts those policies

It's a lot of work, but we don't have the choice :-(

- [ ] Add a method in the User object, something like `isCompliant`, that will tell if users have confirmed emails and accepted Terms & Privacy. If not, we should block email sending (reminders, notifications,...) automatically.
- [ ] Add an `env` variable, `ENABLE_GDPR_COMPLIANCE` that defaults to `TRUE`.

cc @asbiin

**Comment by Mokto** [comment]
This is needed for the /oauth/signup route on the API too, right ?

**Comment by djaiss** [comment]
That's an excellent point actually. For sure, yes (unfortunately). We'll have to manage the case.

**Comment by djaiss** [comment]
Done
