### ISSUE TITLE
Missing foreign keys on many tables

### ISSUE THREAD

**Issue by tomzx** [monicahq/monica#1198]
I was taking a look at the source code and noticed that many tables appear to be missing their foreign keys. Is there any particular reason for this omission?

I also have noticed that most of the columns that would be used as foreign keys are integer and not unsigned integer, which currently makes it not possible to create a foreign key between said columns and the likely unsigned int primary key of the table they relate to.

I've started working on something to address both of these things, but I'd like to see if such change would have a larger impact.

Thanks!

**Comment by djaiss** [comment]
Indeed, there are no foreign keys, almost none actually.
This was made because I wasn't sure how good the compatiblity with Postgrsql or sqlite with this feature would be
The work to address this is.... gigantic to say the least. If you can do it, and make it work, that'd be some feat.

**Comment by tomzx** [comment]
Alright, so I've got foreign keys working.

There's about 40 broken tests that will need to be fixed after I've done an initial fix to the `AccountTest` class (see https://travis-ci.org/TomzxForks/monica/jobs/369859640).

**Comment by asbiin** [comment]
@tomzx That's a great idea! You may want to create a PR for that?
BTW, we have switched to CircleCI recently ;)

**Comment by djaiss** [comment]
I've read that foreign keys, by default, do not work well with SQLite.
We need to see if we want to support SQLite or not.

**Comment by tomzx** [comment]
@djaiss I believe FKs in SQLite work just fine. However they are not enabled by default, see: https://www.sqlite.org/foreignkeys.html#fk_enable.

@asbiin Will do as soon as I'm done fixing the tests! Should be soon given there's 2 errors and 2 failures left to fix (see https://travis-ci.org/TomzxForks/monica/jobs/369933164).

**Comment by asbiin** [comment]
This is now fixed
