### ISSUE TITLE
SQL export assumes a "monica" database

### ISSUE THREAD

**Issue by tomzx** [monicahq/monica#1213]
https://github.com/monicahq/monica/blob/a6ac8a8f5fa526f4f903d80a9c3896b670c6f0bd/app/Jobs/ExportAccountAsSQL.php#L86

Seems it would be more appropriate to look for the current connection database (or the environment `DB_DATABASE`).

**Comment by djaiss** [comment]
Ohhh that is a nice catch. Good one.

**Comment by tomzx** [comment]
Apparently there's many more:

https://github.com/monicahq/monica/blob/da73a6e15d9d06702116fdc89d207d417ebef6ff/app/Http/Controllers/SettingsController.php#L107

https://github.com/monicahq/monica/blob/da73a6e15d9d06702116fdc89d207d417ebef6ff/app/Http/Controllers/SettingsController.php#L145

https://github.com/monicahq/monica/blob/da73a6e15d9d06702116fdc89d207d417ebef6ff/app/Http/Controllers/Api/ApiContactController.php#L346

https://github.com/monicahq/monica/blob/da73a6e15d9d06702116fdc89d207d417ebef6ff/app/Contact.php#L1241

**Comment by djaiss** [comment]
Oops.
