### ISSUE TITLE
Is it possible to use the default local mail server?

### ISSUE THREAD

**Issue by Erwyn** [monicahq/monica#1224]
Hello there,

I would like to know if it's possible not to configure an external mail server but use the default direct one? How to do so?

**Comment by turtles2** [comment]
@Erwyn I don't know enough about email to answer your question directly. But I know that Monica is based on Laravel. Which offers many ways to send emails. Read this [doc](https://laravel.com/docs/5.6/mail) to learn about the various ways laravel can send email out of the box. 

@djaiss Correct me if I am wrong. But Monica does use the Laravel Mail feature?

**Comment by Erwyn** [comment]
@turtles2 I'm gonna take a look at this thanks

**Comment by djaiss** [comment]
@turtles2 yes, Monica uses the built-in Mail feature - so you can use https://github.com/monicahq/monica/blob/master/config/mail.php to configure with a variety of providers.

**Comment by djaiss** [comment]
@Erwyn have you succeed?

**Comment by Erwyn** [comment]
Hello Régis,

Sorry haven't got the time to try yet, I'll let you know when I'm on it.

2018-04-30 1:29 GMT+02:00 Régis Freyd <notifications@github.com>:

**Comment by Erwyn** [comment]
So haven't found relevant documentation yet, so I think I'm going to use the Gmail SMTP instead.

**Comment by djaiss** [comment]
I wonder if Gmail will allow it.

**Comment by Erwyn** [comment]
How do you guys do it? you use mailchimp?

**Comment by djaiss** [comment]
[Postmark](https://postmarkapp.com/). Always loved them.

**Comment by cruisemaniac** [comment]
I run my own mail server and just set it up to work with monica. Like its mentioned above in the comments, all you're required to do is to put in the corresponding settings in the `MAIL_` section in the `.env` file.

This really doesnt have anything to do with monica per-se and is more of the laravel standard feature set.
