### ISSUE TITLE
Dashboard tells me to wish deceased grandma a happy birthday

### ISSUE THREAD

**Issue by rickpastoor** [monicahq/monica#1239]
That's too bad, because she passed away. But thanks for letting me know ;)

I like the reminder. Probably something like '[firstname] would have turned [x] on this date.' would work.

![schermafbeelding 2018-04-30 om 13 07 53](https://user-images.githubusercontent.com/149958/39424572-9ad72a24-4c77-11e8-9486-d9a13bd31b33.png)

**Comment by djaiss** [comment]
Ouch :-( That's not good. I'll fix that.

**Comment by ronaldevers** [comment]
Similarly, for deceased people, the contact detail view has "Stay in touch" (next to "Edit tag") at the top-left in the page header. I think for deceased people that should be hidden. As far as I have seen it, I think the rest of the UI makes sense for both living and deceased people.

**Comment by fsmontenegro** [comment]
One more issue with deceased contacts: even though a contact is deceased, the age calculation feature on another contact's relationship link doesn't seem to take that into account. My father passed away at 69, 6 years ago, but when I go to my step-mother's contact page, it lists my father (her ex-husband) as 75.
![image](https://user-images.githubusercontent.com/10501259/71566728-eccc8780-2a87-11ea-9f02-fc75423e99b8.png)
![image](https://user-images.githubusercontent.com/10501259/71566738-fb1aa380-2a87-11ea-94f4-fcd3a7ce02f9.png)
Am I doing something wrong? Still a newbie at using Monica.
