### ISSUE TITLE
Contacts 'sort by last activity' sorts by modification time

### ISSUE THREAD

**Issue by wearpants** [monicahq/monica#1257]
I'd expect this sort order to sort by my last activity (phone call etc), but it seems to sort by the last time the record was modified in any way instead.

**Comment by turtles2** [comment]
@wearpants Can you provide more info. What version are you running? What steps to reproduce. As I have edited an activity and sorted by last date newest to oldest and it worked. I am running 2.10 which is the newest version.  Could this be confusion on what an activity is? As as far as the sorting is concerned it is only the items under Activities on the Contacts Page. 

@djaiss In attempting to reproduce I found the current sorting to be convoluted with multiple sorts being done in different places. I propose that we move all sorting to SortedBy method on the contact class. If you want I can open a separate issue to discus.

**Comment by wearpants** [comment]
Oh, I would have expected a phone call to count for sorting purposes

**Comment by djaiss** [comment]
> Looks like I am the one who implemented this feature. I am not sure what I was thinking. Probably just wanted to get it shipped. If your cool with it I would like to go back and do it right.

😀
Yeah I'm totally ok to refactor it and make it right!

**Comment by turtles2** [comment]
@djaiss I don't believe there is a bug here only confusion on what an Activity is. Per @wearpants 

> Oh, I would have expected a phone call to count for sorting purposes

 if that is the case we should go ahead and close this
