### ISSUE TITLE
Gifts don't show Comments

### ISSUE THREAD

**Issue by QantumEntangled** [monicahq/monica#127]
I've added gifts to a contact, both idea & already-presented, with and without a link, and there's no way to view the comment attached to the gift that I can find. Link from Activity just takes me to the contact, link on the gift takes me to the web-link I added to the gift.

I couldn't find an open or closed issue relevant to this and none of the pull requests or roadmap items seemed to be related. *I am using the https://app.monicahq.com/ hosted version.

**Comment by QantumEntangled** [comment]
Also verified that after adding 4+ gifts the dashboard statistics counter still says `0` gifts.

**Comment by funcoding** [comment]
The issue has been fixed in pull request #186

**Comment by Nebucatnetzer** [comment]
The bug about the counter has been fixed, the one about the gift comment is most likely still present.

**Comment by djaiss** [comment]
This is fixed in production.
