### ISSUE TITLE
Mysql crashes when editing children that aren't contacts

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#1273]
**Describe the bug**
Adding children to one member or a previously-created spousal (Love) relationship does not consistently relate to both members and ultimately causes mysql to crash with exit code 137. 

What I did:
1. Created to contact entries: Ray Anderson and Andrea Anderson, then related the two as spouses. 
2. When into Andrea Anderson's record and decided to add Ray & Andrea's children, in Andrea's record. I did not create Contacts for the children. I entered Christina and Anna, both women, which were properly entered on Andrea's contact. I then went to Ray's contact and observed that while the children's first names appeared, they were indicated as Sons. Edited Christina's entry to daughter successful. When I click to edit Anna's entry Monica crashes and I observe the above exit code in the terminal window.

(Side note, I observe the URL addresses to contact entries are noticeably different with version 2.1.)

**Which version are you using:**
 - Self hosted, version 2.1
 - Hosted version via docker hub

**Additional context**

**Comment by turtles2** [comment]
Weird, I tried to reproduce but they would not show up on Rays. I am running the current master which should be 2.1 as well. 

Side note, that is due to the HashIds I added to prevent info leakage.

**Comment by tomzx** [comment]
Looks like the daughter <-> son issue is known @ #1182.

**Comment by djaiss** [comment]
Two things:
* If you had a couple (a father and a mother), currently, if you add 2 kids to the mother, they won't show up on the father contact sheet. Right now this is not possible. Are you sure you haven't linked them differently?
* I can't reproduce the fact that the genders are not the right ones, despite having tried :-/ How can I reproduce the case where genders are wrong?

**Comment by asbiin** [comment]
I think this is fixed.
