### ISSUE TITLE
Allow multiple contact fields for an individual

### ISSUE THREAD

**Issue by Ductapemaster** [monicahq/monica#128]
Currently the software only allows for a single entry for the contact info fields: phone, email, address, etc.  It would be great if you could enter multiple.  This would also help support #125

**Comment by djaiss** [comment]
You mean, multiple phones, emails, etc...?

**Comment by Ductapemaster** [comment]
Sorry for the late response, but yes that is exactly what I meant!  It would be great if there was one field for each piece of contact info at the start, and then the ability to add an arbitrary number of additional ones if you needed.

**Comment by TheGP** [comment]
Yep, + so we can add own contact points, like Line, Telegram, etc

**Comment by djaiss** [comment]
This is coming in 1.1.0 😄

**Comment by djaiss** [comment]
This is now in production and in the upcoming 1.1 release.
