### ISSUE TITLE
Connection not secure with production enabled

### ISSUE THREAD

**Issue by Svarto** [monicahq/monica#1287]
**Describe the bug**
When connecting to self-hosted Monica, Firefox complains about an unsecure connection even though app_env=production is enabled and SSL is configured through traefik. It says that only some information is unsafe, such as submitting forms or images.

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.
**Which version are you using:**
version 2.1.0

**Additional context**

I have my monica instance behind a reverse proxy, so basically it is monica.personalserver.com > https > traefik reverse proxy > http > monica docker with production app_env enabled.

any ideas how to fix this?

**Comment by danielpieper** [comment]
Unfortunately this is not a .env configuration issue and must be implemented as described in the laravel documentation link above.
