### ISSUE TITLE
Add Birthday reminder when setting birthdate of the contact

### ISSUE THREAD

**Issue by QantumEntangled** [monicahq/monica#129]
I added children to a contact and it auto-generated a reminder for the child's birthday. But there was not reminder created for the contact's birthday.

*There SHOULD be reminders for contact's birthdays.

**Comment by djaiss** [comment]
Interesting. I just forgot to do it. Let's do it. (I've renamed the name of this issue for the clarity).

**Comment by ivangretsky** [comment]
A must have!
Plus would be nice to have a calendar view of upcoming events on the dashboard. Just dreaming)

**Comment by rickpastoor** [comment]
This is a key feature for me! Interestingly, the form promises that it will automatically add a reminder, but indeed it seems to be missing :)

Great project!

**Comment by rickpastoor** [comment]
@djaiss I'd love to see this one added to the roadmap as well, or this copy should be removed:

![schermafbeelding 2017-06-15 om 10 06 01](https://user-images.githubusercontent.com/149958/27171566-4186279c-51b2-11e7-9069-23cf6aa4920e.png)
