### ISSUE TITLE
Contact search dropdown shows non-contacts that link to nowhere

### ISSUE THREAD

**Issue by jonasvp** [monicahq/monica#1299]
**Describe the bug**
When searching for people in the top bar, it shows non-contacts: for instance, children or spouses that haven't been turned into "real" contact entries. When selecting them, I get redirected to the list of contacts, however.

**Expected behaviour**
When selecting a non-contact, I'd like to get redirected to the contact that the non-contact was assigned to.

**Screenshots**
![Dropdown with non-contacts](https://user-images.githubusercontent.com/117138/39802167-a171bdca-536d-11e8-9371-32936d84bc7f.png)

**Which version are you using:**
 - Hosted version on https://app.monicahq.com

**Comment by djaiss** [comment]
Indeed it's a bug that we need to solve and that bothers me as well 😀
