### ISSUE TITLE
Missing requirement: pragmarx/countries-laravel

### ISSUE THREAD

**Issue by kidk** [monicahq/monica#1310]
When I try to run 'php artisan setup:test' I get a missing requirement for 'pragmarx/countries-laravel.

Is this outdated or should I create a pull request for the requirement?

Simple `composer require pragmarx/countries-laravel` works.

**Comment by asbiin** [comment]
Hi!
`pragmarx/countries-laravel` is already required by composer:
https://github.com/monicahq/monica/blob/master/composer.json#L29
A simple `composer install` should have solved your problem here.

**Comment by kidk** [comment]
You are correct. Strange, must have failed the install in the beginning.

Thanks for the response.
