### ISSUE TITLE
Timezone: Can't select Berlin/Bern

### ISSUE THREAD

**Issue by looperhacks** [monicahq/monica#132]
The code concerning the issue can be found here: https://github.com/monicahq/monica/blob/2e6760e7dbcccd5375707ce1b7ce9c099f40f4b7/resources/views/settings/index.blade.php#L85

When updating the timezone to *(UTC+01:00) Berlin* on the settings page, it selects *(UTC+01:00) Bern* after saving. In the code, both Berlin and Bern have the value *Europe/Berlin*.

~~I'd create a PR for that, but I'm not sure that this line is everything that needs to be changed.~~

Also: Why is Paris so far up in the select list?

**Comment by looperhacks** [comment]
There are other problems with the list (wrong values for the select). Some are fixable, like *(UTC-07:00) La Paz* (is currently America/Chihuahua), but other entries don't seem to have an associated timezone, like *(UTC-06:00) Guadalajara* (I can't find an entry in the [list of possible timezones](https://secure.php.net/manual/en/timezones.america.php)).

How should the entries that aren't a valid timezone be handled? Just delete them?

**Comment by DRogue1337** [comment]
stackoverflow.com/questions/1727077/generating-a-drop-down-list-of-timezones-with-php

Maybe use on of the answers there to just generate a list?

**Comment by Nebucatnetzer** [comment]
I've setup monica today and still experience this problem. After I changed the timezone to Bern I got an error.

```
 (1/1) InvalidArgumentException
Unknown or bad timezone (Europe/Bern)
```

**Comment by djaiss** [comment]
This is now fixed. Thanks @Nebucatnetzer
