### ISSUE TITLE
Countries drop down no longer populated after upgrade to 2.1.1

### ISSUE THREAD

**Issue by coodeneko** [monicahq/monica#1336]
After upgrading my personal server to version 2.1.1 from 2.1.0 the countries drop down is no longer populating with data. The /countries is returning with a 404 error.

**Comment by turtles2** [comment]
When upgrading did you run migrations and composer update? As Countries were switched to an external package in 2.1.1 @asbiin Implemented this if what I suggested above does not fix it please post the specific 404 error you are getting along with more info on your setup to help troubleshoot.

**Comment by coodeneko** [comment]
I ran both command as required by https://github.com/monicahq/monica/wiki/Update-your-server during the upgrade.

I am running:
Ubuntu 16.04.4
Nginx 1.14.0
PHP 7.2.5
MySQL 5.7.22
I am running in production mode.

Nginx nor php log no errors. It looks like monica should be generating some sort of log in storage/logs but the folder is empty. I tried switching to the syslog channel but still no errors were being logged anywhere. Also switching from production to local and APP_DEBUG to true continue to produce no logging. If there is anything I am missing for logging please let me know.

Here is the error when viewing a contact.
![error while viewing contact](https://user-images.githubusercontent.com/1547515/40026689-4911e404-5811-11e8-82df-0d653ed72722.jpg)
Going to /countries gives a pretty generalize "Sorry, the page you are looking for could not be found."

**Comment by coodeneko** [comment]
I figured out my problem. The route cache wasn't cleared after the update. Clearing it solved the issue. Thanks for the help @turtles2 and @asbiin.

If anyone else experiences it the command is `php artisan route:clear`.
