### ISSUE TITLE
Contact tags duplicate when filtering contacts.

### ISSUE THREAD

**Issue by austinlg96** [monicahq/monica#1338]
**Describe the bug**
Go to monicahq.com/people.
Click on a tag.
Click on the same tag again.
The tag is now duplicated in the filter instead of A) removed from the filter or B) nothing.
For example it says: "Showing all contacts tagged with: [- Red] [- Red]"
It appears that there is no limit to the number of duplicates and that using other tags has no effect on them.

**Which version are you using:**
Self Host V 2.1.1
Fresh install, performed a git clone and docker build within the last 2 hours.
I have not tried it against the public version.

**Comment by turtles2** [comment]
This is indeed a bug. @djaiss I will get this fixed.
