### ISSUE TITLE
Email reminders are very shouty

### ISSUE THREAD

**Issue by milliams** [monicahq/monica#1339]
When a reminder email is received it looks something like:
```
Hi Matt,

YOU WANTED TO BE REMINDED OF:

Wish Joe happy birthday.

FOR:

Joe Bloggs
```
This comes across as very shouty where simply making these lower-case would help.

Looking at the source this is defined in `monica/public/js/langs/en.json`, `monica/resources/lang/en/mail.php` and `monica/resources/lang/es/mail.php`. I'm not sure why it is repeated in these files but changing the content of `want_reminded_of` to `'You wanted to be reminded of'` and `'for'` to `'for:'` would do the trick.

As far as I can tell, the rest of the messages are not full upper-case so this would perhaps make it more consistent too.

**Comment by djaiss** [comment]
Indeed. I agree. They are ugly and not that useful.
I'd like to have much better reminders and it'll come in the next weeks, I hope. This will also solve this issue.
