### ISSUE TITLE
Do not show deceased people on dashboard & list

### ISSUE THREAD

**Issue by TheGP** [monicahq/monica#1345]
Currently, it shows deceased people right on the dashboard.

I use this feature for people I stop contacting. But if it would be real deceased people, it will remind about them always, which is not good.

So I suggest to remove them in a dashboard at least. And, maybe, from the list of contacts too (could make a small link to show them back, as they like in some sort of archive)

**Comment by djaiss** [comment]
Good idea! you are right.

**Comment by djaiss** [comment]
We should
- remove deceased people from the dashboard

for now.

**Comment by tcmal** [comment]
I'll do this
