### ISSUE TITLE
Error when attempting to generate a personal access token on self-hosted version

### ISSUE THREAD

**Issue by superstrong** [monicahq/monica#1355]
**Describe the bug**
When I attempt to create a personal access token, I am asked to provide a name. After providing a short name ("local"), I receive an error page:

```
Whoops! Something went wrong!
Server Error
```

**Screenshots**
https://dsh.re/f3821

**Which version are you using:**
 - Self-hosted v 2.1.1 on Heroku with ClearDB, free version of everything

**Additional context**
I am able to generate a token with the exact same name ("local") on the hosted version of Monica.

**Comment by djaiss** [comment]
@superstrong this looks like you haven't run `php artisan passport:install` to generate the initial keys.

**Comment by superstrong** [comment]
@djaiss Thanks, I did not see those instructions, they are not included on the Heroku installation page --  it is quite easy to go from zero to Heroku installation without seeing that there is a bunch of other stuff to be done.

**Comment by superstrong** [comment]
I proposed the update here https://github.com/monicahq/monica/issues/1364

**Comment by superstrong** [comment]
Sorry, I spoke too soon, this is still not working.

I am trying to curl locally in order to interact with my self-hosted app. (Specifically, I'm trying to bulk-delete a bunch of contacts that got imported incorrectly.

When I follow the [instructions](https://github.com/monicahq/monica/wiki/Installing-Monica-(Generic)) for installing Monica on your own server, it directs me to run `php artisan passport:install` on the server, which I'm doing in a bash shell on Heroku.

When I run that, it looks like this:
```
~ $ php artisan passport:install
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 42
Client Secret: ########################################
Password grant client created successfully.
Client ID: 52
Client Secret: ########################################
```

What do I do with these secrets? They are nowhere near as long as the personal access token generated by the hosted app, and neither one works as an Authorization header in the API. I get a 500 when attempting any simple call like `GET /contacts/` using it.

Reading the Laravel documentation, it appears I'm supposed to use that as part of building my own OAuth client?

By contrast, I am able to use the API with the hosted app using the personal access token generated by the hosted app.

On a related note, the [API documentation](https://www.monicahq.com/api/overview) itself does not make any reference to using the personal access token, only the OAuth 2 token.

**Comment by anmol26s** [comment]
I have same problem . I want to access mobile app. But I don't know how to do that.

**Comment by rahimnathwani** [comment]
@superstrong I have the same environment setup as you (self-hosted on Heroku).

There seem to be two issues:

1. Generating and saving the Oauth keys with `php artisan passport:install`
2. Knowing what to do with the 'Personal access client secret' and/or the 'Password grant client secret'. In particular, is either of those the OAuth 2 token referenced in the documentation.

I haven't yet looked into the second point, but there is at least one Heroku-specific issue with the first one. When you run that `php artisan passport:install` command, two files are created in `~/storage`. You can see these two files immediately after you run the command. But they don't appear to persist if the dyno is re-spawned.

One potential solution is to store the tokens in environment variables, and re-create the files whenever a dyno is brought up, with a post-install command in `composer.json`. This is described in [this comment](https://github.com/laravel/passport/issues/242#issuecomment-296477065).

I tried following those instructions and [committed a small change to my personal fork](https://github.com/rahimnathwani/monica/commit/fc432f7b12a528dd7b241c802f63e7efab9ffb2b), but after the automated deploy, I started getting 500 errors for any page. So I rolled back.

The heroku logs showed some errors related to  Illuminate Foundation, but I'm not familiar with it and don't know what they mean. For example:
```
PHP Fatal error:  Uncaught ErrorException: file_put_contents(/tmp/build_10173b72becc267db837423b7b408312/storage/framework/views/9e1b8f3c8fac9f2fdc4d2c80c7f806094604e60c.php): failed to open stream: No such file or directory in /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
```

**Comment by rahimnathwani** [comment]
@superstrong After we solve the problem of persisting the OAuth keys, I think we then need to generate personal access tokens from the web UI.

But according to the [Laravel documentation on personal access tokens](https://laravel.com/docs/5.8/passport#personal-access-tokens), [a small change is needed in the code](https://github.com/rahimnathwani/monica/commit/73a796d71e9a7f95e7a8eed9774713b32551c57d).

I think that, if the Oauth keys exist, and we modify the code to Instruct passport to use the personal access client created with `php artisan passport:client --personal`, then we'll be able to create a personal access token in the web UI. (The web UI calls `https://XXX.herokuapp.com/oauth/personal-access-tokens` but that returns an error:

```json
{
    "message": "Key path \"file:///app/storage/oauth-private.key\" does not exist or is not readable"
}
```

**Comment by rahimnathwani** [comment]
I got this working (i.e. on Heroku, I can now go to the Monica web UI and generate personal access tokens, and I can use those tokens to access the API).

Pull request #2629 includes documentation for how to get it to work.

**Comment by asbiin** [comment]
@rahimnathwani Thanks for your help.
Passport has already a way to pass the keys, using the environment variables `PASSPORT_PRIVATE_KEY` and `PASSPORT_PUBLIC_KEY`.
You just need to escape return lines with `\n` to get this works.

**Comment by asbiin** [comment]
Documentation has been updated
