### ISSUE TITLE
Adding debt in Safari on macOS not possible

### ISSUE THREAD

**Issue by marbetschar** [monicahq/monica#1356]
**Describe the bug**
If you want to add a new debt on macOS using Safari, it shows an error message that the form is unsafe and asks is you really want to submit. As soon as you submit the form monica redirects to the dashboard - without adding the debt. Tested in Chrome too - there it works.

**Screenshots**
<img width="1273" alt="bildschirmfoto 2018-05-20 um 20 22 10" src="https://user-images.githubusercontent.com/392542/40282176-96bb31d4-5c6b-11e8-8a70-26e67f31dde6.png">

**Comment by sharx0r** [comment]
I got a similar error when adding activities. I'm running monica in docker behind HAProxy. i have HAProxy working with https and let'sencrypt. While accessing monica via HAProxy and trying to add an activity i get an error 405:

(From the docker container's log:)
> x.x.x.x - - [25/May/2018:20:10:16 +0000] "GET /activities/store/h:bLKlXa8EmqEnyge0p4 HTTP/1.1" 405 20781 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"

I do not get this error when accessing the docker container directly via it's ip + port. At least not in chrome + firefox. Sadly i can not test this in safari at this moment.

I'm pretty sure my error is related to my setup with https and HAProxy with monica serving requests via http. Just thought my information could be helpful in this issue.

**Comment by pqhf5kd** [comment]
I'm unable to recreate this issue.

Tested using the hosted version in Safari 12.0.1 on macOS 10.14.1.

@sharx0r & @marbetschar are you able to retest?
