### ISSUE TITLE
Add description on how to start application

### ISSUE THREAD

**Issue by Ethunxxx** [monicahq/monica#1362]
So far, I'm not very experienced with applications like Monica, but I'm eager to learn and eventually contribute. I followed the [installation steps for Ubuntu](https://github.com/monicahq/monica/wiki/Installing-Monica-on-Ubuntu) and now have everything setup. However, the Wiki page does not say how I can start Monica on my computer. Could this be added somewhere, please?

**Comment by djaiss** [comment]
Indeed we need instructions then on how to configure either Apache or Nginx.

If you are inexperienced I would say to try to install Monica with either [Vagrant](https://github.com/monicahq/monica/wiki/Installing-Monica-on-Vagrant) or [Homestead](https://laravel.com/docs/5.6/homestead), which is a Vagrant box maintained by Laravel. These are the easiest options.

**Comment by privong** [comment]
Coupled with this, it would also be good to more explicitly note in the setup documentation which directories should be readable by which users.

**Comment by CZechBoY** [comment]
There is some Dockerfile, so maybe only needed thing is Docker?

**Comment by privong** [comment]
@CZechBoY It would be nice to have documentation for how to set it up independently, for people who prefer not to use containers.

**Comment by asbiin** [comment]
documentation has been updated.
