### ISSUE TITLE
Is there a SaaS like option for self hosted installs?

### ISSUE THREAD

**Issue by cruisemaniac** [monicahq/monica#1363]
Hi team,

Monica seems to be a wonderful tool. I've looked around and per my understanding there is no SaaS-ified offering of this tool. Only ONE user can store all contacts and details. Any other user added can see the same details.

Is there a way out of this or is this a new feature / in the pipeline ?

**Comment by djaiss** [comment]
@cruisemaniac unfortunately this is not yet possible. Why would you need this kind of feature?

**Comment by cruisemaniac** [comment]
@djaiss Let me repeat what you said - I can have multiple accounts on an instance - This means individual journals, contacts, etc. This is pretty much what I want.

I'm not sure what I missed when going over the few screens that I saw. Can you point me to documentation please?

**Comment by djaiss** [comment]
I don't understand your comment.

You can create an account, then in your account you can invite someone else if you want - in that case, for your account (and yours only), you can have you and the ones you invite access the same data. **The same data**.

If you need individual journals, contacts,  etc... per user, you need as many different accounts as users, which is possible on https://monicahq.com and on your own server if you install Monica yourself.

**Comment by cruisemaniac** [comment]
@djaiss Got this... And just figured it out as well.

I'll close this request.

Thanks!
