### ISSUE TITLE
[Wiki] Add Heroku instructions for creating personal access tokens

### ISSUE THREAD

**Issue by superstrong** [monicahq/monica#1364]
I've proposed changes to the wiki here to help those running on Heroku: https://github.com/superstrong/monica-wiki/commit/6708dfb621400a19eecbf572d50fcd69cefca650

**Comment by djaiss** [comment]
Thanks a lot! I've applied your changes in our wiki! 🎉 😀

**Comment by rasulkireev** [comment]
I don't see those changes in the wiki.
