### ISSUE TITLE
Enable tinker in production mode

### ISSUE THREAD

**Issue by cruisemaniac** [monicahq/monica#1367]
Coming from the rails console mode of working, not finding tinker installed as part of production was a bummer.

Is there a specific reason why this decision was made?

To be able to add / remove accounts / users in prod mode when registration is disabled is hard without tinker IMO.

**Comment by djaiss** [comment]
Because the codebase is originally Laravel 5.2 and it wasn't included at the time, I think.

And this is something we've missed during upgrade. Going to change the title of this issue so we know it's a feature request.
