### ISSUE TITLE
monica:update --force fails with symlink() error

### ISSUE THREAD

**Issue by cruisemaniac** [monicahq/monica#1371]
`monica:update --force` seems to be trying to symlink a storage directory.

Is this a valid error?
```
php artisan monica:update --force
✓ Maintenance mode: on
php artisan down --message=Upgrading Monica v2.1.1 --retry=10

✓ Resetting application cache
php artisan cache:clear

✓ Resetting route cache
php artisan route:cache

✓ Resetting view cache
php artisan view:cache

✓ Performing migrations
php artisan migrate --force=true

✓ Filling the Activity Types table
php artisan db:seed --class=ActivityTypesTableSeeder --force=true

✓ Symlink the storage folder
php artisan storage:link
✓ Maintenance mode: off
php artisan up


In Filesystem.php line 228:

  symlink(): No such file or directory

```

My storage folder is at `/var/www/monica/storage`.

What is the symlink command trying to create a link for

**Comment by asbiin** [comment]
Hi.
This error is due to
- directory rights
- apache configuration
- laravel
- storage move
depending on your case.

It's not related to the project itself.

**Comment by djaiss** [comment]
You can fix this by removing the symbolic link in `public/storage`

**Comment by cruisemaniac** [comment]
@djaiss your idea worked... Thanks!
