### ISSUE TITLE
Email validation form differ

### ISSUE THREAD

**Issue by asbiin** [monicahq/monica#1381]
Validation of email field is not the same on register form and settings form:
[SettingsRequest.php#L29](https://github.com/monicahq/monica/blob/master/app/Http/Requests/SettingsRequest.php#L29)
`'email' => 'required|email|max:2083|unique:users,email,'.$this->id,`
[RegisterController.php#L72](https://github.com/monicahq/monica/blob/master/app/Http/Controllers/Auth/RegisterController.php#L72)
`'email' => 'required|email|max:255|unique:users',`

Wich one is right?

**Comment by djaiss** [comment]
I'm pretty sure SettingsRequest is an error. I'll check this.
