### ISSUE TITLE
Slack workspace for this community

### ISSUE THREAD

**Issue by superstrong** [monicahq/monica#1385]
Having technical discussions via Github comments can be painfully slow and low-resolution.

A Slack workspace where people can, when ready, engage in deeper synchronous discussions can be super productive. Adding [slackin](https://github.com/rauchg/slackin) makes it possible for people to self-invite themselves from a link.

**Comment by djaiss** [comment]
We do have one actually 🙈
But it's only for the core members right now. I'll add Slackin and open the channel for everyone, it's a great idea.

**Comment by tomzx** [comment]
There's technically also https://gitter.im/monicahq/monica, but I believe it's rarely ever used.

**Comment by Mokto** [comment]
@superstrong you can now access our slack via this link https://slack.monicahq.com/.

See you on slack !
