### ISSUE TITLE
Monica asks to confirm email even for instances set to not confirm emails

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1404]
If I don't set `APP_SIGNUP_DOUBLE_OPTIN`, it should default to false.

Therefore, it should not require to confirm email on login.

However, Monica asks to confirm the email even if the env variable is not set.

I think this is because `registered()` (https://github.com/monicahq/monica/blob/master/app/Http/Controllers/Auth/RegisterController.php#L111) is not called anywhere.

**Comment by asbiin** [comment]
Should'nt we just change `true` to `false` in https://github.com/monicahq/monica/blob/master/config/monica.php#L23 ?

**Comment by djaiss** [comment]
@asbiin exactly. Good point. I'll do it tonight.

**Comment by djaiss** [comment]
Oh you already submitted a PR. I'll take a look.
