### ISSUE TITLE
Installing Monica on a remote server - default homepage #249

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#1408]
Hey, just got wind of this project. Been looking for something like this for years!

I've spun up a new droplet on DigitalOcean (Ubuntu 16.04 LTS) and followed the installation instructions closely. When done, I got the "Welcome to monica" prompt, but when I access my server's IP I get the Apache2 Ubuntu Default Page.

Any thoughts why this might happen?

**Comment by djaiss** [comment]
Hi @tomgs 

Do you have an idea of what could be wrong @asbiin ?

**Comment by tomgs** [comment]
Is it possible that I need to change the apache configuration to point to the right place? I installed monica in the root folder of my server, so perhaps I should edit sites-available (put the monica folder there) and sites-enabled (add a new block for the monica app) and see if it works? Will try that now.

**Comment by tomgs** [comment]
Yep, that was it. Followed the instructions [here](https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/) and I can see the Monica sign-up page!

I think this should be stated more clearly inside the ubuntu installation guide. I'll insert that into the repo as well.

**Comment by tomgs** [comment]
Just [updated the repo](https://github.com/tomgs/MonicaWikiUpdates) - let me know if it's OK an we can close this issue. ;)
