### ISSUE TITLE
Allow multiple users in one account

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#142]
So a couple can use the same account, for instance.

**Comment by cedewey** [comment]
I do prisoner solidarity work and I could see Monica being extremely valuable to that work. Prisoner solidarity work is oftentimes done by multiple people and we constantly run up against challenges of communicating with one another how someone is doing, especially if the prison is interfering with correspondence (ie: not letting letters through).

I know that allowing multiple users to relate to a person is a non-trivial enhancement, but it really would be game changing for this work.

**Comment by djaiss** [comment]
@cedewey I would have never thought of using our tool for this use case, but I find it to be a great idea and I'm humbled that this is even possible. We'll work on it.

**Comment by cedewey** [comment]
That's great to hear! It will be a much appreciated enhancement. :)

**Comment by djaiss** [comment]
The first step of implementing this is now in production. You can now have multiple users in the same account.

A second iteration would be to track who has  done what in said account.
