### ISSUE TITLE
New version GDRP requirement breaks login

### ISSUE THREAD

**Issue by Svarto** [monicahq/monica#1422]
**Describe the bug**
I updated to 2.2.0 and try to log in, I get asked to confirm my email address, when clicking on the button I get redirected to a www.mymonica.com/:url which doesn't exist and results in a "page not found error". No email confirmation is sent.

**Screenshots**
self hosted version, just updated to 2.2.0

**Additional context**
I have received email reminder just fine, so the email should be working correctly however somehow the link to send the confirmation email is broken I think....

Hovering over the link "click here" also shows the url as www.mymonica.com/:url...is this intended? Do I need to change something in my .env? I tried to set the POLICY_COMPLIANT=false as I am myself the host and the sole user of the monica, but still get requested to confirm my email and can't login.

**Comment by djaiss** [comment]
@Svarto the patch is already on master, we haven't pushed a new version yet.

In a few hours we'll publish 2.2.1 with the fix.

**Comment by asbiin** [comment]
Indeed, sorry for that. It's already fixed in #1414 and #1416 
The correct url is: /confirmation/resend

**Comment by asbiin** [comment]
Version v2.2.1 fix this
