### ISSUE TITLE
When importing contacts through vCard, also import notes

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1426]

**Comment by ipince** [comment]
I think this is very important (generally, importing _all_ fields in the vCard format, but this is particularly useful).

If you point me in the right direction, I'm happy to implement this.

**Comment by iloveitaly** [comment]
@ipince I'd love this as well. Here's the file that needs to be modified to add this functionality: https://github.com/monicahq/monica/blob/master/app/Services/VCard/ImportVCard.php

Would also be great to export notes in vcards as well.
