### ISSUE TITLE
Indicate in the documentation that a cronjob needs to be setup for local instances

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#143]

**Comment by beajeanm** [comment]
We may also mention systemd timers instead of cron.
We can link to [https://www.euantorano.co.uk/posts/using-laravel-scheduled-tasks-with-systemd-timers/](url) or use it as inspiration.

**Comment by djaiss** [comment]
@beajeanm I'll indicate cron and the community will be able to add more details in the README if needed ;-D

**Comment by djaiss** [comment]
This is done.
