### ISSUE TITLE
Documentation: Edit to the Ubuntu Installation WIki

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#1431]
Hey Guys,

At least on Ubuntu there's a difficulty in determining which php modules composer will need to do its job. I've listed all the packages along with some helpful instructions on how to install Monica on a standalone Ubuntu server on a document, and would be happy to add it to the documentation to ease installation.

I can't see a way to open up a pull request for the wiki - can I just post my addition in a different repo and you'll update from there?

**Comment by tomgs** [comment]
Great, here it is:

https://github.com/tomgs/MonicaWikiUpdates

**Comment by tomgs** [comment]
@djaiss FYI

**Comment by tomgs** [comment]
@asbiin Or should that be you? :)

**Comment by tomgs** [comment]
Saw the docs were moved back, and you've updated everything @djaiss ! Thanks! Closing

**Comment by djaiss** [comment]
Thanks @tomgs
