### ISSUE TITLE
Can't login to default accounts after clean install

### ISSUE THREAD

**Issue by jappareti** [monicahq/monica#1433]
After a fresh install on my local system with Valet, I tried logging into `admin@admin.com` with password `admin`, and I got the error that I need to verify the email address. Not sure how I would go about verifying `admin@admin.com` 🤔 

I have `APP_SIGNUP_DOUBLE_OPTIN=false` set in my `.env.dev`. I registered a user within an email verification and was able to login no problem.

I think it's happening because `confirmed` is seeded with `0` in the `users` table. I ran `UPDATE monica.users SET confirmed=1 WHERE email='admin@admin.com';` in Mysql and I was able to successfully login.

The same issue goes for `blank@blank.com`.

This is probably related to #1374 and #1183

**Comment by asbiin** [comment]
Yes ! you're probably right !
For this feature, I din't use setup:test command, I generally created a new blank user with the UI form. Thus the setup:test was not tested !
I will fix this, unless you want to help us @jappareti ?

**Comment by jappareti** [comment]
Sure I can take look!
