### ISSUE TITLE
Avatar in 'Journal' page links to nowhere

### ISSUE THREAD

**Issue by Dagolin** [monicahq/monica#1438]
**Describe the bug**

![b](https://user-images.githubusercontent.com/15082118/40877259-3abc29fc-66b0-11e8-9097-5295df359be6.gif)

**Comment by turtles2** [comment]
@Dagolin Can you tell me what URL that avatar is trying to take you to? If you can do that can you also provide the URL that the contact would have?

**Comment by Dagolin** [comment]
Turns out that it's just a [typo hash_Id should be hash_id](https://github.com/monicahq/monica/blob/master/resources/assets/js/components/journal/partials/JournalContentActivity.vue#L134) should be.

**Comment by turtles2** [comment]
For reference this is a regression introduced by #777 Thank you for fixing it.
