### ISSUE TITLE
monica does NOT work on Ubuntu 16.04

### ISSUE THREAD

**Issue by kissgyorgy** [monicahq/monica#1439]
**Describe the bug**
The [wiki installation instruction page](https://github.com/monicahq/monica/wiki/Installation-instructions) states that:
> The preferred OS distribution is Ubuntu 16.04

which is not true, because `composer install --no-interaction --no-dev` says that at least PHP 7.1 is needed. Please fix the Wiki page with the correct OS. (I tried with PHP 7.0 with 2.2.1 and it doesn't work.)

**Which version are you using:**
 - Tried to install my own server from v1.6.2 until v2.2.1, neither of them worked.

**Comment by turtles2** [comment]
How does the Ubuntu version affect the PHP version? You can install PHP 7.1 on Ubuntu 16.04 I have done so. You can install any PHP version on Ubuntu 16.04 just google PHP 7.1 install Ubuntu 16.04, I would recommend using PHP 7.2 as that it what most of us run and Monica is tested against. 

@djaiss the WIKI dose have an error in the PHP version you may want to correct.

**Comment by kissgyorgy** [comment]
@turtles2 It also says 
> The preferred OS distribution is Ubuntu 16.04, simply because all the development is made on it and we know it works.

This is very misleading, because when I read something like this, I tend to believe it just to realize it's a lie when I wasted maybe hours...
I can't edit the Wiki.

**Comment by djaiss** [comment]
@turtles2 thanks! We are going to move the documentation back to the code itself. That way the community will be able to edit it more freely.

**Comment by kissgyorgy** [comment]
> We are going to move the documentation back to the code itself. That way the community will be able to edit it more freely.

> I am sorry that you feel that way. Moving forward we will have the docs back in the repo which will help to make them more accurate.

I also think that's the right way to do it! Thanks.

> and finally you can use docker.

Docker worked out fine, thanks. However it has some problems I'm willing to fix if I have more time, but otherwise it's fine.

> I have to say it, too tempting. We also have wasted thousands of hours (literally) creating this project for two years for free.

If at the end something good comes out of it, that's not wasted hours at all.  
Wasting hours is when you *know* it won't work at all and you should not have tried it at the first place because it was a dead end. If nobody did it before that's not wasted work either, because you learned something new.

The point I'm trying to make I obviously like this project, it's a really original and good idea, but you could have spare me a couple of hours if there were no wiki or if it would be updated.

**Comment by tomgs** [comment]
For now, and for future reference until the wiki is fixed, I fixed a few issues with the installation instructions [here](https://github.com/tomgs/MonicaWikiUpdates).

**Comment by djaiss** [comment]
This PR will take care of this.

https://github.com/monicahq/monica/pull/1445
