### ISSUE TITLE
Error while php artisan migrate --force

### ISSUE THREAD

**Issue by anmol26s** [monicahq/monica#1442]
I get error while updating the app: 

 php artisan migrate --force

```
In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: ALTER TABLE `cache` CONVERT
  TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;)


In PDOStatement.php line 143:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes


In PDOStatement.php line 141:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

```

**Comment by djaiss** [comment]
@asbiin seems to be linked to the recent migration we've made for the emojis?

**Comment by asbiin** [comment]
@anmol26s what is your version of mysql ?

**Comment by anmol26s** [comment]
@asbiin 
```
mysql --version
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

```

**Comment by erdmenchen** [comment]
I get the same error when running `php artisan monica:update --force`

**Comment by djaiss** [comment]
Really sorry about that.

This is linked to this file https://github.com/monicahq/monica/blob/master/database/migrations/2018_05_24_203000_convert_mysql_encoding.php

It works on all my environments but obviously breaks yours...

I'd like to simply delete this migration and submit a new release but I need to see if it'd solve your problems:
* Delete this file
* Perhaps you could also delete in the `migrations` table the line `2018_05_24_203000_convert_mysql_encoding` (which should be the last line) - but I think it shouldn't be there if the migrations trigger an error
* Run `php artisan monica:update` again

I hope you've also made a backup of the DB before running migrations - perhaps we should find a way to do that automatically somehow to prevent this kind of things from happening in the future.

**Comment by anmol26s** [comment]
As far as [YunoHost Monica package](https://github.com/YunoHost-Apps/monica_ynh) we will stick to version v2.1.1 till the fix comes.

**Comment by erdmenchen** [comment]
After reverting back all the changes from 
https://github.com/monicahq/monica/commit/643efa1bd60222f48d119f36d94ae90d0c5eea13#diff-8a025ad5d4f4fade612727b1bb0e974f
I was able to run the migration again and update to the latest version.

So deleting the particular migration from this commit and reverting the changes to config/database, fixes this... but this is only a hotfix, this does not fix the root cause I think...

**Comment by gramakri** [comment]
Would be great if there is a link from https://github.com/monicahq/monica/releases/tag/v2.2.1 to this issue (assuming this is the issue that you are warning users about).

**Comment by asbiin** [comment]
Thank you for the report!

To be clear: we do not test Monica on all databases versions. We just can't. Sorry for that.
This migration should works fine on mysql > 5.7.7. For other database system, I cannot garantee it will works (obviously, it's not!).

It will be very usefull if some of you can test the fix from #1466 on `fix/migration-utf8mb4-1442` branch.

**Comment by anmol26s** [comment]
Sorry for the delay.
Fresh installs work. But upgrade from previous version fails.
```
sudo /usr/bin/php7.1 artisan migrate --force

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: ALTER TABLE `cache` CONVERT
  TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;)


In PDOStatement.php line 143:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes


In PDOStatement.php line 141:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

**Comment by asbiin** [comment]
@anmol26s ok now it should works.
I've added a new command called `migrate:collation`, which is called from `monica:update`.
It handles the utf8<->utf8mb4 migration regarding the value of `DB_USE_UTF8MB4` variable.

Hope it will make it!

**Comment by anmol26s** [comment]
This has fixed the issue. Thanks a lot for quick fixed and giving a wonderful app like Monica.
