### ISSUE TITLE
Update .env.example default timezone list

### ISSUE THREAD

**Issue by OmgImAlexis** [monicahq/monica#1446]
Currently the [.env.example](https://github.com/monicahq/monica/blob/ac239bb6e0bf0ba47b8643a144e8db5c7a4f100e/.env.example#L53) points to `resources/views/settings/index.blade.php` for the default language list yet it was removed in [this commit](
https://github.com/monicahq/monica/blame/bb297d0c06b36363d25419aa7c32e191178edc92/resources/views/settings/index.blade.php#L37).

Maybe it could be moved to the wiki?

**Comment by djaiss** [comment]
@OmgImAlexis excellent observation!

Thanks for pointing that out!

**Comment by djaiss** [comment]
Addressed by #1447
