### ISSUE TITLE
monica Index document?

### ISSUE THREAD

**Issue by ManfredWisniewski** [monicahq/monica#1452]
I have successfully installed monica. It finished and says: "You can now register to the first account by opening the application: URL ....

However when I open said URL it presents me with a 403 Forbidden error. There is noch valid index document in the monica directory.  What is the default DirectoryIndex and where can I get it?

Thanks!

**Comment by jatls** [comment]
Are you trying to install in a subdirectory on your server? That's currently not supported and will cause the 403 error. If so, try installing to a subdomain instead, updating your .env APP_URL field accordingly.

**Comment by ManfredWisniewski** [comment]
I installed monica in a subdomain - but I did not figure out the "/public" directory at first. I changed the web root directory of the subdomain to /public and now it works fine. Maybe that should be mentioned in the install docs or checked during the install process? I got everything to work and the installer happily told me to go to https://my.subdomain and check it out so I was pretty confused at first. :)

**Comment by Bibabidu** [comment]
Can you tell me how you fixed the problem please @ManfredWisniewski?

I've created a subdomain and linked it to the folder in which I installed monica. 
I've tried my regular folder for subdomains '/sub/monica' and '/public'.
Both times I got the same error. The APP_URL was said to the subdomain. 
Thanks!

**Comment by 3ruce** [comment]
This one threw me as well... `monica.mydomain.com` threw a 403 but `monica.mydomain.com/public` brought up a login screen...

**Comment by asbiin** [comment]
@3ruce as explain in installation docs, you have to point your root http server to /public subdirectory.
