### ISSUE TITLE
Entire row of contact should be clickable on People page

### ISSUE THREAD

**Issue by jappareti** [monicahq/monica#1458]
On the `/people` page, I think the entire row should be clickable to take you to that contact's page. Right now, only the text of the person's name and their avatar is clickable, which is too small of an area. The row highlights when you hover, so I think it's expected behavior that the entire row should also be clickable. What do you think?

![monica_ _personal_relationship_manager](https://user-images.githubusercontent.com/1170323/41010101-78ba1372-68ea-11e8-9cf9-d4145ba79050.png)

I'm happy to make a PR for this.

**Comment by djaiss** [comment]
Thanks! Good suggestion. Addressed here #1500 :-D
