### ISSUE TITLE
Can not find how to pay

### ISSUE THREAD

**Issue by inerte** [monicahq/monica#1461]
On https://www.monicahq.com/pricing there's a link to https://app.monicahq.com/register but it's just redirecting to https://app.monicahq.com/dashboard

**Comment by djaiss** [comment]
@inerte you have to go to https://app.monicahq.com/settings/subscriptions 😀

**Comment by inerte** [comment]
Thanks @djaiss , now I know where to pay. But the link at https://www.monicahq.com/pricing is still wrong, though :)
