### ISSUE TITLE
Documentation: Setting Up E-Mail For Monica On Ubuntu

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#1472]
Not sure how to go about this, and haven't seen anything on the Wiki.
Can someone give a brief overview of what Monica uses for E-Mail? I've got everything set up and working crisply besides that part.

**Comment by tomgs** [comment]
Sounds like something that should be included in the Wiki. Once I'm done setting it up I'll update the instructions I wrote with that part as well.
Thanks @turtles2 !

**Comment by djaiss** [comment]
Indeed, thanks @turtles2 !

**Comment by tomgs** [comment]
@fmcpherson The link shows nothing....

**Comment by tomgs** [comment]
@turtles2 Following up on this:

1. Opened a terminal attached to my Monica Heroku dyno (via the Heroku web interface).
2. Tried to install/verify `guzzle` using 
3. Got the following error:
```
W
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
~ $ composer require guzzlehttp/guzzle
Using version ^6.3 for guzzlehttp/guzzle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover


In DuskServiceProvider.php line 43:

  It is unsafe to run Dusk in production.


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

**Comment by tomgs** [comment]
Solved in https://github.com/monicahq/monica/issues/2740
