### ISSUE TITLE
Download all contacts as vCards

### ISSUE THREAD

**Issue by leijurv** [monicahq/monica#1483]
Right now I can click `Export as vCard` individually on each contact, I'd like an option in Export data... alongside SQL to be exporting all contacts as vcf files.

**Comment by djaiss** [comment]
@leijurv why would you need this feature?

**Comment by leijurv** [comment]
@djaiss I took an export of my Google Contacts into Monica and went through and fixed all the duplicates and references and photos and etc. I'd now like to import it into my phone and calendar, but I can't without clicking export one at a time.

**Comment by ipince** [comment]
Same here.

Also, I think good import/export capabilities is _very_ important for the product. From the README:
```
Data is the property of the users and they should be able to do whatever they want with it.
```

Users should own their data. I think not being able to export their data in usable formats is a hindrance to this. :)

**Comment by asbiin** [comment]
This feature is covered with Carddav implementation (but carddav has to be actived)
