### ISSUE TITLE
Unable to export as vCard for any contact, internal error

### ISSUE THREAD

**Issue by leijurv** [monicahq/monica#1484]
**Describe the bug**
Clicking `Export as vCard` for any contact causes an error.

**Screenshots**
<img width="1150" alt="screen shot 2018-06-13 at 4 22 58 pm" src="https://user-images.githubusercontent.com/3837873/41388403-7a4ccdea-6f27-11e8-8d31-75725fdbd612.png">

Maybe a dependency is missing from the docker image?

**Which version are you using:**
I'm running the latest docker `monicahq/monicahq`, which is `v2.3.0`.

**Comment by djaiss** [comment]
This specific error is linked to the fact that you are missing Debugbar. You don't need it per se, so put `APP_DEBUG` to false in your .env file and you won't need this facade anymore.

It'd be interesting to see if another kind of error is triggered when you try to export though.

**Comment by leijurv** [comment]
Would it be possible to add Debugbar to the Dockerfile for monicahq/monicahq?

**Comment by djaiss** [comment]
> Would it be possible to add Debugbar to the Dockerfile for monicahq/monicahq?

But disabled by default?

@asbiin what do you think?

**Comment by leijurv** [comment]
Sure, but maybe enabled when `APP_DEBUG` is true? Is that possible?
