### ISSUE TITLE
Typos in the documentation

### ISSUE THREAD

**Issue by tuxiqae** [monicahq/monica#1488]
Hi, I've two typos on "monica/docs/installation/ubuntu.md".

> 1. Clone the repository
> 
> You may install Monica by simply **closing** the repository. In order for this to work with Apache, which is often **pre-pacakged** with many common linux instances (DigitalOcean droplets are one example), you need to clone the repository in a specific folder:

- 'closing' -> 'cloning'
- 'pre-pacakged' -> 'pre-packaged'
![image](https://user-images.githubusercontent.com/39622904/41461706-1d37f152-7099-11e8-8d5f-79a6aaa56834.png)

**Comment by djaiss** [comment]
Thanks! Feel free to submit a pull request to fix those typos 😀
