### ISSUE TITLE
Can't edit birthdate directly, only by clicking calendar

### ISSUE THREAD

**Issue by dosch** [monicahq/monica#1489]
When adding the exact date of someone birthday I want to add the year the person was born in. But the only way is to click through a calendar, which has monthly incremental steps.

If a person is born some years ago, it takes very very long to get to the right year.

![screen shot 2018-06-15 at 20 47 47](https://user-images.githubusercontent.com/5372610/41484505-64b97098-70dd-11e8-9d38-778a51a39f60.png)

**Comment by djaiss** [comment]
Actually you have to click on the year in the calendar to select the year directly. 

I agree though that this is not ideal :-/

**Comment by dosch** [comment]
<img width="377" alt="screen shot 2018-06-20 at 09 01 23" src="https://user-images.githubusercontent.com/5372610/41642418-8aa2bcea-7468-11e8-9ddc-d84cf16325d2.png">

Ah yes, now I see. This is rather unexpected behavior :-)

**Comment by allo-** [comment]
I observed the same, but there are two instances of the date chooser in monica, one works with "dd.mm.yyyy" and the other (this one) has this problem and only works with "yyyy-mm-dd", even when the calendar widget inserts the date in "dd.mm.yyyy" format. So it is probably a setting of the widget, which is different on the two places it is used.

**Comment by asbiin** [comment]
Actually, the date widget has been improved, and the date format is now right, according with the locale of the user:
![image](https://user-images.githubusercontent.com/25419741/44304451-6ca6f580-a35c-11e8-863b-3df53fdcb5ad.png)

It is even possible to enter the date manually.

I propose to close this issue.

**Comment by Flimm** [comment]
@asbiin I didn't realise that the language used configured in the user's account settings affected the format of the date used. That's useful to know.

In that case, I would like there to be a language for users from the UK, so as to be able to get the date format dd/mm/yyyy.

**Comment by Flimm** [comment]
I think there is still an issue with entering dates manually. For instance, if I enter 23/01/1991 (meaning 23 Jan 1991), the date does not get saved properly. No error is shown. I guess the code is expecting mm/dd/yyyy, not dd/mm/yyyy (with the English language), but nothing is shown to the user to indicate that.
