### ISSUE TITLE
Add contact error "First name field is required" blocking even when First name is supplied

### ISSUE THREAD

**Issue by jbwhit** [monicahq/monica#1493]
**Describe the bug**
When adding a son/daughter to an existing contact, an error is thrown that says "The first name field is required." -- Even if a first name is entered. This happened to me several times over several contacts. I reproduce the behavior on a test account with the gif below. 

**Screenshots**

![add-son-daughter-bug](https://user-images.githubusercontent.com/105829/41502625-326b8252-7173-11e8-9a33-c3cdc60a4bb2.gif)

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Comment by apfelmus123** [comment]
I get the same error on the self hosted version after updating to 2.3.0
