### ISSUE TITLE
2.2.1 self-host journal not showing

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#1494]
**Describe the bug**
~Journal is blank~ no entries showing, but smiley face bar is showing - (see screen 1), although my entries are still there (see screen 2). Note - when trying to add a new journal entry, it's not showing, and when clicking the smiley face bar it disappears and won't show on the new refresh (won't even show the "come back tomorrow" message.

**Screenshots**

**Screen 1**
![monica_ _personal_relationship_manager](https://user-images.githubusercontent.com/8835035/41527841-0ce71de6-72f1-11e8-9515-5dc371a9346e.jpg)

**Screen 2**
![tom_ _root_monicaubuntudroplet____ _ssh_ _204x20](https://user-images.githubusercontent.com/8835035/41511510-b6892694-7280-11e8-8109-6252c4c64cfc.jpg)

**Which version are you using:**
 **- A server you maintain yourself (if so, please indicate your current version of Monica) - 2.2.1**

**Additional context**
Note that this only happened after updating to 2.2.1 and setting a cronjob for the `php artisan schedule:run` command to run every minute. [See exact setup in my fork here](https://github.com/tomgs/monica/blob/master/docs/installation/ubuntu.md#5-set-up-cronjob).

**Comment by tomgs** [comment]
Just checked again - same thing:

![monica_ _personal_relationship_manager](https://user-images.githubusercontent.com/8835035/41758643-c2547fc6-75f2-11e8-951a-bf6f0313913d.jpg)

**Comment by djaiss** [comment]
Can you upgrade to 2.3.1 (that just shipped)?
It should be fixed.

**Comment by tomgs** [comment]
I thought it was included in 2.3.0, sorry my bad:)
Will update now and see if it works.

**Comment by jatls** [comment]
I'm still having this bug in 2.3.1
