### ISSUE TITLE
Docker mysql container exits with code 137

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#1498]
I've had a recent spat of the Docker mysql container on my install of monica shutting down with an exist code of 137, which indicates it ran out of memory. I have my instance of monica running on a Lightsail Debian server that has 512 MB of memory, which I would expect to be enough. I have been running top and it appears I've got 435MB used while I have monica up and running with no swap. 

I've rebooted my server, and run updates and so far it appears to be relatively stable. I am curious to learn from others who have their own installs about how large of a server they are using for one user. I've thinking about adding memory limits to the docker-compose.yml to manage this, but at the moment just monitoring. 

For reference, I am seeing this with monica 2.1.1; I have not yet updated to 2.3.0.

**Comment by asbiin** [comment]
Using mysql docker without any issue.
This is not monica related problem.
