### ISSUE TITLE
Can't delete contacts

### ISSUE THREAD

**Issue by shaananc** [monicahq/monica#1502]
**Describe the bug**
Attempting to delete a contact results in the following error using Safari (but not Firefox):

```

(1/1) MethodNotAllowedHttpException
--
in RouteCollection.php line 255
at RouteCollection->methodNotAllowed(array('GET', 'HEAD', 'DELETE'))in RouteCollection.php line 242
at RouteCollection->getRouteForMethods(object(Request), array('GET', 'HEAD', 'DELETE'))in RouteCollection.php line 176

```

Also results in an error warning that this will result in an insecure request on both browsers.

**Which version are you using:**
Monica master branch commit fe083ea00148c17f4622ce35e4e850a6cd5d1773
Using HTTPS.

**Comment by allanlw** [comment]
This is very likely the same issue as described in #1545 that results from an incorrect HTTPS configuration.

**Comment by asbiin** [comment]
This is fixed.
