### ISSUE TITLE
Laravel Cloudflare/HTTPS Support

### ISSUE THREAD

**Issue by shaananc** [monicahq/monica#1503]
**Is your feature request related to a problem? Please describe.**
Currently using flexible HTTPS with Cloudflare, without HTTPS rewriting results in a lot of HTTP links as Laravel does not automatically detect the protocol used by the end user, just what is proxied by Cloudflare.

Additionally, Monica should support an HTTPS configuration out of the box.

**Describe the solution you'd like**
1. A modification of the app to detect use of an HTTPS frontend proxy w/appropriate link rewriting
2. Support natively in the docker image/app for HTTPS

**Comment by allanlw** [comment]
See also #1545.

**Comment by asbiin** [comment]
Just set `APP_TRUSTED_CLOUDFLARE=true` in you `.env` file
