### ISSUE TITLE
Missing BC Math or GMP extension.

### ISSUE THREAD

**Issue by badry-abderrahmane** [monicahq/monica#1505]
**Description of the bug**
After enabling Debug I got this Error: Missing BC Math or GMP extension.

**Versions**
 - Hosting version on http://contacts.hsprint.ma
 - Latest Version of Monica
- Php Version: 7.2

**Additional context**
I have installed all the required exts:
after runing php -m i got:

bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

**Comment by asbiin** [comment]
Indeed, you need bcmath extension.
See https://github.com/monicahq/monica/blob/master/composer.json#L9

**Comment by badry-abderrahmane** [comment]
Still giving me the same error even if i reinstalled the needed extension.

**Comment by asbiin** [comment]
Closing this issue, as you need bcmath or gmp extension.
