### ISSUE TITLE
Dusk causing failure to deploy to Forge

### ISSUE THREAD

**Issue by s0lutions** [monicahq/monica#1524]
**Describe the bug**
When I tried to deploy current code to forge it kept failing. With following error

> @php artisan package:discover

In DuskServiceProvider.php line 43:
                                           
  It is unsafe to run Dusk in production.  

**Which version are you using:**
Setting up on Forge
Version - Latest commit 8fe1740

**Additional context**
I solved by adding this to composer.json. But there is probably a better solution
"extra": {
        "laravel": {
            "dont-discover": [
                "laravel/dusk"
            ]
        }
    }

**Comment by djaiss** [comment]
What is your value in your env. for 
```
APP_ENV=production
APP_DEBUG=false
``` 
?

**Comment by s0lutions** [comment]
It was set to local. 

I think forge creates its own env. file during the deploy process. I could not find clear instruction on how to control this during the deploy.

**Comment by s0lutions** [comment]
Not sure this needs to be solved here just wanted to record it somewhere incase others having same issue deploying to Forge.

**Comment by djaiss** [comment]
Interesting. Thanks @s0lutions . Is this working now?
