### ISSUE TITLE
Global "From" Address is hardcoded

### ISSUE THREAD

**Issue by kstrauser** [monicahq/monica#153]
Right now, all emails are hardcoded in `config/mail.php` to come from

```php
    'from' => ['address' => 'regis@monicahq.com', 'name' => 'Regis from Monica'],
```

This should come from an environment variable that that site owners can specify their own senders. The current value, besides being confusing to people getting reminders from a domain they don't recognize, is likely to be lost to spam filtering. Right now `monicahq.com` has an [SPF record](http://www.openspf.org) that says "all valid email from a sender @monicahq.com originates from these specific IP addresses":

```shell
$ dig +noall +answer -t txt monicahq.com
monicahq.com.		199	IN	TXT	"v=spf1 a mx include:spf.mtasv.net ~all"
$ dig +noall +answer -t txt spf.mtasv.net
spf.mtasv.net.		65757	IN	TXT	"v=spf1 ip4:50.31.156.96/27 ip4:104.245.209.192/26 ~all"
```

A lot of mailservers would see my server claiming to send an email from that domain, say "that mailserver is lying! It must be a spammer!", and cause all sorts of problems.

**Comment by adrum** [comment]
It seems weird that there's a setting for `APP_EMAIL_NEW_USERS_NOTIFICATION` in .env as well. We should probably streamline this.

## Possible Solution

- Add `APP_EMAIL_FROM_NAME` and `APP_EMAIL_FROM_ADDRESS` to `.env` for use in `config/mail.php`
- Deprecate `APP_EMAIL_NEW_USERS_NOTIFICATION`
- Use `APP_EMAIL_NEW_USERS_NOTIFICATION` as a fallback for either of the new .env vars to guarantee backwards compatibility for existing installations. We might might be able to use `Monica` (or something) as the name fallback.
- Use `APP_EMAIL_FROM_ADDRESS` in `app/Jobs/SendNewUserAlert.php` and whatever email jobs could popup in the future

**Comment by kstrauser** [comment]
In #133, @adrum wrote:

> #153 differs from the .env settings APP_EMAIL_NEW_USERS_NOTIFICATION? It seems like these should be one settings, and by possibly adding APP_EMAIL_FROM_NAME?

I think they're different things. The `_NEW_USERS_NOTIFICATION` is a recipient. The proposed `_FROM_NAME` (and/or `_FROM_ADDRESS`) would be a sender.

The difference is that I, an admin, would like to know when people have signed up for my instance. They, as users, should get emails from a daemon, not from my personal email. Or at least it should be my option as an admin to separate those roles.

**Comment by adrum** [comment]
@kstrauser  Ah gotcha. Thank you for clearing that up. Makes sense why I never received an email on signup. I treated `_NEW_USERS_NOTIFICATION` as `_FROM_ADDRESS` during my test run. I was surprised I never received an email as a new user. (This may or may not be a bug. I didn't really go investigating yet.)

**Comment by adrum** [comment]
## Better Possible Solution

- Add `MAIL_FROM_NAME` and `MAIL_FROM_ADDRESS` to `.env` for use in `config/mail.php`

**Comment by adrum** [comment]
I will probably have a PR for this soon..

**Comment by djaiss** [comment]
Yes we need to clean this asap actually.

There is the need to have two email addresses.

1. One is for the email address used to send emails from the application (the reminders, at the moment, are the only emails that the app sends to users).
2. The other is for instance owners: this email address will be used to send notifications of new users to.

There is the need to have two distincts env variables for that.

**Comment by kstrauser** [comment]
Yay, thanks!
