### ISSUE TITLE
Relationships sometimes have wrong gender prefix (like "brother" instead of sister)

### ISSUE THREAD

**Issue by Kaishiyoku** [monicahq/monica#1533]
**Describe the bug**
When I have a contact like my father and add a relationship between me and him, the prefix is *son*. But when I add a relationship between my sister and my father, the prefix is *son*, too. Same issue goes for sister/brother. The gender is wrong although I created my contacts with the right gender.

**Screenshots**
![chrome_2018-07-03_10-38-22](https://user-images.githubusercontent.com/5131112/42208835-7f635368-7ead-11e8-858e-5e33743ce394.png)

**Which version are you using:**
 - Self-hosted, v2.3.1

**Comment by steffen-lorenz** [comment]
+1 also from me

**Comment by jonasvp** [comment]
This is probably related to my bug report in #1182

**Comment by Kaishiyoku** [comment]
@jonasvp yes. I'll close this issue in favor of yours

**Comment by Kaishiyoku** [comment]
duplicate of #1182
