### ISSUE TITLE
Add yourself as a partner or family member

### ISSUE THREAD

**Issue by Dalethium** [monicahq/monica#1542]
I feel like adding a profile for yourself in the same capacity as adding a profile for a friend makes no sense, like "how we met" is kind of a weird question to ask and answer by yourself about yourself. 

Perhaps make a special profile for the "active user" that can be configured via the options panel for the use of relationships and such.

Thanks! Have a great day!

**Comment by ChucklesTheBeard** [comment]
Duplicate of #33

**Comment by djaiss** [comment]
Duplicate indeed.
