### ISSUE TITLE
"How did you meet ..." throws MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by dennis-tra** [monicahq/monica#1545]
Hello there,

first of all thank you for this great project and the work every contributor put into it. Unfortunately I have a problem with my self-hosted Monica setup.

**Describe the bug**
I'm running Monica with Docker on an ubuntu 18.04 server. I followed [these](https://github.com/monicahq/monica/blob/master/docs/installation/docker.md) instructions to set everything up. I added/imported some of my contacts and everything seemed to work fine. 

Now when I try to add the "How did you meet XYZ" information I get the following error:

<img width="1433" alt="monica" src="https://user-images.githubusercontent.com/11836793/42410396-53236e3e-81e9-11e8-8e87-dc2f1fe051dc.png">
This is the route it is trying to access `https://my.server.com/people/h:some-noise/introductions/update`.

I get the same error for trying to add depts and trying to add activities. Basically always when I'm entering information on a separate page from the contact details page.

**Which version are you using:**
I'm using Monica 2.3.1

**Additional context**
When running `docker-compose` the only error/warning message I get is 

> AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message

I can't judge if that's relevant or not.

Let me know if you need more information. Thanks in advance!

**Comment by dennis-tra** [comment]
Ok, I found out the Form is not posting to the https version of my server. Monica serves an insecure form. If I manually change the post URL to https it works. Now I need to figure out why Monica is not using the https url.

**Comment by dennis-tra** [comment]
The problem was, that I was running Monica behind nginx and didn't forward the `X-Forwarded-Proto`.Now my nginx config looks like this:
```
    location / {
        proxy_pass http://127.0.0.1:1234;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

**Comment by allanlw** [comment]
As a note to future spelunkers: if you need to get HTTPS proxying working correctly for Monica but it is still generating http:// links, you need to make sure that your proxy is in the Trusted Proxy list in the configuration. For more info, see https://github.com/fideloper/TrustedProxy
