### ISSUE TITLE
Deletion account not working

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1555]
A user just told me that deleting an account doesn't work in production.
I need to investigate.

**Comment by mheap** [comment]
This is likely due to `u2f_keys` not having an `account_id` field. I just hit the same on a standalone install

**Comment by imageslr** [comment]
Hi! I'm a junior developer and I'm now learning monica. One of the questions that bother me at the beginning is why there are `account` table, `users` table, and `account_id` in other tables? In my experience, I only use `users` table and `user_id` is enough. Is there some design principles or contracts? I am so grateful to you if you could reply or give some links about the problem.
