### ISSUE TITLE
Activities no longer appear in Journal

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#1561]
**Describe the bug**
Prior to release 2.3.1 activities were automatically added to the Journal. Since release 2.3.1. prior activities and new activities no longer appear in the journal.

Since 2.3.1 only entries directly entered via Journal appear in the journal.

**Which version are you using:**
 - Version 2.3.1, self hosted using Docker images on hub.docker.com

**Comment by cedewey** [comment]
I'm experiencing the same thing on the hosted plan.

**Comment by djaiss** [comment]
Thanks for the report. I think I know why,  I'll fix it.

**Comment by djaiss** [comment]
This https://github.com/monicahq/monica/pull/1619 will fix it.
