### ISSUE TITLE
A migration is trying to update a missing table `activity_type_groups`

### ISSUE THREAD

**Issue by Dagolin** [monicahq/monica#1573]
**Describe the bug**

1. In the latest migration [2018_07_08_104306_update-timestamps-timezone.php L26](https://github.com/monicahq/monica/blob/master/database/migrations/2018_07_08_104306_update-timestamps-timezone.php#L26) we are tying to update a deleted table `activity_type_groups` see [2018_07_03_204220_create_default_activity_type_groups_table.php L190](https://github.com/monicahq/monica/blob/master/database/migrations/2018_07_03_204220_create_default_activity_type_groups_table.php#L190)

2. A error `Undefined variable : $table` happens at [2018_07_08_104306_update-timestamps-timezone.php L38](https://github.com/monicahq/monica/blob/master/database/migrations/2018_07_08_104306_update-timestamps-timezone.php#L38)

**Comment by djaiss** [comment]
Yes this will be fixed in tomorrow's release. Thanks for flagging the problem.
