### ISSUE TITLE
Contacts details missing for a user, invited by other User

### ISSUE THREAD

**Issue by w3labz** [monicahq/monica#1575]
Suppose User A imported contacts using VCARD File, Contacts are visibe to him.

Now User A invited B, now user B can see number of contacts and the list but list is not showing data like Name of Contact. Also on Profile page Contact Name is missing.

Attached 
Screenshot 1 - List of Contacts from User B 
![screenshot1 - contacts page](https://user-images.githubusercontent.com/16626001/42737685-1c69c75a-8895-11e8-9c47-3a4dee040477.png)

Screenshot 2 - Profile Page of a Contact from User B 
![screenshot2 - profile page](https://user-images.githubusercontent.com/16626001/42737684-1c1a5b66-8895-11e8-9453-1c7fed4bad69.png)

Please help.

**Comment by w3labz** [comment]
Its hosted on a local windows pc using LARAGON.

**Comment by djaiss** [comment]
This is currently a bug. You need to set `firstname_lastname` as the value for the `name_order` column in the User table for this user.

We need to fix this asap.
