### ISSUE TITLE
Mark a contact as being dead

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#159]
Morbid, but still useful.

**Comment by ToeiRei** [comment]
I would also suggest that breaking up with someone should be considered with that

**Comment by djaiss** [comment]
Yes, and especially the case when a family breaks up: the ex should become a separate contact and inherits the child of the previous couple too. This is an interesting and complex use case that I'd like to add.

**Comment by Nebucatnetzer** [comment]
@djaiss there is a request for custom relationships between contacts.
Wouldn't that easily fix the problem? I would require a bit more configuration from the user
but would allow maximum flexibility.

**Comment by djaiss** [comment]
I think custom relationships is needed, but requires a bit of thinking before we move to support it, as it has to be right from the get go. Because once a feature is implemented and used, it's very hard to come back or change direction.

**Comment by ToeiRei** [comment]
Imho it's linking to another profile/person. Nothing funky at all.

**Comment by degan6** [comment]
Anyone have any ideas on how to add this?

I'm thinking we can add an input field below the birthday in the edit contact view.

And replace the age field with the date of their death. Maybe use a counter from the date to show how long its been since then?

**Comment by djaiss** [comment]
To support this, this is what we should do (this is a complete copy of @degan6's comment):

- add a checkbox at the top of the Edit profile `This person is dead` (but written with a better tone)
- when checked, replace the age field with the death date.
- add a special icon on the profile representing the status
- add a special icon in the list of users
- add a special icon in the dropdown listing users when linking contacts together

This will also require a migration to add a new `is_dead` boolean type column in the Contact table.

**Comment by hupili** [comment]
Can we use tag to achieve this? a `dead` tag.

> I would also suggest that breaking up with someone should be considered with that

Regardless of whether the contact is dead, marking a connection as dead could be useful, :). Then we can hide it from some places to reserve attention span.

**Comment by ToeiRei** [comment]
You could rate a relationship that way as @hupili suggests

**Comment by djaiss** [comment]
The ability to mark a contact as deceased is in production and will end up in the v1.0.0 scheduled to be release very very soon.

You can read more in the #642 PR.
