### ISSUE TITLE
Visual glitch with avatars at "last consulted" when scaling browser window

### ISSUE THREAD

**Issue by thiemo** [monicahq/monica#1592]
**Describe the bug**
As demonstrated by the attached screenshot, under the "last consulted" section the avatars populated with an image erroneously scale in width when resizing the browser windows, as opposed to the text avatar which do not scale.

**Screenshots**
![1](https://user-images.githubusercontent.com/305926/43050754-8efa2f84-8e0e-11e8-955e-f11adcfd7240.gif)

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Additional context**
Reproduced on Safari and Chrome.

**Comment by pqhf5kd** [comment]
This is still an issue on 2.11.2 (in Safari 12.0.1)

**Comment by thiemo** [comment]
This is still an issue on Monica Version: 2.11.2 and Safari 12.0.1

**Comment by asbiin** [comment]
This is fixed
