### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by dosch** [monicahq/monica#1600]
**Describe the bug**
I use the search bar to search for a contact. A unique name appears, I press enter on my keyboard to open that person; nothing happens. 

**Screenshots**
![screen shot 2018-07-24 at 09 07 26](https://user-images.githubusercontent.com/5372610/43122369-0c636356-8f21-11e8-8ccf-c0f4e0122f20.png)

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Additional context**
Pressing tab to select the contact, or using the arrow keys on the keyboard to select the contact, might help

**Comment by djaiss** [comment]
Well it's not a bug per se - you have to click on the contact with your mouse! We should improve this though.

**Comment by dosch** [comment]
true. I also had issues clicking the contact, but that might be related to my Wacom...

Then this one is just related to this feature request: https://github.com/monicahq/monica/issues/1479
More keyboard shortcuts in Monica! ;-)

**Comment by vandenheuvel** [comment]
I have this problem from time to time, even with clicking using the mouse. And not just at the search bar, also when adding contacts to activities. Search works properly then, it's just the clicking of the name that has closes the search box and removes the search term from the text field, without actually adding the name to the list. @djaiss should I create a separate issue, or do you want to reopen this one?
