### ISSUE TITLE
Use Conventional Commit message in our commit messages

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1605]
I'd like to automate the creation of the changelog. The tools that do that out there, all use the notion of [conventional commit message](https://conventionalcommits.org/) - what we have in the Chandler repository by the way.

The idea is to use keywords before each commit message. Then we can use those keywords to generate automatically the changelog.

For instance, `feat: allow provided config object to extend other configs` or `feat(lang): added polish language`.

The keywords that we could support (heavily inspired by [config-conventional](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional)):
* `ci`,
* `chore`,
* `docs`,
* `feat`,
* `fix`,
* `perf`,
* `refactor`,
* `revert`,
* `style`,
* `test`

An additional benefit would be to have an even cleaner commit log that we have right now.

What's your opinion on this @asbiin ?

**Comment by djaiss** [comment]
Also, we could follow this for the changelog https://keepachangelog.com/en/0.3.0/

**Comment by asbiin** [comment]
I agree it should not be very hard to use.
