### ISSUE TITLE
Feature request: Contact archiving

### ISSUE THREAD

**Issue by brianclemens** [monicahq/monica#1623]
**Problem:**
There are people I have long since fallen out of contact with cluttering up the contacts list.  However it would be nice to keep them around instead of deleting them entirely on the off chance I need to reach out to them again.

**Solution:**
Possibly add the ability to mark certain tags as hidden by default.  Or add something along the lines of the 'mark contacts as deceased' feature, though that doesn't hide them by default yet.

**Comment by djaiss** [comment]
Interesting feature. Thanks for sharing!
