### ISSUE TITLE
When adding new person, put man or woman as default in gender drop-down

### ISSUE THREAD

**Issue by tmuras** [monicahq/monica#1627]
Gender drop-down is compulsory and at he moment it defaults to nothing.
If we make it default to "man" or "woman" then this will match nearly 50% of the choices. Much better than current - 0% :).

**Comment by tmuras** [comment]
I guess the options are:
1. Set default to "woman" - I don't think man will find it anti-masculist.
2. Make it configurable - even in some obscure place like a config file, no need for UI even.

**Comment by allo-** [comment]
Idea: Use radio buttons instead. It's visible without click and one click less to select the gender.

**Comment by tmuras** [comment]
Another idea - let's ignore the feminist / anti-feminist views and opinions and just focus on the data. According to https://en.wikipedia.org/wiki/Human_sex_ratio : "Due to higher female fetal mortality,[2] the sex ratio at birth worldwide is commonly thought to be 107 boys to 100 girls,[3] although this value is subject to debate in the scientific community. The sex ratio for the entire world population is 101 males to 100 females."

Therefore it simply makes sense for a default to be a "man" as the most common option :).

+1 for the idea of converting to radio buttons.

I know that this change seems trivial but if you have to add a lot of records, every small improvement like that helps.

**Comment by asbiin** [comment]
We could add a setting for the user to choose the default gender to select when creating a contact.

**Comment by cawlin** [comment]
I believe the most straightforward solution is to stop requiring gender.

For many, there is no reason to record the gender of an individual in their personal CRM. @djaiss I'd love to understand why this is a required field at all - if it is merely to add variable pronouns (she, her, he, him) then I suspect there are better ways to ask for this information *or* work around implementing specific pronouns.

Very interested in moving this issue forward as I see it as a blocker for my own personal workflow.

**Comment by allo-** [comment]
Personally I think gender is what belongs to the basic data I want to have for a person. It identifies a person and it affects a lot of relationships.
The non-binary aspect is already covered, in the settings you are able to add more genders.
What needs to be covered is the issue: Selecting a gender in this dialog is rather complicated. I still believe radio buttons would be nice. When someone adds a lot of genders, maybe radio buttons for the first 5 (And people can reorder the list in the settings as needed) and a radio button "other" with a dropdown or freetext field next to it.

**Comment by tmuras** [comment]
I agree with @allo- .
What should sort out the problem is:
* radio buttons (less clicking)
* configurable default value (male / female / unknown / whatever)

**Comment by cawlin** [comment]
@allo-  @tmuras I see two different issues

1. The workflow issue of needing to select something - a default selection and different input type (like a radio button list) solves that, 100% agree.
2. Requiring gender by default. I still believe as a _personal_ crm it would be nice to leave it out and allow people to add it as a requirement if they want to.

Just my 2 cents as someone who was turned off by the option and noticed a similar comment on Product Hunt.

**Comment by allo-** [comment]
I think it should be integrated, with quick options for a small set and
an input field for the full options. Gender categories (more than
freetext) can be used later on to make  relationships easier. You do not
need to offer an option to add a female person as father. You probably
want to display the option to add a contact as husband before the wife
option. A free text field for everybody who identifies as non-binary may
be present and then do not filter (or sort) such lists anymore.
That's why I suggested using three radiobuttons (male, female, not set)
as default to be available with one click and a UI like a textbox for
the other choices.
