### ISSUE TITLE
Upgrade failing for version 2.4.2 for YunoHost

### ISSUE THREAD

**Issue by anmol26s** [monicahq/monica#1634]
Hi
Update for some users having Monica instances is failing on YunoHost for version 2.4.2. I am not able to reproduce it on my server. Someone has clue why its failing ?

Artisan update is giving the error:
```
$ sudo /usr/bin/php7.1 artisan monica:update --force
26380 DEBUG   Class 'Lahaxearnaud\U2f\U2fServiceProvider' not found
```
Complete log is here:
https://10qt.net/zerobin/?8ca9c584f625c80f#MZsTH//kd4TF7UyIAN7SyLSmm2xl+cBqVEsIdHp8EG4=

**Comment by djaiss** [comment]
That means the service is not loaded because the package is actually missing.

You need to run `composer install` first. I don't know why the script doesn't do it.

**Comment by anmol26s** [comment]
Hopefully this is solved.
https://github.com/YunoHost-Apps/monica_ynh/issues/23
