### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by errogaht** [monicahq/monica#164]
@djaiss hello!  2FA with Google Authenticator. What do you say?
im found https://www.sitepoint.com/2fa-in-laravel-with-google-authenticator-get-secure/

when i have free time - i can implement this

**Comment by djaiss** [comment]
I'm all for it!

**Comment by alrik11es** [comment]
Fido U2F too please! https://github.com/Firehed/u2f-php

**Comment by else** [comment]
Thanks! However I'm unable to scan the code with 1Password (manually entering works). Ideas?
