### ISSUE TITLE
Typo on subscriptions page

### ISSUE THREAD

**Issue by placeybordeaux** [monicahq/monica#1651]
**Describe the bug**
The first paragraph ends with the word "litterally"

**Screenshots**
![monica-typo](https://user-images.githubusercontent.com/1299864/43626275-fd08ab96-96a5-11e8-9a98-80133716ff77.PNG)

**Which version are you using:**
 - Hosting version on https://app.monicahq.com ( Version: 2.4.2 )

**Comment by mechanarchy** [comment]
@asbiin Can you please close this issue? It was resolved in #2455 :smile:
