### ISSUE TITLE
Issue adding activities (possibly due to lingering effects of v2.2.1 bug?)

### ISSUE THREAD

**Issue by privong** [monicahq/monica#1655]
After upgrading to the most recent version (v2.4.2) I get the error "Whoops, looks like something went wrong." when I try to add new activities.

This was working fine wth version 2.2.1, which is what I first installed. I have attempted to upgrade several times as new versions have come out, but it's never been obvious that the upgrades worked.

**Which version are you using:**
I am running a self-hosted version. The various versions that are reported are:

* webpage footer: Version: 2.2.1
* monica directory: 
  ```
  $ git status
  HEAD detached at v2.4.2
  ```
* monica SQL:
  ```
  MariaDB [monica]> select * from instances;
  +----+---------------+-----------------+----------------+----------------------+------------------------------------------+---------------------+---------------------+
  | id | uuid          | current_version | latest_version | latest_release_notes | number_of_versions_since_current_version | created_at          | updated_at          |
  +----+---------------+-----------------+----------------+----------------------+------------------------------------------+---------------------+---------------------+
  |  1 | 5b6476c9592aa | 2.4.2           | 2.4.2          | NULL                 |                                     NULL | 2018-08-03 15:37:45 | 2018-08-03 15:37:45 |
  +----+---------------+-----------------+----------------+----------------------+------------------------------------------+---------------------+---------------------+
  ```

Regarding the web footer saying v2.2.1, I have deleted the `monica` directory and re-cloned the main repo, as well as dropping the `monica` SQL database. I haven't been able to figure out why the footer provides an incorrect version.

I remember there was some bug introduced in v2.2.1 and it was recommended that people avoid upgrading to it until a fix was released. But unfortunately that was the version that was out when I started using it. I have a fair amount of information already entered into my monica instance, so I'd rather not clobber that if I can avoid it. I tried to be careful about my re-importing of data after installing version 2.4.2. I checked to make sure the table definitions matched and only imported the particular tables containing my contacts' info and activities.

For what it's worth, I am able to add/remove new contacts and add calls. So not everything is broken.

**Comment by djaiss** [comment]
Can you please try to upgrade to 2.5.0 that we just released and see if you still have the problem?

**Comment by privong** [comment]
I tried upgrading using the following command sequence:
```
git fetch
get checkout tags/v2.5.0
composer install --no-interaction --no-suggest --no-dev
php artisan monica:update --force
```

I still receive the same error when trying to add activities.

The version number in the footer of the monica page still says 2.2.1. Checking SQL shows:
```
MariaDB [monica]> select current_version,latest_version from instances;
+-----------------+----------------+
| current_version | latest_version |
+-----------------+----------------+
| 2.4.2           | 2.5.0          |
+-----------------+----------------+
```

**Comment by asbiin** [comment]
not enough information to reproduce this right now
