### ISSUE TITLE
Reminders are Broken

### ISSUE THREAD

**Issue by johnriley** [monicahq/monica#1668]
The birthdate reminder date is either one day or two days ahead of each contact's birthday, despite the description text of the reminder area saying "you'll get a reminder the day of". I've now wished two friends happy birthday the day before! :/

Example:

![screenshot 2018-08-07 10 52 36](https://user-images.githubusercontent.com/5523420/43783670-467b5caa-9a30-11e8-9dab-2a7ba92edf0c.png)
![screenshot 2018-08-07 10 50 41](https://user-images.githubusercontent.com/5523420/43783678-494068b8-9a30-11e8-9a24-9d621543703b.png)

**Comment by johnriley** [comment]
Also, I am currently not receiving reminders at all.

**Comment by djaiss** [comment]
@johnriley Sorry for these problems.

Are you using the hosted version, or do you host your own version? Reminders on our hosted version were indeed broken but this has been fixed and they are now sent.

Regarding the current reminders that are sent too early (or too late), I'm going to investigate.

**Comment by johnriley** [comment]
Regis -- reminders are once again being sent, however the date inside of the platform is the day before the reminder is required. For example, for a Aug 25th birthday, the reminder says Aug 24th. Please advise!

**Comment by johnriley** [comment]
Hi. Bringing this to top of mind. The reminder dates are wrong, similar to the activity dates.

**Comment by djaiss** [comment]
This should be solved now.

**Comment by vandenheuvel** [comment]
Reminders are not (all) being sent (on app.monicahq.com). @djaiss could this be reopened?
