### ISSUE TITLE
Subscription Page Inaccessible in Hosted

### ISSUE THREAD

**Issue by johnriley** [monicahq/monica#1669]
See screenshot for https://app.monicahq.com/settings/subscriptions.

![screenshot 2018-08-07 10 55 12](https://user-images.githubusercontent.com/5523420/43783738-70b6ed72-9a30-11e8-9f24-b66bfec90d8c.png)

**Comment by djaiss** [comment]
It's a known bug that will be solved in a couple of hours when I release the new version!

**Comment by djaiss** [comment]
New version is up.
