### ISSUE TITLE
Country List empty and required

### ISSUE THREAD

**Issue by gvaldezsan** [monicahq/monica#167]
When trying to edit a contacts detail, the Country select is empty and is required. No errors in chrome's console.

**Comment by beajeanm** [comment]
I believe the country list is empty because you forgot to run `php artisan db:seed` as describe in the readme (or you ran it and it failed).
Check the content of the countries table (`select count(*) from countries;`). If it's empty, then this is a setup issue not a bug in the edit contact page.

**Comment by erdmenchen** [comment]
And if you don´t want your Database seeded with the dummy data, then edit your APP_ENV in the .env file before seeding:
`APP_ENV=production`

**Comment by rreuvekamp** [comment]
It's a documentation error then:

> Optional step:
> 
> This step is to populate the instance with fake data, so you can test with real data instead of lorem ipsum.
> 
>     php artisan db:seed to load all seeds.

The step is explained as optional and "so you can test with real data instead of lorem ipsum" doesn't seem relevant if you'd like to run it in production.

**Comment by gvaldezsan** [comment]
I still think we have a bug since the field is marked as optional but has the "required" html5 tag.

@beajeanm I didnt forget but documentation lists that as an optional step for demo data, and tbh fuctionality like that shouldn't be demo data.
@erdmenchen Thanks a lot.
@rreuvekamp I completely agree, that was my train of though for not running them.

**Comment by asbiin** [comment]
#1117 solved this issue
