### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by cdubz** [monicahq/monica#17]
What kind of help are you looking for with testing? I have recently had some experience with [Selenium ](http://docs.seleniumhq.org/) and [Sauce Labs](https://saucelabs.com/) for UI testing (using Python) and might be interesting in helping out.

**Comment by djaiss** [comment]
Thanks for your interest. I'd love some functional testing with Dusk actually, which is a Laravel package (https://laravel.com/docs/5.4/dusk).

I don't think we should introduce a dependency towards a language other than PHP in the current stage.

**Comment by cdubz** [comment]
I imagine Selenium has PHP bindings, but it looks like Dusk makes good sense for a Larvel package.

Are you using anything for dev chat?

**Comment by djaiss** [comment]
@cdubz GitHub ;-D ? No, not yet.

**Comment by ravi-sensify** [comment]
@cdubz, @djaiss - I would potentially be interested in contributing to test efforts as well. Keep me in the loop? -thx

**Comment by cdubz** [comment]
@ravi-sensify- Cool. I'll have time this evening (i.e. in 10 hours or so) and can get Dusk bootstrapped. Feel free to do so sooner if you have the time.

**Comment by ravi-sensify** [comment]
@cdubz - my email is ravi@zaatar.org. I'm on my way to vacation (no email/phone/GitHub etc.) for the next 10 days, so the timing is bad, but I'd be interested in engaging post June 20. -thx again!

**Comment by cdubz** [comment]
FYI - I backed off this as the set up process is a bit onerous (at least for me, having never used Vagrant or Homestead before). I'll watch #30 for a bit.

**Comment by ravi-sensify** [comment]
Great, thanks for letting me know, I've added myself as a watcher on #30 as well. I'm very comfortable with Vagrant (host my own box [here](https://atlas.hashicorp.com/ravi-sensify/boxes/opensuse-13.2-x64) too) but don't know Homestead either :) Thx to both of you! 👍
