### ISSUE TITLE
Manually created a reminder and now getting repeat emails every hour

### ISSUE THREAD

**Issue by xori** [monicahq/monica#171]
![email reminders](http://publications.dsbn.org/misc/share-x/atom_2017-06-09_08-18-24.png)
Each of the above emails are for the same reminder.

The settings I put in a few days ago were 
starting: June 9th 2017
remind me every: 3 months

I've since deleted the reminder, but I assume Monica isn't suppose to nag you to be social.

**Comment by xori** [comment]
related to https://github.com/monicahq/monica/issues/145

**Comment by djaiss** [comment]
This is a bug. I've submitted a fix in production and it should be solved now. Feel free to reopen this issue if you keep receiving emails every hour in a few hours.
