### ISSUE TITLE
Column not found: 1054 Unknown column 'confirmation_code' in 'field list

### ISSUE THREAD

**Issue by sid3windr** [monicahq/monica#1719]
**Describe the bug**

After updating Monica today (after quite a long time) I can no longer log in because I seemingly need to confirm my e-mail address. Clicking on the link to re-send the email results in an error backtrace:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'confirmation_code' in 'field list' (SQL: update `users` set `updated_at` = 2018-08-19 09:27:28, `confirmation_code` = eJnqLrz4EsROeNQduWbcVYqr6FmLRq where `id` = 1)

I can't find the definition for the 'confirmation_code' (nor 'confirmed') field anywhere in database/ so that makes sense? The code was added in #1374.

If it should be there, something went invisibly wrong with one of migrations - how can I fix it?

Setting SIGNUP_DOUBLE_OPTIN=false after the fact does not help.

**Which version are you using:**

I'm hosting my own, git 395e49f039e6bfe864cb16594f8168abfd7d37d1

**Comment by asbiin** [comment]
Did you run `php artisan migrate` or `php artisan monica:update` before testing to log?

**Comment by sid3windr** [comment]
I have run both (did migrate first, now switched to update), but there is no such column in my users table. 

Not sure how it would end up there as it's not found in any of the migrations? (but I'm not really up to snuff with all the modern PHP stuff, so I may be wrong here)

**Comment by asbiin** [comment]
The migration script is provided by a composer package.
Did your run `composer install`  before `php artisan migrate`?

**Comment by djaiss** [comment]
If it's your own instance, you should be able to bypass this restriction.
Can you take a look at your DB and check the `users` table see if you have the `confirmed` and `confirmation_code` columns?

If you do, simply put `confirmed` to 1 and `confirmation_code` to `null` should solve it.
If you don't have them, we need to figure out how it's even possible.

**Comment by sid3windr** [comment]
I don't have the columns - otherwise the MySQL error message would make little sense :-)

And I can't seem to make them appear with artisan either. I could create them manually, of course, but I don't actually want to :-)

**Comment by djaiss** [comment]
Indeed.

I just saw your comment above. You ran `composer update` instead of `composer install`. The update instruction will update locally all the packages without matching what the repository actually needs, whereas the `install` instruction will update the packages to the version Monica needs to run.

I don't think it's linked though, but now you know 😀

What you could do is publish the migration and run it yourself.

In your CLI: 
`php artisan vendor:publish --provider="Bestmomo\LaravelEmailConfirmationServiceProvider" --tag="confirmation:migrations"`

then

`php artisan migrate`. Then it should work. If you do have the backup of your database (just to be safe), could you try this? @asbiin what do you think?

But this should have been done automatically. I wonder how many people have had this problem, you are the first one to report it.

**Comment by sid3windr** [comment]
Plenty of backups, that's no issue. I'll make sure to run `composer install` instead in the future, but I would have assumed after running `install`, it would still have done the migrations.

I tried your suggestion, but:
```
# php artisan vendor:publish --provider="Bestmomo\LaravelEmailConfirmationServiceProvider" --tag="confirmation:migrations"
Publishing complete.
# php artisan migrate
**************************************
*     Application In Production!     *
**************************************
 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.
```

I will acknowledge this is probably pilot error and I may be the only one - I do appreciate all your efforts in helping me fix it!

**Comment by djaiss** [comment]
Hum. 🤔 

Does the `migrations` contain the row `2017_02_02_232450_add_confirmation`?

**Comment by sid3windr** [comment]
No, it's not there. Interestingly adding -v or -vvv to artisan vendor:publish also only shows 'Publishing complete.' ...

**Comment by sid3windr** [comment]
I have restored monica's git checkout directory and the accompanying MySQL backup from before I updated, and have now used `composer install --no-dev` instead of `composer update --no-dev` and I now do have the correct columns in the `users` table. Not sure how I would have fixed the broken install, but at least the cause of it is known: not using `composer install` !

Please note there is no `*_add_confirmation.php` file in database/migrations still (cf. comment abobe), even though it did apply it.

**Comment by wixregiga** [comment]
M

**Comment by djaiss** [comment]
@sid3windr finally! Happy that you have now a usable instance again. Sorry for all these troubles.
