### ISSUE TITLE
reminders are sending every hour

### ISSUE THREAD

**Issue by ytjohn** [monicahq/monica#172]
"We will send an email for each one of the reminders below. Reminders are sent every morning the day events will happen"

![image](https://user-images.githubusercontent.com/163156/26975209-cfaa3006-4cec-11e7-9ad6-97bba24131c3.png)

**Comment by djaiss** [comment]
Damned. I'll fix this today.

**Comment by djaiss** [comment]
From what I see in production, it looks like in https://github.com/monicahq/monica/blob/master/app/Console/Commands/SendNotifications.php,  the second dispatch is not triggered.

```
dispatch(new SendReminderEmail($reminder, $user));
dispatch(new SetNextReminderDate($reminder, $user));
```

The question is now, why?

**Comment by erdmenchen** [comment]
Why do you dispatch it anyway? 
As it is called via a command in the command kernel, there is no need to queue it from my point of view...

**Comment by djaiss** [comment]
How would you trigger the job otherwise?

**Comment by erdmenchen** [comment]
Just dont do it as a job. Do the work inside the command...

EDIT: I see your attempt to fix it. In my opinion this is a bad idea since you introduce duplicated code in different places.

**Comment by djaiss** [comment]
But it's meant to be a job, not a command. If it's a command, I'd still need to run it as a cron, making it harder than a job I think.

If you think we can do it better, I'd welcome a PR anytime.
