### ISSUE TITLE
Arabic Support

### ISSUE THREAD

**Issue by Mohammed90** [monicahq/monica#1727]
Please add Arabic among the supported languages. I can start contributing for the Arabic translation.

Another related feature request: 
Distinguish between maternal uncle/cousin/aunt and paternal ones. I know at least Arabic and Persian have such distinctions, and I assume there are other languages that could have them.

**Comment by asbiin** [comment]
@Mohammed90 Great ! I've open the new language support on crowdin : https://crowdin.com/project/monicahq/ar I invite you to create an account and start translating the application in there.
You should also read the (recommandations)[https://github.com/monicahq/monica/blob/master/docs/contribute/translate.md] all translaters must know about. 

I'll keep this PR open as we have some code to update to support a new language.

**Comment by Mohammed90** [comment]
Is there a staging environment to verify how the translation looks like? I want to verify the looks with the complexity of switching RTL to LTR mid-sentences.

**Comment by asbiin** [comment]
Unfortunately we currently not have a staging environment for lang tests. If you are a developer you can grab the l10n_master3 branch and regenerate the assets to test the modification.
