### ISSUE TITLE
Stuck process in production

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#173]
This made the CPU go >97% for 5 hours.

I think it called SendReminderEmail with perhaps a user or something that didn't exist anymore.

```
{
   "displayName":"App\\Jobs\\SendReminderEmail",
   "job":"Illuminate\\Queue\\CallQueuedHandler@call",
   "maxTries":null,
   "timeout":null,
   "data":{
      "commandName":"App\\Jobs\\SendReminderEmail",
      "command":"O:26:\"App\\Jobs\\SendReminderEmail\":6:{s:11:\"\u0000*\u0000reminder\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":2:{s:5:\"class\";s:12:\"App\\Reminder\";s:2:\"id\";i:305;}s:7:\"\u0000*\u0000user\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":2:{s:5:\"class\";s:8:\"App\\User\";s:2:\"id\";i:765;}s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:5:\"delay\";N;}"
   }
}
```

**Comment by djaiss** [comment]
I've cancelled this job at the moment, the CPU is back to normal. I need to investigate as soon as I can.

**Comment by erdmenchen** [comment]
There should be a max attempt variable and a timeout defined in the job class, so that this is not going to block a system.

See the Laravel docs: https://laravel.com/docs/5.4/queues#max-job-attempts-and-timeout

**Comment by djaiss** [comment]
@erdmenchen thanks! It's fixed now, all jobs now have a max attempt!

**Comment by erdmenchen** [comment]
@djaiss You are welcome, keep up the good work!
