### ISSUE TITLE
Plural form for vuejs messages

### ISSUE THREAD

**Issue by asbiin** [monicahq/monica#1731]
With vuejs messages, some plural forms does not work completely. Some locales needs more than two formats (1 / 0 or more), which fits in english.

vue-i18n component will certainly update, but in the meantime, we could use [messageformat](https://messageformat.github.io/messageformat/)

**Comment by djaiss** [comment]
Which plural forms do not work?

**Comment by asbiin** [comment]
See especially this one: https://crowdin.com/translate/monicahq/5/en-he#1220

**Comment by asbiin** [comment]
Fixed by #3080
