### ISSUE TITLE
Store images in AWS S3

### ISSUE THREAD

**Issue by asbiin** [monicahq/monica#1742]
We plan to move images for app.monicahq.com in S3 - see #1735.

This issue is to check if everything is ready to store images in S3.
See https://laravel.com/docs/5.6/filesystem

- [x] create an [S3 bucket](https://s3.console.aws.amazon.com/s3/home) for Monica
- [x] create a new [strategy](https://console.aws.amazon.com/iam/home?#/policies) - see [s3strategy.txt](https://github.com/monicahq/monica/files/2342251/s3strategy.txt) : replace %BUCKET% with the name of the bucket
- [x] create a new [group](https://console.aws.amazon.com/iam/home?#/groups) and apply the strategy
- [x] create a new [user](https://console.aws.amazon.com/iam/home?#/users) in the newly group
- [x] update `.env` with `DEFAULT_FILESYSTEM=s3`, and AWS keys
- [x] test uploading an avatar in the new bucket 
- [x] put our instance down in production: `php artisan down`
- [x] run command `php artisan monica:moveavatars -vvv`
- [x] put our instance back up in production: `php artisan up`

**Comment by djaiss** [comment]
Steps

- [ ] create an S3 bucket for Monica
- [ ] share S3 credentials with @asbiin and @djaiss
- [ ] test locally if it works locally without any change in the codebase
- [ ] if it doesn't work, make it work
- [ ] check if we need to change the path of the files that are stored locally in the database. If we do, we need to prepare a migration for this.
- [ ] put our instance down in production
- [ ] move all current images that are stored locally to S3
- [ ] run migration if needed
- [ ] put our instance back up in production

**Comment by dosch** [comment]
Do you mean images of the interface, or contact images? Because if the latter, please be aware that GDPR applies...

**Comment by djaiss** [comment]
@dosch contact images.

GDPR enters into account when we need to delete the data. Do you see another impact?

**Comment by dosch** [comment]
No, GDPR enters into account as soon as you are processing personal data. 

Monica is of course doing that as a core business, about which you can have all sorts of thoughts... but if you start using processors for some of that data you need to have a Data Protection Agreement with them.

**Comment by djaiss** [comment]
Interesting insight. Thanks for sharing.
We are not using processors for images, we do resize them ourself. We do plan to store data on S3 though, which is different than today where we do store them on the local storage. I'm pretty sure Amazon has the DPA you are talking about - I'll check.

**Comment by asbiin** [comment]
OK so the steps are

- [ ] create an [S3 bucket](https://s3.console.aws.amazon.com/s3/home) for Monica
- [ ] create a new [strategy](https://console.aws.amazon.com/iam/home?#/policies) - see [s3strategy.txt](https://github.com/monicahq/monica/files/2342251/s3strategy.txt) : replace %BUCKET% with the name of the bucket
- [ ] create a new [group](https://console.aws.amazon.com/iam/home?#/groups) and apply the strategy
- [ ] create a new [user](https://console.aws.amazon.com/iam/home?#/users) in the newly group
- [ ] update `.env` with `DEFAULT_FILESYSTEM=s3`, and AWS keys
- [ ] test uploading an avatar in the new bucket 
- [ ] put our instance down in production: `php artisan down`
- [ ] run command `php artisan monica:moveavatars -vvv`
- [ ] put our instance back up in production: `php artisan up`

**Comment by asbiin** [comment]
Migration has been done. Everything is ok, we can go back on migrate the application!
