### ISSUE TITLE
Replace custom avatar generation with better library

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1746]
Our current way of generating avatars for users suck, for a lot of reasons. We should make it better or use a library from the community.

This one, for instance: https://github.com/laravolt/avatar

**Comment by pqhf5kd** [comment]
I can't see anything in the release histroy, but the avatars on 2.11.2 look very similar to the ones in Laravolt's example. Has it been implemented?

**Comment by djaiss** [comment]
@pqhf5kd nope, but https://github.com/monicahq/monica/pull/2112 will take care of all 😀
I'll try to finish this PR today.

**Comment by djaiss** [comment]
Well, I haven't finished it, but it's pretty close to being done.
