### ISSUE TITLE
Ability to track life events

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1762]
Facebook has a nice feature that lets users record life events.
We don't have something similar but it would be nice to let us record important life events too. Let's copy the feature.

### Description

- A contact has a set of life events.
- A life event belongs to a category of events.
- A life event has a date the event happened.
- We can add a note that goes along the event.

Adding a life event does not interfere with a core data of a contact. For instance, 

### Out of scope

This will be the v2 of this feature.
* Ability to define custom life event type or category of life events.
* Ability to add a reminder for the event.
* Ability to associate contacts with the life event.

### List of default categories and types

Work & education
- New job
- Published book or paper
- retirement
- New school
- Study abroad
- Volunteer work
- Military service

Family & relationships
- First met
- New relationship
- Engagement
- Marriage
- Anniversary
- Expecting a baby
- New child
- New family member
- New pet
- End of relationship
- Loss of a loved one

Home & living
- Moved
- Bought a home
- Home improvement
- New roommate
- New vehicule
- Holidays

Health & Wellness
- Organ donor
- Overcame an illness
- Quit a habit
- New eating habits
- Weight loss
- Glass, contact, other
- Broken bone
- Removed braces
- Surgery
- Dentist

Travel & Experiences
- New hobby
- New instrument
- New language
- Tatoo or piercing
- New license
- Travel
- Achievement or award
- Changed beliefs
- First word, Kiss, other
- New sport

The difference between activities and life events: activities are things you do with the contact. A life event is about the contact itself, independent of your interaction with him.

**Comment by rickpastoor** [comment]
Love it!

**Comment by tbirrell** [comment]
Whats the word on v2 for this? There are a few things on that list I'm finding a need for (specifically contact association). So I just wanted to see if you had anything ongoing before posting a feature request and/or starting to write some of it myself.

**Comment by djaiss** [comment]
@tbirrell no v2 planned yet, but in the current version, I planned for the future by adding a column called `specific_information_structure` in the life_event_types table. 

This columns is meant to be a json where we'll be able to store specific data about each life event type, like if you say someone goes on holidays, indicate the length of the holidays and a reminder about it - stuff like that.

Then, when creating a new life event, the front end would pull those information and build the corresponding custom form, therefore populating the `specific_information` column in the `life_events` table upon save.

I think life events should be a big part of Monica and I also would like to make them much better.

If you want to talk about life events, the best would be to open a new issue and describe one feature request (one feature request per issue is best).
