### ISSUE TITLE
Installation Via Heroku - 2 Dynos?

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#1764]
To get past the no-cron thing on Heroku I just bought a Hobby dyno.
After using the Deploy To Heroku button [here](https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md), and waiting for the entire thing to load, I see this in my management page on Heroku:
![tom-monica_ _resources___heroku](https://user-images.githubusercontent.com/8835035/44928626-145ef300-ad61-11e8-95da-a24d05c157ac.jpg)

These are **2** dynos, and not a single one - one for the app and one for the update script, it seems.

I am not familiar with Heroku, and was wondering why is that - why do I need 2 dynos to run a Monica installation on Heroku, and only 1 EC2 instance if I choose to go the AWS route? 

They are two different animals, I'm aware - one is a container and the other a full fledged-server on which I can cron jobs as I please - but I would love a technical answer.

**Comment by tomgs** [comment]
@asbiin Thoughts on this?

**Comment by asbiin** [comment]
@tomgs when you deploy with the heroku button, only 1 dyno is activated for the "web" one.
The "queue" dyno is only helpfull if you set `QUEUE_DRIVER=database` (default is 'sync').
You shall need the Heroku Scheduler too:
![image](https://user-images.githubusercontent.com/25419741/45253146-9f904800-b362-11e8-916b-8980fc2a83d8.png)
Click on it and set `php artisan schedule:run` as a scheduled command.

**Comment by tomgs** [comment]
Oh, great - probably a good idea to add that to the installation instructions for Heroku.
Just wrote it up and made a PR - [here](https://github.com/monicahq/monica/pull/1793).

One thought though: the instructions say there's no cron on the free version, but what we're doing here is setting up cron via the Heroku Scheduler, while using the free plan. Isn't that contradictory?

**Comment by djaiss** [comment]
@tomgs 

> One thought though: the instructions say there's no cron on the free version, but what we're doing here is setting up cron via the Heroku Scheduler, while using the free plan. Isn't that contradictory?

Yeah it appears to be a mistake from our instructions.

**Comment by tomgs** [comment]
@djaiss Fixed it now [here](https://github.com/monicahq/monica/pull/1807).

**Comment by djaiss** [comment]
So I guess this issue can be closed?

**Comment by tomgs** [comment]
Yep, forgot to close.
