### ISSUE TITLE
Positioning contact photos

### ISSUE THREAD

**Issue by bmckenna88** [monicahq/monica#1775]
After uploading a photo/avatar, I'd like to choose the area of the photo to show. 

<img width="1027" alt="photo-positioning-monica" src="https://user-images.githubusercontent.com/19333754/44996799-8e64c700-af6f-11e8-9265-4cb459ec95b2.png">

**Comment by djaiss** [comment]
I know there are some nice libraries that do that. Let's see if there are some in [Awesome Vue](https://github.com/vuejs/awesome-vue).
