### ISSUE TITLE
Updating Heroku-Hosted Instance Locks Me Out Due To E-Mail

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#1776]
**Describe the bug**
After following the instructions [here](https://github.com/monicahq/monica/blob/master/docs/installation/update.md) to update my Heroku Monica instance, I get the screen below. When I click the "re-send confirmation e-mail" button, it shows that it sent it - but I never get an email for the confirmation.

**Screenshots**
![Login Error](https://user-images.githubusercontent.com/8835035/45054073-95392a00-b094-11e8-8164-e1ddf2d5d24e.png)
![confirmation email sent. Tho, not really](https://user-images.githubusercontent.com/8835035/45054099-a5e9a000-b094-11e8-837a-d898bd23f8b1.png)

**Which version are you using:**
 - A server you maintain yourself (Heroku, Monica V2.6.0)

**Additional context**

**Comment by tomgs** [comment]
I used the deploy to Heroku button on the Readme - didn't change anything. It's false by default, if I understand correctly, and the Heroku CLI is acting up so I can't really validate that now. Is there any way to override this manually?

**Comment by tomgs** [comment]
So, it's not available for edit in the config vars either.
I'm going to delete this dyno and set a new one, making sure the e-mail functionality is working (so even if I do get locked out of the account, I'll get the verification e-mail properly). Closing for now.

**Comment by asbiin** [comment]
@tomgs thanks! I was testing and the verification is needed even is APP_SIGNUP_DOUBLE_OPTIN is set to false, is the `confirmed` attribute is wrong on the user.
I will change that

**Comment by tomgs** [comment]
Awesome. One other important thing - I never saw detailed MailGun setup instruction for any type of installation. Thought about writing them up and updating the installation instructions for all the platforms, but not sure where to start. If you've got the time to run me through it or an internal document to spare, I'd be happy to take that on.

**Comment by tomgs** [comment]
Not sure how I can edit those in Heroku - they're not part of the config vars, as far as I can tell

**Comment by asbiin** [comment]
Oh yes you can: just go to "Settings" tab and click on "Reveal Config Vars" button, then you can add some vars.

**Comment by tomgs** [comment]
@asbiin will write that up and make the appropriate PRs in the next few days. Thanks for all your help!

**Comment by vongohren** [comment]
@tomgs did a PR ever come :) I was looking for the same
@asbiin is that all you need? How about api key or anything like that? Smtp connection secret and such?

**Comment by asbiin** [comment]
@vongohren everything is handle by the `mailgun` driver. Just set the 5 environment variable describe upper.

**Comment by tomgs** [comment]
@vongohren Never got around to it! Will do now. 
Also, I imagine the MailGun secret is the API key, right @asbiin?

If so - [here's a link ](https://help.mailgun.com/hc/en-us/articles/203380100-Where-can-I-find-my-API-key-and-SMTP-credentials-) that shows how you can get your API key.

**Comment by tomgs** [comment]
And all done with the PR - see [here](https://github.com/monicahq/monica/pull/1864).

**Comment by tomgs** [comment]
For anyone looking at this with MailGun causing them trouble - see this:
https://github.com/monicahq/monica/issues/2740
