### ISSUE TITLE
Duplicate entries on Personalization > Features

### ISSUE THREAD

**Issue by grojas7** [monicahq/monica#1785]
**Describe the bug**
After the recent update that added the "Conversations" feature if I go to settings>personalization>features I see duplicate entries for every feature except "conversations" (refer to screen shot)

**Screenshots**

![screenshot_2018-09-05 monica personal relationship manager](https://user-images.githubusercontent.com/15941783/45107110-cac22f80-b0f5-11e8-9019-f03937297b06.png)

**Which version are you using:**
 - Hosting version on https://app.monicahq.com with monthly subscription.

**Additional context**
- Tried on Firefox and Chromium.
- My instance is set up for Spanish.
- I disabled some features right before the new update came out.
- Already tried enabling all features, logging out and then going back in. Issue persists.

**Side question**
I have been translating Monica to Spanish via Crowdin, is there something I can do to get my translations reviewed soon?

**Comment by asbiin** [comment]
I confirm this
Cc @djaiss

**Comment by djaiss** [comment]
Ok that's an important bug. And I know why.
I'll fix this tonight.
