### ISSUE TITLE
Notes written in right-to-left languages are rendered left-to-right in English localization

### ISSUE THREAD

**Issue by r-darwish** [monicahq/monica#1799]
**Describe the bug**
When using Monica in the English language, writing notes in a right-to-left written language, such as Hebrew, results in the note being rendered left to right instead. This effects both the alignment of the text as well as the text direction.

This bug does not apply when using the interface localized in Hebrew.

**Screenshots**
![image](https://user-images.githubusercontent.com/1383193/45261241-98bb1100-b406-11e8-9c9d-0955b196f949.png)

The text in the screenshot should say "Some text in Hebrew, some text in English and some more text in Hebrew" but instead appears as "some more text in Hebrew, some text in English, Some text in Hebrew"

**Which version are you using:**
Self hosted server - 2.7.1

**Comment by asbiin** [comment]
Thanks for sharing @r-darwish, but I don't see how we could fix this ...

**Comment by r-darwish** [comment]
RTL languages are rendered as expected in Trello, Google Keep, Facebook, Twitter, and probably every other major service. In all of them I use the English interface. 

I believe that they dynamically set the text direction of the element based on the content of the text.

**Comment by r-darwish** [comment]
There are some suggested solutions [here](https://stackoverflow.com/questions/7770235/how-can-i-change-the-text-direction-of-an-element). I'd be fine with `dir='auto`` as I personally don't use Internet Explorer.
