### ISSUE TITLE
doc: Add Cloudron as installation method

### ISSUE THREAD

**Issue by gramakri** [monicahq/monica#1800]
Hi Monica team,
Thanks for this app. We have been maintaining a Monica package on Cloudron for quite a while now at https://git.cloudron.io/cloudron/monica-app. The initial package was developed by Derek Martin. We also have automated browser tests for monica (under tests/).

Would be great if you could add Cloudron as one of the installation methods in your docs. I will make a PR shortly for the same. Thanks!

**Comment by gramakri** [comment]
Also, if you would like to try Monica on Cloudron, we have a demo instance at https://my-demo.cloudron.me (username: cloudron password: cloudron).

**Comment by djaiss** [comment]
Awesome. Thanks @gramakri
