### ISSUE TITLE
Activities date is not accurate

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1813]
Feedback from user:

When adding an activity with the date 09/09/2018, the saved result shows 09/08/2018. I noticed the same behavior when editing an existing activity. 

![recording activity](https://user-images.githubusercontent.com/61099/45330092-b20cac00-b531-11e8-8eee-09950ad870ae.gif)

The same activity recorded above is appearing under June 2018 in the journal timeline, despite happening during September 2018. The other activity (Drinks @ Marlton Hotel), also happened during September 2018. 

<img width="828" alt="journal timeline" src="https://user-images.githubusercontent.com/61099/45330089-afaa5200-b531-11e8-9fda-36756829989e.png">

**Comment by johnriley** [comment]
So annoying!

**Comment by djaiss** [comment]
This is fixed in the next release.

**Comment by saulpw** [comment]
This bug exists for me still.  I am using the hosted version.

**Comment by pqhf5kd** [comment]
I'm also having this issue.
I don't see any notes in the release history that suggests it was fixed.
@djaiss can we reopen this or create a new issue?

<img width="977" alt="screenshot 2018-11-21 at 19 36 19" src="https://user-images.githubusercontent.com/20027419/48861886-f97ea680-edc4-11e8-9f0d-9b341fda5bb0.png">
<img width="871" alt="screenshot 2018-11-21 at 19 38 35" src="https://user-images.githubusercontent.com/20027419/48861948-28951800-edc5-11e8-9c6c-35b587bdb71f.png">

**Comment by johnriley** [comment]
Yes, please reopen.
