### ISSUE TITLE
Recent calls don't appear in dashboard

### ISSUE THREAD

**Issue by maxnup** [monicahq/monica#1825]
I can't see recent calls in the dashboard. I log different calls in different contact pages but I don't see it in the dashboard page.

**Comment by maxnup** [comment]
![image](https://user-images.githubusercontent.com/21296272/46027237-a999a100-c0ed-11e8-9483-a57428dafe6a.png)

**Comment by djaiss** [comment]
Do you self host? I can't reproduce the bug. Is there a trace in the console in the dev tools of the browser?

**Comment by maxnup** [comment]
No, I don't. I use it in the global server. I created an account and I started using it. It's strange...

**Comment by maxnup** [comment]
![image](https://user-images.githubusercontent.com/21296272/46997253-8cba2180-d11f-11e8-9e02-01e4bfa3f37d.png)

I don't know if this help to find the cause of the problem that it persist yet.

**Comment by asbiin** [comment]
This is related with #2210
