### ISSUE TITLE
Often, clicking on a search result has no effect

### ISSUE THREAD

**Issue by vandenheuvel** [monicahq/monica#1830]
When I search for contacts, either in the header or when adding contacts to activities, I get results as I would expect. When I click on one of them, the list of search results collapses, as is to be expected, but then often nothing happens.

After, everything behaves just as if I hadn't searched for contacts at all. That is, I can search again, and the above often repeats itself.

I've been struggling with this problem for months. Sometimes, the functionality just works, but then several seconds later the problem occurs. I tried adding a contact to an activity many times in a row, while nothing happened. Then, all of a sudden, it just worked as expected. Failures often follow failures, but when it works, it often keeps working. It seems that failures occur more often when adding a contact to an event, than failures occur while searching from the header.

I'm hosting the hosted app using latest Firefox and latest Chromium. 

Referencing #1600 for completeness.

**Comment by djaiss** [comment]
I didn't know search was broken like this. Really sorry to read this. Perhaps #1831 will help here. Otherwise I'll investigate.
When that happens, do you see any errors in the Console?

**Comment by vandenheuvel** [comment]
The console remains empty.

**Comment by asbiin** [comment]
Search field has been refactored recently
