### ISSUE TITLE
Batch-Import Birthdays From Facebook

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#1834]
There's a few mobile apps that pull all your friend's data off facebook, and then let you set reminders based on the birthdays of all your friends.
I would like to have an option to log into facebook, pull the birthdays of all my friends, and then compare the list of FB friends with the list of Monica contacts to see which contacts' birthdays I can populate.

I can write the FB part, but I'm not sure how to integrate it into monica as a feature. @djaiss thoughts?

**Comment by degan6** [comment]
Could you list a few of the apps?

**Comment by tomgs** [comment]
@degan6 All of these probably have the same functionality:

https://www.google.co.il/search?q=play+store+reminder+birthdays&oq=play+store+reminder+birthdays&aqs=chrome..69i57.4764j0j7&sourceid=chrome&ie=UTF-8

But i was specifically referring to:

https://play.google.com/store/apps/details?id=com.marcow.birthdaylist&hl=en_US

**Comment by djaiss** [comment]
> I would like to have an option to log into facebook, pull the birthdays of all my friends

From Monica? How does FB let you pull these information? Or will you scrape the info through a Chrome extension?

As for the feature in Monica itself, we can do anything with the API, but first I need to understand how you will get the data in the first place.

**Comment by tomgs** [comment]
Ah, OK. My bad then. Thanks for explaining!

**Comment by Wouter0100** [comment]
Isn't this possible by providing the VCalendar URL from Facebook? See [here](https://www.facebook.com/help/152652248136178/).
