### ISSUE TITLE
2FA error after entering incorrect code

### ISSUE THREAD

**Issue by vandenheuvel** [monicahq/monica#1841]
When logging in using 2FA with correct username, password and 2FA code, everything works find and I get redirected to the dashboard. However, when I use the correct username, correct password but enter a wrong 2FA code before typing the correct one, I get redirected to https://app.monicahq.com/validate2fa where the message "Whoops, looks like something went wrong." appears in a large, red font.

![screenshot from 2018-09-25 12-53-24](https://user-images.githubusercontent.com/20440137/46010160-01221780-c0c2-11e8-9812-80886f8f9779.png)

After, manually navigating to https://app.monicahq.com results in a redirect to the dashboard.

I am using the 2FA mobile application, not the U2F security key. This is on the latest Firefox.

**Comment by asbiin** [comment]
This is not reproductible.
It might be resolved

**Comment by vandenheuvel** [comment]
I just reproduced this on app.monica.com. @asbiin could you reopen the issue? I can help you reproduce it. Firefox 66.0.5.

**Comment by vandenheuvel** [comment]
@asbiin this is still an issue. If you could reopen it, that would be great.
