### ISSUE TITLE
Features lost while importing data from 2.3.1 to 2.7.1

### ISSUE THREAD

**Issue by jpalczewski** [monicahq/monica#1851]
**Describe the bug**
Recently, I have been migrating from one server to another - so, I exported from old 2.3.1 instance an .sql file and tried to import it. At first, I got many https://stackoverflow.com/questions/12966626/mysql-cannot-add-or-update-a-child-row-a-foreign-key-constraint-fails related problems but adding those magic snippets fixed it. However, now I got problem with monica itself - it looks like demo version, because none of features are enabled and none are shown in "personalization". Is there any way to reset those from artisian?

**Screenshots**
![obraz](https://user-images.githubusercontent.com/4793526/46154056-a977dd80-c274-11e8-9d1d-5e848b857a6c.png)
![obraz](https://user-images.githubusercontent.com/4793526/46154101-bc8aad80-c274-11e8-9967-f05cc5bb06a6.png)

**Which version are you using:**
Dockerized version aka `image: monicahq/monicahq` with `image: mysql:5.7` database.

**Additional context**
At first I removed whole database - then recreated it with `utf8mb4_polish_ci` comparision set.

**Comment by djaiss** [comment]
This is because modules tables is either empty or they are deactivated in your personalization settings tab.

**Comment by jpalczewski** [comment]
> This is because modules tables is either empty
@djaiss, that's true, `modules` is empty(so there's none of them in personalization settings tab). Is there any way to fill it?(I did a migration step that docs said to do).

**Comment by asbiin** [comment]
If the moduls table is empty ... it should'nt, so we can't do anyhting.
Backup your data, rebuild a new instance and try import your datas.
