### ISSUE TITLE
Missing table when hosting to Heroku

### ISSUE THREAD

**Issue by vongohren** [monicahq/monica#1859]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
When hosted to heroku, all works fine, until you acctually is going to register a user.
It failes and gives an SQL error about missing table "default_life_event_types"

It exists a "default_life_event_categories".

To fix it to get further I duplicated the table to the name that was missing.
Then it worked.

**Which version are you using:**
 - A server you maintain yourself
I just pushed the Heroku add button on https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md

**Additional context**
It is very easy to remake, and probably some migrate gone wrong

**Comment by asbiin** [comment]
This is related to #1882

**Comment by vongohren** [comment]
I see that #1882 is closed now, and something merged, is it possible to close this?
