### ISSUE TITLE
RuntimeException ciphers

### ISSUE THREAD

**Issue by pcegarra** [monicahq/monica#187]
[RuntimeException]
  The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

Any idea?

**Comment by webdistortion** [comment]
Remove the predefined key in your .env file it's not long enough for Laravel 

change it to : 
APP_KEY=xlhF31NeOlibJcoOW9tvZg7TkHcAZI3a

Should get you up and running.

**Comment by djaiss** [comment]
Indeed. I've update the README to indicate that.

Actually you can run `php artisan key:generate` to create the right random key for you.

Feel free to close the issue once it's solved.

**Comment by kstrauser** [comment]
That doesn't work for me if `APP_KEY` is unset:

```shell
/var/www/monica # unset APP_KEY
/var/www/monica # php artisan key:generate


  [RuntimeException]
  The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
```

**Comment by erdmenchen** [comment]
Insert a random 32 character long string as the app key. THEN run the artisan command key:generate to generate a valid new one.

**Comment by kstrauser** [comment]
Is there a reason to do that beyond just using the random 32 character long string you made?

**Comment by BranTurner** [comment]
@kstrauser No, any 32 char string will do! If `php artisan key:generate` isn't working, you can always try `php artisan key:generate --show` which will give you a string you can manually enter into the .env file.

**Comment by tetov** [comment]
Should this really be closed? I think there should be an update either to the README or .env.example should have 32 char string in APP_KEY.

**Comment by BranTurner** [comment]
@tetov I agree a 32 char key should be included in `.env.example`, I think the error might confuse a lot of people who aren't familiar with Laravel.

**Comment by djaiss** [comment]
This is now included as part of `.env.example`.

https://github.com/monicahq/monica/blob/master/.env.example
