### ISSUE TITLE
Table monica.default_life_event_types on creation of user

### ISSUE THREAD

**Issue by anmol26s** [monicahq/monica#1880]
On creation of first user I am getting this error : 
Something went wrong:
`
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'monica.default_life_event_types' doesn't exist (SQL: update `default_life_event_types` set `migrated` = 1)`

Further I have disabled `APP_SIGNUP_DOUBLE_OPTIN` but still I get email verification notice on the new user registration.

**Comment by asbiin** [comment]
This might be related to #1882

**Comment by anmol26s** [comment]
@asbiin 
Is there temporary sql fix for this, so that I can have new user?

**Comment by djaiss** [comment]
2.8.1 is out

@anmol26s does it fix the issue?

**Comment by anmol26s** [comment]
@djaiss 
Yes \o/ 
This push fixes the issue. Thanks for fast merge and release.
