### ISSUE TITLE
monica cannot be installed in a subdirectory

### ISSUE THREAD

**Issue by leggewie** [monicahq/monica#1883]
I am reporting this against v2.8.0.  Maybe I am overlooking something but it seems that monica cannot be installed in a subdirectory of DocumentRoot, but requires its own (sub)domain to function correctly.  It would be nice if this limitation was lifted.

**Comment by asbiin** [comment]
Hi @leggewie this is already filed in #139

**Comment by leggewie** [comment]
Thanks.  I tried to search for that bug apparently used the wrong keywords.  Thank you for pointing out the dupe and sorry for the noise.
