### ISSUE TITLE
Set relationship to a person

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#19]
Feedback from user:

Please add an option to set relationship to a person ( wife, husband, son , friends)

**Comment by mschmo** [comment]
And more obscure relationship examples: coworker, classmate, roommate, etc so may want to give the option for defining a custom relationship title and not set it to a fixed enum.

**Comment by enko** [comment]
To get inspirations what can be a relationship, have a look at [gramps](https://gramps-project.org/) which is in some way similiar to what you want to archive, but in some way not.

**Comment by degan6** [comment]
Is this being worked on by anyone?

**Comment by lathomas64** [comment]
would be a very useful feature especially if custom relationships were allowed.

**Comment by Ali1** [comment]
Hello. Just discovered Monica, great just what I've been looking for for a while! First thing I've noticed is Spouse and Children Relationships. Any effort to create a more robust relationships model is a +1 from me.

In my head, would be great if we can create more relationships. And smarter relationships where after linking two contacts, further links are suggested. Perhaps a comprehensive configuration like:
```
{
'Parent' => {
  'reverse' => 'Offspring', // When creating a parent, suggest a reverse offspring relationship
},
'Offspring' => {
  'reverse' => 'Parent',
  'autolink' => {
    'Sibling' => { 
      'Uncle/Aunt' // When creating an offspring relationship, user's own siblings become Uncle/Aunt to the offspring
    },
    'Parent' => {
      'Grandparent' // When creating an offspring relationship, user's own parent becomes Grandparent to the offspring
    }
  }
},
...
```

The Relationship Model

```
id
account_id
contact_id
relationship_to_contact_id
relationship
priority_relationship // as people have a lot of relationships, some could be highlighted on a profile if the user chooses
```

What do people think about something like this?

**Comment by djaiss** [comment]
After the mobile app, this feature is the next big thing I should do (or one of the next big things). The reason I haven't implemented it so far is the fact that this is really complex and that I want to make it right.

I think Monica should reflect reality. 

- Monica could have default values (spouse, children, parents, brother/sister, uncle and all the kind of relationships that are family related basically).
- We should be able to define other type of relationships.

However, some types of relationships should be locked in the sense that we should not allow their deletion. I'm thinking here about specifically the `spouse` and `children` type. Why? Because we need to be able to control core contact information in order to control how we present it to the user, and those two fields are considered core. In the future I'd like to add more details in the reminders, or when you mouse over a name in the UI. We would then display those core contact information.

To make things worse, keep in mind that some types of relationship have custom needs. For instance, in the `spouse` type of relationship, we could add interesting metadata to it: wedding anniversary, first met date, breakup reason,... The same is true for many other types of relationship.

This would be the ideal situation and the vision we should aim for. Doing all this in one shot will be super complex, and take a very long time. We need to go step by step:

- remove the tables `relationships` (that currently represent spouses) and `offsprings`/`progenitors` and implement a single, standard relationship table that would allow the exact same functionality for now.
- modify the API to reflect this change.
- add ability to manage metadata for a specific relationship type (as explained above), and manage the impact on the API.
- make sure that this new system allows for automatic reverse relationship (defining a children would set the parent automatically for instance).
- then implement other type of relationships, that we would add one by one to make sure we get it right for each relationship type. We'd need to change the UI probably in this case too.
- finally, add custom fields.

It will take some releases to get it there. Considering how much the API will change because of these changes, we'll probably have to bump the version to 2.0.0 once this ships.

**Comment by djaiss** [comment]
The first step to support this has just been merged.

Monica now comes by default with many more relationship types. We'll enable custom relationships in the future.

* Partner
* Spouse
* Date
* Lover
* In love with
* Ex
* Parent
* Child
* Sibling
* Grand parents
* Grand children
* Uncle
* Nephew
* Cousine
* God father
* God son
* Friend
* Best friend
* Colleague
* Boss
* Mentor

**Comment by djaiss** [comment]
This feature has shipped.
