### ISSUE TITLE
Parse Error, helpers.php:444

### ISSUE THREAD

**Issue by cllorca** [monicahq/monica#190]
Parse error: parse error, expecting `'&'' or `"variable (T_VARIABLE)"' in /usr/local/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 444

Just followed the readme to install monica on my local machine. After restarting apache I'm getting this parse error. I didn't get any errors during any of the composer/bower/artisan processes, so I'm not sure what to do here. App will not load beyond this point. Digging for clues in the meantime...

**Comment by djaiss** [comment]
Can you provide the full log error please?

**Comment by cllorca** [comment]
How can I get more debug info? apache's error_log and access_log do not have any additional details. Let me see if I can increase the log level. This is apache2 / php71 on a macbook pro.

**Comment by cllorca** [comment]
Set apache to log level 'debug' but the error log doesn't show any more info on the php error going on. Will keep digging

**Comment by djaiss** [comment]
Have you set the env variable `APP_DEBUG`  to true?

**Comment by webdistortion** [comment]
Also check your PHP version and post it back here. <?php phpinfo(); ?> in your root.

**Comment by cllorca** [comment]
by default APP_DEBUG is set to true in .env
PHP 7.1.5 (cli) (built: May 13 2017 13:28:23) ( NTS )
php/apache installed via homebrew on my mac. I have a linode server I was going to test deploy on but php isn't up to date enough on that box.

**Comment by cllorca** [comment]
Found this: https://github.com/laravel/framework/issues/16674
Looks like php cli is 7.1 but my php mod for apache is still 5.5. Updating that now.
