### ISSUE TITLE
Whoops! Something went wrong. - When opening a contact

### ISSUE THREAD

**Issue by dosch** [monicahq/monica#1906]
When opening a contact from either the search or contact list, I get a *Whoops! Something went wrong* message.
![screenshot 2018-10-11 at 12 30 00](https://user-images.githubusercontent.com/5372610/46798255-b951f000-cd51-11e8-9808-ca42d3381aba.png)

This is a selfhosted instance of Monica, using Yunohost. I just updated to 2.8.1.

**Comment by jatls** [comment]
I'm having this same issue currently after the update to 2.8.1.

**Comment by jatls** [comment]
It looks like the migrations didn't work properly at the last update and that's mucking things up. Will try with a fresh database and import my backup tomorrow, then report back.

**Comment by asbiin** [comment]
@dosch did you ran `php artisan migrate` or `php artisan monica:update` on your instance ?

**Comment by djaiss** [comment]
After 2.8.1? We know we had a problem with 2.8.0 but not 2.8.1 :-/

If you can, please activate `DEBUG=TRUE` in your .env file - you'll get a dump of what's going on when you load the page.

**Comment by dosch** [comment]
> @dosch did you ran `php artisan migrate` or `php artisan monica:update` on your instance ?

I ran:
```
$ sudo yunohost app upgrade -u https://github.com/YunoHost-Apps/monica_ynh monica
```

>  please activate `DEBUG=TRUE` in your .env file
Where can I find the .env file?

**Comment by djaiss** [comment]
I don't know how Yunohost works. But definitely your error is about a migration that didn't run. A migration is a script that changes the database structure. I have no idea on how you can enter into your yunohost instance and run `php artisan monica:update`

**Comment by dosch** [comment]
ok, I will try to find that out. 
Please note that I am able to see the contacts in the Monica App...

**Comment by dosch** [comment]
> It looks like the migrations didn't work properly at the last update and that's mucking things up. Will try with a fresh database and import my backup tomorrow, then report back.

Did you find anything? I am still stuck... :-(

**Comment by jatls** [comment]
> Did you find anything? I am still stuck... :-(

I started with a fresh database, imported my backup, rolled back migrations, re-ran migrations and got it back working again. There were a couple of errors in the tables I had to manually fix because of the last migration that didn't work properly. I don't have any clearer answer than that though. I kinda just fiddled with it til it worked.

**Comment by dosch** [comment]
> rolled back migrations, re-ran migrations

Is there any documentation on how to do this?

Or, if all fails, can I use my Mysql dump to move back to the MonicaHQ? I think this self-hosting is a bit too complicated and the date is too important for me to loose...

**Comment by virtadpt** [comment]
I'm seeing the same problem with both v2.9.0 and e8a7aa591c4cbbed24fe79620c273e3670bcf8b5.  I'm running `php-7.2 artisan monica:update --force` and seeing it run to completion (`Monica v2.9.0 is set up, enjoy.`), no errors reported, but when I try to load any page (with DEBUG=TRUE in .env) I get an "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drwho_monica.terms' doesn't exist (SQL: select * from `terms` order by `created_at` desc limit 1)" exception.

Running `php-7.2 artisan migrate:status` shows that no migrations after 2017_06_13_035059_remove_gifts_encryption have run, they're all showing up as "No" in the output.

**Comment by asbiin** [comment]
@dosch You will find some information on [Laravel documentation here](https://laravel.com/docs/5.7/migrations#rolling-back-migrations).
Anyway, all of your problems seems to be related to update or migration problem with your hosted system, and we cannot provide support here.

**Comment by dosch** [comment]
understood. I have removed my Monica instance from now... will wait till carddav and caldav are supported and then move to monicahq.com

sadly all my past data is gone... oh well

**Comment by djaiss** [comment]
> sadly all my past data is gone... oh well

What do you mean? Can't you retrieve your old data from the database?
