### ISSUE TITLE
Life event spelling: Tatoo

### ISSUE THREAD

**Issue by jatls** [monicahq/monica#1924]
Life event says "Tatoo" but correct spelling is "Tattoo".

**Comment by DanielKim1** [comment]
`rg --files-with-matches tatoo | xargs sed -i 's/tatoo/tattoo/g' && rg --files-with-matches Tatoo | xargs sed -i 's/Tatoo/Tattoo/g'` seems to do the job, but it makes changes to several very large files in `public/js/` that are impossible to check manually. Is there any risk that changes to these files will break things?

**Comment by asbiin** [comment]
@DanielKim1 There are some files to change, but any of 'public/js/lang': these are generated files.
See https://github.com/monicahq/monica/pull/1875 for another example of life event misspell.
