### ISSUE TITLE
Contact List to Ability to Open Contact in New Tab

### ISSUE THREAD

**Issue by chrisspiegl** [monicahq/monica#1939]
When navigating to the `/people` page on Monica (online and self-hosted), I can only click the contacts one by one. The usual "CMD+Click" to open a contact in a new tab does not work, neither does a "Right Click + Open in New Tab".

Ideal behavior would be that both of these work as per usual to make managing multiple contacts easier without having to go back and forth all the time.

Thanks 💪

**Comment by asbiin** [comment]
Yes, this is done in #1888

**Comment by djaiss** [comment]
This has been merged tonight. Will be in production in the next days, and in a release soon.
