### ISSUE TITLE
2FA not necessary for mobile app

### ISSUE THREAD

**Issue by vandenheuvel** [monicahq/monica#1948]
I assumed that after setting up 2FA on app.monicahq.com, authentication for my account would require two things: the username-password combination and the 2FA code.

Yet, I just logged into the mobile app with just the username-password combination. This means that there is in fact no security benefit to setting up 2FA: obtaining just the username-password combination is enough to compromise an accounts data. Just install the app, and bypass 2FA.

Instead, I expect the 2FA code to be required for any access to my account, regardless of platform.

**Comment by asbiin** [comment]
Yes we are aware of that. 2fa is not yet required on OAuth login. The feature will be implemented soon.

**Comment by asbiin** [comment]
I've open #1950 to implement this

**Comment by vandenheuvel** [comment]
Great, thanks!
