### ISSUE TITLE
Successful pasword reset lands on 404

### ISSUE THREAD

**Issue by cllorca** [monicahq/monica#196]
Not sure if this is a bug in my instance or all instances, but I successfully reset a password when it redirected me to monicainstance.tld/home except /home doesn't seem to be a valid view/route so it returns a 404 instead. Went looking in the code to try to find where it redirects to /home but couldn't find it. Will gladly patch if I knew where the success redirect came from...

**Comment by djaiss** [comment]
Thanks a lot for caring. The fix has been pushed and is now in production. Sorry that you had to go through this error.

This is how I fixed it: https://github.com/monicahq/monica/commit/151347eb690b762467e638a0884cff96d86136a2

**Comment by cllorca** [comment]
Awesome!
