### ISSUE TITLE
Contact Page - "Last activity " field is missing since v2.9.0

### ISSUE THREAD

**Issue by sylvainmetayer** [monicahq/monica#1960]
I don't really know if this is a bug or if it is an evolution of the UI but on a contact page, before v.2.9.0, their was a field next to the tags, that indicate the last activity with this contact. This field is now missing. 

![azeae](https://user-images.githubusercontent.com/8873695/47608903-a4ee4280-da35-11e8-8444-dc3fba6b0237.png)

**Which version are you using:**
 - Self-hosted, v2.9.0

**Comment by asbiin** [comment]
This is fixed
