### ISSUE TITLE
Error 500 - file_put_contents : failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Bibabidu** [monicahq/monica#1963]
**Describe the bug**
I've got a new hosting package with a shared hoster and I'm trying to set-up Monica. I can finish the installation successfully, without errors from composer, but I can't access Monica through the browser. I'm getting an Error 500 in both Edge or Chrome. You can view the log results from the error log below. 

**Which version are you using:**
 - Shared hosting package with Monica 2.9.0

**Additional remarks:**
I suspect that the errors come from how the shared host sets up the file system. For me Monica is under /sub/monica/ but it seems that the web user accesses it under /var/www/vhosts/example.com/sub/monica/. This leads to the application not finding the files.  If added all possible paths to the allowed path as the error output complains about it, but this didn't help. Any ideas how to fix this?

**Error Log:**
> [Sun Oct 28 14:07:22.888634 2018] [proxy_fcgi:error] [pid 14066] [client 80.115.225.111:50407] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/sub/monica/storage/framework/views/6b45a78ab32886557d7b1c93032dbc8dd8e1af9e.php): failed to open stream: No such file or directory in /var/www/vhosts/example.com/sub/monica/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122\nStack trace:\n#0 /var/www/vhosts/example.com/sub/monica/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/vhosts...', 122, Array)\n#1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'file_put_conten...', '/var/www/vhosts...', 122, Array)\n#2 /var/www/vhosts/example.com/sub/monica/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/sub/monica/sto...', '<?php $__env->s...', 0)\n#3 /var/www/vhosts/example.com/sub/monica/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\\Filesystem\\Filesystem->put(...\nPHP message: PHP Fatal error:  Uncaught ErrorException: file_exists(): open_basedir restriction in effect. File(/sub/monica/storage/framework/views/6b45a78ab32886557d7b1c93032dbc8dd8e1af9e.php) is not within the allowed path(s): (/var/www/vhosts/example.com/:/tmp/:/sub/monica/storage/framework/views/:/sub/monica/storage/) in /var/www/vhosts/example.com/sub/monica/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:23\nStack trace:\n#0 /var/www/vhosts/example.com/sub/monica/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_exists(): ...', '/var/www/vhosts...', 23, Array)\n#1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'file_exists(): ...', '/var/www/vhosts...', 23, Array)\n#2 /var/www/vhosts/example.com/sub/monica/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(23): file_exists('/sub/monica/sto...')\n#3 /var/www/vhosts/example.com/sub/monica/vendor/laravel/framework/src/Illumi...\n'

Thanks a lot for your help!

**Comment by Scrxtchy** [comment]
I fixed this by clearning the cache/views/ etc from artisan. Regenerating my app key and setting up as production again fixed this problem, but now I'm getting other errors ;_;

**Comment by asbiin** [comment]
It could be a problem with the directories rights.
Change rights of `storage/framework` dir so php/apache can write in it.
