### ISSUE TITLE
v2.9.0: Attempting to pull up an entry with an outstanding debt owed errors out

### ISSUE THREAD

**Issue by virtadpt** [monicahq/monica#1977]
Environment: PHP v7.1, shared hosting (Dreamhost).
Version of Monica: v2.9.0 (tags/v2.9.0, from Git)
Attempting to load an existing entry for a person results in the framework throwing an error.  Debugging output is turned on in .env; stack traces copied to Pastebin:
* https://pastebin.com/F9L9NPgF (Class 'NumberFormatter' not found)
* https://pastebin.com/MkAUSeEG (Class 'NumberFormatter' not found)
* https://pastebin.com/zPn5FKwv (Class 'NumberFormatter' not found)

**Comment by asbiin** [comment]
Hi @virtadpt 
NumberFormatter is php class base, see http://php.net/manual/en/class.numberformatter.php
Do you have `intl` php extensions?

**Comment by sfbalg** [comment]
I don't know, I'll look when I get home.

**Comment by virtadpt** [comment]
I did not, but I enabled them using [Dreamhost's documentation](https://help.dreamhost.com/hc/en-us/articles/360003820252-How-to-enable-the-intl-extension) and that seems to have done the trick.

**Comment by asbiin** [comment]
@virtadpt is it working now? If so, we can close this issue.

**Comment by virtadpt** [comment]
It appears to be working now.  I've put it through its paces by updating some of my entries, and there are two copies of the Android app associated with it at this time.

I think it's safe to close it, but this is something that will need to be taken into consideration.  I'll probably write a post about using Monica before the end of the year that mentions these points.
