### ISSUE TITLE
Navigating to Journal causes "Whoops, looks like something went wrong." page.

### ISSUE THREAD

**Issue by lukefabish** [monicahq/monica#198]
Here's what happens:

- A few days ago I made a journal entry and saved it. All was well.
- Today I navigated to the journal page, and created a new entry.
- I added text for my entry and clicked save.
- I received an error page in response (see attached image below).
- Navigating to the journal page causes the error page to be displayed again.
- I logged out & back in again. I still get the error page when I navigate to the journal page.

I didn't put anything tricky in the journal entry.

Let me know if I can help out with more info. 

<img width="1177" alt="screen shot 2017-06-11 at 12 29 44 pm" src="https://user-images.githubusercontent.com/24521525/27007783-8cec624a-4ea2-11e7-842f-e6beb9ac7078.png">

**Comment by djaiss** [comment]
I'm going to check this right away. Sorry for the trouble 😢

**Comment by djaiss** [comment]
I've found the problem. Will submit a pull request and fix this soon.

**Comment by lukefabish** [comment]
Hey, really appreciate that. I can open the journal page without an error now, however a new journal entry I saved appears as below. Let me know if I can help out with more info.

<img width="1235" alt="screen shot 2017-06-11 at 11 27 54 pm" src="https://user-images.githubusercontent.com/24521525/27011393-16202e88-4efe-11e7-9c53-82d2aee91e5f.png">

**Comment by djaiss** [comment]
Have you updated the code and ran the migrations? We've fixed that yesterday.

`git pull origin master`
`php artisan migrate`
