### ISSUE TITLE
Undefined image in quick search results

### ISSUE THREAD

**Issue by RCady** [monicahq/monica#1985]
**Describe the bug**
When doing a quick search the results show an undefined image. This happens regardless of whether or not the contact has an Avatar assigned.

**Screenshots**
<img width="455" alt="screen shot 2018-10-31 at 9 24 12 pm" src="https://user-images.githubusercontent.com/12961794/47829153-0e32c600-dd54-11e8-8bbb-a0ebcbdeeeb7.png">

**Which version are you using:**
- Local environment on Master branch

**Additional context**
On line 54 of search.js we're checking if avatar_url is not equal to null when we should be checking if it is `undefined`. However, I think the issue might be a little more big than that. I don't believe that field is being returned via the API, at least on master branch.

**Comment by allanlw** [comment]
I am also having this issue on my local installation and on the official hosted version. All search results show no avatars and attempt to load `/undefined`, including ones that don't have avatars.

**Comment by LorenzoAncora** [comment]
> All search results show no avatars and attempt to load /undefined, including ones that don't have avatars.

@allanlw I have the same issue after upgrading `2.8.1` &rarr; `2.10.2`.
