### ISSUE TITLE
Upload avatar dialog states incorrect limit

### ISSUE THREAD

**Issue by mtlynch** [monicahq/monica#1988]
**Describe the bug**
The photo/avatar upload widget claims that the max upload size is "10 Kb." Kb = kilobit, so this would be 1.25 KB, which would be insanely small for a photo file.

Fortunately, Monica doesn't enforce a limit anywhere close to this (I uploaded a 258 KB file fine). Suggest removing this warning or matching it to the actual limit.

**Screenshot**

![image](https://user-images.githubusercontent.com/7783288/47890528-a056cf00-de25-11e8-9d64-aaebda8cbc34.png)

**Which version are you using:**

 - A server you maintain yourself: v.2.9.0

**Comment by asbiin** [comment]
I think it's because the `DEFAULT_MAX_UPLOAD_SIZE` var has recently changed from Mb to Kb.
We certainly could get the real max value from php config...
