### ISSUE TITLE
Pagination on the people page (/people)

### ISSUE THREAD

**Issue by fomojola** [monicahq/monica#1992]
Feature Request:
-----------------
Pagination (using jquery datatables or some other similar construct) on the /people page so it only loads 10/25/50/100 contacts at a time and the user can page through and/or search for specific people or sort in a specific order.

Background:
-------------
Just got started with Monica: I'm looking at a number of potential uses, but one of my use cases is trying to maintain a fairly massive contact list (I am up to 18000 contacts). I set it up self-hosted on a little VM and configured it alright, then wrote some Node.JS code to read my contacts (in a custom format) and import them into Monica, creating contact fields for the phone/email, addresses for the contact addresses and a note with the raw json so I'd be able to refer to it in the future for fields that don't have a natural storage place (I have a UUID attached to each contact that I currently store in the food_preferencies field as that is the only field searchable via the API that isn't in use for something else).

![screen shot 2018-11-02 at 11 23 10 am](https://user-images.githubusercontent.com/264253/47924272-b8643800-de91-11e8-9370-58d9ea3f3e95.png)

My import is still in progress (not the most efficient code, but I am at 16726 contacts as of this very moment). However, whenever I visit /people it tries to load all 16726 contacts into a single page: it takes quite a while to do, slows the browser down, and I may only be interested in a single contact.

**Comment by djaiss** [comment]
18 000 contacts?
My god, clearly Monica wasn't made for that.

That being said it's a nice use case and a good problem for us to solve.
We could probably do a table with Vue to paginate the listing, somehow. And have better search capabilities.

Let's make that happen (sooner than later).

**Comment by fomojola** [comment]
Thanks for the update: I am abusing it probably more than expected, but other than that I haven't had an issue, and once I got the /contactfields/ API bug fixed it actually wasn't bad. I had it on an undersized VM so I wasn't that worried. 

I'm not that familiar with Vue, but if I get past my primary exercise here and its still out there to build I can take a stab at it: I'm much more an old-school jQuery/AngularJS operator, but the new new thing can't be THAT much different. Objections to adding something like datatables? My first pass at Google turned up https://vuejsexamples.com/data-table-package-with-server-side-processing-and-vuejs-components/.

**Comment by ein-stein-chen** [comment]
@asbiin I think this can be closed as #2135 is merged and released in 2.15.0

**Comment by asbiin** [comment]
Thanks @ein-stein-chen
