### ISSUE TITLE
Docker (Compose) Environment

### ISSUE THREAD

**Issue by mattdavenport** [monicahq/monica#20]
This project would greatly benefit from a `Dockerfile`, as well as a `docker-compose.yml` for easy onboarding of new developers. I for one am unfamiliar with the Laravel ecosystem, so this would be of great help.

**Comment by djaiss** [comment]
I agree. I however have no knowledge at all concerning Docker and the creation of a Dockerfile. If the community could help here, that'd be awesome.

**Comment by HackToHell** [comment]
@djaiss I will work on this and will send a PR.

**Comment by djaiss** [comment]
This has been done. Refer to the README to see how it works.
