### ISSUE TITLE
Cannot Create Contacts

### ISSUE THREAD

**Issue by WonderingDane** [monicahq/monica#2002]
**Describe the bug**
After installing and creating my account, I am not able to create any contacts. I can click the "add contact", but the contact will never show up on the site.

**Which version are you using:**
 - Selfhosted 2.9.0

**Additional context**
I'm thinking the contact isn't added to the database, but no error is shown. I have edited .env to match the database and user created in the how-to.

Running it on Ubuntu 18.04 with PHP 7.2.

I followed this guide:
https://github.com/monicahq/monica/blob/master/docs/installation/ubuntu.md

**Comment by WonderingDane** [comment]
Trying to add a journal entry gives me the error:
_Whoops, looks like something went wrong._

**Comment by djaiss** [comment]
Please enable `APP_DEBUG=true` in the .env file and report the error you see here.

**Comment by asbiin** [comment]
Not enough information right now to solve this.
