### ISSUE TITLE
Linking 'How we met' to another contact results in broken links

### ISSUE THREAD

**Issue by scheidm** [monicahq/monica#2003]
**Describe the bug**
* I added my friend Gina
* I added my friend Ricky
* I attempted to add Ricky as the one who had introduced me to Gina on 'How did you meet'
* The link 'Met through Ricky' on Gina's page was https://app.monicahq.com/people/253068
* This link took me to https://app.monicahq.com/people/notfound saying he was not found
* Added Ricky to Gina as a friend.
* The link 'Friend Ricky' went to https://app.monicahq.com/people/h:8KM4NnBXkwOr4XvjQ3mp
* This link works fine.
Someone want to look into this?

**Screenshots**
https://photos.app.goo.gl/pEHaZWmAUnVsd5gd7
https://photos.app.goo.gl/X7j1MuTNA1wHKG1P7
The two different links

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Comment by asbiin** [comment]
Thanks for the report, we will look into this.
