### ISSUE TITLE
Conversations route points to debt controller

### ISSUE THREAD

**Issue by daniele-athome** [monicahq/monica#2011]
Clicking the "Log conversation" button brings you to the "create debt" page.

[Is this right?](https://github.com/monicahq/monica/commit/c8941e4a92a27d701057be1003df748300fcb405#diff-7e3ce459dfcc113722bdf4667ceffc11R154)

```
Route::resource('people/{contact}/conversations', 'Contacts\\DebtController')->except(['show']);
```

Using latest master on my own server.

**Comment by asbiin** [comment]
@daniele-athome You're right: I will fix it right away.
