### ISSUE TITLE
Class 'Ircop\Antiflood\AntifloodServiceProvider' not found

### ISSUE THREAD

**Issue by andreasjacobsen93** [monicahq/monica#2023]
Updating to v2.10.0 gives the following error:
`Class 'Ircop\Antiflood\AntifloodServiceProvider' not found`

I have tried installing the library with composer, but it times out.

How do I update my instance without getting error?

Edit: Downgraded again, for now.

**Comment by djaiss** [comment]
We had this error a few hours ago too.
We don't know why we had it. We had to remove a specific file to make it work. We are going to investigate.

**Comment by djaiss** [comment]
For info, we had to remove `bootstrap/cache/config.php`.
