### ISSUE TITLE
Can't add tag

### ISSUE THREAD

**Issue by rgaiacs** [monicahq/monica#2025]
I'm using https://app.monicahq.com/ and I can't add a tag.

# How to reproduce

1. Log in into https://app.monicahq.com/
2. Select one contact

![screenshot from 2018-11-12 15-21-35](https://user-images.githubusercontent.com/1506457/48356950-583e7480-e68f-11e8-8660-c845e4090c68.png)

3. Click on "Add tags"

![screenshot from 2018-11-12 15-21-19](https://user-images.githubusercontent.com/1506457/48356971-62607300-e68f-11e8-9f8e-4dd4484af11c.png)

4. Type something on the text box. And click on "Save"

# Current behaviour

No tag is displayed.

![screenshot from 2018-11-12 15-20-56](https://user-images.githubusercontent.com/1506457/48357033-80c66e80-e68f-11e8-9676-4bdcab477f71.png)

# Expected behaviour

Tags are add and updated.

**Comment by djaiss** [comment]
Ok, it might be a UX issue.
You need to add a tag by pressing `enter`.
Then the tag appears. Then you can press save.

Does that help? If so, we might change the UX a little bit.

**Comment by rgaiacs** [comment]
> Does that help?

Yes. Thanks.

> If so, we might change the UX a little bit.

Different platforms has different ways to add tags and I never now if I need to add "," or ";" or " " or press "TAB" or press "Return" ... If you listed the unfinished tag name as the top option would be easy to know that users are expected to press "Return" or click on it.

Feel free to close this issue and open another one for UX improvement.

**Comment by searoso** [comment]
> Ok, it might be a UX issue.
> You need to add a tag by pressing `enter`.
> Then the tag appears. Then you can press save.
> 
> Does that help? If so, we might change the UX a little bit.

I prepared to post a bug, but should try this - should help. For mobiles it's make sense to change the UX.

> **Describe the bug**
> Can't add tags to contact using AOSP Browser 8,1,0.
> A clear and concise description of what the bug is. If your comment is `it doesn't work`, we won't know what to do with it.
> 
> **Screenshots**
> If you can, add screenshots to help explain your problem. An image is always helpful.
> **Which version are you using:**
>  - Mobile version
>  - A server you maintain yourself (Version: 2.11.2)
> 
> **Additional context**
> Click _add tags_, input text, and clicking _save and close_ do nothing.
>

**Comment by al3x-huang** [comment]
Also had this issue in 2.14.0. Very confusing that I had to dig to find this but pressing enter does produce the expected behavior.

**Comment by surphil** [comment]
This one is really confusing, because next to the input is a "speichern und schließen" (sth like "save and close") link wich is clickable but does not work (behavior is like a "cancel" button.

**Comment by asbiin** [comment]
Agree with that. Would someone fill a new bug entry please?
