### ISSUE TITLE
Cannot open work information page on 2.10.0

### ISSUE THREAD

**Issue by mccollam** [monicahq/monica#2026]
**Description**
Clicking on "Update work information" on a contact causes the following error:

```
Whoops! Something went wrong.
Undefined variable: avatar (View: /home/forge/default/resources/views/people/_header.blade.php) (View: /home/forge/default/resources/views/people/_header.blade.php)
```

This occurs both on a self-hosted environment as well as monicahq.com.

**Details**
It appears to be an issue loading the avatar for this page.  Removing line 6 from `resources/views/people/_header.blade.php` ("`{!! $avatar !!}`") causes the page to open (though does, obviously, remove the avatar image from any page that uses this header).

**Comment by djaiss** [comment]
Sorry for this bug.
A fix is in progress, I'll push it today.
