### ISSUE TITLE
What is the purpose of moving away from font awesome for the new header icons?

### ISSUE THREAD

**Issue by tbirrell** [monicahq/monica#2034]
I upgraded to 2.10.1 and it included some icons for the new header card that are included as SVGs in a partial blade file. Near as I can tell, the other icons on the page are still font awesome. Is there a reason that you are starting to use custom SVGs? My concern is that it makes it difficult to match the style of the app whenever someone adds a custom element that did not come from `monicahq/monica`

**Comment by djaiss** [comment]
Yes, there is a reason. I want to get rid of external dependancies as much as possible. I'm not fan of where FontAwesome is going in terms of product - it's more and more complex and I don't want to have to deal with it. We are doing the same for other stuff too - we write our own Vue where we can, we get rid of Jquery, we write our own packages where it makes sense. The less dependancy we have, the better and simpler the product will be. The goal is not to reinvent the wheel - the goal is to avoid being dependant when we can avoid it.

So over time we'll replace FontAwesome by something we control entirely.

The new SVGs come form https://thenounproject.com and I'm confident that we can find any styles or icons that we need in the future.

**Comment by djaiss** [comment]
Also, good eye to have catch that ;-)

**Comment by tbirrell** [comment]
That is good to hear. I can support that. Thank you for the link to thenounproject. I hadn't heard of them before.
