### ISSUE TITLE
Cannot update conversations

### ISSUE THREAD

**Issue by mccollam** [monicahq/monica#2039]
**Description**
Attempting to update a conversation results in a `MethodNotAllowedHttpException` error.

**Steps to reproduce**
1. Create a new conversation entry for a contact.
2. Save the conversation.
3. Open the previously created conversation.
4. Add a new conversation item or update the existing one.
5. Attempt to save by clicking "Update".
6. Observe that an error occurs.

**Affected versions**
Observed on 2.10.1 on monicahq.com and 2.10.0 (self-hosted).

**Full error message**
(1/1) MethodNotAllowedHttpException
in RouteCollection.php line 255
at RouteCollection->methodNotAllowed(array('PUT', 'PATCH', 'DELETE'))in RouteCollection.php line 242
at RouteCollection->getRouteForMethods(object(Request), array('PUT', 'PATCH', 'DELETE'))in RouteCollection.php line 176
at RouteCollection->match(object(Request))in Router.php line 633
at Router->findRoute(object(Request))in Router.php line 622
at Router->dispatchToRoute(object(Request))in Router.php line 611
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 33
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 31
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 31
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 62
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 104
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 52

**Comment by mccollam** [comment]
(Duplicate of #2038 which came in as I was writing this up)

**Comment by allanlw** [comment]
@mccollam  FYI I opened a PR for fixing this too: #2040

**Comment by mccollam** [comment]
@allanlw cheers!
