### ISSUE TITLE
Database Changes and Optimisation

### ISSUE THREAD

**Issue by BranTurner** [monicahq/monica#204]
There are a few locations where the database can be cleaned up, and optimised slightly: 

1.  Redundant "surname" column in "contacts" table
2.  Do not strictly need "has_kids" column, you can just query if "number of kids" > 0
3.  Might be better to remove "number_of_reminders", etc. and query their respective tables and cache the result, then you don't need to store this information in multiple places. [Laravel's caching interface allows increment and decrement of these values.](https://laravel.com/docs/5.4/cache#cache-usage) 
4.  Could move the contact information (e.g. phone number) to its own table to solve #128. A `contact_type` and `contact_details` table, or something similar - this would work similar to how activities currently work. This would also allow the removal of the Twitter, FB, and LinkedIn profile links from the `users` table. 
5.  Column naming is strange in some places. Although you have a "currencies" table, in "gifts" there is a column named "value_in_dollars" - perhaps this should be currency agnostic? I have noticed this in the Monica front-end too. 
6.  In the 'activities' table the date column is named "date_it_happened" which presumes it happened in the past. Perhaps this should be changed to accommodate for #195 

Just a few suggestions that might help optimise things! @djaiss - if you agree with any let me know and I might have some time to work on a PR - and congratulations on making such a useful piece of software! :)

**Comment by djaiss** [comment]
Thanks a lot for this issue @BranTurner 

Advice: next time use the numbered list instead so it's easier to reply to each point. I've edited your issue so it's easier to answer.

That being said:

1. I agree. In the first version I used this field, but I decided to stop doing it when I launched it so it's less data to enter. We can remove it.
1. I agree. I don't know why I've don't this.
1. Yeah I agree too. I wanted to reduce the load of queries on the database, especially on the dashboard. Imagine when we'll have importers from Google Contacts for instance. People will introduce 500 contacts - if they do document them all, we'll have to run a big query on the dashboard to display the total number of X (kids, tasks etc...) for all the contacts. Do you have a better idea for this use case?
1. Ok we can move contact information to its own table, but not change the number of items for now per contact. If we do allow for multiple phones etc... I want to make sure that the UI allows for it first. Changing the DB structure for this is possible as a first step.
1. Totally agree. At first we only had dollars, so it made sense to have `value_in_dollars`. Currency agnostic is the key. On the front end, we've released yesterday multi currencies support. The codebase is far from being ideal, I know - this is why the community is there 😄 
1. If we want a date in the future, I think we need to think more about it than just changing the column name. It has much more complex impact.

Thanks a lot!

**Comment by BranTurner** [comment]
Thanks for the feedback :) 
Apologies for any confusion, I am not suggesting any feature changes, just modification of the database and underlying code to allow for implementation of the referenced features further down the line!

**Comment by alpedhuez** [comment]
Quick note on currency - while I can change the currency in settings and have it show up on the Debts page as £, on the contact profile page it still shows up as $

**Comment by djaiss** [comment]
@alpedhuez created this https://github.com/monicahq/monica/issues/332 Sorry about that.

**Comment by camdroid** [comment]
Not sure whether this is exactly the right place for this question, but why don't the database tables use any foreign keys? For example, I guess that `account_id` in the `activities` table should match the `id` field in the `accounts` table, but when I'm looking at it, I don't see anything enforcing that?

Could be wrong - I haven't poked around much, and I'm not familiar with Laravel. But just looking at the tables on my instance, I don't see any foreign keys or other constraints - was that an intentional choice?

**Comment by djaiss** [comment]
@BranTurner what do you think of closing this issue and open new ones with other improvements?

**Comment by BranTurner** [comment]
@djaiss Absolutely, feel free to close this! 

My only concern at the moment RE: databases is that there are a few large changes (e.g. allowing multiple phone numbers for contacts, allowing referencing of contacts within contacts, etc.) that need to be made to the database, and these be problematic without thorough tests.

I'm hoping to find some time to write tests for Monica soon - I've been saying I'll do it for a while now!

**Comment by asbiin** [comment]
Well done.
