### ISSUE TITLE
Link to Twitter profile

### ISSUE THREAD

**Issue by rgaiacs** [monicahq/monica#2044]
The link to Twitter profile is wrong on the version on https://app.monicahq.com.

![screenshot from 2018-11-14 11-24-57](https://user-images.githubusercontent.com/1506457/48479719-0cf7a380-e800-11e8-9e34-f253696eed1a.png)

The link points to `https://app.monicahq.com/people/jane.doe` instead of `https://twitter.com/jane.doe`.

**Comment by salsolatragus** [comment]
In `Settings > Personalization` you can set Twitter protocol to `https://twitter.com/`. Worked for me.

<img width="835" alt="screenshot 2018-11-14 15 48 19" src="https://user-images.githubusercontent.com/154050/48490081-e39d3e80-e824-11e8-8d91-5aa68ef9fd34.png">

**Comment by rgaiacs** [comment]
@salsolatragus Thanks for the info. Any reason for the protocol not be set by default?

**Comment by salsolatragus** [comment]
No clue, I'm just a user myself. Just happened to have found this workaround just the other day :)

**Comment by tbirrell** [comment]
I think the assumption is that you paste the full link into the field, not just the twitter handle, which would cause the link to echo twice if it was set in the protocol (`https://twitter.com/https://twitter.com/jane.doe`). Though, this could be solved with a mutator on the modal to get the best of both worlds.

**Comment by djaiss** [comment]
Thanks for the issue. This is nearly a bug, I would say, because you shouldn't have to find a workaround to make this work. We have to fix this.
