### ISSUE TITLE
View activity window does not permit clicking through to other people involved

### ISSUE THREAD

**Issue by scheidm** [monicahq/monica#2048]
Clicking users in the 'View' modal dialogue for an existing activity pops them off the list, the same effect as though you were in edit mode.

Reloading the page shows it does not effect the data, but it does prevent clicking through to other people involved in an event.

At the moment I can get around this by right clicking, but this seems like unexpected behavior.

**Comment by djaiss** [comment]
I see. This is an unexpected behaviour indeed. We need to make this better.
