### ISSUE TITLE
Wrong hashID on the Storage settings page

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#2050]
Bug report from a user:

```php
Whoops! Something went wrong.
Call to a member function hashID() on null (View: /home/forge/default/resources/views/settings/storage/index.blade.php)
```

**Comment by stevenirby** [comment]
I too am getting the same error, when navigating to the storage page in the settings:

https://app.monicahq.com/settings/storage

Login
Go to settings page
Click on Storage

See error from above.

**Comment by djaiss** [comment]
Fixed here https://github.com/monicahq/monica/pull/2094
