### ISSUE TITLE
Where are the uploaded files stored in Monica

### ISSUE THREAD

**Issue by anmol26s** [monicahq/monica#2056]
Hi
I saw that we can now upload files for the contacts.
Is the files are stored on the database or some directory. Yunohost package for Monica deletes the sources and restore the config file with new sources. If the files are stored in the some directory then Yunohost will require to backup that directory and restore it to new sources otherwise the uploaded files can be lost. If its stored in database then sorry for the noise, I wanted to be sure.

**Comment by anmol26s** [comment]
So if I don't update by git pull then taking backup of storage/app/public/documents is enough?

**Comment by asbiin** [comment]
@anmol26s you should backup the entire `storage` dir.

**Comment by anmol26s** [comment]
Thanks for the information.
