### ISSUE TITLE
Converting a named relationship to a real contact deletes it

### ISSUE THREAD

**Issue by Flimm** [monicahq/monica#2059]
If you add a relationship and fail to check "Create a contact entry for this person", the name is simply added to the side-bar. You can click "edit", and then check "create a contact entry for this person". If you do that, that contact gets deleted.

What I expected to happen: the contact gets converted to a real contact record.

**Comment by asbiin** [comment]
Indeed. It's really not an expected feature!

**Comment by djaiss** [comment]
This has been fixed. https://github.com/monicahq/monica/pull/2121
