### ISSUE TITLE
Why foreign key is account_id instead of user_id?

### ISSUE THREAD

**Issue by imageslr** [monicahq/monica#2063]
I found every table use account_id as foreign key. However, when I log in, I'm using `email` and `password` in `users` table. So can I just use `user_id` instead of `account_id` when design my database?

Why there is necessary to have an extra `accounts` table? What is that table for?

I have searched it for a long time yet I have not found any related resource. Could you please give me some direction? Any resource link would be great helpful.

Thank you in advance.

**Comment by tbirrell** [comment]
A server with an instance can have many accounts. And each account can have many users. I've always assumed it is this way because of the https://monicahq.com app. But if you wanted to set it up yourself for a group of people (like family or something), the accounts let you segregate the data so that others can't see other peoples stuff.

**Comment by djaiss** [comment]
Your explanation is correct @tbirrell 

Thanks for taking the time to answer!

**Comment by imageslr** [comment]
Thank you very much! @tbirrell @djaiss 

> And each account can have many users. ... But if you wanted to set it up yourself for a group of people (like family or something), the accounts let you segregate the data so that others can't see other peoples stuff.

So basically, this "account-user" mechanism is mainly designed for the purpose that one can invite other families to access and manage contacts, informations within one account. An account is for more than one people to share.Is that correct? Is that correct? 

So `users` table contains `login name` and `password` for a specific user, and `accounts` table contains `account_id` which all resources are divided by.

I will appreciate it if you could tell me whether I understand right. @tbirrell

**Comment by imageslr** [comment]
Thank you! @asbiin
