### ISSUE TITLE
Cannot enter activity date more than 10 years past

### ISSUE THREAD

**Issue by kairathmann** [monicahq/monica#2065]
When trying to enter an activity date more than 10 years past, submission fails with a validation error.

Using hosted version on 2018-11-17.

<img width="619" alt="screenshot" src="https://user-images.githubusercontent.com/925420/48663679-e0f45080-ea93-11e8-8870-f23b5f2d2fc9.png">

**Comment by djaiss** [comment]
Yes this was done on purpose. Do you remember what you did more than ten years ago?

**Comment by pqhf5kd** [comment]
> Yes this was done on purpose. Do you remember what you did more than ten years ago?

I don't but some people may be adding data from other sources (paper journals, text files, etc)
Actually there are a few events (on major holidays) that I have a vague memory of and would like to note them down before I completely forget them.

**Comment by kairathmann** [comment]
> Yes this was done on purpose. Do you remember what you did more than ten years ago?

Yes, because I was entering data from notes I had taden about someone I met twelve years ago.

**Comment by Venhaus** [comment]
@djaiss what was your intention behind this limitation? If people have old activities they'd like to enter, why not just let them? Seems unnecessarily restrictive to me. 🤔

**Comment by djaiss** [comment]
It was supposed to be a smart decision from a time where I didn't know better 🙈 

We can easily remove this limitation. I'll do it.

**Comment by djaiss** [comment]
This will be in the next release.
