### ISSUE TITLE
Dates of activities save as 1 day previous

### ISSUE THREAD

**Issue by jyrodgers** [monicahq/monica#2074]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
When I enter an activity with a contact and save it, the date on the date of that activity in the log is for the previous day. Example: If I enter the date of the activity as 2018-10-17 the activity in the log is 2018-10-16.

**Screenshots**

<img width="651" alt="screen shot 2018-11-20 at 2 58 11 pm" src="https://user-images.githubusercontent.com/4572538/48808232-04f2a480-ecd5-11e8-82db-8dfb1b41df2e.png">
<img width="871" alt="screen shot 2018-11-20 at 2 58 23 pm" src="https://user-images.githubusercontent.com/4572538/48808233-04f2a480-ecd5-11e8-96b6-9c2415702ffa.png">

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Comment by djaiss** [comment]
Oh I see what's going on here.
The date is correctly saved but timezone is taken into account when displaying the information - which is wrong somehow. We need to fix this.

**Comment by tbirrell** [comment]
There are two viable solutions to this problem as I see it.

1. Stop using `DateHelper` in `activity/index.blade.php`. 
2. Refactor `DateHelper` to allow skipping the TZ check for the various methods 

The first option fixes the immediate problem, though perhaps at the deteriment of consistancy.

The second option would look something like:

    public static function getShortDate($date, $faceValue = false)
    {
        $date = new Date($date, ($faceValue ? null : static::getTimezone()));
        $format = trans('format.short_date_year', [], Date::getLocale());

        return $date->format($format) ?: '';
    }

If we went that route, this should be done to all the `DateHelper` methods for consistancies sake, and would defult to existing behavor, so should not effecting anything. But it would allow us to display the datetimestamps at face value when necessary.

**Comment by johnriley** [comment]
Any update on this?

**Comment by danielbachhuber** [comment]
I've seen this issue too!

To confirm, the date stored is correct, but the display date is incorrect? If this is the case, then I'm experiencing #2192 too.
