### ISSUE TITLE
Error Importing vCards

### ISSUE THREAD

**Issue by thetrumper** [monicahq/monica#2085]
Hi! Sorry if I'm not doing this right. I'm new to GitHub.

I've noticed a bug in importing vCard contacts. The page will look like it's working and loading, but then go to another page that says "Undefined offset: 1"

I'm using docker so I made a new container with app_debug on and when it errored again it gave me the attached image (I covered up the phone numbers to preserve privacy). I'm wondering if it's erroring because the contacts only have the last name and a blank first name.

![error](https://user-images.githubusercontent.com/45055218/48881829-79b50400-ede5-11e8-9226-e822f02a1a8b.jpg)

**Comment by thetrumper** [comment]
I should add that going back to the dashboard of my site, some contacts are imported (39 in my case) and going to settings it shows that there is "still an import going on" and to wait a minute but nothing happens.

**Comment by thetrumper** [comment]
Update: it worked when I fixed all my contacts that just had a last name so that it was first name only or first and last name.

**Comment by Venhaus** [comment]
@thetrumper I encountered the same issue. Uploading a contact without a first name causes the entire import to be seemingly processed infinitely. 

<img width="840" alt="screenshot 2018-11-23 at 16 06 30" src="https://user-images.githubusercontent.com/19996174/48949865-c1e53b00-ef39-11e8-8299-070202c1fe04.png">
