### ISSUE TITLE
Empty dashboard image is missing

### ISSUE THREAD

**Issue by asbiin** [monicahq/monica#2088]
When dashboard is empty (no contact), we display a welcome message, with an image.
The image is missing:
![image](https://user-images.githubusercontent.com/25419741/48889237-72b5e200-ee35-11e8-8063-0d5e0907ad7d.png)

@djaiss This is due to removal of the image in#2067, and I'm pretty sure it was not your intention:
https://github.com/monicahq/monica/pull/2067/files#diff-616bf7e09893aa765b382b5f1125d7d6
You removed a lot of images that day, are they all to be removed?

**Comment by djaiss** [comment]
Damn. Not it wasn't my intention at all.
