### ISSUE TITLE
Memory usage increases rapidly, long loading times

### ISSUE THREAD

**Issue by trwnh** [monicahq/monica#2089]
On a VPS with 512MB - 1GB of RAM, it is inconvenient to see that Monica is using approximately 400MB of RAM just after loading 2 or 3 pages. I am self-hosting a personal instance on a Linode 1GB plan, and I'm noticing that there's some pretty bad performance and load times... It takes about 7 seconds to load a list of 2 people. It takes about 3-4 seconds for successive loads. Similar results with contact pages. In doing this, i notice Apache quickly balloons from 20-30MB of RAM usage to 200MB, 400MB, 490MB, 510MB, and rising. There is possibly a memory leak, or otherwise improper and inefficient usage of resources for resources that shouldn't change much and shouldn't require that much memory.

Here's an example network profile from Firefox: 
![image](https://user-images.githubusercontent.com/10606431/48927766-8184af00-ee9e-11e8-861e-ba48783c2061.png)

You can see a wait time of almost 6.5 seconds just attempting to load settings.

Here's systemctl status output:
![image](https://user-images.githubusercontent.com/10606431/48927811-d9231a80-ee9e-11e8-97ef-27897d712566.png)

You can see a usage of almost 580MB just after loading 2 contacts and some other settings / dashboard pages.

Here's /settings/api profiled:
![image](https://user-images.githubusercontent.com/10606431/48927854-2b643b80-ee9f-11e8-8a2c-c1a6bee3f07f.png)

5.3 seconds for initial load, a bit of a wait, and then another 2.3 seconds for extra loads.

**Comment by djaiss** [comment]
I think your installation has issues. I don't have those numbers at all in production. We are on a 2Gb Linode servers with literally thousands of users. My contact list of ~100 contacts loads in 2.4 sec and consumes 16.5Mb (on Firefox).

**Comment by trwnh** [comment]
That might be. I've since switched to using nginx directly instead of proxying to apache, and I'm getting much better results -- 741ms load, first GET finishes in 318ms, nginx process only using 6.6MB. Not sure if there's something wrong with my httpd.conf or with the way Arch packages apache, but I'm not too keen on fumbling around with apache to find out. Closing! :)

**Comment by djaiss** [comment]
😀
