### ISSUE TITLE
vCard import does not include contact photo

### ISSUE THREAD

**Issue by Venhaus** [monicahq/monica#2092]
When using the vCard import feature, a contact's photo is not added as their avatar. 

The responsible method `importPhoto` in `App\Services\VCard\ImportVCard` appears to be a placeholder:

```php
} elseif (starts_with($entry->PHOTO, 'data:')) {
    // Import photo image
}
```

**Comment by asbiin** [comment]
@Venhaus indeed. We are working on a new avatar handle backend, so this feature will be done later.

**Comment by alexriabtsev** [comment]
any chance this feature would appear in the nearest future?
