### ISSUE TITLE
Cancel button text in the profile editing view is left aligned on mobile

### ISSUE THREAD

**Issue by Venhaus** [monicahq/monica#2096]
**Screenshots**
Current Situation:
<img width="381" alt="screenshot 2018-11-25 at 22 59 25" src="https://user-images.githubusercontent.com/19996174/48985401-636db780-f107-11e8-98e5-289f09d5a0bb.png">

Should be:
<img width="380" alt="screenshot 2018-11-25 at 22 59 07" src="https://user-images.githubusercontent.com/19996174/48985407-6ff21000-f107-11e8-8af5-9f13b656d150.png">

**Which version are you using:**
Hosted, displayed on Safari on an iPhone X

**Comment by djaiss** [comment]
Thanks for the issue @Venhaus  and for the PR.
We'll merge it asap.
