### ISSUE TITLE
Auto-select "I know the exact birthdate of this person, which is" when date input is focused

### ISSUE THREAD

**Issue by TheActualWalko** [monicahq/monica#21]

**Comment by sid3windr** [comment]
Some more rationale about why to do this is in #341 (which I closed as it was effectively a dupe of this issue).

**Comment by djaiss** [comment]
Thanks for the suggestion. It's now in production!

**Comment by sid3windr** [comment]
This is either broken again, or not fully functional... Creating a contact still does not auto-refocus the radio button, losing birthday information.

**Comment by asbiin** [comment]
UI has changed
