### ISSUE TITLE
Debt: Literal "dashboard.for" should not be presented to the user

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#210]
For example adding a $999 debt owed to you (the user) by PersonA yields:

`PersonA: You are due $999 dashboard.for test debt description`

https://github.com/monicahq/monica/blob/master/resources/views/dashboard/index.blade.php#L160

I believe the fix is to change this:

```html
<span class="debt-description">{{ trans('dashboard.for') }}</span>
```

to:

```html
<span class="debt-description">{{ trans('dashboard.debts_for') }}</span>
```

**Comment by djaiss** [comment]
Thanks a lot!
