### ISSUE TITLE
Rate journal entry

### ISSUE THREAD

**Issue by andreasjacobsen93** [monicahq/monica#2102]
I often write a journal entry at the end of the day, and would like to rate my day too, but I don't like having the rating as a separate entry, since it often relates to what I wrote in the journal.

It would be nice if a journal entry could be rated, OR if it was possible to write an optional comment when you rate the day, which is showed together with the rating.

**Comment by djaiss** [comment]
Thanks for the issue @andreasjacobsen93 
This is a great idea. Definitely a good improvement that we could make.

Just so you know, in the future I'd like Monica to have great journaling capabilities. I imagine it to be a good competitor of an app that I really love, [Day One](https://dayoneapp.com/), and we will have all the data to make it possible (info about people, activities, mood, etc...)

**Comment by djaiss** [comment]
It's coming in the next release! Thanks for the idea.
