### ISSUE TITLE
setTags API call removes existing tags on Contact, when it should let them remain

### ISSUE THREAD

**Issue by mattdp** [monicahq/monica#2119]
I've written an API importer for my tags from a previous CRM, and noticed a strange behavior when getting ready to run it on my data.

In the API docs for Tags, it says setTags should not affect existing tags, simply add new ones if needed.

<img width="434" alt="personal crm - monica api documentation 2018-11-29 20-29-03" src="https://user-images.githubusercontent.com/1626189/49268655-9240a200-f415-11e8-8b17-3a3463adf83f.png">

However, when calling setTags from the API, I observed different behavior. Here's an example before:

![image](https://user-images.githubusercontent.com/1626189/49268684-be5c2300-f415-11e8-826f-ac1e9ee567b3.png)

and after

<img width="353" alt="after_settags" src="https://user-images.githubusercontent.com/1626189/49268690-c4520400-f415-11e8-8e13-5e6e72742a54.png">

Note that the latter two tags have disappeared.

Additionally, [in the relevant controller](https://github.com/monicahq/monica/blob/1f65b18a3c47b962fbc5b31eca93031ffeb85821/app/Http/Controllers/Api/ApiContactTagController.php), a comment in line 28 explicitly refers to detaching existing tags.

Please let me know when you have a chance to correct this behavior, so that I can run my importer nondestructively. Thanks for making such a great tool - I'm excited to have my full data in there!

**Comment by djaiss** [comment]
Thanks for the issue @mattdp. It's indeed a bug that I'll fix over the weekend.

**Comment by mattdp** [comment]
@djaiss Really appreciate the quick response, thanks! I look forward to testing the fix.

**Comment by djaiss** [comment]
Here we go.

**Comment by mattdp** [comment]
@djaiss Thanks for the quick fix! I'm really excited to use this, and have been checking every week - any estimation on when the next release will be (totally understood if you're taking a bunch of time off for holiday or general relaxation)? Thanks, and have a wonderful holiday + new year!
