### ISSUE TITLE
A better way to get a user avatar

### ISSUE THREAD

**Issue by AliN11** [monicahq/monica#2130]
Hi. In `App\Helpers\AvatarHelper` I saw that you put HTML code inside your PHP code. A better way is to separate HTML from your code by putting HTMLs in `resources/views` folder and then call them with `view('foo')->with($data)->render()`. 
If you are interested in this feature, I'll create a new pull request. Thanks.

**Comment by djaiss** [comment]
Thanks @AliN11 for your issue.
Indeed, this helper was a quick patch and is completely removed in the following PR #2112  😀
