### ISSUE TITLE
Adding Tabs in the Contact Profile

### ISSUE THREAD

**Issue by tbirrell** [monicahq/monica#2131]
Now that we have `Life Events` broken up from everything else via a tab, I was wondering if there is any plan in the future to break everything up into tabs. 

I think this would be a good idea since eventually the page will get really tall otherwise. I imagine between notes and activities, some contacts will get pretty crowded. And once people start importing conversations, this could get out of hand quickly.

So is this sort of thing on the roadmap? If not, is it a change that you would be open to?

**Comment by djaiss** [comment]
@tbirrell a new tab is coming in the coming days (the Photos tab, see #2132 )  😀

We won't have any choices than adding more tabs as we add new features.

**Comment by tbirrell** [comment]
Oh okay! Do you have any plans to split up existing features by tab? Or only new ones going forward?

**Comment by djaiss** [comment]
> Do you have any plans to split up existing features by tab?

Probably, yes, as we move forward - or by group of features of similar nature. I've been working on a redesign for months now trying to find the right approach for Monica but I still struggle with it. Therefore for now, we'll keep adding more tabs when it makes sense.

Which existing features would deserve to have his own tab in your opinion?

**Comment by tbirrell** [comment]
I've been experimenting with splitting notes and activities off into their own tabs on my instance since they are so tall. Vue isn't really my cup of tea though, so I don't have anything I can show off yet.

**Comment by djaiss** [comment]
Yeah I think the activity list can become really big at some point. I've been thinking of addressing that.

The initial design of Monica had each feature as a dedicated tab, then I switched to the current approach. I kinda like having everything on one page, but it'll be harder to keep this structure over time for two reasons
- we'll have more and more features over time, making the profile page super busy
- we'll have more and more content per feature over time, increasing the size of the page as well

But I like having all this on a single page.
In the past I also tried to redesign the page with this in mind. Take a look at this. Do you think this kind of structure would be better suited?

![summary - notes](https://user-images.githubusercontent.com/61099/49544409-ccdc8b80-f8a8-11e8-8080-25cf61926c12.png)

**Comment by tbirrell** [comment]
That's something like what I'm envisioning. I hadn't thought about moving profile navigation to the sidebar. That would definitely move away from the single-page idea in a way that tabs currently sidestep. However, the content box of the screen is very nearly identical to what I'm experimenting with. Is this from old code? Or just a mockup? If you have it laying around, is it publically visible?

That aside, I definitely agree that any comprehensive use of Monica will eventually necessitate a layout closer to this than an SPA.

**Comment by djaiss** [comment]
This is a mockup I'm currently working on. Purely design. I have other versions as well. It’s not public right now – I probably should make those mockups public somewhere. I just iterate a lot on them, trying to find the best solution for my vision. I don't think that in the future we can avoid having this kind of structure, considering how rich I envision some features to become. For instance, I see activities having a lot of metadata around it, with some nice graphs we could have, or filters etc... all of them taking a lot of real estate.

**Comment by tbirrell** [comment]
Oh okay. That makes sense. Do you anticipate this becoming a complete overhaul at some point? Or an iterative process on the current structure?

**Comment by djaiss** [comment]
Considering how much time we have each week available to work on the project, and considering that the core team has 2 members (me and @asbiin)... we can't do a complete overhaul in one big PR.

We will have to work iteratively on this.
