### ISSUE TITLE
Deploy to Heroku button

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#215]
We need to provide an official Deploy to Heroku button for people who want to host Monica on Heroku on a basic plan.

Documentation: https://devcenter.heroku.com/articles/heroku-button

The only problem I can see with this is how we can script the fact that we need a database, as Heroku only provides DB through addons. We need to investigate.

**Comment by BranTurner** [comment]
You can specify required addons in the [app.json](https://devcenter.heroku.com/articles/app-json-schema#addons) file. You would need to request a Heroku postgres instance, and then should be good to go!
