### ISSUE TITLE
Cannot delete account due to inexistence of contact_photo.account_id

### ISSUE THREAD

**Issue by jbiswas** [monicahq/monica#2159]
**Describe the bug**
When deleting an account in a fresh install of v2.10.2, I get the following error:

> SQLSTATE[42S22]:
> Column not found: 1054 Unknown column 'account_id' in 'where clause' (SQL: delete from `contact_photo` where `account_id` = 1)

I am running this on a local server with a checkout of v2.10.2 from git.

From my mysql DB, I get this:

```
MariaDB [monica]> describe contact_photo
    -> ;
+------------+------------------+------+-----+---------+-------+
| Field      | Type             | Null | Key | Default | Extra |
+------------+------------------+------+-----+---------+-------+
| contact_id | int(10) unsigned | NO   | MUL | NULL    |       |
| photo_id   | int(10) unsigned | NO   | MUL | NULL    |       |
| created_at | timestamp        | YES  |     | NULL    |       |
| updated_at | timestamp        | YES  |     | NULL    |       |
+------------+------------------+------+-----+---------+-------+
4 rows in set (0.01 sec)
```

**Comment by jbiswas** [comment]
Thanks @djaiss. I think I see what happened. I must've run setup:production. While I was still on the master branch and only after checked out the tagged version. Is there a way to use an older DB model without losing any data?

**Comment by djaiss** [comment]
I think it should work now with the new release.
