### ISSUE TITLE
Allow customization of life events types 

### ISSUE THREAD

**Issue by rolisz** [monicahq/monica#2163]
Similarly to how you can add custom genders and activities, you should be able to add custom life events. For example, I want to add one for when someone had a major health problem (heart attack for example).

**Comment by croulibri** [comment]
Would it be possible to add "participants" for life event too?
Indeed, in case of "changing house" or of "birth", this concerns often all members of a family. This would avoid copying the same event in all profiles of family members.

**Comment by ThisIsQasim** [comment]
Just found out about this amazing project. Deployed on my server and have been frantically documenting my friend's & family's life since. However just hit a blocker that I can't add custom life events (e.g. Graduation, Resignation, First Date, etc.) Has there been any progress on this?
