### ISSUE TITLE
Problems on first steps

### ISSUE THREAD

**Issue by simonszu** [monicahq/monica#2175]
I try to set up MonicaHQ via Docker, with a dedicated, non-containerized MariaDB. It turns out that i will have a bad time. 

At first i created an account for myself. The mail address i was using was "mail@simonszu.de". After submitting the form, i got an error that this mail address doesn't comply to some RFC guidelines (with text color light gray on white background - hard to read). This surprised me, since it is a very valid mail address. Nevertheless, the account was created. 

After that, i reviewed the settings and changed them according to my needs. Unfortunately, after submitting this form, i got a supposedly HTTP 500 error, with nothing more than "Whoops, looks like something went wrong."

Well, i'd like to debug what went wrong, but `docker logs -f monica` just shows the access log of the underlying web server, and no application or debug logs - so i created this issue now. I'm quite tech savy, but it looks like you need to fix your general user experience first ;)

Nevertheless, i'll be glad to help you to track down this issue. :)

**Comment by elasticrhu** [comment]
This error confused me at first too. It actually refers to the e-mail settings in your .env file rather than the one you submit on the webpage when you're creating an account.

**Comment by simonszu** [comment]
OK, but there is still the HTTP 500 Error when submitting the settings form.

**Comment by simonszu** [comment]
This was fixed in the more recent versions.
