### ISSUE TITLE
One off reminders broken

### ISSUE THREAD

**Issue by elasticrhu** [monicahq/monica#2176]
Currently there is a 23 in 24 chance of someones "**one off**" reminders being broken. The _send:reminders_ is scheduled for **every hour**.

However, the reminders will only be sent if the hour matches the exact hour the user set in "**Time of the day reminders should be sent**"

This would be fine, but the reminders are deleted after they have **attempted** to be sent. So if the crontab fires off at 1am and your reminders are set for 7am then they will be attempted and deleted at 1am but never sent because `1am != 7am`. As per:

`./app/Models/User/User.php` -> `isTheRightTimeToBeReminded()`

I think the best fix would be to only dispatch `SetNextReminderDate` after the notification has been sent rather than after it has been attempted.

**Comment by djaiss** [comment]
Oh!
Very good catch @elasticrhu.

I'll fix this very quickly.

**Comment by djaiss** [comment]
Actually reminders are also broken on other use cases. As soon as 2.11 is released, I’ll rewrite the reminder system entirely (again). I’m sick of it being so fragile. It should be resilient.

**Comment by elasticrhu** [comment]
To be honest, even something like this would make them workable for now:

```
diff --git a/app/Jobs/Reminders/ScheduleReminders.php b/app/Jobs/Reminders/ScheduleReminders.php
index 9bd89c61..34bc2aa2 100644
--- a/app/Jobs/Reminders/ScheduleReminders.php
+++ b/app/Jobs/Reminders/ScheduleReminders.php
@@ -47,7 +47,7 @@ class ScheduleReminders implements ShouldQueue
 
         if (count($users) > 0) {
             NotificationFacade::send($users, new UserRemindedMail($this->reminder));
+            dispatch(new SetNextReminderDate($this->reminder));
         }
-        dispatch(new SetNextReminderDate($this->reminder));
     }
 }
```

It would be great if they were only soft deleted/hidden too so that I can review old reminders - but that's more of a feature request! :smile:
