### ISSUE TITLE
Make gender optional when creating a contact

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#2179]
This has been requested by a lot of people and I think it makes sense. There is a lot of impact on the codebase though to make it work.

**Comment by tbirrell** [comment]
Default it to a third, unknown, gender. I do not think it is worth the amount of effort needed to allow it to to be `null`. 

Just take the translation strings for example. It would be easier to add `'people.whatever_unknown_godfather' => 'godparent'` than it would be to add `if($gender !== null)` everywhere to try to handle a `null` case.

**Comment by asbiin** [comment]
The main issue #1981 will resolve this.
