### ISSUE TITLE
Journal bug

### ISSUE THREAD

**Issue by webchun** [monicahq/monica#218]
Hi I tried to add a journal on monicahq.com and it returned some random characters
![image](https://user-images.githubusercontent.com/4277547/27015432-c9914d88-4f37-11e7-80ef-ad8e4227fd76.png)

**Comment by BranTurner** [comment]
This is a problem with encryption in the JournalController - I've submitted a pull request to fix this at #220. Thanks for pointing this out!

**Comment by djaiss** [comment]
![image](https://media.giphy.com/media/mHjBdBZuqBvJC/giphy.gif)

I'm sorry you encountered that bug.

**Comment by webchun** [comment]
niiice ;)
