### ISSUE TITLE
Activities date does not match was is entered, "back-steps" on editing activity

### ISSUE THREAD

**Issue by privong** [monicahq/monica#2192]
The "activities" entry and display seems to apparently incorrectly enter/display/edit the dates for activities. Every time the activities creation/editing window is entered, the date is shifted earlier by one day.

Steps to reproduce:
1. Add an activity for a particular date
2. The activity list on the user page shows the activity, but has it listed as the day prior to the one that was entered.
3. If the activity is edited, the date shown in the edit is the same as the page shown on the user page. If this is saved without changes, the activity gets bumped 

After step 1, the SQL database shows the following:
```
| 95 |          1 |             NULL | test                                                                             | NULL                                                                                                                                     | 2018-12-24 00:00:00 | 2018-12-24 05:13:13 | 2018-12-24 05:13:13 |
```

After step 3, it then shows:

```
| 95 |          1 |             NULL | test                                                                             | NULL                                                                                                                                     | 2018-12-23 00:00:00 | 2018-12-24 05:13:13 | 2018-12-24 05:16:13 |
```

The `date_it_happened` field is the one that changed. I wonder if this is some sort of timezone (configuration) issue. But it's not obvious to me why that might have this effect.

I am self-hosting monica and am running v2.11.0. This bug was also present in the previous version that I ran: v2.10.2. This appears to be related to #1813 and #2074. I am filing a new bug report since neither mention the issue of the activity date "back-stepping" on successive edits.

**Comment by djaiss** [comment]
This was fixed here https://github.com/monicahq/monica/pull/2241
It's live in production already, and should end up in the next release.

**Comment by djaiss** [comment]
(Also, sorry about this problem and thanks a lot for reporting it)
