### ISSUE TITLE
Reminder email is one day too late

### ISSUE THREAD

**Issue by rickpastoor** [monicahq/monica#2233]
Ok this is a bit embarassing.

I got a reminder email this morning. It does not contain the actual date of the birthday. The link to the profile is broken + it does not show on the dashboard (which I assumed was a bug), so I send my best wishes. After searching for my friend, it appears the the birthday of his son actually was yesterday.

<img width="726" alt="schermafbeelding 2018-12-31 om 08 24 51" src="https://user-images.githubusercontent.com/149958/50556144-92161980-0cd5-11e9-9a68-c4163cd97a41.png">

Here's the profile:

<img width="398" alt="schermafbeelding 2018-12-31 om 08 25 22" src="https://user-images.githubusercontent.com/149958/50556153-a528e980-0cd5-11e9-9ce8-965b11784568.png">

**Comment by asbiin** [comment]
I think this is fixed now
