### ISSUE TITLE
How to get the mobile app?

### ISSUE THREAD

**Issue by wilsonmar** [monicahq/monica#2238]
When I search for "Monica" and "Chandler" in the iPhone app store, I don't see the app.

**Comment by wilsonmar** [comment]
On page https://github.com/monicahq it says the Chandler mobile app is deprecated.

**Comment by Wulfheart** [comment]
[Here's](https://www.monicahq.com/blog/state-mobile-apps) a blog post regarding this topic.

**Comment by djaiss** [comment]
It'll come back. That's for sure. The problem is the lack of time :-/

**Comment by tbirrell** [comment]
@djaiss With a little spit and polish, we could clean up the web version to be easier to use on mobile. Granted it wouldn't be a replacement for the eventual mobile app, but it would be a relatively easy stopgap.

**Comment by joshuapinter** [comment]
This is my first time hearing about Monica. Not only is it Open Source but it's also Canadian! Fantastic!

I built a mobile app called [ntwrk](https://ntwrk.app/) a couple years ago as a side project. The goals are nearly identical.

Right now it's a free app with a paid Pro version but I've been pondering it's future. Maybe that's an integration with Monica or maybe it's open sourcing it entirely. 

Anyway, thought I'd leave a note here to share my appreciation of the project and my thoughts.

**Comment by issmirnov** [comment]
Thanks for the info. Could the official blog be updated? It pops up as the first result in Google, so other folks will also be confused.

https://www.monicahq.com/blog/mobile-application

**Comment by Flimm** [comment]
Yes, please update the official blog post, it still comes up in Google search.
