### ISSUE TITLE
Adding long contact causes notes, reminders to drop to bottom of page

### ISSUE THREAD

**Issue by aheinricy** [monicahq/monica#2242]
If you add a contact that is 39 characters or greater it causes the main section to drop down to the bottom of the page.

Steps to reproduce:
1. Under "Contact Information" click edit.
2. Click Add
3. Add contact type of "Facebook"
4. Add content of 39 characters (eg. https://www.facebook.com/xxxxxxxxxxxxxx)
5. Notice that main area moves down to bottom of page.

**Comment by djaiss** [comment]
Sorry about this. It kept happening but I never knew how to fix this. Now I know.
I'm going to fix it.
