### ISSUE TITLE
Navigating to a contacts page returns status 500 after adding a gift

### ISSUE THREAD

**Issue by eugiellimpin** [monicahq/monica#226]
I've encountered this twice already. Now I can't access two of my contacts. Here's how to reproduce:

1. Go to the contact's page
2. Add a gift
  - check "Gift already offered"
  - fill up "What is this gift"
  - add a value
3. Click Add

Weird thing is I can access the add gift form via `https://app.monicahq.com/people/<id>/gifts/add` but `https://app.monicahq.com/people/5188/` returns status 500

**Comment by BranTurner** [comment]
I think this is a database error, whereby the field length is too short so cannot accommodate the encrypted string. 

Either: 

1. Encryption of gifts details be avoided
2. Increase length of the field from 255 VARCHAR
3. Add validation to prevent overflow of encryption key

**Comment by djaiss** [comment]
We need to remove the encryption from the gifts table as well. This is just causing too many headaches. I'll take care of it today.

**Comment by djaiss** [comment]
This should now be fixed in production, thanks a fix pushed yesterday.

**Comment by djaiss** [comment]
Can you check if this is solved now and close the issue accordingly? Thanks

**Comment by eugiellimpin** [comment]
Thanks @djaiss! It's working perfectly now.
