### ISSUE TITLE
Add a sanity check for MAIL_FROM_ADDRESS

### ISSUE THREAD

**Issue by bendauphinee** [monicahq/monica#2261]
When registering for the first time after a fresh install, the system is unable to send the email and instead throws a stack trace.

After tracking this, it's because the .env var MAIL_FROM_ADDRESS default is not a sane email address. Either add a sanity check for this to warn the web-side user that this needs to be set, or change the default to some sort of noemail@somethingvalid.com address.

Sanity check would make more sense imho, but I don't know how to implement it.

**Comment by djaiss** [comment]
Thanks for the issue and the explanation. I actually don't know what a sanity check is in this context, so would you mind explaining what it would do?

**Comment by asbiin** [comment]
Maybe the default for `MAIL_FROM_ADDRESS` in `.env.example` should be empty, instead of something wrong. It will be easier to not use the variable if it's not set: in this case, the email will just not be sent.
