### ISSUE TITLE
Chandler deprecated?

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#2275]
Hey - this is a great project and I'd be happy to stay updated on its process.
So 2 questions really @asbiin @djaiss:

1. Is there a mailing list for this? Or a slack channel?
2. What happened to Chandler? Why is it deprecated?

**Comment by tbirrell** [comment]
https://www.monicahq.com/blog/state-mobile-apps
TL;DR, the main project sorta got away from the app, so now its easier to regroup at some point than try and play catchup.

**Comment by tomgs** [comment]
Oh I didn't know there was a blog! Is it listed on the repo's main page? Should probably add that somewhere...

Thanks!

**Comment by djaiss** [comment]
There is a mailing list but I suck at marketing so… I should use it more 😀 
https://tinyletter.com/monicahq

There is a slack but it's not really active actually. The best way to know what's going on is to follow the releases that we do every… half a month or so. https://help.github.com/articles/watching-and-unwatching-releases-for-a-repository/

**Comment by djaiss** [comment]
Also I'm starting to learn how to make a mobile app at the moment. I will have to take a little break from the web app to ship the mobile app. If only I had more free time… 😀
