### ISSUE TITLE
can't edit patronimic name

### ISSUE THREAD

**Issue by searoso** [monicahq/monica#2277]
**Describe the bug**
Imported a lot of contacts via VCard. Found a mistake in patronimic name (it's displayed in contact page and search). But no field to correct in _edit contact information_ page.

**Which version are you using:**
 - A server you maintain yourself (Version: 2.11.2)

**Comment by asbiin** [comment]
@searoso Can you give us some details? Screen capture for instance?

**Comment by searoso** [comment]
Sorry for being busy on other stuff. 

I can mailto:regis@monicahq.com the screenshot.

Btw, I switched to Monica service, but didn't correct the patronymic before import.
