### ISSUE TITLE
Update the Gender from (Man/Woman) to (Male/Female)

### ISSUE THREAD

**Issue by RayBB** [monicahq/monica#2297]
I would like the contact creation options to say Male/Female instead of Man/Woman. Man/Woman are sex but Male/Female are gender. [More info here.](https://en.wikipedia.org/wiki/Sex_and_gender_distinction)
It's a small distinction but I think it will mean a lot to those who care about this issue. It's also a little weird when adding my nephew to select "man" despite him being very young.

**Comment by tbirrell** [comment]
This is already self-editable. Go to `Settings` > `Personalization` > `Gender types`. And add/edit the genders to your heart's content. Djaiss would know better, but a brief look at the code makes this a fairly large change to bake into the app. Especially since the users can already customize it.

**Comment by RayBB** [comment]
Ah I didn't realize it could be changed. This is great!

Still think it may be worth baking into the defaults for inclusivity sake but I understand there are many requests.

**Comment by OrinSafko** [comment]
@RayBB I did the same thing. I just renamed man / woman to male / female.

**Comment by OrinSafko** [comment]
@trwnh Ah got it! I changed my setting back to Man / Woman instead of Male / Female, and now people are showing with the proper relationship. Thanks for cluing me in on this. I will leave them as the default Man / Woman for now then.

**Comment by asbiin** [comment]
I don't think this is a good idea.
The main issue #1981 will resolve this.
