### ISSUE TITLE
Docker (with Kubernetes)

### ISSUE THREAD

**Issue by fire** [monicahq/monica#23]
I'll be interested in creating a docker and kubernetes compatibile image for monica. Will be a bit busy though, so if it's not done feel free to do so on your own.

**Comment by fire** [comment]
It will be using postgresql.

**Comment by fire** [comment]
https://github.com/laradock/laradock seems active

**Comment by fire** [comment]
``docker run --name monica-postgres -e POSTGRES_DATABASE=monica -e POSTGRES_USER=homestead-e POSTGRES_PASSWORD=secret-e POSTGRES_ROOT_PASSWORD=secret -d postgres```

``docker run --name monica-postgres-test -e POSTGRES_DATABASE=monica_test-e POSTGRES_USER=homestead-e POSTGRES_PASSWORD=secret-e POSTGRES_ROOT_PASSWORD=secret -d postgres```

**Comment by fire** [comment]
Ignore the last post.

http://laradock.io/getting-started/#Usage seems to work.

**Comment by djaiss** [comment]
I've never tried to use Postgre instead of mySQL. I think it should work, thanks to Laravel though.

**Comment by fire** [comment]
Sorry, I refuse to contribute to AGPL software. Someone else will be willing to provide this.

**Comment by jdotjdot** [comment]
I'd be interested in potentially helping out with a Dockerfile and Helm chart. Is this something you'd be interested in?

**Comment by asbiin** [comment]
@jdotjdot We already have a [docker image](https://hub.docker.com/r/monicahq/monicahq/) and a [Dockerfile](https://github.com/monicahq/monica/blob/master/scripts/docker/apache/Dockerfile). I don't know about k8s, but you can try it?

**Comment by thies226j** [comment]
> I'd be interested in potentially helping out with a Dockerfile and Helm chart. Is this something you'd be interested in?

Did you get it to work? I do not know how to go about this. I had a working compose file and rendered it as a manifest with Kompose. That creates a PVC for the monica folder to hold the data, but this doesn't work, as there won't be an artisan file to run on startup. Running without the pvc works somehow but throws errors, as log files aren't writable.

**Comment by LuminousPath** [comment]
I have a chart that *works* but it's a work-in-progress, and relies on you already having a mysql setup. Planning on changing this to auto-create db instances if you want them sometime later though.

you can find it here: https://github.com/LuminousPath/charts/tree/master/monica

**Comment by thies226j** [comment]
> I have a chart that *works* but it's a work-in-progress, and relies on you already having a mysql setup. Planning on changing this to auto-create db instances if you want them sometime later though.
> 
> 
> 
> you can find it here: https://github.com/LuminousPath/charts/tree/master/monica

If you want me to, I could take a look at the chart and make an option for creating a db.

**Comment by crtaylor243** [comment]
The links to @LuminousPath's Helm charts are broken. Updated link: https://github.com/LuminousPath/helm-monica
