### ISSUE TITLE
Discussed Topics Journal

### ISSUE THREAD

**Issue by staeff777** [monicahq/monica#230]
As many of the commenters on HN I really like this idea. Two weeks ago I started my personally Logs in Evernote for exactly this purpose. There are already many features I never thought of, but which are quite practical.

My main purpose of this application would be to track the topics I discussed with my friends and families.
This is were the application currently lacks a bit.

I could add notes, but I don't think that's their real purpose and they are not well formatted.
I could also add remarks on activities, but they are then hidden and I don't want to add a new activity for each discussion I had with a colleague, for example.

I think that "Discussed Topics" this would make another good useful Item. Maybe this could even linked with the Journal. I could write I journal entry and link it with contacts. On the Contact page I could see Journal entrys linked with that Contact.

Those are more some thoughts instead of one feature request. Maybe you'll find a good solution within the philosophy of monica.

**Comment by Phrohdoh** [comment]
For what this is worth I use the activities functionality for just this.

I am curious why you don't want to add an activity for each discussion but would want to add a discussed topic entry.

The activities placeholder text is:
> Keep track of what you've done with Abigail in the past, and what you've talked about

**Comment by staeff777** [comment]
You are probably right.

The way I used it until now, the current implementation of activities hides the information of an discussion in the comment. (I'd like to format the text, e.g. a bullet list, or some paragraphs) 

Maybe, the easiest solution would be to make the "describe what you did field" a larger one.  It currently looks more like a headline. Until now I did not even thought about using this field for the information that where interesting for me.

I'd rather like to scroll through previous events and their content than opening each one of them separately.

__________
One idea for a far away version would be a free form field, that supports mentions, hashtags? (not sure if tags are useful), and other shortcuts for dates and tasks:

`Coffee with @Abigail, $yesterday. Talked about her mothers recovery. She was happy about it. !!call her $tomorrow!!`

**Comment by Phrohdoh** [comment]
Agreed that functionality such as that would be useful but is probably far-off.

Perhaps direct markdown support would be sufficient though I am not sure if sanitation of that is easy (but md itself isn't directly related to what you're after so I'll refrain from rambling about that).

**Comment by staeff777** [comment]
Ok. Let me finalize my now distilled thoughts into one feasible feature request:

Allow multiple lines in the "describe what you did" field.

**Comment by djaiss** [comment]
Definitely a priority in the next months.
