### ISSUE TITLE
 Click Settings Error, the error message is as follows:

### ISSUE THREAD

**Issue by ltsss** [monicahq/monica#2316]
local.ERROR: Class 'Collator' not found {"userId":1,"email":"222222@qq.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Class 'Collator' not found at /var/www/html/monica/app/Helpers/CollectionHelper.php:17)
[stacktrace]

**Comment by asbiin** [comment]
@ltsss Collator is a php class base, see http://php.net/manual/en/class.collator.php
You have to install intl php extensions.
See https://github.com/monicahq/monica/issues/1967
