### ISSUE TITLE
Can't edit contacts

### ISSUE THREAD

**Issue by lydgate** [monicahq/monica#2324]
Hey, love the app but I'm having a problem!

**Describe the bug**
When I click the "Edit Contact Information" on any contact, it briefly flashes up a form, which then disappears, and I'm left on a page that just has the header and footer. Browser is chromium on Linux, also tried it on a chromebook with all plugins disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/771/51531700-1a4f9080-1e36-11e9-95b1-9f72a059e495.png)

**Which version are you using:**
I'm running the latest git in Docker with an external database, though the bottom of the pages say 2.11.2. 

**Additional context**
Happens on every contact, not just one.

**Comment by asbiin** [comment]
This might be related to a glitch that will be fixed in #2318

**Comment by asbiin** [comment]
I've copied the fix in #2325 to merge it right now.

**Comment by lydgate** [comment]
Yep! contact-edit-2019-01-22 fixes it for me :)

**Comment by asbiin** [comment]
Nice, thanks for the feedbacj @lydgate
