### ISSUE TITLE
Can't add people to activities

### ISSUE THREAD

**Issue by lydgate** [monicahq/monica#2327]
Great project guys! Having an issue with multi-people activities.

**Describe the bug**
I can successfully create an activity with an individual. However if I try to add another to the "Who was involved?" list, then it successfully searches, but when I click any name it takes me back to the dashboard, aborting the activity creation. If I create it without anyone, the creation works.

This happens whether I am creating or editing the activity. The end result is that I can only create activities with one person. From the log looks like I get a 302 redirect):

`172.17.0.1 - - [22/Jan/2019:12:26:07 +0000] "POST /people/search HTTP/1.1" 200 755 "http://localhost:83/activities/add/h:9qyA7LJYWZ18mVavMj" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
172.17.0.1 - - [22/Jan/2019:12:26:08 +0000] "GET / HTTP/1.1" 302 360 "http://localhost:83/activities/add/h:9qyA7LJYWZ18mVavMj" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
172.17.0.1 - - [22/Jan/2019:12:26:08 +0000] "GET /dashboard HTTP/1.1" 200 14184 "http://localhost:83/activities/add/h:9qyA7LJYWZ18mVavMj" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
172.17.0.1 - - [22/Jan/2019:12:26:08 +0000] "POST /dashboard/setTab HTTP/1.1" 200 - "http://localhost:83/dashboard" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
172.17.0.1 - - [22/Jan/2019:12:26:08 +0000] "GET /dashboard/calls HTTP/1.1" 200 91 "http://localhost:83/dashboard" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"=`

**Which version are you using:**
Self-hosted, latest git.

**Additional context**
Not sure if there's any way to add individuals besides clicking? Hitting enter just takes me to the next field.

**Comment by lydgate** [comment]
Still happening with the latest git.

**Comment by LukasRos** [comment]
After the latest update on app.monicahq.com I can no longer add people to individuals. Clicking on a name to select it causes a navigation back to the dashboard. Tested with multiple browsers.

**Comment by psteinweber** [comment]
Same here.

**Comment by asbiin** [comment]
I confirm. We will fix this ASAP

**Comment by asbiin** [comment]
OK this is fixed now, on app.monicahq.com too.

**Comment by LukasRos** [comment]
Thanks for fixing this so quickly! Though, another issue has appeared: I can select the contacts now, but I can't save the updated activity:

"Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`monica`.`activity_contact`, CONSTRAINT `activity_contact_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE)"

This happens when updating an activity, not while creating a new one, it seems. I've sent a bug report through Sentry, too.

**Comment by asbiin** [comment]
@LukasRos your right, updating an activity to add a people to this activity won't work. I saw your feedback on sentry too, thanks you for that.
I'm fixing it right now.

**Comment by asbiin** [comment]
OK this is now fixed on app.monicahq.com
