### ISSUE TITLE
Country Dup: United States listed Twice

### ISSUE THREAD

**Issue by blindly** [monicahq/monica#233]
![country](https://user-images.githubusercontent.com/1953656/27039674-94979d74-4f5c-11e7-93b6-6ba5a295c489.PNG)

When editing a contact and selecting country, "United States" is listed twice.

**Comment by colourgarden** [comment]
United States is listed twice in the [countries table seed](https://github.com/monicahq/monica/blob/master/database/seeds/CountriesSeederTable.php#L221).

I don't know Laravel well enough to know whether just changing this file will alter the `<select>` on the front-end or if a script needs to written to remove it from the DB as well (@djaiss).

**Comment by BranTurner** [comment]
Removing it will work just fine - but reseeding the DB will be required after the update. I just submitted a pull request #238.

**Comment by colourgarden** [comment]
Additional PR submitted to reorder the countries by ISO code to improve readability - https://github.com/monicahq/monica/pull/239
