### ISSUE TITLE
AGPL doesn't align with a portion of the README

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#234]
In the README you have:

>You have the liberty to clone the repository and set it up yourself on any hosting provider, for free. I'm just asking that you don't try to make money out of it yourself.

The AGPL (in fact all GPLs) explicitly allow others to make money.

If your license is AGPL + no commercial offerings (outside of your eventual commercial product) that should be made more clear.

This is your software and as such you have the right do what you like with it regardless of the license others must follow but your statement reads a bit oddly to me.

It sounds like asking for free work from the community without someone (an individual, company, etc) being able to profit from the community (except yourself).

I don't mean this to sounds harsh if it has at all come across like that. I'm just asking for licensing clarifications.

**Comment by djaiss** [comment]
To be clear I've never asked for the community to provide free work, at all. This was not my intention when I open sourced it. My goal, by open sourcing it, was to allow anyone to install it on their own servers, and also let people see that I don't do anything evil in the codebase. I was absolutely mind blown to see so many people caring about the project and contributing.

Sorry if I gave the wrong impression. I'm planning this week to make sure I put the right license in place. I'm still unsure which one it should be.

My plan is clear: I'd like to generate some revenues out of this tool so I can sustain it on the very long run. I also plan to continue letting anyone install it on their own server for free, without me having any kind of control on it, even when I'll have a paid plan on .com. For this I'm looking to what Wordpress, Sentry and GitLab do, for instance. I'm a big fan of their business model, where everyone wins basically.

**Comment by Phrohdoh** [comment]
Fantastic to hear!

So far I am loving the product and would even pay for it so I wasn't at all trying to imply you shouldn't profit from it.

AGPL is what you want if you want to be sure that upstream MonicaHQ can always benefit from all changes made by any private host/instance.

MIT is extremely liberal and (as a result) business friendly (most businesses avoid GPLs like the plague).

**Comment by ocdtrekkie** [comment]
Discussion is still kinda ongoing in #38.

I think the biggest thing @djaiss may need is a CLA, so that he has options to do proprietary things with his own project, while limiting others from doing the same. As in discussion #38, I urge him to decide on this sooner rather than later, because arguably, each additional PR he merges can add to the complexity of ensuring his code rights are in order.

**Comment by Phrohdoh** [comment]
Yes a CLA is the right step for @djaiss but, as noted in the noted issue, you cannot build something truly open source and legally prevent commercial usage.

**Comment by Nebucatnetzer** [comment]
I personally wouldn't mind if I couldn't use it commercially as long as I could host it myself and there isn't something like a "Pro" version which profits from the contributions and contains exclusive features.

**Comment by Phrohdoh** [comment]
Thinking about this a bit more I'm not sure an explicit CLA is necessary.

See section 11 "Patents" of the AGPLv3 text.

> 11. Patents.

> A "contributor" is a copyright holder who authorizes use under this
License of the Program or a work on which the Program is based.  The
work thus licensed is called the contributor's "contributor version".

> A contributor's "essential patent claims" are all patent claims
owned or controlled by the contributor, whether already acquired or
hereafter acquired, that would be infringed by some manner, permitted
by this License, of making, using, or selling its contributor version,
but do not include claims that would be infringed only as a
consequence of further modification of the contributor version.  For
purposes of this definition, "control" includes the right to grant
patent sublicenses in a manner consistent with the requirements of
this License.

> Each contributor grants you a non-exclusive, worldwide, royalty-free
patent license under the contributor's essential patent claims, to
make, use, sell, offer for sale, import and otherwise run, modify and
propagate the contents of its contributor version.

**Comment by ocdtrekkie** [comment]
@Phrohdoh Well, the issue is, if at some point @djaiss wants to commercialize the project, he may wish to do things which fall outside of AGPL. That section simply ensures that the contributions are also licensed under AGPL. It doesn't look like it grants any permission to relicense, dual license, or anything similar.

I suppose the biggest question @djaiss needs to answer is how he wants to potentially monetize the project, so he can make sure his needs are covered, and then permit everything else.

**Comment by djaiss** [comment]
I think I'll let the AGPL actually.

I want everyone that contributes to use it for free. This is the path I'm following:

- there will be a paid plan
- the software will be downloadable by anyone and the downloadable version will be the paid version - that means if you do host it yourself, you will actually have the "pro" version.
- if you do contribute on GitHub with PR, you will be able to use the .com version for free as well (you'll have a special flag or something in your account).

**Comment by Phrohdoh** [comment]
In that case this needs to be removed from the README as the GPL proper family of licenses explicitly allows you to monetize.

> I'm just asking that you don't try to make money out of it yourself.

**Comment by ocdtrekkie** [comment]
@Phrohdoh Arguably, he can "ask" regardless of the license. He just legally wouldn't be able to go after someone who disregards his request.
