### ISSUE TITLE
"The vcard failed to upload"

### ISSUE THREAD

**Issue by ehrlichja** [monicahq/monica#2354]
**Describe the bug**
Attemping to upload a vcard exported from mac Contacts. 9 contacts in the file, 3.9mb.

If I upload one at a time, or 2 at a time, it works.

**Screenshots**
![screen shot 2019-01-27 at 11 14 40 pm](https://user-images.githubusercontent.com/481499/51820045-69a81d80-2289-11e9-9d26-b3bb588f19fc.png)

**Which version are you using:**
Just pulled the latest monicahq docker container.

**Additional context**
Could this be a memory error? This is a shared, 2gb VM.

**Comment by asbiin** [comment]
Is it still the case now?

**Comment by tuxone** [comment]
Hi, 

I have the same issue with version 2.14.0 on a 1gb VM. Can't find any hint through logs.
