### ISSUE TITLE
How to update Monica docker container?

### ISSUE THREAD

**Issue by ROODAY** [monicahq/monica#2356]
Monica keeps telling me there's a new version available, but I can't seem to find instructions for updating the docker container version. Can someone point me in the right direction?

**Comment by Pitasi** [comment]
Maybe you just need to pull the updated image and recreate the container? Just guessing, didn't have the chance of trying it by myself.

You can also check available versions in the Docker hub: https://hub.docker.com/r/monicahq/monicahq/tags

**Comment by asbiin** [comment]
This is not a specific monica question.
You will find some help here: https://stackoverflow.com/questions/26734402/how-to-upgrade-docker-container-after-its-image-changed
