### ISSUE TITLE
Updated italian translation

### ISSUE THREAD

**Issue by Pitasi** [monicahq/monica#2359]
Hi, thanks for this great project. While I just started using it, I immediately realized that the Italian translation was less than half complete - and most of the sentences didn't make a lot of sense at all.

I basically translated everything, but only now that I completed my job I stumbled on the fact that I just can't upload the file to crowdin directly. So I'm gonna upload it here and hopefully a mod can do it for me :)

Probably there are still some rough edges, I did my best and I'll continue updating it on crowdin whenever I'll have the chance, using Monica should give me more context for each sentence.

Thanks,

[lang_it.tar.gz](https://github.com/monicahq/monica/files/2804994/lang_it.tar.gz)

Antonio.

**Comment by asbiin** [comment]
@Pitasi I've uploaded all of your translation in [crowdin page](https://crowdin.com/project/monicahq/it#).
Be aware that this is not the standard process ...
If you want to add some translation or fix others, it would be great and useful for us !
Thank you.
