### ISSUE TITLE
Resend verification email?

### ISSUE THREAD

**Issue by ehrlichja** [monicahq/monica#2378]
I received the verification email from my instance but it expired. How do I resend?

**Comment by ehrlichja** [comment]
Any tips in general about troubleshooting email? I have spent a bunch of time trying to make sure every config value is entered correctly, quoted, etc. Any way to see some logs or trigger a test email?

**Comment by asbiin** [comment]
> trigger a test email

That I want to add in the admin panel, see #1876

**Comment by asbiin** [comment]
Resend verification email is already possible if you try to log in.
