### ISSUE TITLE
Key path does not exist or is not readable

### ISSUE THREAD

**Issue by ROODAY** [monicahq/monica#2385]
I'm trying to use the Monica API to get view my journal entries, so I followed the API documentation but ran into the following error:
```
Key path "file:///var/www/monica/storage/oauth-private.key" does not exist or is not readable
```
The error shows up when I try visiting https://mymonicaurl.com/api/journal, and also when I tried creating a  personal access token in the settings page. I'm not sure what to do about this as I'm running Monica in a docker container, and it would seem that this path that's being referenced is inside the container.

**Comment by ein-stein-chen** [comment]
I don't run Monica inside a docker-container but I guess that something like: 
```
docker-compose run monicahq shell
php artisan passport:install
exit
```
could do what you need.
See: [Documentation for docker installation](https://github.com/monicahq/monica/blob/master/docs/installation/docker.md#use-docker-compose-to-run-a-pre-built-image)
and [Ubuntu Generic Installation - 3. Configure Monica - Point 6](https://github.com/monicahq/monica/blob/master/docs/installation/ubuntu.md#3-configure-monica)

**Comment by ROODAY** [comment]
Thanks, that did the trick!
