### ISSUE TITLE
ErrorException: Trying to get property 'contact' of non-object 

### ISSUE THREAD

**Issue by justsomebody42** [monicahq/monica#2388]
**Describe the bug**
This error started to show up on my Dashboard just recently.
The list of birthdays is unchanged to when it was working.

**Which version are you using:**
Selfhosted. master, commit e9b28661

**Additional context**
I added:
`                @if (!is_object($reminderOutbox->reminder))
                    @continue;
                @endif
`
in resources/views/dashboard/_monthReminder.blade.php as a workaround.
When I printed $reminderOutbox->planned_date to see if an existing birthday was missing, I saw that the same birthday showed up twice. 
The first line without reminder object, the second line showed up fine.
Maybe this helps to find the cause...

**Comment by jatls** [comment]
I experience the same bug and have used your same workaround in the meantime.

**Comment by justsomebody42** [comment]
Fixed here: https://github.com/monicahq/monica/pull/2502
