### ISSUE TITLE
Description is not saved

### ISSUE THREAD

**Issue by LukasRos** [monicahq/monica#2390]
I tried creating new contacts and editing contacts in the hosted version of Monica. I found the following bugs:
- photo uploads fail, an S3 URL is generated but that URL shows "Access Denied" when trying to access it directly
- any value entered in the description field is not saved and/or not displayed

**Comment by LukasRos** [comment]
I take the first bug back, the photos appeared after some delay. But the other bug remains.

**Comment by reverendrainwater** [comment]
I cannot add, remove, or change the description of contacts either. Using the hosted version.

**Comment by asbiin** [comment]
Hello. It's fixed now, even on app.monicahq.com
