### ISSUE TITLE
Importing data

### ISSUE THREAD

**Issue by cynddl** [monicahq/monica#24]
It would be nice to have options to automatically populate the database from either files (eg. CSV) or third parties (eg. Google Contacts with the [People API](https://developers.google.com/people/)).

**Comment by nitinthewiz** [comment]
Second this. If nothing else, a contacts list CSV import would do wonders...

**Comment by mkaz** [comment]
I created a PR #60 which adds Google CSV import, would love some eyes on testing it out.

**Comment by asbiin** [comment]
We have now multiple ways to import data with csv of vCard.
