### ISSUE TITLE
Adding conversation with no messages shows error but succeeds

### ISSUE THREAD

**Issue by stephen304** [monicahq/monica#2401]
When logging a conversation without adding any messages, the page displays an error when attempting to save, but it actually successfully saves. (I don't add messages to conversations because I only want to log that I talked to that person that day, so I can make sure I am interacting with everyone I need to regularly)

**Screenshots**
![2019-02-08-123956_1432x1164_scrot](https://user-images.githubusercontent.com/981915/52495541-fd89bb80-2b9e-11e9-9bf8-eef5c190fbdd.png)
![2019-02-08-124008_1706x276_scrot](https://user-images.githubusercontent.com/981915/52495542-fd89bb80-2b9e-11e9-9f0e-216d34242628.png)

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Note**
The screenshot shows "How did you communicate" to be blank, but it actually just changes to blank after pressing submit.

**Comment by fmalk** [comment]
Same thing happens to me on a 2.14.0 self-hosted version.

Person's page request for https://selfhosted/people/h:xyzabcde/conversations returns newly added objects:

![image](https://user-images.githubusercontent.com/208820/61670407-f2909680-acb9-11e9-94d2-c2d40c5856a9.png)
