### ISSUE TITLE
Save contact tags in (CardDAV) vCard 'CATEGORIES' field

### ISSUE THREAD

**Issue by ein-stein-chen** [monicahq/monica#2412]
**Is your feature request related to a problem? Please describe.**
Adding tags to a contact in the monica site won't result the tag being added to the vCard and thus not beeing synced to the CardDAV client.
Viceversa: A category/tag added to a contact with a CardDAV client (like Thunderbirds CardBook addon) won't be added in monica as a tag and will delete the category in the client after a change of the contact in monica.

**Describe the solution you'd like**
Use the vCard field 'CATEGORIES' [1] to store the tags. This would fit perfectly as [1] states: 

> 6.7.1.  CATEGORIES
>   Purpose:  To specify application category information about the vCard, also known as "tags".

[1] https://tools.ietf.org/html/rfc6350#page-43

**Comment by asbiin** [comment]
Thank you for the feedback @ein-stein-chen 
This is an interesting idea, I will look at this soon.
