### ISSUE TITLE
no avatars after recent update

### ISSUE THREAD

**Issue by jfnklstrm** [monicahq/monica#2420]

**Comment by jfnklstrm** [comment]
After updating monicahq I can no longer see any avatars. When i ssh into my server I can see the images in the folder - but in the app there is an empty image holder. Anynone with the same problem? Anyone solved it?

**Comment by asbiin** [comment]
Did you ran `php artisan monica:update`?
Which version did you had before the upgrade?
Is it a symlink for 'storage' in public dir? It should redirect to the storage/app/public directory.

**Comment by jfnklstrm** [comment]
Yes, I ran the script and all went well but the avatars. I went from 2.6
directly  to the 2.12 release. Maybe that is bad practice for updating. I
ran it on Centos. 7

-- 
Jofen Kihlström

På 11 februari 2019 till 19:10:41, Alexis Saettler (notifications@github.com)
skrev:

**Comment by jfnklstrm** [comment]
Whiped the droplet and reistalled v2.12.0 directly - but still same issue. The software runs fine exept for the lack of avatars. When I try to open just the image in a new tab I can see that the software is looking in /storage/avatars/
Tried to run the update script to see if that resolved any issue - but no such luck. Anyone having any ideas to try out. Right now I run it on a VM to iron out the kinks before running it as critical app. So Im all ears for experiments that might make Monica work properly...

![error monica](https://user-images.githubusercontent.com/47507719/52818983-7198f780-30a8-11e9-91df-eda3be02592c.png)

**Comment by jfnklstrm** [comment]
I have looked further - and maybe Im on to something (but Im new to Centos so I need som help fixing it). I get an error about the php-gd module not being installed. My problem is that I don't know how to update a specific module or even getting it registred in the system.

**Comment by asbiin** [comment]
Not enough information to solve this right now.
