### ISSUE TITLE
Journal does not load

### ISSUE THREAD

**Issue by LukasRos** [monicahq/monica#2423]
When I go to the journal view, the page is empty, it only shows that it loads content. But I can confirm with developer tools that the entries were fetched from `/journal/entries` correctly, they're just not displayed.

**Comment by pqhf5kd** [comment]
My journal is only showing Journal Enteries and not Activities.

@LukasRos do you have any Journal Enteries?

**Comment by LukasRos** [comment]
@pqhf5kd I use only activities.
