### ISSUE TITLE
Dutch translations needs checking

### ISSUE THREAD

**Issue by IcyPalm** [monicahq/monica#2437]
Sorry if this is not a proper topic for an issue but this seemed the best way to communicate this.

Over the past few weeks I have been completing the translation of Monica to Dutch and it is done.(for now at least)

It is not perfect, I tried my best but I think it needs to be used to fine-tune the translation and specific tone. 

Is there a way to notify other Dutch translators to check my suggestions?

**Comment by asbiin** [comment]
Every translation is handle in crowdin.
See https://github.com/monicahq/monica/blob/master/docs/contribute/translate.md
