### ISSUE TITLE
Missing custom icons for contact fields

### ISSUE THREAD

**Issue by ein-stein-chen** [monicahq/monica#2452]
**Describe the bug**
When adding a icon to a custom contact field the icon never shows up. Not in the 'Settings > Personalization-page and also not in the contact-page. (See screenshots)

**Additional context**
The problem here is a little difference in css. For comparison a working and not working icon from the Firefox inspector:

_Working icon:_
![Working Icon](https://user-images.githubusercontent.com/17032639/52914122-c913af00-32c4-11e9-93de-e27bd3db8e61.png)

_Not working icon:_
![Not working icon](https://user-images.githubusercontent.com/17032639/52914127-d5980780-32c4-11e9-9162-a11997585785.png)

For the working icons there are entries in the app-ltr.css file linking the icon-class (.fa-address-card-o) to the associated unicode character:
![app-ltr.css](https://user-images.githubusercontent.com/17032639/52914163-5d7e1180-32c5-11e9-9681-0925c3d550f1.png)

An basic ugly fix is to add for every custom item you use an additional css rule and import them. (in my case into the app-ltr.css file):
![Fix with own css-file](https://user-images.githubusercontent.com/17032639/52914230-32e08880-32c6-11e9-8867-c5970319b76c.png)

**Screenshots**
![Personalization-Page](https://user-images.githubusercontent.com/17032639/52914018-d2e8e280-32c3-11e9-9c60-43b171bbfcbb.png)
![contact-page](https://user-images.githubusercontent.com/17032639/52914022-e2682b80-32c3-11e9-8c1e-ea47df6c221c.png)

**Which version are you using:**
 - A server I maintain myself with Monica version 1.12

**Comment by ein-stein-chen** [comment]
Could be related to #2034

**Comment by tbirrell** [comment]
Monica still uses FontAwesome 4.7 which includes `fa fa-imdb`. Doublecheck `package.json` to make sure you have `4.7`. If not, that's your problem.

**Comment by ein-stein-chen** [comment]
The problem is not that the `fa fa-imdb` icon is missing, but that all Icons are missing.
I did a fresh install of monica 2.12.0
This is how the Settings -> Contact field types looks:
![Contact field types Panel](https://user-images.githubusercontent.com/17032639/53867500-4abd4980-3ff4-11e9-9fc6-d1ed788bc6a9.png)

Because of the fresh install the line: `"font-awesome": "^4.7.0",` in `package.json` under `dependencies` is present.

**Comment by justsomebody42** [comment]
Thanks ein-stein-chen!
I had the very same problem and your workaround worked for me as well.
Can you give me a hint where/how to identify the correct content for each icon?
I want to add some more...

**Comment by asbiin** [comment]
This is fixed! The icons are here again with fa-* scheme
