### ISSUE TITLE
Upgrading to 2.0.1 duplicates relationships

### ISSUE THREAD

**Issue by barttenbrinke** [monicahq/monica#2460]
**Describe the bug**
Hi, I am trying to upgrade from a 1.4.1 install to 2.12.0 I've updated to 1.8.2 now which seems to be ok. However if I upgrade to 2.0.1, all my "SIGNIFICANT OTHER" relationships double, which is not very handy. Is there something specific I need to do to prevent this?

**Comment by tbirrell** [comment]
The upgrade from 1.x.x to 2.x.x introduced a breaking change with relationships. See the [Release Notes](https://github.com/monicahq/monica/releases/tag/v2.0.0) for further information.

**Comment by asbiin** [comment]
We didn't notice anything like this. Is it still the case ?
