### ISSUE TITLE
"No scheduled commands are ready to run." on php artisan schedule:run

### ISSUE THREAD

**Issue by tomgs** [monicahq/monica#2463]
**Describe the bug**
In order for the e-mail reminders to be sent, a cron job must be setup so that it runs the `php artisan schedule:run` every once in a while. In Heroku, this is done using the [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler):

![heroku_scheduler](https://user-images.githubusercontent.com/8835035/53105668-37ad7280-353a-11e9-95ca-dc5f04e3b3e2.png)

However, in order to test it, I've tried running it manually using the Heroku built-in console, like so:
![tomgs-monica___heroku](https://user-images.githubusercontent.com/8835035/53105756-5f9cd600-353a-11e9-8b7d-327236d5ff5e.png)

This is the result:

![tomgs-monica___heroku_and_monica_update_md_at_master_ _monicahq_monica](https://user-images.githubusercontent.com/8835035/53105517-f1581380-3539-11e9-9c90-968beca0eaac.png)

If it's hard to read, it says `No scheduled commands are ready to run.`

I've specifically set up a few contacts so that I'm reminded to contact them daily, and set the defualt time the reminders need to be sent at (via the Monica GUI settings) to an hour from now, waited the hour and then ran the command - and still, no reminders were sent.

Running `heroku logs -a my-app` showed the same `No scheduled commands are ready to run.` as before.

Thoughts on how to solve this? I thought this was a MailGun problem all long but it seems this has something to do with the reminders not being triggered at all....

**Screenshots**
See above.

**Which version are you using:**
Monica v2.12.0 on a Heroku hobby dyno, running the heroku-16 stack

**Comment by keywordnew** [comment]
> In order for the e-mail reminders to be sent, a cron job must be setup so that it runs the php artisan schedule:run every once in a while.
> then ran the command - and still, no reminders were sent.

To clarify, are the reminders going out at all?

**Comment by asbiin** [comment]
This is finally fixed by #2652 !
That was a hard trick, as schedule is not necessarily running at fixed hour, but it's working now.

**Comment by keywordnew** [comment]
@tomgs the fix was deployed in v2.14.0, released 3 days ago. Any chance you've had a chance to update your heroku instance? I've pushed the new version up but the email reminders have yet to show. 

Mailgun dashboard shows no emails sent.

<img width="878" alt="Screen Shot 2019-05-19 at 6 33 55 PM" src="https://user-images.githubusercontent.com/10335475/57991590-daf02400-7a64-11e9-9eaa-0edd4d990430.png">

Now Heroku Scheduler is actually running though!

<img width="1225" alt="Screen Shot 2019-05-19 at 6 34 32 PM" src="https://user-images.githubusercontent.com/10335475/57991603-efccb780-7a64-11e9-9937-e3abf9872917.png">

**Comment by tomgs** [comment]
No email reminders for me. And the scheduler was running in the last
versions as well...

**Comment by asbiin** [comment]
It's working well on my test instance.
Did you follow every steps of https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md ?
I've updated the doc recently, see in particular the instructions to set the "Heroku Scheduler". If you didn't set the scheduler, reminders can't work.

**Comment by keywordnew** [comment]
Yes, I followed the steps when I first set up that instance.

I also did a migration after updating, as the release notes for v2.14.0 indicated that a migration was needed. But the CLI said nothing was migrated.

> You are now able to open the application and register a new user.

The above line is _after_ the instruction to set up a Heroku Scheduler job. Do I need to make a new user for the job to work?

**Comment by asbiin** [comment]
> I also did a migration after updating, as the release notes for v2.14.0 indicated that a migration was needed. But the CLI said nothing was migrated.

This is not needed on heroku, as everything is already handled. You just may want to backup your DB before doiong an upgrade.

**Comment by tomgs** [comment]
I'll spin a fresh monica install later today or tomorrow, and see if it
goes.
I really hope this works, Monica is such an amazing piece of software,
looking forward to using it.

**Comment by tomgs** [comment]
This is still not working, btw. Trying to debug in #2588 if anyone's seeing this.
