### ISSUE TITLE
add a relationship by including myself

### ISSUE THREAD

**Issue by simon511000** [monicahq/monica#2472]
I wish I could add a relationship by including myself.
For example I would like to add a contact "mom" and add a relationship. And instead of selecting a contact, I select myself.

**Comment by mechanarchy** [comment]
Duplicate of #33.

This feature is in [the 2019 Q1 roadmap](https://github.com/monicahq/monica/issues/2306) so it should be coming soon.

**Comment by simon511000** [comment]
Thank you !
