### ISSUE TITLE
Birthday reminder not being sent

### ISSUE THREAD

**Issue by psteinweber** [monicahq/monica#2480]
I have set up birthday reminders for many of my contacts, however I don't seem to receive the emails. They do show up in the dashboard of the app.

I have checked the spam folder. And I also receive the "stay in touch with XYZ" emails without any problems. 

But the birthday reminders don't happen.

Can anyone else confirm this behaviour/bug, or is something wrong on my end? I'm using the hosted version.

**Comment by djaiss** [comment]
No this is a bug on our end.

**Comment by djaiss** [comment]
Found the bug. Will fix it before this weekend. Really sorry about that.

**Comment by gramakri** [comment]
Does this apply to all reminders and not just birthday reminders? I setup a reminder but haven't gotten an email about it. (normal emails like invitation/confirmation etc work)

**Comment by djaiss** [comment]
Yep this applied to most reminders actually.

This should be fixed in both the new release and in production. Sorry this happened!
