### ISSUE TITLE
Unable to visit security page [self-hosted]

### ISSUE THREAD

**Issue by mfkapfer** [monicahq/monica#2483]
**Problem**
When visiting the /settings/security page I get an error message. Settings regarding the password or the 2FA are not reachable at the moment. Any other settings can be changed smoothly.

**Screenshots**
<img width="1064" alt="error_message" src="https://user-images.githubusercontent.com/15227481/53686978-d00fd800-3d2e-11e9-8cf7-c6ddd1eaf950.png">

**Which version are you using:**
 - A server I maintain myself with Monica version 2.12.0.

**Additional context**
I spotted the error in 2.11.2 and thought it might resolve itself with an update to the latest release.

**Comment by asbiin** [comment]
This was fixed with #2625
