### ISSUE TITLE
Email reminders not sending

### ISSUE THREAD

**Issue by iopuhjkl** [monicahq/monica#2485]
I have successfully been receiving MonicaHQ reminders via email to my inbox. However, as of February 8, those reminder emails have ceased. Have you encountered this problem before? How might it be solved?

I am using the hosted platform, not my own instance.

**Comment by djaiss** [comment]
Indeed. This is a bug that is being fixed as we speak. Sorry about this problem.

**Comment by djaiss** [comment]
This should be fixed in both the new release and in production. Sorry this happened!
