### ISSUE TITLE
Change of valid denominations in India, should be reflected in the 'frequent bank notes'.

### ISSUE THREAD

**Issue by AniketSK** [monicahq/monica#2488]
The file https://github.com/monicahq/monica/blob/master/database/seeds/json/2017_08_02_124102_add_world_currencies.json lists the following as the frequent bank notes.
`
"banknotes": {
      "frequent": [
        "5",
        "10",
        "20",
        "50",
        "100",
        "500",
        "1000"
      ],
`

**Describe the bug**
The Rs. 1000 note has been taken out of circulation and the Rs.200 and Rs.2000 notes have been added. The reserve bank of india, the central banking institution for India which prints currency lists the valid notes [here](https://paisaboltahai.rbi.org.in/).

**Which version are you using:**
2.12.0 the version running on https://app.monicahq.com/

**Additional context**
Demonetization was the term for the removal of the Rs.1000 note if you need additional context or news articles.

**Comment by asbiin** [comment]
Thank you for your report @AniketSK .
Anyways, these data are currently not used in monica.
This file is used to create the collection of currencies you can see in settings, the only datas imported are: iso code (key), name, and symbol.
