### ISSUE TITLE
Reminders for current day don't show up in dashboard

### ISSUE THREAD

**Issue by casidiablo** [monicahq/monica#2496]
Today March 5th was my grandpa's birthday. Yesterday it was showing up in the dashboard. But today, I only see events **after** March 5th. That makes no sense to me. Why hide events of the current day?

I'm running `2.12.0`

**Comment by Bounz** [comment]
Similar issues:
- https://github.com/monicahq/monica/issues/740
- https://github.com/monicahq/monica/issues/839

**Comment by casidiablo** [comment]
Closing as it is duplicated.
