### ISSUE TITLE
"Overcame an Illness" typo

### ISSUE THREAD

**Issue by beattheprose** [monicahq/monica#2497]
There is a typo in the "Add life event" feature for "Overcame an Illness." It shows up correctly in the selection list, but when the event is recorded, it becomes "Overcam an Illness"

### Examples:
![monica1](https://user-images.githubusercontent.com/45179933/53898378-d7392d80-402f-11e9-84ae-43e84ba0b2db.PNG)
***
![monica2](https://user-images.githubusercontent.com/45179933/53898409-e4561c80-402f-11e9-997e-6cb77b0d72ef.PNG)

#### Monica Version
2.12.0 on app.monicahq.com

**Comment by IcyPalm** [comment]
Correctly noticed! This is already addressed and fixed here: #2455
If I'm not mistaken it is just waiting for a new release

**Comment by asbiin** [comment]
Thank you for the report.
As mention, it will be fixed in the next release.
