### ISSUE TITLE
Speed up "Add a person" UI

### ISSUE THREAD

**Issue by TheActualWalko** [monicahq/monica#25]
As a user with many friends to add, I'd like to be able to quickly get all the basic info for people who matter to me into the system in as few interactions as possible.

Some ideas:

- give options "Submit and add more information" and "Submit and add someone else" to submit a new person
- don't default to "Man," force me to click on "Man" or "Woman" for each person (although this is an extra click 50% of the time, I forgot I had to select "Woman" for several people and had to come back and edit, which took more time over all)
- include "Add a new person" as a direct link in the header

**Comment by ocdtrekkie** [comment]
I would actually recommend dropping the man/woman option altogether. You will get flack from people for offering a binary option. It is probably preferable to either allow "other" or throw out the setting altogether. Maybe a "preferred gender pronoun" field or something in the more extended information box, if you really need it.

**Comment by enko** [comment]
I like how diaspora handles this: Just a plaintext field. You can enter whatever you want.

**Comment by ocdtrekkie** [comment]
In short, if your gender selection can't handle "attack helicopter", it needs work. :P

**Comment by TheActualWalko** [comment]
I agree with the above points. I believe gender identity accommodation should be tracked and discussed as a separate issue.

**Comment by ocdtrekkie** [comment]
Gonna agree with you now if only because nobody is noticing the discussion in this issue, and there are now two more on the topic.

**Comment by TylerL-uxai** [comment]
Here are some UI ideas I had. One got 1400+ views. Hopefully you can apply them to your open source project! :)

https://codepen.io/TylerL-uxai/pen/jWMwzy remove "submit" buttons
https://codepen.io/TylerL-uxai/pen/QvezdM hotkeys

**Comment by Nebucatnetzer** [comment]
I would recommend splitting this issue.
This are basically three separate changes.

**Comment by Nebucatnetzer** [comment]
How about we rename this issue to something like:
Allow more/custom genders?

**Comment by djaiss** [comment]
This issue had 2 points:
* the ability to add another contact right after adding a contact. This is adressed in #634 
* the notion of custom genders. I've created another issue for this: https://github.com/monicahq/monica/issues/635
