### ISSUE TITLE
Connection could not be established with host mailtrap.io [Connection timed out #110]

### ISSUE THREAD

**Issue by GaneshKandu** [monicahq/monica#2500]
Hi,

I am Trying to install Monica on my machine ( VM  )
Getting Error after Register new user while install

```

Whoops! Something went wrong.

Connection could not be established with host mailtrap.io [Connection timed out #110]

Back to homepage
```
LOG FILE
[_laravel-2019-03-07.log](https://github.com/monicahq/monica/files/2941065/_laravel-2019-03-07.log)

**Comment by yegle** [comment]
When I installed Monica yesterday, this was due to not setting DNS server in docker.

**Comment by yegle** [comment]
But for your case it looks like the network connection failed (I.e. DNS resolution is fine).

**Comment by asbiin** [comment]
I think this is solved?
