### ISSUE TITLE
MonicaHQ service fails to build with docker-compose at step 10: non-zero return code of 27

### ISSUE THREAD

**Issue by oozone** [monicahq/monica#2509]
Hi

As stated: the monicahq fails to build on my debian machine at step 10: error non-zero return code 27. Please see attached image for the context. Any clues?

Thanks! 

![stackoverflow](https://user-images.githubusercontent.com/4332841/54076140-491bac00-42a8-11e9-852a-25a5bc809afd.png)

**Comment by asbiin** [comment]
Sorry, there is not enough information here for us to help you ...

**Comment by asbiin** [comment]
Please provide more details if you wish some help.
