### ISSUE TITLE
Bug: MoneyHelper::format can not format correctly for non two "2" minor unit currencies 

### ISSUE THREAD

**Issue by makitosan** [monicahq/monica#2540]
**Describe the bug**
MoneyHelper::format method is implemented correctly only for two "2" minor unit currencies which is major pattern such as USD, GBP, EUR, etc. But non two "2" minor unit currencies such as JPY and ISK.

You can find some non two "2" minor unit currencies in the following moneyphp configuration file.
https://github.com/moneyphp/money/blob/2a07142b76749275a767be50d317128ba6b78b7f/resources/currency.php

| currencies | input value | display value |
|:---:|:---:|:---:|
| USD | 100.00 | $100.00 |
| JPY | 100 | ¥10,000 (wrong) |

**Which version are you using:**
 - ver 2.12.1

I will send PR in a couple of days, please review and merge it if it's OK.

**Comment by djaiss** [comment]
Thanks for this comment. We indeed do not know all the cultural differences and we apologize for this kind of mistakes. Your help here is greatly appreciated.

**Comment by asbiin** [comment]
Fixed by #2541
