### ISSUE TITLE
Incorrect UI label under "Addresses"

### ISSUE THREAD

**Issue by ocelotsloth** [monicahq/monica#2547]
**Describe the bug**

Under the address section, `Latitude (numbers only) (optional)` appears twice. The second instance should say `Longitude (numbers only) (optional)`.

**Screenshots**
![2019-03-22 12_37_27-github](https://user-images.githubusercontent.com/9255772/54838632-75b7c680-4c9f-11e9-8977-6ac7836b2ddd.png)

This second screenshot shows that the second box should be the Longitude. I've tested putting some Lat/Long coords in and it works fine, it just has the wrong label.

![2019-03-22 12_39_38-github](https://user-images.githubusercontent.com/9255772/54838702-a1d34780-4c9f-11e9-9e50-200f65575144.png)

**Which version are you using:**

This is a new install of Monica 2.12.1 running inside of a docker container.

**Additional context**

I tried to search the codebase for instances of this string to find an issue and didn't come up with anything that looked like where this UI element is defined. If somebody points me towards where these views are defined in Laravel projects I could just open a PR myself.

**Comment by asbiin** [comment]
I think that's a bad copy/paste !
