### ISSUE TITLE
Last Consulted Not Updating

### ISSUE THREAD

**Issue by timmyk0** [monicahq/monica#2565]
**Describe the bug**
Just updated to 2.12.1, and now the "last consulted" at the top of the Monica page does not update. Before it would always show the last person I viewed and keep updating as I viewed people. Now it stays static with the same people. It worked fine before the update to 2.12.1. 

**Additional context**
I tried looking at release notes and other current bugs to see if this was already reported and I could not find anything, sorry if that's not the case. If there's something simple I can do to fix this or figure out why it's happening please let me know. 

Thanks!

**Comment by tbirrell** [comment]
Same for me, though it occasionally updates for reasons I can not determine. Also on 2.12.1

**Comment by sylvainmetayer** [comment]
I have the same bug with 2.14.0
