### ISSUE TITLE
POST /contacts/ errors with undocumented required field "The is birthdate known field is required"

### ISSUE THREAD

**Issue by jasonstrimpel** [monicahq/monica#2596]
**Describe the bug**
I create a `POST` request to the `https://app.monicahq.com/api/contacts/` endpoint in an attempt to create a new contact. Following the [documentation](https://www.monicahq.com/api/contacts#create-a-contact), I supply the example `JSON` payload and receive error code 32 for three fields that do not appear in the documentation.

The error response:

	{
	    "error": {
	        "message": [
	            "The is birthdate known field is required.",
	            "The is deceased field is required.",
	            "The is deceased date known field is required."
	        ],
	        "error_code": 32
	    }
	}

**Screenshots**
<img width="1373" alt="Screen Shot 2019-04-13 at 15 56 47" src="https://user-images.githubusercontent.com/908118/56076530-ea94a100-5e04-11e9-869e-6ee44608022e.png">

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Additional context**
By updating `is_dead` to `is_deceased` I was able to resolve the `The is deceased field is required.` error. I could not figure out any of the other fields.

**Comment by shavs** [comment]
I can confirm that this an issue with the documentation - the fields that are missing are:

| Property | Replaces? | Appears in JSON Response |
|---|---|---|
| `is_deceased` | `is_dead` | False - only `is_dead` appears |
| `is_birthdate_known` | none, added to response | False, behaviour seems to override `birthdate_is_age_based`, `birthdate_is_year_unknown` and `birthdate_age` in the request |
| `is_deceased_date_known` | none, added to response | I'm unsure of the side effects - I think it's overriding the `deceased_date`->`is_year_unknown` property, but I'm unsure. |

I am unsure whether this affects the self-hosted version of the site, however, I am making the assumption that both the hosted version at `https://app.monicahq.com` is the same version that can be self-hosted.

I'd see that either: 

- the documentation needs to be changed, to fit the new properties on the request
- the API needs to be changed to fit the request, to be consistent with the response

**Comment by shavs** [comment]
Also, as a general rule-of-thumb - with Laravel or Lumen response validation messages, you can generally translate the validation messages into underscored properties. For example:

```json
{
    "error": {
        "error_code": 32,
        "message": [
            "The is birthdate known field is required.",
            "The is deceased field is required.",
            "The is deceased date known field is required."
        ]
    }
}
```

```json
{
    "error": {
        "error_code": 32,
        "message": [
            "The is_birthdate_known field is required.",
            "The is_deceased field is required.",
            "The is_deceased_date_known field is required."
        ]
    }
}
```

... I agree it should not be necessary, but it may assist with debugging the API in future.

**Comment by asbiin** [comment]
Thanks @shavs for the fix, we will update the doc.

**Comment by asbiin** [comment]
Related to #2251

**Comment by mattdp** [comment]
Related: https://github.com/monicahq/monica/issues/2398. I believe solving this solves both issues.

**Comment by asbiin** [comment]
API doc has been updated.
See https://github.com/monicahq/marketing_site/pull/75
