### ISSUE TITLE
Dashboard tabs are broken

### ISSUE THREAD

**Issue by cynddl** [monicahq/monica#26]
On the main page, the two buttons “_What's coming_” and “_Latest actions_” are somehow broken.

We can click on them to switch tabs but their state doesn't change (the first one is always selected).

**How to reproduce the issue**
1. Go to https://app.monicahq.com/dashboard
2. Click on the second tab
3. Click on the first one

**Comment by djaiss** [comment]
Yes it's an issue with Bootstrap. If someone had some time to spare to fix this, it would be awesome.

**Comment by BranTurner** [comment]
I've submitted a temporary fix for this, but please feel free to ignore if you'd prefer to wait for the upcoming Bootstrap release!
