### ISSUE TITLE
The people overview table overflows on Firefox Mobile

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#261]
![screenshot_20170613-172049](https://user-images.githubusercontent.com/2287221/27091130-88124668-505f-11e7-8838-1f1c34a2e9a6.png)

**Comment by djaiss** [comment]
Yes, it's not super mobile friendly at the moment, I know. I should fix this.

**Comment by Nebucatnetzer** [comment]
No problem, I just continue to collect everything I find so that we have a complete list of it.

**Comment by tetov** [comment]
I've noticed this on both Safari and Chrome on iOS as well.

**Comment by asbiin** [comment]
Fixed
