### ISSUE TITLE
error importing a vcard file

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#263]
I tried to import a vcard file exported from Thunderbird however I got this error:

`The provided vcard file was not found or is not valid!`

Is there some way to validate the file?

**Comment by yamakadi** [comment]
The file needs to have .vcf as it's extension and must be located somewhere relative to the base directory.

For instance, if it's in storage, you need to put 'storage/contacts.vcf'. Home directory also works, like '~/Desktop/contacts.vcf'.

**Comment by Nebucatnetzer** [comment]
I have a test.vcf and used this command:
sudo artisan import:vcard myemail@something.com ~/ansible/test.vcf

as well as:
sudo artisan import:vcard myemail@something.com /home/ansible/test.vcf

both failed.

**Comment by yamakadi** [comment]
Could you provide the file by any chance so I can check the issue? And can
you also try to put it in the base directory of your Monica installation
and just try with 'test.vcf'?

**Comment by Nebucatnetzer** [comment]
I could create a new version with a test contact and send you that.

I give that a try.

**Comment by Nebucatnetzer** [comment]
It worked when I moved the file to the installation root.
I'll create a PR to update the documentation for this.

**Comment by Nebucatnetzer** [comment]
@djaiss does the vcard import work for you if the file is not in the
root of the Monica installation?

**Comment by yamakadi** [comment]
For me, it only works if I use ~ as home folder. @djaiss also used that
successfully I think. It's not meant to work that way though. It appends
'./' to the address and uses the root directory as base directory.

**Comment by Nebucatnetzer** [comment]
Okay, I was asking because I wasn't sure if it really makes sense if I update the readme
or if it's just a quirk with my installation.

However it's probably safer when we write that the file should be put into the
installation root?

**Comment by yamakadi** [comment]
Yup!

**Comment by djaiss** [comment]
This has been pushed to production (see #302 ).
