### ISSUE TITLE
Introduce step mom / step dad relationship option

### ISSUE THREAD

**Issue by tedstriker** [monicahq/monica#2638]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Is your feature request related to a problem? Please describe.**
It would would be nice if step mom / step dad relation ships could be selected as type of relationship.

**Describe the solution you'd like**
add another relationship type.

**Describe alternatives you've considered (optional)**
I selected mum / dad as an alternative, which works as long as the "real" mum / dad are not referred to in Monica.

**Additional context**
If you need more context, let me know.

**Comment by r4taw2mg** [comment]
I think, it would be even more convenient, if the relation types could be configurable for every instance of Monica. (I think, activities are already made configurable.)

**Comment by tedstriker** [comment]
That's true, but that's another story. For now, just the option mentioned above would be fine.

**Comment by asbiin** [comment]
Fixed by #2723
