### ISSUE TITLE
Change DB_PASSWORD

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#2641]
I am using the dockerized version of Monica. I see DB_PASSWORD in docker-compose.yml and .env. If I want to change this password how do I do it? It seems to me to be created the first time the database is created and has to match thereafter but I don't see a way to change it apart from in mysql.

**Comment by alhdo** [comment]
I think that's your responsability to change your own database password. It's not part of Monica to change it for you. Monica is not a database manager so it's completely normal if you can't do it. I don't think it's an issue. Thanks

**Comment by asbiin** [comment]
Indeed, this is not a Monica issue.
You can find some help here: https://docs.docker.com/samples/library/mysql/#mysql_user-mysql_password
