### ISSUE TITLE
PRM as an additional layer on top of a CardDAV provider

### ISSUE THREAD

**Issue by r4taw2mg** [monicahq/monica#2677]
May this goes a little to far for a feedback, but I did not find another place to intiate a discussion.

I was looking into Monica because I am looking for a tool to help me keep contact with the people I know in a more systematic way. And to store information that is usually not stored in online databases like the ones offered by Google, Apple, fruux, NextCloud etc. But I do not want to to replicate / import data into another database as I am quite happy with the e.g. the synchronisation to mobile devices those solutions do offer.

So I am essentially looking for an additional layer on top of the contact information I already have. A layer for additional information on a contact, especially a history of encounters and some planning for further meetings, calls, dates. Basic data like names, phone numbers, adresses would still remain in the "pure" contact database. For exchange a common protocol like CardDAV could be used.

As far as I can see, this is not the approach Monica has taken. And unfortunately I failed to find any other solution following that path. (Maybe I have to build it myself?)

What do you think of this idea?

**Comment by asbiin** [comment]
Carddav is already supported on Monica, and will be activated on our own instance soon. Is this what you are looking for?

**Comment by djaiss** [comment]
No @asbiin. @r4taw2mg would like a tool that is built upon Carddav to store additional information on the contacts. Monica would just be a layer on top of an existing solution.

Thanks for the issue, but I’ll close this issue because this is not the direction of the project.
