### ISSUE TITLE
Wrong gender in german translations

### ISSUE THREAD

**Issue by allo-** [monicahq/monica#2687]
The german translations of relationships are all following the scheme "Father/Mother of X" and the abbreviation in the profile view reads "father" ("Vater"). The same happens for Brother/Sister, what is abbreviated as "brother".
So a profile has for example two fathers and one brother, when the person has a father, a mother and a sister linked with their profile.
I guess the english words there are genderless like "parent", but the translation has a (male) gender.

**Comment by asbiin** [comment]
This has been tested profundly, and should not be a problem right now.
I don't thinks it's a wrong translation. Can you give us some screenshots ?
Can you check if the gender types are right setted in the setting page (i.e. https://app.monicahq.com/settings/personalization ) : each gender has a 'sex' field associated. It it's not well setted, it could lead to a wrong abbreviation on the profile view.

**Comment by allo-** [comment]
Indeed, there were the correct groups (Man, Woman, Unknown) with the correct people associated, but all of them had gender "Unknown". Seems that something was not migrated correctly during the upgrade.

Now the labels are correct. Thank you!
