### ISSUE TITLE
Mark a gift as given/offered

### ISSUE THREAD

**Issue by sloria** [monicahq/monica#269]
There is currently no way to mark a gift as "given."

**Comment by dpinezich** [comment]
I would love to implement this, but there are some questions regarding the current datastructure:

If we want to transform a giftidea to a gift already offered it is straightforward (in my understanding) add a button to action, get a date when it was offered, change the according fields in the gifts table. 

But if I look at the current "gift already offered" datastructure we have one problem to solve. We should also offer the possibility to insert a date when the gift was offered (by default it is just the creation_date to avoid null entries)?

How are your intentions into this?

**Comment by djaiss** [comment]
The ability to mark a gift as offered is now live.
