### ISSUE TITLE
Ambiguity about backups in Privacy policy

### ISSUE THREAD

**Issue by st-sloth** [monicahq/monica#2695]
The [privacy policy](https://www.monicahq.com/privacy) contains sentences

> We do hourly backups of the database.

and 

> When you close your account, we immediately destroy all your personal information and don't keep any backup.

While not contradictory, this might be interpreted as both
* indeed, personal information is immediately deleted from the current database, as well as from all the historical database backups (which is kinda weird since backups are usually immutable),
* personal information is immediately deleted from the current database, but backups are kept intact (as usual), and user information is still restorable for the backup retention time (which makes the statement false).

**Comment by djaiss** [comment]
You are right. This is one of the issue of having backups. I don't know what we can do about it actually. Backups are deleted after 30 days, so basically I should change it to indicate that your data is actually deleted in 30 days, that'd be the actual truth.

This is the new text:

> When you close your account, we immediately destroy all your personal information from the production database, but your information is kept in the backups that we keep for 30 days. After 30 days, your information will be completely destroyed.


Thanks for helping us noticing this issue.
