### ISSUE TITLE
Storage Files in AWS S3 

### ISSUE THREAD

**Issue by degan6** [monicahq/monica#270]
Laravel already has awesome support for this, so it shouldn't too hard to implement. 

It would also allow Heroku users to store files.

We might need to add a db field to keep track of where the file is located.

**Comment by degan6** [comment]
I can get started on this. Would love feedback on the idea.

**Comment by djaiss** [comment]
I shouldn't be too hard, since file uploads currently already use the Storage API to save on disk. In theory, it would work with S3 out of the box if you provide S3 credentials, but this should be tested.

**Comment by degan6** [comment]
#396

**Comment by biomcanic** [comment]
Hi, I'd like to know if this integration is developed, I'm interested in using S3 for avatars in a Heroku install.

Thanks!
