### ISSUE TITLE
OAuth token with docker container

### ISSUE THREAD

**Issue by tedstriker** [monicahq/monica#2720]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
I can't create a API token from a docker container instance of Monica.
![image](https://user-images.githubusercontent.com/795203/58372117-72e48680-7f19-11e9-902a-ed3f638ad349.png)

How am I supposed to provide/configure the certificate and private key?

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.
**Which version are you using:**
- Version 2.14.0
- Docker

**Additional context**

**Comment by asbiin** [comment]
Right! It's not documented.
1. run `docker ps` to get the name of the container where to execute next commands
```
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS                           NAMES
d9c3bd4f28f3        monicahq/monicahq   "entrypoint.sh apach…"   4 days ago          Up 4 days           0.0.0.0:3000->80/tcp            monica_monicahq_1
```

2. Following documentation [here](https://github.com/monicahq/monica/blob/master/docs/installation/generic.md#7-optional-setup-the-access-tokens-to-use-the-api),  execute 
```sh
docker exec -it monica_monicahq_1 php artisan passport:keys
docker exec -it monica_monicahq_1 php artisan passport:client --personal --no-interaction
```
This generate the encryption keys and instanciate personal passport client, to allow creation of an oauth client token.

Be careful to backup the encryption keys, for example with
```sh
docker cp monica_monicahq_1:/var/www/monica/storage/oauth-public.key .
docker cp monica_monicahq_1:/var/www/monica/storage/oauth-private.key .
```

I will look at create these keys and personal client with the launch script.
