### ISSUE TITLE
Editing a contact which doesn't exists throws an exception

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#276]
```
Sorry, the page you are looking for could not be found.
(2/2) NotFoundHttpException

No query results for model [App\Contact] 24
```

Steps to reproduce:

1. Open a contact twice
2. Delete it in the first tab
3. Move to the second tab and click on "Edit contact information"
4. Monica throws an exception

This should probably return a message like:

> The contact you are trying to edit doesn't exist anymore.

Otherwise it might be a bit confusing for the users.

Edit:
The same happens by the way if you want to open a contact which got deleted.
Maybe a more generic message like

> The contact you're trying to interact with, doesn't exist. Would you like to create it?

Could be used for both cases and then offer a button to create a new contact?

**Comment by djaiss** [comment]
Good catch.
