### ISSUE TITLE
Exported SQL file doesn't contain user information

### ISSUE THREAD

**Issue by Bounz** [monicahq/monica#2760]
**Describe the bug**
Followed the instruction given in https://github.com/monicahq/monica/blob/master/docs/installation/update.md#importing-sql-from-the-exporter-feature article. Everything went good, but in the end, I wasn't able to login to the new instance receiving an error `These credentials do not match our records`.

Also, I found no INSERT statements related to the `users` table in `monica.sql` generated during export data.

**Which version are you using:**
Self-hosted Monica v. 2.14 on both instances.

**Additional context**
Right now backup and restore feature is completely useless as user can't log in to the new restored Monica instance.

**Comment by ManuelHettich** [comment]
I am running into the same problem: I cannot log in after successfully importing my export from monicahq.com.

**Comment by asbiin** [comment]
This be fixed now.
