### ISSUE TITLE
contacts sorting behaves a bit strange

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#277]
I imported my contact with the vcard import.
Some of the contacts had only a first name but no second name. 
After I added the last name they get added to the top of the list 
regardless of the sorting mode I'm selecting.

The contacts which had a first name and a last name from the beginning work just fine.

I experience the same behavior with contacts I add manually. They just get added to the
top of the list and don't ever get sorted.

**Comment by asbiin** [comment]
This is fixed
