### ISSUE TITLE
Installing as a subdirectory

### ISSUE THREAD

**Issue by filipe-silva** [monicahq/monica#2782]
Hello, so not sure if this counts as a bug, I had the app as a subdomain but I been trying to change to subdirectory many times now, I probably just missed something.

I've followed the tutorial, and I'm self hosting on Ubuntu, current version 2.14.0.

**Describe the bug**
My error is a 500, caused by this:

[Sun Jun 16 13:19:24.559878 2019] [core:error] [pid 20950] [client 93.108.212.229:65531] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., 

**Additional context**
I'm using https, in case it matter.
And using an alias on my vhost config, so it could be that but not sure.

It would be great to hear if someone has manage to use this app in a subdirectory.

**Comment by filipe-silva** [comment]
I found the anwser here:
https://stackoverflow.com/questions/56146327/laravel-considering-a-directory-as-its-route
It says to use RewriteBase inside the .htaccess in the public folder, I did and it worked.

However this isn't a good solution, since it's a file that can be changed with new releases.

If anyone knows how to use RewriteBase or something similar in a virtualhost, please share.
I'm using apahe 2.4.

**Comment by asbiin** [comment]
You can add the RewriteBase configuration into your host apache conf, instead of the .htaccess.

Anyway, this is a support question about your host (apache), rather than Monica related question.
