### ISSUE TITLE
add an option to select a default sorting option

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#279]
It would be a nice addition to be able to select a default sorting method for my contacts.

**Comment by beajeanm** [comment]
The last sorting method is remembered by default, is that enough or are you thinking of something different?
(As you pointed out in #277  sorting seems to be broken at the moment)

**Comment by Nebucatnetzer** [comment]
For me it always switches back to "Sort by first name A → Z"

**Comment by koop4** [comment]
Wouldn't it be easier to display the contact as a table and use the table header to sort?

**Comment by Nebucatnetzer** [comment]
Aye that would be nice.
Maybe the table could have customizable columns?

**Comment by djaiss** [comment]
This setting is now saved in the database. You should always have the same sorting.
