### ISSUE TITLE
Apache routes correctly but Monica doesn't start

### ISSUE THREAD

**Issue by iamhazel** [monicahq/monica#2811]
Hi everyone. I have installed Monica on CentOS7 using httpd on subdomain monica.example.com. I completed all installation steps successfully I think, but when I navigate to the proper domain, I just get the standard Apache page. If I create an index.html file in Monica's root directory, it loads fine. So the routing is correct. It's like there was supposed to be an index.php file included or something, but there isn't.

I'm sure I'm missing something stupid. Any help would be appreciated.

**Comment by Svarto** [comment]
Did you configure the Apache web server? 

Look at Step 5: https://github.com/monicahq/monica/blob/master/docs/installation/ubuntu.md

I am not familiar with CentOS, but sounds like you haven't changed the default Apache sites-available to be Monica specific.

**Comment by asbiin** [comment]
This is a request for apache configuration, rather than support on Monica itself.
