### ISSUE TITLE
problem with dropdown for adding existing contact

### ISSUE THREAD

**Issue by chiajlingvoj** [monicahq/monica#2825]
Using 2.14.0 self-hosted on Yunohost

Imported my contacts (approximately 370) from a *.vcf file, want to add relationship info... when I select a person to add a relationship and then select "existing contact", the dropdown does not show everyone, but rather only about 20 seemingly random contacts.

**Comment by ephzero** [comment]
I was puzzled by this too. It's actually a typeahead search, so if you start typing a "missing" contact's name, they should appear in the list.

**Comment by chiajlingvoj** [comment]
That didn't seem to work...

**Comment by asbiin** [comment]
It's working well.
Please reopen this issue if you have more information to share to show us it's a bug.
