### ISSUE TITLE
"Edit contact information" button only allows editing personal information

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#283]
It is my belief that the button should:
1) Allow editing all information, or
2) Be renamed to "Update personal information" and moved into the personal information section (similar to the "Update work information" link)

**Comment by Nebucatnetzer** [comment]
To me the second option would make more sense.

**Comment by Phrohdoh** [comment]
@Nebucatnetzer I agree.

**Comment by djaiss** [comment]
I think this issue is not relevant anymore considering how much the product has changed since then.
