### ISSUE TITLE
Hide "Stay in touch" for deceased contacts

### ISSUE THREAD

**Issue by GeorgeHahn** [monicahq/monica#2843]
The contact page shows a 'Stay in touch' button/reminder. It would be nice to hide this button for deceased contacts.

Current UI (Version: 2.14.0):

![image](https://user-images.githubusercontent.com/502747/61583437-53d43080-ab27-11e9-9c48-567dc0176192.png)

**Comment by tomgs** [comment]
I am sorry for your loss, and this is a nice feature to have.

**Comment by virtadpt** [comment]
...this.  Please?

**Comment by asbiin** [comment]
Fixed by #2845
