### ISSUE TITLE
Conversations log not showing

### ISSUE THREAD

**Issue by fmalk** [monicahq/monica#2846]
**Describe the bug**
Person's page doesn't show conversation logs, but shows phone logs just fine.
The XHR request for https://selfhosted/people/h:xyzabcde/conversations returns an array just fine.
Error appeared on first conversation log, adding more doesn´t help. Message count on each didn't seem to affect, neither source (icon).

**Screenshots**
![image](https://user-images.githubusercontent.com/208820/61670633-bc9fe200-acba-11e9-84ae-848e180a253c.png)

**Which version are you using:**
 - Self-hosted, PHP 7.1 and Monica 2.14.0

**Additional context**
I've noticed this bug https://github.com/monicahq/monica/issues/2401 while trying to figure the error in this one.

**Comment by tao** [comment]
I have this problem too, I just created a brand new Heroku deployment and the conversations section isn't showing up after I added my first one.

**Comment by Underestimated** [comment]
I can add to this too, same experience, the log is just missing, never been there from install on a fresh install.

**Comment by galexynye** [comment]
Same for me, also on Heroku
