### ISSUE TITLE
Import VCF & CSV files

### ISSUE THREAD

**Issue by radiogorillaz** [monicahq/monica#285]
This way we can ditch other contact apps.

This is my first ever Github submission. Hope I did it correctly.

**Comment by djaiss** [comment]
You did wonderfully.

Import CSV file is a good idea. If you do host Monica on your own server, you can [already do that](https://github.com/monicahq/monica#importing-vcards-cli-only). If you don't, you'll have to wait a bit to make this possible.

**Comment by radiogorillaz** [comment]
Shoot...I thought I read everything before submitting. Will look into this. Sorry!

**Comment by BrunoMRP** [comment]
I have a rudimentary version of this working. I don't know Laravel well so i'm derping around a bit. 
In the next few days i'll submit a merge request

**Comment by asbiin** [comment]
This is already possible now.

**Comment by alexriabtsev** [comment]
@asbiin couldn't find csv import at self-hosted monica v.2.2.1

**Comment by HeinrichHartmann** [comment]
Same here. I have been poking around for a while now: I can't find a way to import csv files. Since you closed this as "already possible", @asbiin, may I kindly ask you to add some guidance on how to do this, or re-open the issue, so it's transparent that this feature is missing.

**Comment by HeinrichHartmann** [comment]
Update: I have worked around this in the following way:

1. Convert csv to vcard file using [this](https://gist.github.com/HeinrichHartmann/b6b1f0953b74dfebf33a8d73c7448cea) script below
2. Upload the vcard file using the import UI

I was not able to get the API import working (`POST /contacts` complained about missing fields, no matter what I provided).
