### ISSUE TITLE
Implement an activities details view

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#288]
As a user I want to be able to view the data I have entered for an individual activity.

---

It is unintuitive to have to 'edit' an activity to view the recorded information when the action I actually want to perform is reading not writing.

Perhaps [an eye](http://www.myiconfinder.com/uploads/iconsets/256-256-e67be78b33a03225936cb8531374997b-eye.png) icon or similar should be placed to the left of the edit pencil icon.

For usability clicking the containing div (class `table-cell`) should probably also view said activity (this is of course up for debate).

---

Side thought: Instead of a separate detail view I did consider an accordion but that cannot be deep-linked to easily and is more complex than a single-purpose view.

---

A details view for other sections may eventually be desired (perhaps I am tracking payments of a single debt entry and continuously edit the debt's description and will some day want to view the entire text).

**Comment by Pablohn26** [comment]
This feature would be awesome

**Comment by Nebucatnetzer** [comment]
I agree that something like this is needed.
Maybe would make the whole title a link to the detail view?
IMO this would be even more intuitive than an eye icon on the side
and it's probably anyway the thing you want to do the most with an activity.

**Comment by djaiss** [comment]
This is done, technically. Soon we'll also have a new Activity detail page, coming in 2.6.0.
