### ISSUE TITLE
Excessive memory usage when sending reminder emails

### ISSUE THREAD

**Issue by charlesoblack** [monicahq/monica#2885]
**Describe the bug**
Whenever a reminder email is triggered, I run into too high memory usage (which then bleeds over into excessive CPU usage since it then uses SWAP).

**Version:**
 - A server I maintain myself on version 2.14.0

**Additional context**
This happens with reminders and "stay in touch". Not sure about birthdays yet. Eventually the system comes back but the email is never sent.

**Comment by charlesoblack** [comment]
Looks like this also occurs when updating birthdays.

**Comment by asbiin** [comment]
Do you have some logs about the "high memory usage"?

**Comment by charlesoblack** [comment]
I'm not sure where the logs are located. I'm running through docker, too. Where would I find them?

**Comment by charlesoblack** [comment]
Clearly not many people care about this. Closing the issue.
