### ISSUE TITLE
Add a link to the project's GitHub on monicahq.com

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#289]
Ideas:

~~- Unauthed: Add a "View on GitHub" or "Get the source" button next to "Support on Patreon"~~
- Authed: Add a link in the footer

The link ref should be configurable per instance (maybe in a config db table, or a config file?) because the source for a hosted instance out in the wild may not be the upstream source.

**Comment by djaiss** [comment]
Good idea. I also need to give a LOT of love to the marketing site.

Keep in mind that the marketing site is on [a separate codebase](https://github.com/monicahq/monicahq.github.io) (on purpose), so it's tricky to put logged/unlogged checks.

**Comment by Phrohdoh** [comment]
This was done in #306.
