### ISSUE TITLE
Email Verifications Don't Work

### ISSUE THREAD

**Issue by Ryonez** [monicahq/monica#2895]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
When clicking "Verify email address" in the verification email, a page opens in your browser with the following message:
![image](https://user-images.githubusercontent.com/16157130/62842230-cab6b080-bd04-11e9-918e-c33b16e6eecb.png)

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.
**Which version are you using:**
 - Self-hosted Docker Image, Version 2.14.0

**Comment by Ryonez** [comment]
I will note that the user's 'email_verified_at' field was filled in in the database.

**Comment by asbiin** [comment]
This should be fixed now, and it's tested as well.
