### ISSUE TITLE
Polish: Add a singular localization key 'reminders_in_day'

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#291]
Currently 'reminders_in_days' is used which results in strings like `in 1 days` which isn't proper English.

https://github.com/monicahq/monica/blob/02d424aced4032fd3d3205629d99d0171f167b57/resources/views/dashboard/index.blade.php#L101 would need to special-case a 1-day difference (at least for English).

---

Side note: Humanizing date offsets should be a separate concert/ticket (such as `<reminder> in 1 day` becoming `<reminder> tomorrow`).

---

This is a very low priority polish.

**Comment by djaiss** [comment]
I agree. With Laravel it's very easy to do actually (management of plurals). Let's put that as an enhancement, it's simple to do.

**Comment by Phrohdoh** [comment]
https://laravel.com/docs/5.4/localization#pluralization

**Comment by Phrohdoh** [comment]
@djaiss What do you think of this?

```php
<?php $reminder_day_diff = $reminder->next_expected_date->diffInDays(Carbon\Carbon::now()) + 1 ?>
{{ trans_choice('dashboard.reminders_in_days', $reminder_day_diff, ['number' => $reminder_day_diff]) }}
({{ \App\Helpers\DateHelper::getShortDate($reminder->getNextExpectedDate()) }})
```
![screen shot 2017-06-19 at 2 18 47 pm](https://user-images.githubusercontent.com/4861023/27301830-467e4748-54fa-11e7-8c7e-45d405038f86.png)
