### ISSUE TITLE
Remove unnecessary loops and simplify model update

### ISSUE THREAD

**Issue by aecdanjun** [monicahq/monica#293]
Simplify model update:
https://github.com/monicahq/monica/blob/master/app/Http/Controllers/SettingsController.php#L57

Remove unnecessary loops:
https://github.com/monicahq/monica/blob/master/app/Http/Controllers/SettingsController.php#L74

**Comment by yamakadi** [comment]
These are being addressed by #253. You can check out the commits to see the new conventions being used.

**Comment by djaiss** [comment]
Thanks a lot for the issue. However, and I don't mean to be harsh, but this kind of issue is not really useful if it doesn't come with code that suggests an improvement. I love feature requests as issues or bug reports, but here, I don't really know what to do with it.

**Comment by djaiss** [comment]
Hum actually never mind, just saw a PR with your improvements. My bad. I'm out. Next time, reference the issue on the PR so I know :-D

**Comment by aecdanjun** [comment]
My bad :( 

Sorry!

**Comment by djaiss** [comment]
Thanks for raising the issue! It's now fixed.
