### ISSUE TITLE
ErrorException: Trying to get property 'id' of non-object (View: resources/views/people/relationship/edit.blade.php)

### ISSUE THREAD

**Issue by noplanman** [monicahq/monica#2954]
**Describe the bug**
- Add a relationship to a contact without ticking `Create a Contact entry for this person.`
- Try to edit that relationship.
- Error page with message: `Trying to get property 'id' of non-object (View: /var/www/monica/resources/views/people/relationship/edit.blade.php)`

**Screenshots**
![](https://user-images.githubusercontent.com/9423417/63948676-96fbba80-ca68-11e9-8de3-7f3380d823b3.png)

**Which version are you using:**
 - v2.14.0 on Docker

**Comment by asbiin** [comment]
I cannot reproduce this error.
What is the url of `Edit` link?
Do you have access to the database behind your instance?

**Comment by noplanman** [comment]
Edit link: `http://localhost:4321/people/h:YdkNepQqjQly0XZMnG/relationships/7/edit`

Yes, I have access to the DB 👍 
What shall I check?

**Comment by asbiin** [comment]
There should be an item with id=7 in the `relationship` tabel, and `contact_is` and `of_contact` are existing contacts in the `contacts` table.

**Comment by noplanman** [comment]
✅ Item with `id=7` in the `relationships` table
✅ `contact_is` and `of_contact` are existing contacts in the `contacts` table.

I dug a bit deeper and it has to do with `$partner->gender->id` which has been fixed with #2705. Next release should be fine in that case 👍 

(Interestingly though, if there is a contact that gets created when creating the relationship, even if `gender` is also `null`, it works 🤔)

**Comment by asbiin** [comment]
Yes, gender can be null.
Next release will fix this.
Thanks !
