### ISSUE TITLE
Write instructions for connecting to the MySQL database from the host machine

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#297]
This is a reminder for myself either later tonight or tomorrow (unless someone beats me to it!).

I figured I'd put this under `docs/database/connecting.md`.

**Comment by djaiss** [comment]
I don't know exactly what you plan to write, but be careful in creating new folders and documents. If you do, make sure that they are easy to find (link from other documents that themselves are linked from the README page).

**Comment by erdmenchen** [comment]
I think we should not put effort into documentation that is not directly about using or installing monica.

Tools like docker are well documented already out there. Just one search away.
If you want to say so, this is duplicate code 😉

**Comment by djaiss** [comment]
I agree that this is thin line. However I think it can be worth it to help reduce the barrier of entry for people who want to contribute to the project.
