### ISSUE TITLE
Where is release 2.15.0?

### ISSUE THREAD

**Issue by Ryonez** [monicahq/monica#2985]
According to this link there is a version 2.15.0:
https://www.monicahq.com/changelog

My question is, where is it? There is no docker update or release files on github.

**Comment by asbiin** [comment]
Nice catch @Ryonez ;)
We have a little delay with this release, because of some migration problem we have detected while testing the version. It should be released in a few days now.

**Comment by Ryonez** [comment]
Sweet, good to know. Shall keep an eye out for it.

**Comment by djaiss** [comment]
Yep we had some unexpected issues with this release. Sorry about that.

**Comment by parkr** [comment]
Just noticed this as well. Subscribed.

**Comment by asbiin** [comment]
It's there: https://github.com/monicahq/monica/releases/tag/v2.15.0 !
