### ISSUE TITLE
MySQL "Got an error reading communication packets", "Aborted connection XX to DB" - Unable to set up Monica log-in screen

### ISSUE THREAD

**Issue by madmads11** [monicahq/monica#2989]
I've been working on this for a good 6 hours or so and this is where I'm up to.
I am running the latest Monica on Docker, using Docker-Compose. I have been following [your guide](https://github.com/monicahq/monica/blob/master/docs/installation/docker.md) on how to set it up, using MySQL.

**.env file and docker-compose.yml file**
Here's my .env file: https://pastebin.com/9341guKy
The only thing I have changed is `DB_HOST=` to say `DB_HOST=mysql` to point to the mysql docker container

Here's my docker-compose.yml file: https://pastebin.com/ipjfxp3c
I changed the volumes under both services to `/home/docker/monica_data:/var/www/monica/storage` and `/home/docker/monica_mysql:/var/lib/mysql` respectively, to point to my docker folder.

I left the `volumes` section at the bottom untouched, as you can see.

**Running mySQL and Monica containers**
Step 1. When I run `docker-compose up` this is the result: https://pastebin.com/ycEB2zHv
The migration complete after a while, but looks good so far.

Step 2. When I try to access localhost:3000 this is what I get: https://imgur.com/a/YGoeDzt
And in the terminal this is printed: `monicahq_1  | 172.18.0.1 - - [07/Sep/2019:01:29:20 +0000] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"`

Step 3. So I cannot see the log-in screen at all. If I try running `docker-compose exec monicahq php artisan setup:production` as the tutorial suggests to set up the server this is the result: https://pastebin.com/7LjzABJD
and on the docker-compose terminal, I get this error: `mysql_1     | 2019-09-07T01:33:40.854846Z 17 [Note] Aborted connection 17 to db: 'monica' user: 'homestead' host: '172.18.0.6' (Got an error reading communication packets)`

Step 4. Again, if I try accessing localhost:3000 I get the same result as before (https://imgur.com/a/YGoeDzt) and once again the docker-compose terminal prints `monicahq_1  | 172.18.0.1 - - [07/Sep/2019:01:29:20 +0000] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"`

**Observations**
Interestingly, if I attempt to run `docker-compose exec monicahq php artisan setup:production` again, it gives me errors saying there are duplicate entries, so I'm guessing the database has been written and created properly.

My suspicion is that my errors stems from this message: `mysql_1     | 2019-09-07T01:22:45.914113Z 2 [Note] Got an error reading communication packets` as seen on line 192 in https://pastebin.com/ycEB2zHv from the first time I run `docker compose up` in step 1.

Nothing changes if I restart the containers, same error. Attempting access from an external_IP:3000 gives the same blank screen and a connection message in the docker-compose terminal.

What could possibly be my mistake? If you need more info/logs/etc, let me know. If I was unclear, let me know and I will explain my setup differently. Thank you for investigating.

**Comment by TechRabb1t** [comment]
First of all please change the root pw in the docker-compose yaml. Then try to create the volumes in another directory, for example /opt/monicahq or something like that. Docker can have problems with permissions in user based directorys.

Regarding your concerns about the error message, I get the same with my mysql container but monica itself works fine, so it's probably more a server side error with apache2.

**Comment by madmads11** [comment]
> Then try to create the volumes in another directory, for example /opt/monicahq or something like that. Docker can have problems with permissions in user based directorys.
This fixed it! Wow thank you, I cannot tell you my relief. Much appreciated.
I created the folder in the volume you suggested.

**Comment by TechRabb1t** [comment]
No problem, I'm glad you solved the issue.

Please don't forget to mark the issue as closed :)
