### ISSUE TITLE
Journal entry date does not match edited activity date

### ISSUE THREAD

**Issue by mechanarchy** [monicahq/monica#2993]
**Describe the bug**
When creating an activity, it defaults to today's date. If you later edit the date on the activity, it will appear correctly on the contact page. However, the automatically created Journal entry is not updated correctly. It will display the edited date in the calendar icon, but it will be sorted into the list at the wrong position (ie, 'today' at the time it was made).

I am using a server I maintain myself, version 2.14.0 from the docker image.

**Steps to reproduce**
1. Create a Contact, eg "John Doe"
1. On John Doe's page, create an activity and fill in the required fields.. Leave the date set at default (it should be the current date). Save the activity.
1. Edit the activity, and change the date to be at some point in the past.
1. Go to your Journal view.

Expected result: The linked Journal Entry should appear in the list at the correct date.

**Screenshots**
Contact page view (after editing the date):
![image](https://user-images.githubusercontent.com/1166756/64482475-f9f20c00-d235-11e9-93a2-f7ad8a53639b.png)

Journal view (after editing the date). Note that the "Monday 22nd" text is correct, but its position in the journal is wrong (it should be in July but it is in September).
![image](https://user-images.githubusercontent.com/1166756/64482467-cf07b800-d235-11e9-98da-2db425907539.png)

**Additional info**
Here's a sanitised snippet from the `/journal/entries` API response:
```json
{
  "id": 123456,
  "date": {
    "date": "2019-09-07 00:00:00.000000",
    "timezone_type": 3,
    "timezone": "UTC"
  },
  "journalable_id": 123456,
  "journalable_type": "App\\Models\\Account\\Activity",
  "object": {
    "type": "activity",
    "id": 123456,
    "activity_type": null,
    "summary": "Second interview",
    "description": null,
    "day": 22,
    "day_name": "Mon",
    "month": 7,
    "month_name": "JUL",
    "year": 2019,
  },
  "show_calendar": false
}
```

**Comment by LukasRos** [comment]
I had observed the same issue lately. The problem is that updating an activity doesn't update the associated journal entry, which is responsible for the order on the journal page. I'm creating a pull request with a fix.
