### ISSUE TITLE
DAV Support on v2.14.0

### ISSUE THREAD

**Issue by Wulfheart** [monicahq/monica#3013]
How can CardDAV/CalDAV be used? Where is the documentation of this feature located?

**Comment by schtibal** [comment]
Agreed! I've just stumbled across Monica, and looks like a good option. I'm currently using self-hosted Nextcloud for my contacts, syncing to Android using DAVx5.  Porting my Nextcloud contacts to a self-hosted Monica looks like the perfect thing for me, but despite tracking through all the git issues, I can't find how to set it up!
After creating an account on app.monicahq.com to test drive before installing my own, I tried to connect to app.monicahq.com and app.monitorhq.com/dav with no luck. 
Can anyone offer some pointers?

**Comment by bbrendon** [comment]
Does anyone know what settings are supposed to work for iOS and MacOS ?

I was able to get it working on iOS using login/password and server name.

MacOS I've tried many variations without success.

**Comment by asbiin** [comment]
Sorry guys! I will create a documentation soon.
https://app.monitorhq.com/dav works on most DAV clients (DAVx5, Thunderbird + CardBook, etc.)
For login, your login/password may work, but it is more secure to use : login + Api Token

**Comment by asbiin** [comment]
See the great new doc at https://github.com/monicahq/monica/blob/master/docs/user/carddav.md
