### ISSUE TITLE
Contact Information Labels

### ISSUE THREAD

**Issue by pqhf5kd** [monicahq/monica#3023]
Contact Information Labels appear to be broken.
<img width="272" alt="Screenshot 2019-09-17 at 12 13 18" src="https://user-images.githubusercontent.com/20027419/65033093-b0e03d00-d944-11e9-80bd-cc857150ad02.png">
<img width="269" alt="Screenshot 2019-09-17 at 12 13 40" src="https://user-images.githubusercontent.com/20027419/65033107-b3db2d80-d944-11e9-9f8f-bee7c0e8daac.png">
<img width="269" alt="Screenshot 2019-09-17 at 12 13 52" src="https://user-images.githubusercontent.com/20027419/65033109-b50c5a80-d944-11e9-94fc-9207b8c31d6d.png">

**Comment by asbiin** [comment]
What do you mean?
Maybe it's not clear, but nothing is broken here.

**Comment by pqhf5kd** [comment]
Here I've added several entries:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/20027419/67163623-55550500-f371-11e9-97e8-2dc78c90f3c0.png">

How do I know what each entry is? Email, Landline, Mobile, Facebook, custom label, etc

If I edit the entry, I'm not given the option to change the label.

**Comment by pzl** [comment]
> How do I know what each entry is?

There used to be icons next to each line, essentially describing each (an envelope icon, a phone icon). It appears the project wants to move away from the font product they used to show the icons, and this was a bit left behind in the transition.

> If I edit the entry, I'm not given the option to change the label.

Yeah, I guess that's just how it works. If you need a different contact type, then delete the entry and create the type you did want.

**Comment by pqhf5kd** [comment]
I see previous posts regarding Font Awesome now. If it's being removed then the options need to be removed and the 'Contact Field Type' 'Name' should be displayed. 

@djaiss

**Comment by asbiin** [comment]
@pqhf5kd There was indeed a (real) problem! The icons should reappear after the fix is deployed.
