### ISSUE TITLE
Please keep support for PHP 7.2

### ISSUE THREAD

**Issue by pwaring** [monicahq/monica#3037]
I've received an update about Monica 2.15.0 and it states that PHP 7.3 is now a requirement. Is there a reason why support for PHP 7.2 has been dropped? It is still a supported release by the PHP project until 30 November 2020 and server distributions such as Ubuntu LTS are unlikely to ship 7.3 until the next release cycle.

**Comment by tbirrell** [comment]
I second this. Unless there is a specific reason for dropping `7.2`, I think we should keep it.

**Comment by asbiin** [comment]
php 7.3 was needed by some dev-depend module. I didn't figured I could fix this, I've just found a way out!
