### ISSUE TITLE
New error in v2.15.2 photo upload - Permission Denied

### ISSUE THREAD

**Issue by Svarto** [monicahq/monica#3050]
**Describe the bug**
Uploading a profile photo to a contact results in an error message that states "permission denied". This only started to happen since upgrading to v2.15.2. The upgrade included a successful running of "php artisan monica:moveavatarstophotosdirectory"

**Screenshots**
![image](https://user-images.githubusercontent.com/24279217/65832665-1a5a3700-e2c7-11e9-9dff-ec0d9bfef0b4.png)

**Which version are you using:**
I self-host, just upgraded to 2.15.2

**Additional context**
It worked fine before the latest update, I was then on version 2.14.0.

**Comment by sylvainmetayer** [comment]
It seems that your web server is unable to access / create the photos folder inside the public folder. What are the permissions of theses folders ?

**Comment by jatls** [comment]
I encountered a similar error this morning and resolved it by changing ownership/permissions on the relevant folder.

**Comment by asbiin** [comment]
Indeed, you must set directories rights.
