### ISSUE TITLE
remove contacts duplicates

### ISSUE THREAD

**Issue by alexriabtsev** [monicahq/monica#3054]
Monica doesn't have contacts duplicates feature which is essential as I'm importing hundreds of contacts from different sources (Google Contacts, LinkedIn, Facebook, emails...).

**Describe the solution you'd like**
I'd like to be able to see and merge duplicates inside monica.

**Describe alternatives you've considered (optional)**
Now I'm using Google Contacts to dedup my contacts but it's not a solution as it works only with Google Contacts but monica would keep all my contacts.

**Comment by asbiin** [comment]
Hi. I think this is quite the same as #1687 right?

**Comment by alexriabtsev** [comment]
exactly! merge my feature request and please do it ;)

**Comment by asbiin** [comment]
duplicate of #1687

**Comment by asbiin** [comment]
@alexriabtsev thanks. Don't hesitate to participate too ;)

**Comment by alexriabtsev** [comment]
> @alexriabtsev thanks. Don't hesitate to contribute too ;)

I'm not developer unfortunately
