### ISSUE TITLE
Inconsistent product description between app and marketing site

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#307]
monicahq.com refers to Monica as "...the first real Friends Relationship Management" while this app describes it as a ["Personal Relationship Management"](https://github.com/monicahq/monica/blob/f2440906213deb188f3c0cf75e4c256fa1357ae9/app.json#L3) tool.

Personally I prefer the latter but either way we should be consistent.

**Comment by djaiss** [comment]
If you could submit a PR on https://github.com/monicahq/monicahq.github.io that'd be awesome. I'll do it later this week otherwise.

**Comment by Phrohdoh** [comment]
This was done in https://github.com/monicahq/monicahq.github.io/pull/5.
