### ISSUE TITLE
Avatars in /journal entries missing [v2.15.2]

### ISSUE THREAD

**Issue by kotnik** [monicahq/monica#3074]
**Describe the bug**

I visit `/journal` and little contact images are missing. Contacts have working avatars, changing them does not make them appear in Journal. Images from `/journal/entries` where the frontend is fetching entries from are just fine, I can open `object.attendees[].avatar.url` in browser just fine.

**Screenshots**

![](https://bin.kotur.org:9441/UKuBRAqnwYw7Q2.png)

**Which version are you using:**

 - A server I maintain running v2.15.2

**Additional context**

There are no errors in logs.

**Comment by baptistemarchand** [comment]
This seems fixed. Can we close the issue?
