### ISSUE TITLE
Is there any admin interface?

### ISSUE THREAD

**Issue by ivangretsky** [monicahq/monica#309]
Good day!
Thanks for this product - I really have been thinking about something like this a number of times before I found monica.

I installed it on a shared hosting without much problems following instructions [here](https://github.com/monicahq/monica#setup-monica). I really had a doubt about the last step - seeding fake data, especially users. But I did it. So now I have 2 users which are not supposed to be here as I planned to use the installation for myself only.

Is there any admin web interface where I can manage registered users? If not, how to do it? What is a proper way to add a new user (myself)?

**Comment by Phrohdoh** [comment]
Currently there is not an admin interface for these types of administrative tasks.

The best way to add a user that I am aware of is going through the registration process.

You can connect to the MySQL db directly and remove records (users, contacts, etc) that you do not want.

**Comment by ivangretsky** [comment]
I do not know Laravel. Maybe there are some artisan commands to remove all related content at once?

**Comment by Nebucatnetzer** [comment]
If you just want to use it,  I recommend that you follow the instructions here:
https://github.com/monicahq/monica/blob/master/readme.md#get-started

The instructions you used are meant for developers.
