### ISSUE TITLE
Self host results in error

### ISSUE THREAD

**Issue by githubber** [monicahq/monica#310]
Hi, This looks awesome.
After following the instructions I end with this when I try to login:

Not Found
The requested URL /login was not found on this server.

What went wrong??
Shane

**Comment by Nebucatnetzer** [comment]
Which instructions did you follow?

**Comment by githubber** [comment]
Thanks for responding. I initially followed this:
https://github.com/monicahq/monica/blob/master/docs/installation/generic.md
but it just sort of ended. I didn't know how to start it. SO I found this:
https://github.com/monicahq/monica/blob/master/docs/installation/debian.md
which explained more about how to install and start the Apache server. Near the bottom of that oage there are instructions about removing the html folder and symlinking monica's Public folder to /var/www/html.. and after I restarted the server the main welcome page would load, but then the next url, http://mydomain/login, would not.

I noticed there were two lines in the .env file:
APP_ENV=local
APP_URL=http://localhost

and I changed local -> production, and localhost to my IP. Restarted Apache. Home page would load, but anything after wouldn't: login, register, etc.

It seems like it is a Laraval issue, but since I am clueless about that I have no idea what to do. I was emboldened by this line at the bottom of the second link above:
"Finally we can restart Apache and are up and running." Sadly, I am not up and running.

**Comment by Nebucatnetzer** [comment]
Now that you're mentioning it I did change the APP_URL to my real url.
However I didn't change the APP_ENV variable so that shouldn't be the problem.

Did you grant the www-data user ownership of the monica installation?
And the system you're using is Debian Stretch?

**Comment by Nebucatnetzer** [comment]
Ah and something else which I just noticed:

You probably have to change in:
/etc/apache2/apache2.conf

```<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
```
to
```<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```

**Comment by githubber** [comment]
Thank you so much for your input. I'll keep in mind, but I'm too tired to try all over again.

**Comment by Nebucatnetzer** [comment]
Thank you for reporting it.
I've created a pull request to update the guide which hopefully should work better now :)

**Comment by djaiss** [comment]
@githubber can you close this issue if you think it's solved? Thanks!

**Comment by githubber** [comment]
well, could you give me a few pointers on how to install monica to a folder like /var/www/html/monica/public ? I want to use a few other apps on the server so can't have Monica using the /var/www/html alone.
