### ISSUE TITLE
Where do I place the .env file?

### ISSUE THREAD

**Issue by madmads11** [monicahq/monica#3118]
Apologies if this is a stupid question, but where do I place my .env file?

in my docker-compose.yml, MonicaHQ's volume looks like this:
`      /home/docker-monica/monica_data:/var/www/monica/storage`
Do I then put my .env file in the `/home/docker-monica/monica_data` folder?

If so, how do I refer to it in docker-compose? In the example, it simply says:
`    env_file: .env`
Is this enough direction to specify it's location?

Thank you for your patience. I'm trying to set up MonicaHQ behind a reverse proxy and it is not working, I'm suspecting this is the problem.

**Comment by tbirrell** [comment]
The project root. Where ever the `.env.example` currently lives. Just copy the file in the same directory and rename it `.env`.

**Comment by asbiin** [comment]
@madmads11 I think your asking the question regarding to a docker instance?
You have to place the `.env` file in the same directory of the `docker-compose.yml` file. It is not a good idea to put it in any volume created.
Another solution is to place environment variable in the `docker-compose.yml` directly.

**Comment by Paladiamors** [comment]
I have the same problem and am trying to put the .env file into the root directory but monicahq does not seem to pick up the configuration:

`docker run --mount type=bind,source=/tmp/monicahq/.env,target=/var/www/.env monicahq/monicahq`

Is this the right location?

**Comment by kfa496** [comment]
same problem here. i also dont know where to place env file
