### ISSUE TITLE
Add a console command which sends a test email

### ISSUE THREAD

**Issue by cashweaver** [monicahq/monica#3128]
I propose adding a new console command which would send a basic email to a specified user account. The purpose of this feature is to aid in debugging email/SMTP configurations in the self-hosted application. The command should cause an email to be sent regardless of any app state (eg: [Time of the day reminders should be sent](https://github.com/monicahq/monica/issues/1020#issuecomment-374817879)).

Perhaps it should accept the user's ID as an argument as a means of obtaining the `to` email address.

**Comment by mechanarchy** [comment]
This would have been useful for me when I was trying to set up Mailgun. As a workaround I just kept trying the "forgot password" link with my email, which worked but involved a couple more steps.

**Comment by theexplosivegroup** [comment]
@mechanarchy That's what i did too!
