### ISSUE TITLE
Feature request: Characteristics

### ISSUE THREAD

**Issue by jeremydenoun** [monicahq/monica#313]
I'd like to add some characteristics to a contact (for reminder, search, statistics, ...) but I think this shouldn't use static columns/table definitions.

I imagine a feature like we can find into e-commerce software where you can add on products some "fields" with a type and a name.

Example :
- Should be invited to my party ? (bool: Yes / No)
- Pets Name (text)
- Introduction context (textarea)
- Favorite Color (select: blue/red/white...)

I think this can be done with 1-to-N join table associated to a global characteristic table but we should plan to be careful with :

- if field is mandatory or not (for next update)
- edition/deletion process
- migration consistency

@djaiss this can reach your roadmap ?

**Comment by Nebucatnetzer** [comment]
This could probably be achieved with this request #79

**Comment by jeremydenoun** [comment]
you've right this is a duplicate I close it
