### ISSUE TITLE
Uneditable Date Selector in Personal Information Page

### ISSUE THREAD

**Issue by slgphantom** [monicahq/monica#3130]
**Describe the bug**
Uneditable date selector in the personal information page. Specifically, when I choose the option "
I know the day and month of the birthdate of this person, but not the year…", the month is editable, but the date is stuck in "25" regardless of the value you choose in the drop-down menu

**Screenshots**
![image](https://user-images.githubusercontent.com/22796160/67547437-b003ad80-f731-11e9-959f-0b7dce33ea81.png)

**Which version are you using:**
 - Self-hosted Server (Ubuntu 18.04.3), Version: 2.15.2

**Comment by slgphantom** [comment]
Duplicate of #3045 

It seems to be a problem of Chromium-based browsers. The date select box just sticks to the current date and cannot be changed

**Comment by charlessteiner** [comment]
I have the problem in Firefox. The drop down does not drop but I key in the date.

**Comment by mechanarchy** [comment]
I'm using a Chromium-based browser (`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.99 Safari/537.36 Vivaldi/2.9.1705.41`) with a self-hosted instance of 2.15.2 and **don't** experience this issue. 

However, Firefox (`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0`) on the exact same machine **does** - the dropdown can be opened but closes itself after a fraction of a second.

**Comment by nr458h** [comment]
I'm on 2.14 and it is even worth because I can't edit any date not only in the contact details also for example in activities ...

**Comment by asbiin** [comment]
Using Firefox for a long time, and I never saw this problem.
