### ISSUE TITLE
New name pattern

### ISSUE THREAD

**Issue by keunes** [monicahq/monica#3139]
I use the 'nick name' field to enter people's 'calling name' (roepnaam, in Dutch) - how we call ppl in daily life. That's also the name by which I'd like to display & sort contacts.

Therefore, I'd like to suggest a new name pattern: `<Nickname> (<First name> <Last name>)`, which would resort to `<First name> <Last name>` if there is no nickname.

**Comment by maxcell** [comment]
If we want to build this, I definitely love this idea!

I am a person who doesn't go by their first name and I love it when people go by the name I tell them instead.
