### ISSUE TITLE
Fields not highlighted/activated upon click / not able to enter apostrophe 

### ISSUE THREAD

**Issue by keunes** [monicahq/monica#3149]
**Describe the bug**
I'm using Monica in Rambox, where I also have messaging & email web-services active. After reloading the tab, I can activate fields & type apostrophies (" and ') and special characters via dead keys (é á). However, when another page gets loaded as I click on a link, the fields don't get 'active' any-more (they don't change colour) and when using the apostrophe key nothing happens. When I then reload the page afresh it works again.
Note that I don't have this issue in any of the other Rambox tabs (Mastodon, Whatsapp, Gmail).

**Screenshots**
![Screenshot from 2019-10-31 00-01-37](https://user-images.githubusercontent.com/11229646/67905622-41c84c00-fb72-11e9-947a-2344ebeb732f.png)
![Screenshot from 2019-10-31 00-03-28](https://user-images.githubusercontent.com/11229646/67905623-41c84c00-fb72-11e9-97fb-1021fb08b829.png)
Note in the second box the 'add content' box indicates the field is active, while there is no cursor and a wrong background colour.

**Which version are you using:**
 [x] Hosting version on https://app.monicahq.com

Would be happy to try and help debug, if I need to provide any extra details.

**Comment by asbiin** [comment]
I've never seen this unexpected behiavor, and I have no idea what can cause it.
Unfortunatly, I cannot reproduce this, unless you can provide us other information?

**Comment by keunes** [comment]
@asbiin What kind of other information would you (possibly) need?

**Comment by asbiin** [comment]
First check if every resources are loaded and you have no 404 or other errors. Then any log...

**Comment by asbiin** [comment]
This is not reproductible right now.

**Comment by keunes** [comment]
I've since moved to [Ferdi](https://getferdi.com/) where this is not an issue. Thanks again for working on Monica.
