### ISSUE TITLE
APP_DISABLE_SIGNUP=true does not work

### ISSUE THREAD

**Issue by minthemiddle** [monicahq/monica#3159]
- The setting `APP_DISABLE_SIGNUP=true` does not do anything and seems to be unsupported
- I could not find any reference to the env in any code within Monica
- Also, using the `true` setting does not prevent registration
- This is on latest commit (`8652de20764`)
- Also this setting should be in the UI setting for the admin, not in the env

**Comment by asbiin** [comment]
The environment variable is used here https://github.com/monicahq/monica/blob/master/config/monica.php#L25 and it works perfectly.
There is no admin setting for now, but we are working on that, see #1876

**Comment by minthemiddle** [comment]
That is another config reference. I do not see any code where there are conditional actions based on the setting. I do not see any differences nor tests that could prove that it works and will file a more detailed bug report.
