### ISSUE TITLE
Heroku SQLSTATE[42S22]: Column not found: 1054 Unknown column 'temperature_scale' in 'field list' 

### ISSUE THREAD

**Issue by theexplosivegroup** [monicahq/monica#3175]
**Describe the bug**
I have installed Monica on to Heroku, however cannot get past registration.

I receive the folliwing error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'temperature_scale' in 'field list' (SQL: insert into `users` (`account_id`, `first_name`, `last_name`, `email`, `password`, `locale`, `timezone`, `currency_id`, `temperature_scale`, `updated_at`, `created_at`) values (5, FirstName, LastName, emailaddress, password, en, Australia/Melbourne, 17, celsius, 2019-11-09 03:41:24, 2019-11-09 03:41:24))

when i try run 'php artisan migrate' -  i get:

In Connection.php line 664:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'CHARACTER SET utf8mb4 DEFAULT NULL  
   COLLATE `utf8mb4_unicode_ci`' at line 1 (SQL: ALTER TABLE gifts CHANGE abo  
  ut_object_id about_object_id INT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE  
   `utf8mb4_unicode_ci`)                                                       
                                                                               

In PDOConnection.php line 63:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'CHARACTER SET utf8mb4 DEFAULT NULL  
   COLLATE `utf8mb4_unicode_ci`' at line 1                                     
                                                                               

In PDOConnection.php line 61:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'CHARACTER SET utf8mb4 DEFAULT NULL  
   COLLATE `utf8mb4_unicode_ci`' at line 1 

**Which version are you using:**
hosting version on heroku, latest version

**Additional context**
It appears as thought the weather migration isn't in the database migrations table, as referred to in previous issue.

Any ideas guys? SUPER keen to try out this app!

**Comment by asbiin** [comment]
Hi.
It appears migrations have not been passed totaly.
You have to re-run the migration process (php artisan migrate). If it's not working ... I don't know what to do then !

**Comment by theexplosivegroup** [comment]
Hi Asbiin,

Thanks for the response!

The php artisan migrate command gives the errors:
In Connection.php line 664:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
n your SQL syntax; check the manual that corresponds to your MySQL server v
ersion for the right syntax to use near 'CHARACTER SET utf8mb4 DEFAULT NULL
COLLATE utf8mb4_unicode_ci' at line 1 (SQL: ALTER TABLE gifts CHANGE abo
ut_object_id about_object_id INT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE
utf8mb4_unicode_ci)

In PDOConnection.php line 63:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
n your SQL syntax; check the manual that corresponds to your MySQL server v
ersion for the right syntax to use near 'CHARACTER SET utf8mb4 DEFAULT NULL
COLLATE utf8mb4_unicode_ci' at line 1

In PDOConnection.php line 61:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
n your SQL syntax; check the manual that corresponds to your MySQL server v
ersion for the right syntax to use near 'CHARACTER SET utf8mb4 DEFAULT NULL
COLLATE utf8mb4_unicode_ci' at line 1

and wont' work

**Comment by djaiss** [comment]
Yep, we've seen that the latest update to DBAL breaks our migration (https://github.com/doctrine/dbal/pull/3311). We'll revert the update of this package very soon.

**Comment by theexplosivegroup** [comment]
@djaiss Great stuff!
Super keen to get it up and running!

**Comment by theexplosivegroup** [comment]
HI @djaiss, I'm not sure this issue is fixed. I updated my heroku and now received:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aaxwfbqdhklfzc0y  
  .significant_others' doesn't exist (SQL: alter table `significant_others` d  
  rop `last_name`)
