### ISSUE TITLE
how does the search work?

### ISSUE THREAD

**Issue by icf20** [monicahq/monica#3177]
hello I am testing monica and for some reasons search field dont work for me, I dont know if is a bug or a fault of my setup

**Comment by asbiin** [comment]
The search works very well!
We can't help without a minimum of context... Don't hesitate to complete your issue here.

**Comment by theexplosivegroup** [comment]
@icf20 The search only works with the name i think. I don't you're able to search via tags or job or anything like that

**Comment by asbiin** [comment]
For search improvements, I invite you to follow #1017 or #2590

**Comment by icf20** [comment]
@asbiin ok then is a issue on my end

@theexplosivegroup in my case i does not work even by name 

when i got time i will take a better look at this and open a proper issue
