### ISSUE TITLE
Sponsor button seems to be buggy

### ISSUE THREAD

**Issue by jkbecker** [monicahq/monica#3217]
When I click the sponsor button, I'm getting this error message:

<img width="460" alt="Screenshot 2019-11-17 at 13 41 39" src="https://user-images.githubusercontent.com/31668498/69012111-19956700-0940-11ea-92e8-80316bee89a7.png">

**Comment by mechanarchy** [comment]
This is because @djaiss is in the `FUNDING.yml` file:
https://github.com/monicahq/monica/blob/751c5bd86bbb02c6ba740a7ada266015bd0672d0/.github/FUNDING.yml#L1

But isn't registered as part of the [GitHub Sponsors](https://github.com/sponsors) feature.

**Comment by asbiin** [comment]
Fixed now
