### ISSUE TITLE
Add possibility to log phone calls

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#322]
Not the phone call itself, but the fact that you've had a call.

I imagine a Quick Log call button, that you could just press, and it would record the fact that you've had a phone call. That way, we could know when you last called someone, and have smart filters and reminders to call a friend.

Also, once the API is done, I'm sure we could make this logging automatic on Android.

**Comment by Phrohdoh** [comment]
> Also, once the API is done, I'm sure we could make this logging automatic on Android.

This is iffy and should be opt-in.

**Comment by djaiss** [comment]
OF COURSE. This is a no brainer. Just saying that if the feature was there, I'd do it. But every single feature that will be potentially dangerous to your privacy, will be optin.

Keep in mind that once the API is out, I will have no control over an Android app that uses my API to do something. If the developer creates an app that logs automatically the calls, I won't be able to do anything about it.

The phone calls will be a new Object entity, stored in a new table, and will be available through the API.
