### ISSUE TITLE
FYI: I made a Franz module for Monica

### ISSUE THREAD

**Issue by jkbecker** [monicahq/monica#3244]
Hi all,
I am using [Franz](https://meetfranz.com/) to bundle all my messenger services into one neat app.
I thought I would let you know that I built a plugin for Franz that integrates Monica neatly into the application: https://github.com/jkbecker/recipe-monica
Any feedback much appreciated!
Feel free to close this at any time, I just wanted to make you aware of its existence and I hope it will be helpful to more folks than just myself.

**Comment by djaiss** [comment]
Thanks a lot @jkbecker for this 😀

**Comment by asbiin** [comment]
Hi @jkbecker I've just tested it and it's working nice! Thank you!
Any chance to have it integrated on the official websites?
