### ISSUE TITLE
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/monica/vendor/sentry/sentry/lib/Raven/Client.php on line 309

### ISSUE THREAD

**Issue by charlessteiner** [monicahq/monica#3257]
Throwing this error on artisan schedule:run

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/monica/vendor/sentry/sentry/lib/Raven/Client.php on line 309
Full email in spool

Subject: Cron <apache@asdf> /usr/bin/php /var/www/monica/artisan schedule:run
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=53>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/48>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/usr/share/httpd>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=apache>
X-Cron-Env: <USER=apache>
Message-Id: <>
Date: Sat, 30 Nov 2019 14:47:01 -0800 (PST)

fatal: Not a git repository (or any of the parent directories): .git
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/monica/vendor/sentry/sentry/lib/Raven/Client.php on line 309
No scheduled commands are ready to run.

Monica 2.2.1
Apache
Centos 7
PHP 7.4.0

**Comment by mechanarchy** [comment]
Monica [2.2.1](https://github.com/monicahq/monica/releases/tag/v2.2.1) is nearly 18 months old. Are you able to update to a more recent release? The newest version is [2.15.2](https://github.com/monicahq/monica/releases/tag/v2.15.2) and will likely have fixed this issue, especially as this error is in a third party module: Monica updated the `sentry` dependency from version 0.11.0 to 1.0.0 [in March](https://github.com/monicahq/monica/commit/ec8835b88f1d8b19a6c14cd0fb9f78289ec17a0e).

**Comment by djaiss** [comment]
Thanks @mechanarchy for this comment. Indeed, version 2.2.1 is really old and we probably already fixed this bug. @charlessteiner feel free to reopen this issue if the bug still exists after upgrading your instance.
