### ISSUE TITLE
Setting non-repeating reminder creates exception

### ISSUE THREAD

**Issue by skanur** [monicahq/monica#326]
Creating a non-repeating reminder for a contact creates an exception. 

How to recreate the issue:
1. Open any contact, under reminder -> Add reminder
2. Fill the title and date
3. Make sure _remind me about this just once_ is selected
4. Optional comment field can be empty
5. Create reminder

An example of a form that creates exception is shown in the attachment (below):
![bug_monica_upload](https://user-images.githubusercontent.com/5601252/27218038-17ac99c8-5285-11e7-96f8-2bf03abc9626.png)

**Comment by djaiss** [comment]
In theory I've fixed this in the last hour. Can you double check? Thanks a lot!

**Comment by skanur** [comment]
@djaiss It works as expected. Thank you! 

Also, may I add, wonderful job on creating monicahq. Thank you!
