### ISSUE TITLE
SQL broken

### ISSUE THREAD

**Issue by alexriabtsev** [monicahq/monica#3291]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
Monica dashboard doen't load with error: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `users` where `id` = 1 limit 1)

**Screenshots**

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/8425396/70391208-2d7e3700-19db-11ea-854f-0e43f0735bfd.png">

**Which version are you using:**
self-hosted version

**Additional context**
didn't change anything after monica install

**Comment by sylvainmetayer** [comment]
A `Connection refused` might come from an invalid user/password. Did you check them ? Can you run a SQL query with mysql client on your server to check this ? (`mysql -u USER -p DATABASE -e 'SELECT * FROM users;'`

This can also come from  an invalid host `DB_HOST`, what is the value of this variable ?

**Comment by alexriabtsev** [comment]
don't bother I just moved my app to Heroku :)

**Comment by asbiin** [comment]
Thank you @sylvainmetayer for the help!
I hope your Heroku instance is working ;)

**Comment by alexriabtsev** [comment]
@asbiin it is working but I need to move 10k contacts - that's not an easy task!
