### ISSUE TITLE
Add 'me'

### ISSUE THREAD

**Issue by nitinthewiz** [monicahq/monica#33]
'Me' as a contact is important, specially to define relationships of others to yourself. One way to do this is to simply add yourself as a contact. But a better approach would be to have that option in the settings.

**Comment by degan6** [comment]
What other types of features would this have.

**Comment by nitinthewiz** [comment]
I've not thought of anything else yet, because not having 'me' broke all usability for me in a way and I've not used the service after that.

**Comment by erdmenchen** [comment]
This is not so easy:
* it should be possible to mark certain persons as my own parents / spouse / kids
* this relation is not limited to a single person:
  * I can have a mother and a stepmother
  * I can have multiple partners... (one after another ;-) )

Other related features:
* send me birthday greetings on my birthday

**Comment by heliostatic** [comment]
Yes, I should be able to mark contacts as related to me (partner, child, parent)

**Comment by ronaldevers** [comment]
As a new user this has been my main question: how do I record the relationships *to me*! I guess it's not an incredibly important issue because there is an work-around of adding yourself as a contact. I was trying to find what people are doing and found this issue. So I guess that's what I'm doing for now then. Getting reminded to wish myself a happy birthday is going to be a bit strange, a couple months from now :-)

**Comment by diesl** [comment]
Although it is a special case, I was also surprised not to have the possibility to describe a person's relationship to myself. It would add some nice functionality, for example it could be used to filter the people list (family, friends, colleage, etc)

**Comment by chapay** [comment]
It would be also very nice if it worked with several users as well, so everyone can have each own profile and link relationships to other users.

**Comment by trwnh** [comment]
Couldn't this be done simply by adding a feature to mark a designated contact as representing yourself? I don't see why it needs to be an entirely separate feature.

**Comment by degan6** [comment]
Going off @trwnh, it could be a field in the user field that links to a contact_id. That way even if you have an account with many users Monica will show the correct me.

**Comment by robwent** [comment]
Has there been any progress on this?

Having just installed, it seemed pretty odd that I can't mark people as my relations.

**Comment by tylerwgoza** [comment]
I notice that this is on the roadmap for 2019 as of two months ago. But wanted to add an upvote and say that adding an option to a contact (like iOS does) would be an ok way to do it. But wonder if it might not be better to simply add me or self as an option for relationships. That way you don’t have to do any special logic around the “me” contact (disabling birthday reminders, etc...) do you guys have an idea of which way you prefer? I may try to take a stab at a PR for this if you know how you would like this to work. If no one beats me to it.

**Comment by robwent** [comment]
@tylerwgoza I think the problem with that is that it doesn't work in a multi-user environment as 'me' needs to relate to the person who selected the option?

If you just added an option to a contact, eg 'mother' then it would show as mother for other users as well.

**Comment by minthemiddle** [comment]
Option to a contact (as in iOS) would be totally fine.

**Comment by cabello** [comment]
My suggestion: Keeping in mind that this is in theory a multi-user environment, inferring that from the ability to invite people, I think to keep it simple, one should add a new contact, and be able to say: "this is me" while logged in, then "Me" just becomes a shortcut for that record. It would be a fully featured experience but it would be good enough for 80% of the cases, then later this could be revisited.

**Comment by RCheesley** [comment]
Glad to see this being implemented, it was my first question I couldn't figure out once I started using the system!

**Comment by cayblood** [comment]
Not sure if it's possible to create separate logins for the same Monica account, but if so, then it would good to track which contact is self on a per-login basis. For example, I'd like to be able to give my wife a separate login to our joint account, where she could designate the contact representing her as self and I could designate the contact representing me as self.

**Comment by nitinthewiz** [comment]
Bravo @asbiin! Thank you so much for the work you've done in closing this issue! 😄

**Comment by asbiin** [comment]
Thank you @nitinthewiz !
It's just the first step, we still have a lot to do on the contact page, the searches listbox, etc. But we will improve monica with pleasure, as always :)
