### ISSUE TITLE
profile picture doesn't appear.

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#330]
When I upload a profile picture it's just blank.
Does it need some specific ratio?

**Comment by djaiss** [comment]
Normally not. Which version are you using? .com or self hosted?

**Comment by Nebucatnetzer** [comment]
Self hosted

**Comment by Nebucatnetzer** [comment]
Doesn't work on .com either.

**Comment by djaiss** [comment]
It's working on .com but only if you do a page reload... Weird.

**Comment by Nebucatnetzer** [comment]
Ah nevermind just took a bit time to load on .com

**Comment by djaiss** [comment]
Can you verify on self hosted? I'm trying on my local env and it's working.

**Comment by Nebucatnetzer** [comment]
I think I found the problem:

```
ansible@monica:/var/www/html$ ls -l                                                                                                                                           total 32                                                                                                                                                                      drwxrwxr-x 4 www-data www-data 4096 Jun 14 11:45 build                                                                                                                        drwxrwxr-x 2 www-data www-data 4096 Jun 14 11:45 css                                                                                                                          -rw-rw-r-- 1 www-data www-data    0 Jun 12 21:22 favicon.ico                                                                                                                  drwxrwxr-x 4 www-data www-data 4096 Jun 12 21:22 fonts                                                                                                                        drwxrwxr-x 3 www-data www-data 4096 Jun 12 21:22 img
-rw-rw-r-- 1 www-data www-data 1786 Jun 12 21:22 index.php                                                                                                                    drwxrwxr-x 2 www-data www-data 4096 Jun 12 21:22 js
-rw-rw-r-- 1 www-data www-data   24 Jun 12 21:22 robots.txt                                                                                                                   lrwxrwxrwx 1 www-data www-data   32 Jun 12 21:41 storage -> /var/www/html/storage/app/public
-rw-rw-r-- 1 www-data www-data  914 Jun 12 21:22 web.config                                                                                                                   ansible@monica:/var/www/html$ ls storage 
ls: cannot access 'storage': Too many levels of symbolic links
```

**Comment by djaiss** [comment]
How can we fix this?

**Comment by Nebucatnetzer** [comment]
Good question.
I've fixed the symlink by creating a manual one.
The picture still doesn't appear, however I can see that they get uploaded.
They appear in storage/app/public/avatars

I reckon there's something wrong with the apache config.

**Comment by djaiss** [comment]
Ohh Apache. Using nginx here. We need people who knows Apache stuff.

**Comment by Nebucatnetzer** [comment]
I've searched a bit around but couldn't find anything that helped so far.
The Apache config doesn't seem to be too far of, from what I've seen during my quick search.

**Comment by Nebucatnetzer** [comment]
I really don't know why Monica can't show the picture.
I checked that the setup fits what is written in the laravel documentation.
The picture is accessible from the outside:
https://monica.2li.ch/storage/avatars/j3eyl0LGorGJawiFV7Jq1mxoYfSzaCTviLGWk0oj.png

**Comment by Nebucatnetzer** [comment]
Ah I think I just jound the problem.
Monica stores the file as j3eyl0LGorGJawiFV7Jq1mxoYfSzaCTviLGWk0oj.png
but when it wants to serve it, it looks for a slightly different file:
```
<img src="/storage/avatars/j3eyl0LGorGJawiFV7Jq1mxoYfSzaCTviLGWk0oj_110.png" width="87">
```

**Comment by Nebucatnetzer** [comment]
However I noticed that the picture doesn't get cropped this way. Something doesn't work properly here.

**Comment by jcalonso** [comment]
@Nebucatnetzer This can happen in two different scenarios:

1) You haven't setup a supervisor job that keeps your Laravel queue workers running, meaning that the resizing of the image is queued but the job never executed.

2) Even if you have the Laravel queue workers running the resizing can take a bit more than the page reload, that's why you have to reload the page again in order to see the image.

I guess a quick solution is to fall back to the original image if there resize is not there.

I hope this makes sense.

**Comment by djaiss** [comment]
Closing due to a lack of inactivity.
