### ISSUE TITLE
Can't choose the day when I just know the month/day of a contact date of birth

### ISSUE THREAD

**Issue by elanosilveira** [monicahq/monica#3315]
I can't choose the day of the birthdate of a person when choosing "*I know the day and month of the birthdate of this person, but not the year…*".

Every time I click on the "DAY" it keeps going back to the "MONTH". If I want to choose a day, I have to press TAB key and use the arrow keys to select the day.

**Version**: Self-hosted v2.15.2 / app.monicahq.com

![I know the day and month of the birthdate of this person, but not the year…](https://i.imgur.com/ITu0mRM.png)

**Comment by asbiin** [comment]
OK I know where this comes from
