### ISSUE TITLE
Language names should not be translated

### ISSUE THREAD

**Issue by elanosilveira** [monicahq/monica#3323]
As a standard, language names used for drop-down menus should not be translated. There's no reason for them to be translated since someone native in Hebrew, with their interface in Portuguese, would have a hard time finding the right version in Hebrew.

Also, Brazilian is not a language, but the people who live in Brazil. It could sound offensive to a Brazilian.

Arabic [العربية]
Brazilian [Português (Brasil)]
Chinese Simplified [中文]
Croatian [Hrvatski]
Czech [Čeština]
Dutch [Nederlands]
English [English]
French [Français]
German [Deutsche]
Hebrew [עברית]
Italian [Italiano]
Portuguese [Português]
Russian [Русский]
Spanish [Español]
Turkish [Türkçe]

Source: https://en.wikipedia.org/wiki/List_of_language_names

**Comment by elanosilveira** [comment]
@asbiin, This is not a feature. It's just to make it easy for the end user. It should be fixed on https://crowdin.com/. I left a few comments.

**Comment by asbiin** [comment]
Thanks @elanosilveira, but it's a proposal for an enhancement in our application = it's a feature request.
Language name *must* be translated, and they will, but the idea to display the langage in the native langage name is nice. I made a PR for this.

I will have to refuse your translations in crowdin for this reason (5 translation for each langage name).

**Comment by asbiin** [comment]
And thank you by supporting us with your translation!

**Comment by elanosilveira** [comment]
No problem, @asbiin. Thanks. 

Just sharing the right way of displaying supported languages.

**Comment by asbiin** [comment]
I think this looks good this way:
![image](https://user-images.githubusercontent.com/25419741/71426831-87a41b00-26b0-11ea-9b1e-be568c22ea63.png)

**Comment by elanosilveira** [comment]
Right.

Other examples:

https://www.adobe.com/#languageNavigation
https://www.spotify.com/us/select-your-country/
https://www.microsoft.com/en-us/locale.aspx?absoluteReturnUrl=https%3a%2f%2fwww.microsoft.com%2fen-us%2f

**Comment by elanosilveira** [comment]
Brazilian is not a language. Brazilian Portuguese is the right spelling.

**Comment by asbiin** [comment]
--> see my PR, it's fixed.
