### ISSUE TITLE
Reminders not working

### ISSUE THREAD

**Issue by elanosilveira** [monicahq/monica#3324]
**Describe the bug**
I'm not receiving any e-mail reminders. When I invite a user or request to reset my password, I receive an email, but birthdays reminders and stay in touch reminders don't work.

**Which version are you using:**
- Self-Hosted v2.15.2

**Log:**
No errors in storage/logs

ENV file:
```
# Mail credentials used to send emails from the application.
MAIL_DRIVER=mailgun
MAIL_HOST=smtp.mailgun.org
MAIL_PORT="587"
MAIL_USERNAME=postmaster@sandbox4d5a9854920f21.mailgun.org
MAIL_PASSWORD=7132a158e695ef-5645b1f9-09c75161
MAIL_ENCRYPTION=tls
# Outgoing emails will be sent with these identity
MAIL_FROM_ADDRESS=postmaster@sandbox4d5a9854920f21.mailgun.org
MAIL_FROM_NAME="Monica"
# New registration notification sent to this email
APP_EMAIL_NEW_USERS_NOTIFICATION=

MAILGUN_DOMAIN=sandbox4d5a9854920f21.mailgun.org
MAILGUN_SECRET=key-89f723526a2b2653ed5f6fdc

```

**Comment by asbiin** [comment]
It seems you have set a specific queue and then no worker run, or you didn't set a scheduler?

**Comment by elanosilveira** [comment]
I have a cron in /etc/cron.d called 'monica' with the following:

```* * * * * sudo -u www-data php /var/www/monica/artisan schedule:run```

**Comment by elanosilveira** [comment]
@asbiin,

To solve the no crontab for www-data, I ran the following command:
`sudo crontab -u www-data /etc/cron.d/monica`

"_sudo crontab -u www-data -l_" **is now returning**:
`* * * * * sudo -u www-data php /var/www/monica/artisan schedule:run`

**When I ran** "_grep cron /var/log/syslog_":

```
Dec 22 12:17:52 localhost cron[745]: (CRON) INFO (pidfile fd = 3)
Dec 22 12:17:52 localhost cron[745]: Error: bad username; while reading /etc/cron.d/monica
Dec 22 12:17:52 localhost cron[745]: (*system*monica) ERROR (Syntax error, this crontab file will be ignored)
Dec 22 12:17:52 localhost cron[745]: (CRON) INFO (Running @reboot jobs)
root@ubuntu:~#
```

**Cron in etc/cron.d/monica**

`* * * * * sudo -u www-data php /var/www/monica/artisan schedule:run  `

I googled, but I can't find a way to make it work =(.

**Comment by elanosilveira** [comment]
Solution:

`crontab -u root /etc/cron.d/monica`

It will add the monica cron job and the reminders will work again. I'm still getting the bad username error, but I will close this issue anyway.
