### ISSUE TITLE
Allow float in debt amount field

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#333]
When you enter a debt you have to enter it as an integer.
However since this represents money a float would make more sense.

**Comment by djaiss** [comment]
Can this be added as a comment? Is this really needed?

**Comment by Nebucatnetzer** [comment]
Well it would nice if I could write down the exact amount but it surely isn't a deal breaker.
Just something which might irritate some people.

**Comment by djaiss** [comment]
Could you rename the issue to "Allow float in debt amount field" or something?

**Comment by degan6** [comment]
We could leave it as a int and make the view convert the int to "money" format $000.00 for $.

This is what Stripe does, everything is an int and they leave it to you to convert it amount in cents to dollars.

**Comment by Nebucatnetzer** [comment]
Well that wouldn't help. If you ow someone 12.5 you still can't enter the correct amount.
