### ISSUE TITLE
English (UK) Localisation

### ISSUE THREAD

**Issue by andrewaylett** [monicahq/monica#3343]
**Is your feature request related to a problem? Please describe.**
As a user located outside the US, I find US-style dates and Americanisms in the strings to be a distraction.

**Describe the solution you'd like**
Adding an en-gb locale (in CrowdIn) would allow customisation of the locale for non-US users.

**Describe alternatives you've considered (optional)**
I found #3335, which suggests customisable dates.  But I think a complete localisation would be more valuable.

**Additional context**
I'm hoping I might be able to do a chunk of the required work, but I don't think I can get started without having to ask someone else it put in at least a little effort first, sorry.

**Comment by elanosilveira** [comment]
Copy and paste the **en-en** to the **en-gb** localization, changing the date format, for now, would be ok. This way people from the UK would have the correct date and anyone can localize properly later.

**Comment by rc2pc2** [comment]
Hello there! 
I would love to make this my first contribution, may I ask further details on how to proceed?

Thank you in advance
R

**Comment by djaiss** [comment]
Thanks @andrewaylett for the suggestion.

Yes, sure, it would make sense to translate it to UK. I've created the PR (see above) and it will be ready to translate in the coming days.

**Comment by djaiss** [comment]
You can create an account on Crowdin if you want to help translate this new locale 😀 Thanks!
