### ISSUE TITLE
Docker on Heroku requires the port to be set using environment variables

### ISSUE THREAD

**Issue by VikashKothary** [monicahq/monica#3346]
First I want to start by saying the I'm getting familiar with Monica and I've a huge fan of what you're doing.

I'm using the MonicaHQ Docker image. I want to push it to Heroku. However it requires the docker image to be configurable using the `PORT` environment variable.

I'm not familiar with the code but I am assuming two changes are needed. 
1. The Laravel server needs to read the `PORT` environment variable.
2. The Docker image needs to expose the same `PORT` 

See for more information: https://devcenter.heroku.com/articles/runtime-principles#web-servers

**Comment by asbiin** [comment]
Hi

I don't know about docker on heroku, but this article is for heroku standard runtime, which is not about docker.
If you want to deploy on heroku from the sources we have a documentation for this: https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md

You may find some documentation about docker on heroku here, but I'm not an expert: https://devcenter.heroku.com/articles/container-registry-and-runtime
