### ISSUE TITLE
Editing a contact's profile creates duplicate birthday reminders

### ISSUE THREAD

**Issue by sid3windr** [monicahq/monica#335]
Every time you edit a contact, and you have the exact birth date filled in, an extra "Wish happy birthday to" reminder is created.

The code should ideally check if the birthday was already filled in, and if it was, not create a reminder.

Checking if the reminder already exists (was my first idea) is a less ideal way as it will reappear if you manually deleted it before.

**Comment by Nebucatnetzer** [comment]
This was already reported :) #325

**Comment by djaiss** [comment]
Closing this issue as it's a duplicate.
