### ISSUE TITLE
When singing up, lastname should be filled with autocomplete

### ISSUE THREAD

**Issue by tooppaaa** [monicahq/monica#3353]
**Describe the bug**
When signing up, autocomplete doesn't fill lastname

**Additional context**
Chrome 79.0.3945.79

** Potential fix**
Change autocomple="last_name" by autocomplete="family-name"
[Source](
https://developers.google.com/web/fundamentals/design-and-ux/input/forms/#recommended_input_name_and_autocomplete_attribute_values
)

It worked for my by changing the HTML.

**Comment by asbiin** [comment]
Hi @tooppaaa Thank you !
