### ISSUE TITLE
The calling texts doesn't show <ul> lists

### ISSUE THREAD

**Issue by biomcanic** [monicahq/monica#3388]
**Describe the bug**

When you fill a note in a contact with a list like this:
`- Blabla`
`- Blabla`

The dashes are converted to a html list `<ul>`:
- Blabla
- Blabla

But the issue is in the calling texts, although I put a list, it isn't converted to a html list `<ul>`.

**Which version are you using:**
 - A server you maintain yourself with version 2.15.2

**Comment by djaiss** [comment]
Thanks a lot for caring. The fix has been created and will be soon in production and in a new release. Sorry that you had to go through this error.
