### ISSUE TITLE
Can't create Personal Access Token on Heroku

### ISSUE THREAD

**Issue by fsmontenegro** [monicahq/monica#3389]
Hi!

Just trying out Monica right now and it looks VERY promising, thanks for the effort! 

I'm having an issue that when I attempt to create a token for API access (my instance is running on Heroku using the default install), I get the following error message:

![image](https://user-images.githubusercontent.com/10501259/71550606-cb45a000-29a2-11ea-8c6a-7698213037f9.png)

Whoops! Something went wrong.
Key path "file:///app/storage/oauth-private.key" does not exist or is not readable

Not sure how to proceed.

Thanks!

**Comment by elanosilveira** [comment]
Please, check #1355.

**Comment by asbiin** [comment]
Hk @fsmontenegro everything is explain in the doc: https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md#optional-setup-the-access-tokens-to-use-the-api
Don't hesitate to tell us if the doc could be improved!

**Comment by asbiin** [comment]
.. and thanks @elanosilveira for the answer!

**Comment by fsmontenegro** [comment]
Thank you! Setting it up on Heroku was so easy I missed out reading more details... :-) Newbie mistake, my apologies.
Really excited about Monica, seems to be exactly what I'm looking for.
Again, thank you and have a great new year!
