### ISSUE TITLE
extended currency list

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#339]
Is there maybe something like the country list for currencies?
At the moment it's very short. Is there maybe a library or so that we could implement?

**Comment by BrunoMRP** [comment]
This https://github.com/antonioribeiro/countries?

Or maybe this https://github.com/Torann/laravel-currency (probably overkill tough)?

**Comment by Nebucatnetzer** [comment]
The first one looks very promising.

**Comment by djaiss** [comment]
I love the first library indeed. Super promising.
