### ISSUE TITLE
Avatars on journal page show broken img icon

### ISSUE THREAD

**Issue by jatls** [monicahq/monica#3391]
When using adorable avatars, a broken avatar link is shown on the journal page. Everywhere else avatars are shown correctly.

**Screenshots**
https://i.postimg.cc/BQwPd83x/Screenshot-from-2019-12-29-22-36-43.png

**Which version are you using:**
 - Self-hosted 2.15.2

**Comment by elanosilveira** [comment]
It has already been fixed.
