### ISSUE TITLE
Minor feature request: birthday radio button

### ISSUE THREAD

**Issue by sid3windr** [monicahq/monica#341]
When you fill out a person's (contact, SO, child, ...) birthday the radio button for "I know the exact birthdate" should be automatically checked, from a usability perspective.

Very minor issue but every little bit helps!

**Comment by Nebucatnetzer** [comment]
Hm I think this various highly between users.
I personally know from very few persons their exact birthday. Maybe I know the exact date from ca. 10 persons.

IMO it makes sense to select the option which let's you save the form with the least problems (prompts for input).

**Comment by sid3windr** [comment]
But the birthdate input field is only used by the "I know the exact birthdate", isn't it?

I don't mean it should default to "I know the exact date" - "I don't know this person's age" is a fine default. 

But once you manually enter something into the birthday field (I have no idea why it defaults to today, by the way - how many times are you adding a contact the day he/she was born?), I feel it should jump to the "I know the exact birthdate" choice.

Otherwise you're entering the date for nothing because if you don't select the "I know the exact date" option, the date you entered will not be saved. This means if you're not 100% paying attention, the date you entered will be lost forever unless you can look it up somewhere else later.

**Comment by Nebucatnetzer** [comment]
Ah now I see what  you mean.
I agree that behaviour would make sense.

**Comment by Phrohdoh** [comment]
This is a duplicate of #21.

**Comment by sid3windr** [comment]
Darn it, not the first duplicate I open... didn't find it when searching for birthday, should have searched for birthdate instead. Indeed a duplicate, closing!
