### ISSUE TITLE
Restore ability to edit activities

### ISSUE THREAD

**Issue by xorgnz** [monicahq/monica#3415]
**Is your feature request related to a problem? Please describe.**
The new interface for editing activities inline appears to have removed the ability to edit activities after they're created. This makes the feature very frustrating to use, as every little error, say forgetting to fix the date or forgetting a participant means that I have to delete it and create it all over again. 

**Describe the solution you'd like**
An edit button or link from the activity label like there used to be that either opens the issue again in the new inline editor, or the old separate page editor.

**Describe alternatives you've considered (optional)**
At the moment, the only alternative is to delete and start again. This is quite frustrating compared to the previous functionality.

**Comment by mritzmann** [comment]
Same problem. My Use Case: During larger activities it happens that I cannot remember all participants. As soon as further details/participants come to my mind, I want to add them. Unfortunately this is no longer possible at the moment.

**Comment by asbiin** [comment]
Hi. It's not an issue, it was intended, but temporarly.
I'm working on a fix to restore activities edition.

**Comment by xorgnz** [comment]
Thanks @asbiin!
