### ISSUE TITLE
Inline Add Activity twice secretly adds details from first activity to second

### ISSUE THREAD

**Issue by xorgnz** [monicahq/monica#3416]
**Describe the bug**
Using the inline add activity form to create an issue with details results in those details being stored and being automatically included in the next use of that form, even if you haven't clicked "Add Details" to add any details to that form (meaning that this fact is obscured)

Repro steps:
* Click Add Activity to open inline activity add form
* Click Add Details, and enter some text
* Click Add to complete action.
* Click Add Activity to open form for a second new activity
* Click Add to complete action
* Observe that second newly created activity has details from the first

**Screenshots**
A screenshot is not particularly informative here.

**Additional context**
Using MonicaHQ.

**Comment by djaiss** [comment]
Thanks a lot for caring. The fix has been created and will be soon in production and in a new release. Sorry that you had to go through this error.
