### ISSUE TITLE
Make participant names in new activity list links

### ISSUE THREAD

**Issue by xorgnz** [monicahq/monica#3417]
The old list of activities (before inline activity adding was included) used to make participant names in the list be links to that contact's page. They are no longer, which makes shifting to new people more time and click consuming.

**Describe the solution you'd like**
Make participant names links, as shown in image:
![image](https://user-images.githubusercontent.com/931641/71636641-b5ccc080-2c97-11ea-9130-b88b523d282e.png)

**Comment by djaiss** [comment]
Thanks for your suggestion, it’s done and should be live soon.
