### ISSUE TITLE
ctrl-click on contact (avatar or name) creates two tabs with the same contact

### ISSUE THREAD

**Issue by bbrendon** [monicahq/monica#3421]
This is a variation of this bug.
https://github.com/monicahq/monica/issues/3376

You can ctrl-click on contacts but instead of getting a new tab with the contact you clicked on, you get a new tab and ALSO the current tab of the contact you clicked on.

**Comment by elanosilveira** [comment]
I've tried many different ways, but I couldn't reproduce what you reported. Could you please give us more details?

**Comment by bbrendon** [comment]
I was able to get it working by right clicking and then selecting open in new tab.

I'm on windows and I have my ctrl and caps-lock reversed. I wonder if that has something to do with it? I never have a problem on other websites. Very strange.

**Comment by bbrendon** [comment]
Its not the ctrl / caps-lock mapping. I tried it on someone else's computer and got the same results.

**Comment by bbrendon** [comment]
I sent you an email with a video.

**Comment by elanosilveira** [comment]
Please, keep ALL communications here only, so anyone can help you or feel free to send an email if requested. I can't reproduce your problem. It's working perfectly fine.

**Comment by bbrendon** [comment]
Sorry, I'm not going to post my personal information to the world no matter what you say.

**Comment by bbrendon** [comment]
I've tried it on 3 computers. 2 windows, 1 mac. All the same result. I wonder what's different. I even tried it on https://app.monicahq.com/people just in case something was wrong with my instance.

**Comment by asbiin** [comment]
@bbrendon OK I see what's happening, I'll fix it

**Comment by bbrendon** [comment]
@asbiin  I'm glad someone else sees it. Thank you!
