### ISSUE TITLE
How to increase the storage size beyond 512MB?

### ISSUE THREAD

**Issue by minosniu** [monicahq/monica#3423]
Thank you for making self-hosting a smooth sail.

However, the default storage of 512MB is too small for me. I tried modifying the 'max_storage_size" in config/monica.php and restart the container, but the frontend still reports my account storage to be 512MB. 

How to get over this capacity?

**Comment by djaiss** [comment]
Have you modified the `DEFAULT_MAX_STORAGE_SIZE` in your .env file as well?

**Comment by minosniu** [comment]
> Have you modified the `DEFAULT_MAX_STORAGE_SIZE` in your .env file as well?

Putting DEFAULT_MAX_STORAGE_SIZE in `docker-compose.yml` modified my storage size. Thanks!
