### ISSUE TITLE
Faster "Add New Person" user experience via a couple of tweaks

### ISSUE THREAD

**Issue by fsmontenegro** [monicahq/monica#3425]
This is a pair of possibly small feature requests. I noticed that when we search for a contact in the main contact bar, Monica will only display the "Add New Person" option if there were no matches at all against the current database of contacts. If the person I'm searching for doesn't exist yet but shares the same name/substring with others that already exist, the "Add New Person" link doesn't appear. This is frustrating as I'll have to add the person by moving over to "Add Someone" and then fill all the information again.

Here's a snippet of typing Pedr on my current database:
![image](https://user-images.githubusercontent.com/10501259/71696982-8e075680-2d84-11ea-956d-318e15632e1e.png)

Now if I type Pedri, the Add New Person option appears:
![image](https://user-images.githubusercontent.com/10501259/71697007-a24b5380-2d84-11ea-8404-4f096566b1ba.png)

Also, when I do click on "Add New Person" or "Add Someone", it brings me to a blank form.

**Describe the solution you'd like**
I'd like you to consider two changes:
- First, if I choose "add new person" from the drop down, consider copying the current text from the search bar over - if a single string is there, consider that the first name. If two strings separated by a space, prefill as first, last name.

Something like:
![image](https://user-images.githubusercontent.com/10501259/71697164-243b7c80-2d85-11ea-823b-52ed79e9da77.png)
would become
![image](https://user-images.githubusercontent.com/10501259/71697185-30bfd500-2d85-11ea-9f19-a54ed511089d.png)

- The other suggestion is to leave the "Add New Person" dialog option as an option on the drop down of names, even if substrings have been found.

**Describe alternatives you've considered (optional)**
No alternatives at this point.

**Additional context**
First feature request, apologies if this is not the right way to engage with the project.

Merci!!!

**Comment by asbiin** [comment]
Hi @fsmontenegro ! Nice ideas, and this is really good for a first feature request, don't mind!
