### ISSUE TITLE
Adding a person automatically uppercases first letter of name

### ISSUE THREAD

**Issue by sid3windr** [monicahq/monica#343]
While it is probably the most common case, not everyone's last (maybe even first? not sure!) name starts with a capital letter.

Luckily, editing the contact does not re-uppercase the letter, but I'm not sure automatically uppercasing it is the right thing to do.

**Comment by BranTurner** [comment]
@sid3windr Which language? I'm genuinely curious as I've never come across this!

**Comment by sid3windr** [comment]
At least in Belgium and The Netherlands you can have a lowercase letter as first letter.

I thought Italian had it too, but apparently not when using it as an actual surname (as I just googled and found https://www.thoughtco.com/italian-capitalization-rules-2011478).

It's not something one will run into often apparently though...

**Comment by djaiss** [comment]
Fixed https://github.com/monicahq/monica/commit/859dd47e31f774989a0a3247dc26041596cb7dec
