### ISSUE TITLE
Subscription Settings Missing, Autorenew Happened [Hosted Education Account] 

### ISSUE THREAD

**Issue by pqhf5kd** [monicahq/monica#3430]
I subscribed to Monica last January and some time after Regis upgraded me to a premium education account. There is no Subscription panel in the Settings menu under my account but the original subscription I paid for just auto renewed itself.

I can access the panel using a direct link:
https://app.monicahq.com/settings/subscriptions

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/20027419/71767261-b02ae100-2f0a-11ea-8cd5-7d35c414c3ea.png">

**Comment by djaiss** [comment]
Thanks for reporting this behaviour. 
I don't think we need to do something specific about this. It’s not a bug per se, but it’s not ideal, I know. Let's stick with the current behaviour for now.

**Comment by pqhf5kd** [comment]
It might be a niche case but not being able to access billing information is fairly critical. 

I imagine I will get billed again next year (even though I have an education account?), shall I cancel my subscription? Will I loose access or be restricted back to a limited account? What if my payment method had expired before the auto renewal happened?
