### ISSUE TITLE
Allow manual entry of dates

### ISSUE THREAD

**Issue by anchapin** [monicahq/monica#344]
The date selector for me on chrome on Android shows the current month and you have to tap the back arrow many times to get to the correct year for someone's birthday.

It would be nice if you could either manually type in the date in mm/DD/yyyy format or equivalent or make the date selector easier to use for dates from more than a year ago.

**Comment by Nebucatnetzer** [comment]
When you tap on the year in the top left corner of the date selector it allows you to quickly set the year.

**Comment by anchapin** [comment]
Thanks, I didn't realize that.
