### ISSUE TITLE
Unable to add 'gift' record

### ISSUE THREAD

**Issue by daryljones** [monicahq/monica#3442]
v 2.16 updated from master on 01/06/2020.

Existing Gift records are not displayed.

The following error message is displayed when attempting to add a new 'gift' record.

Whoops! Something went wrong.
Key path "file:///var/www/monica/storage/oauth-public.key" does not exist or is not readable

**Comment by biomcanic** [comment]
I have the same issue in Heroku, the previous version was working fine.

**Comment by asbiin** [comment]
Owh, that's unfortunate.
I will look for a solution, but to solve the problem, just follow the `Generate the encryption keys` procedure here:
https://github.com/monicahq/monica/blob/master/docs/installation/generic.md#7-optional-setup-the-access-tokens-to-use-the-api

**Comment by daryljones** [comment]
@asbin  Thanks!  Your suggestion worked for me.

**Comment by pqhf5kd** [comment]
Is this going to be fixed on the hosted version?
