### ISSUE TITLE
Add new activity categories

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#346]
Feedback:

```
* Went for drinks
* Went for coffee 
* Played a game together
```

**Comment by Nebucatnetzer** [comment]
Would it be possible to let the user edit this list?

**Comment by BranTurner** [comment]
I think it would be a good idea to make these user editable. Unless the list is incredibly long, there will always be something someone wants to add that does not apply to 99% of the userbase.

**Comment by djaiss** [comment]
I agree - a good idea for v2  😀

**Comment by Phrohdoh** [comment]
Let the user put text into a free-form text field and auto-suggest categories they have previously entered.

**Comment by pqhf5kd** [comment]
This has been completed correct?

**Comment by djaiss** [comment]
@pqhf5kd indeed 😀
