### ISSUE TITLE
Add participants in activity

### ISSUE THREAD

**Issue by sibuser** [monicahq/monica#347]
Would be really good to be able to add participants in the activity so you could later remember who attended this event.

**Comment by djaiss** [comment]
Do you mean, adding multiple participants in the same activity instead?

**Comment by sibuser** [comment]
Yes. 
For example I met my friend at the party and want to remember who attended this party also so next time you could see the connection.

**Comment by erdmenchen** [comment]
Duplicate of #118

**Comment by djaiss** [comment]
@erdmenchen Indeed. Closing this one in favour of the other one. Thanks.
