### ISSUE TITLE
The debt editing from always defaults to the "you owe" radio button

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#348]
https://github.com/monicahq/monica/blob/master/resources/views/people/debt/form.blade.php#L12

**Comment by mbluemer** [comment]
Can generalize this issue to the debt form not being responsive to existing data. Should probably also change the "Add Debt" button to "Edit Debt"

**Comment by Phrohdoh** [comment]
#350

**Comment by djaiss** [comment]
Why is that a problem?

**Comment by Phrohdoh** [comment]
The interface does not correctly reflect the data and makes (incorrectly) switching a you-are-owed debt to you-owe easily without realizing it.

**Comment by sid3windr** [comment]
Just ran into this as well and surprised this is such an old issue. Suddenly a number of debts showed I owed that person money while it was the other way around, because I edited the debt description and did not pay attention to the radio button.
