### ISSUE TITLE
Activities not Working on Heroku

### ISSUE THREAD

**Issue by galexynye** [monicahq/monica#3482]
**Unable to Use Activities**
Previously created activities appear in the journal but do not show up under the people that are associated with them and unable to create new activities or edit old ones from the journal. 

**Screenshots**
When trying to create a new activity, this error appears. 
![Screen Shot 2020-01-19 at 10 17 32 AM](https://user-images.githubusercontent.com/26336039/72678332-1a17be80-3aa5-11ea-84da-0d0c9a186046.png)

**Which version are you using:**
 - Heroku 
-  Monica 2.16.0  from January 18th
- Tried to a deploy a new instance using JawsDB and had the same issue

**Comment by yammesicka** [comment]
+1 for self-hosted (Google Compute engine). No logs or any other indicator.

Had some activities, but it look like they are missing now (though I can still see them on the database).

**Comment by pepawel** [comment]
+1.
I tried to `execute php artisan passport:keys` but it didn't help.
I'm using Monica on Heroku, 2.16.0.

**Comment by asbiin** [comment]
The passport keys are now used on api calls.
Try follow this doc for heroku: https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md#optional-setup-the-access-tokens-to-use-the-api

**Comment by galexynye** [comment]
@asbiin Thank you, that worked!

**Comment by galexynye** [comment]
The activities show up when entering a new activity all fields work except for the "Add more details". The details don't seem to be written to the database and when you try to edit it there is an error "Whoops! Something went wrong.

    ▪️ T
    ▪️ h
    ▪️ e
    ▪️
    ▪️ r
    ▪️ e
    ▪️ s
    ▪️ o
    ▪️ u
    ▪️ r
    ▪️ c
    ▪️ e
    ▪️
    ▪️ h
    ▪️ a
    ▪️ s
    ▪️
    ▪️ n
    ▪️ o
    ▪️ t
    ▪️
    ▪️ b
    ▪️ e
    ▪️ e
    ▪️ n
    ▪️
    ▪️ f
    ▪️ o
    ▪️ u
    ▪️ n
    ▪️ d "

**Comment by galexynye** [comment]
This issue has been fixed, thanks!
