### ISSUE TITLE
When adding a family or other relationship using the 'existing contact' radio button, Monica indicates the relationship was added but it is not visible in the person record.

### ISSUE THREAD

**Issue by daryljones** [monicahq/monica#3483]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
A clear and concise description of what the bug is. If your comment is `it doesn't work`, we won't know what to do with it.

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.
**Which version are you using:**
 - Hosting version on https://app.monicahq.com
 - Mobile version
 - A server you maintain yourself (if so, please indicate your current version of Monica)

**Additional context**

**Comment by elanosilveira** [comment]
Hi, @daryljones,

It works for me. I'm using version v2.16.0. Could you please follow the template add more details?

Are you using the hosting version?

Thanks,

**Comment by daryljones** [comment]
@elanosilveira - Sorry for not following the template instructions.  I'm running the latest code from the master branch on my own server.  The problem was that I ad the "Love Relationships" option disabled in Feature settings.  This seemed to make "Family Relationships" not work properly. I enabled "Love Relationships" and "Family Relationships" works properly now.

**Comment by asbiin** [comment]
I can confirm it works perfectly.
If you found something, please add more context: actions done, screenshots, etc.
