### ISSUE TITLE
Can't fetch Activities from MonicaHQ with Personal Bearer Token

### ISSUE THREAD

**Issue by davidbhayes** [monicahq/monica#3488]
**Describe the bug**
Making a GET request to https://app.monicahq.com/api/activities/ is failing for me. I'm using a personal bearer token, and able to fetch at least a few other resources I tried. (Context: just started to develop a little should pull data, and hitting this error in the first hour)

The message on the error page is:

> Target class [App\Http\Controllers\Api\ApiActivityController] does not exist.

**Screenshots**
<img width="1392" alt="Screen Shot 2020-01-20 at 1 23 30 PM" src="https://user-images.githubusercontent.com/2613891/72755585-1446d980-3b88-11ea-902e-d4f4f4e7188c.png">

**Which version are you using:**
Hosting version on https://app.monicahq.com

**Comment by asbiin** [comment]
Yes you're right. Api for activities has been removed, and rewrited from scratch.
Thias has been fixed in #3422 already, and it will been released soon.
