### ISSUE TITLE
Include a version string on the interface

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#349]
If this is done bug reports can/should include "I observed X on version x.y.z.123456", etc.

**Comment by erdmenchen** [comment]
That would require versions in the first place 😊
Also a release cycle and versioning schema should be defined.

**Comment by Phrohdoh** [comment]
`git rev-parse --short head` would be better than nothing.

**Comment by djaiss** [comment]
This is not a full time job for me. I can't live off this project for now, so there is no release cycle. Versioning schema will try to follow SemVer.
