### ISSUE TITLE
Wrong spanish translation in relationships

### ISSUE THREAD

**Issue by silva96** [monicahq/monica#3495]
`"La fecha de {{ Name }}"`

fecha means Date, but Date in this context means im dating someone.

In this context, date could be replaced with "cita" instead of "fecha"

`La cita de Benjamin` instead of `La fecha de Benjamin`

![image](https://user-images.githubusercontent.com/4019924/72901954-6b27ec80-3d09-11ea-9d91-b0023b560bd4.png)

**Comment by asbiin** [comment]
Thank you @silva96 .
Please read https://github.com/monicahq/monica/blob/master/docs/contribute/translate.md : translations are handled in our [crowdin project](https://crowdin.com/project/monicahq)
