### ISSUE TITLE
Toggles don't change visually

### ISSUE THREAD

**Issue by silva96** [monicahq/monica#3496]
When clicking these toggles, a message in the right bottom appears

![image](https://user-images.githubusercontent.com/4019924/72907351-7df2ef00-3d12-11ea-8c87-24472f92cc0c.png)

![image](https://user-images.githubusercontent.com/4019924/72907467-9fec7180-3d12-11ea-83cd-a2cce2407194.png)

But toggle state doesn't change visually. If I refresh the page they adopt their correct value

**Comment by djaiss** [comment]
Thanks a lot for caring. The fix has been created and will be soon in production and in a new release. Sorry that you had to go through this error.
