### ISSUE TITLE
Unable to resend verification email so can't access account

### ISSUE THREAD

**Issue by overtron** [monicahq/monica#3505]
**Describe the bug**
I am using the hosted version of the product at https://www.monicahq.com. I've tried the below on mobile and desktop.

I reset my password. Now when I try to log in I'm taken to this screen which asks me to "Verify Your Email Address". 
<img width="550" alt="Screen Shot 2020-01-24 at 9 57 15 AM" src="https://user-images.githubusercontent.com/8304179/73091825-1d89bc00-3e90-11ea-8056-d4d67d58df84.png">

When I click the "click here to request another" since I did not receive the email (checked spam and did a search in gmail). I receive a page that says "Whoops, looks like something went wrong." The url of that page is https://app.monicahq.com/email/resend. 

**Additional context**
I can't remember when I signed up for an account (although I've looked at this project a number of times of the years). What that means is that I signed up a long time ago and my account has been inactive for a significant period of time if that has any impact on why I might be having trouble accessing the service.

**Comment by asbiin** [comment]
Fixed by #3597
