### ISSUE TITLE
On php artisan setup:test I get an error in database/seeds/FakeContentTableSeeder.php

### ISSUE THREAD

**Issue by anegoda1995** [monicahq/monica#3507]
I want to contribute to this project, but I encountered an error in the installation project for developers.
I did all by this instruction: https://github.com/monicahq/monica/blob/master/docs/contribute/index.md#instructions

Branch: **master** (date: 25.01.2020)

**Error**
Error is about validation.
I explored this problem and added some code. After that seed was fully completed.
Now code looks like that:
![image](https://user-images.githubusercontent.com/10788396/73124472-95490b00-3fa4-11ea-9b24-d13c4feef3d7.png)

Tell me please can I push it as a pull request?

**Comment by asbiin** [comment]
Hi @anegoda1995 ! Thank you for your report, but this is already fixed by #3503.
In any case, don't hesitate to open a pull request with a fix, rather than an issue with a fix inside, asking for the right to open a pull request.
