### ISSUE TITLE
API docs lists wrong career endpoint

### ISSUE THREAD

**Issue by JanOwiesniak** [monicahq/monica#3508]
API docs say it is `PUT /contacts/:id/career`

https://www.monicahq.com/api/contacts#update-a-contact-career

but it is actually `PUT /contacts/:id/work`

https://github.com/monicahq/monica/blob/47ef3d75a72267098f2e5463bba6dacaf707bc2b/tests/Api/Contact/ApiContactControllerTest.php#L1438

**Comment by djaiss** [comment]
Thanks for the information @JanOwiesniak and sorry about that. We'll fix this.

**Comment by djaiss** [comment]
This is fixed and live 😀
https://www.monicahq.com/api/contacts#update-a-contact-career
Thanks
