### ISSUE TITLE
A Way to Uninstall Monica from Local Server

### ISSUE THREAD

**Issue by at19** [monicahq/monica#3530]
I installed Monica on my local server as described in the docs.

Whenever I go to http://localhost, I get Monica.

I want to use http://localhost for a different purpose now. But I'm having trouble figuring out a way to remove Monica. Please help.

**Comment by asbiin** [comment]
Just remove every files related to Monica.

You will find some help on stackoverflow for example, but we cannot answer this kind of non-monica related support.

Thank you
