### ISSUE TITLE
Unable to Save Activity Details 

### ISSUE THREAD

**Issue by pqhf5kd** [monicahq/monica#3545]
When saving an Activity with additional details, the details disappear.
<img width="851" alt="Screenshot 2020-02-02 at 20 55 31" src="https://user-images.githubusercontent.com/20027419/73614350-619e5e80-45fe-11ea-80df-a68c82a079b1.png">
<img width="851" alt="image" src="https://user-images.githubusercontent.com/20027419/73614354-6c58f380-45fe-11ea-9296-3b6a100168f7.png">

This was working fine yesterday.

Hosted Monica.

**Comment by asbiin** [comment]
This has just been fixed with #3538
