### ISSUE TITLE
Create UUIDs for data types to be shared via API / Webhooks

### ISSUE THREAD

**Issue by phrohdoh** [monicahq/monica#355]
With UUIDs Monica and third-party applications can exchange information about the same user/contact/event/etc.

**Comment by djaiss** [comment]
Oh! I didn't think of this. That'd be a nice feature indeed. Any tips on which kind of UUIDs we'd need?

**Comment by Phrohdoh** [comment]
A [version 4 UUID](https://tools.ietf.org/html/rfc4122#section-4.4) should cover everything we care about.

[webpatser/laravel-uuid](https://github.com/webpatser/laravel-uuid) is MIT-licensed but I can't speak to the quality of this library. Perhaps Laravel has something like this built in?

I suggest using UUIDs for APIs and routing (you don't want record IDs exposed to end/malicious users) but would keep incrementing integers as primary keys.

**Comment by djaiss** [comment]
Laravel doesn't have something like this by default. I'll take a look at the library.

**Comment by djaiss** [comment]
We can start with User and Account objects. Do you know what is the convention for naming them in a table? `uuid`?

Hum. UUID would only work with a centralized system - not decentralized as Monica would be. The UUID of my contact on my instance might be completely different from the one in your instance. Should we bother having an UUID in that case?

**Comment by BranTurner** [comment]
I don't really understand why you would need UUIDs? It seems like it would add unnecessary complexity. You said you want to avoid exposing record IDs to the API/Routing, but I don't think this is a particular problem in an app such as this. What problems do you see arising from exposing primary keys?

**Comment by djaiss** [comment]
I get the concept of identifying a contact in an unique way across multiple systems - but let's say we have two Monica instances running, representing the same person - how would we agree on an UUID?

We need more details.

**Comment by Phrohdoh** [comment]
@djaiss UUIDs aren't intended to keep track of data duplicated across multiple instances of the same application. Whomever creates the entity is the authority over the UUID.

Assumptions for the following explanation:
* The official hosted MonicaHQ instance has a reminder with the ID of 6
* My API-using app stores data related to this reminder (but not the exact same data as MonicaHQ!)
* When reminder 6 is modified my app will get the new data (date, text, etc) somehow

Integral IDs are typically used for relationships inside of the same application (and moreso inside of the same database instance).

If my app, (example) CarWashSmsReminder, gets data such as this:

```json
{
  "entity": "reminder",
  "action": "delete",
  "id": 6,
}
```

I, or someone in the future (future me included), could understandably come along and wire up this:

```php
$recv = { "entity": "reminder", "action": "delete", "id": 6 };

MyReminder::find($recv->id)->delete(); // I don't know the correct syntax for this. You know what I'm getting at.
```

Which is certainly a bug that we can avoid using a type-system and semantics.

CarWashSmsReminder could have this data:

| ID | ForeignID | HaveSentSms  |
| -- | ---------- | -------------- |
| 5  | 6                | true                 |
| 6  | 7                | false                |
| 7  | 8                | true                 |

Given the above data and psuedo-php we would incorrectly delete CarWashSmsReminder's record with ID 6 but probably wouldn't catch this bug for quite some time.

By replacing `id` with `uuid` (or whatever the data member would be named) we:
* Have a different data type
* Express intent
* (should assume the schema's `ForeignID` is a UUID and possibly named something else)

```php
$recv = { "entity": "reminder", "action": "delete", "uuid": "cd227806-554b-445f-8cca-b27ada14b812" };

// The `uuid` column should have a unique constraint
$to_delete = MyReminder::where(['uuid', '=', $recv->uuid]);
if ($to_delete === null) {
  // CarWashSmsReminder has never seen this reminder before, that's ok
} else {
  $to_delete->delete();
}
```

---

This can be expressed in reverse too.

Say a user is able to manually create reminders in a CarWashSmsReminder mobile app.

When this happens the app would call MonicaHQ's reminder creation API method(s) and, if using UUIDs, be able to provide a value that MonicaHQ probably doesn't have a record for yet.

---

I probably could have explained this a lot better -- there are plenty of materials all over the internet about this.

I do think I need to reiterate that UUIDs do not, and will not ever, solve the case of data duplication they are unique IDs meant to be used with foreign systems that will likely never collide.

**Comment by Phrohdoh** [comment]
One option is to have applications send Monica data as necessary (say Google Keep sends Monica a new note about a user's contact Bob) then Monica responds with ACK and a UUID that Monica generated.

This way the monica instance is always tasked with creating UUIDs.

---

CarWashSmsReminder -> Monica: I made this reminder for user <UUID>'s contact <UUID> with <text>
Monica -> CarWashSmsReminder: Ok, I have created <UUID> for that reminder and will refer to that reminder by <the same UUID> in the future
