### ISSUE TITLE
Can't set CardDav on macOS

### ISSUE THREAD

**Issue by dosch** [monicahq/monica#3551]
**Describe the bug**
- I created a dummy persons in Monica. 
- I created dummy persons in my MacOS contacts.app
- I added the Carddav server to 'Internet Accounts' in MacOS with my credentials.
- There are no error messages and the account is added and appears in the contacts.app
- The dummy contacts on MonicaHQ are not synced to contacts.app
- The dummy contacts on contacts.app are not synced to MonicaHQ

**Screenshots**
![Screenshot 2020-02-03 at 11 30 04](https://user-images.githubusercontent.com/5372610/73645982-bc749c00-4678-11ea-95e6-e6d9f640fc11.png)
![Screenshot 2020-02-03 at 11 30 01](https://user-images.githubusercontent.com/5372610/73645983-bc749c00-4678-11ea-9dd7-3b6f6400e24c.png)
![Screenshot 2020-02-03 at 11 32 55](https://user-images.githubusercontent.com/5372610/73646087-f645a280-4678-11ea-8181-31daba5348e9.png)

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Comment by asbiin** [comment]
I don't know you application, but Carddav is working well. I'm not sure about your `Server path` info. You will find right url in: https://app.monicahq.com/settings/dav

**Comment by bbrendon** [comment]
@dosch  I don't think it works on Mac. It does work on iOS. I've never found instructions for Mac OS that said what to enter that actually works.

On iOS 
https://<server>/dav/principals/<emailaddr>/
emailaddr is the monica login.

**Comment by bbrendon** [comment]
I just spent about 30 minutes messing with this again and I got it working on MacOS Catalina. I have no idea how as I can't repeat it when creating another account.  It feels like the options available when creating the account on macos aren't the same when editing the account. Very frustrating.

**Comment by pqhf5kd** [comment]
> I just spent about 30 minutes messing with this again and I got it working on MacOS Catalina. I have no idea how as I can't repeat it when creating another account. It feels like the options available when creating the account on macos aren't the same when editing the account. Very frustrating.

There are different options when opening the 'Preferences' window and then switching to the 'Accounts' tab under Contacts instead of opening the 'Accounts' window.

**Comment by pqhf5kd** [comment]
@bbrendon Can you post your settings from the Preferences window? 
<img width="636" alt="image" src="https://user-images.githubusercontent.com/20027419/74225735-8f00a180-4cbb-11ea-9604-5ae21c64453e.png">

**Comment by bbrendon** [comment]
server settings tab:
server name: monica.mydomain.com
server path: <blank>
Port: 443
Use SSL : checked.

**Comment by pqhf5kd** [comment]
Thanks bbrendon, but I still can't get it to work unfortunately.

**Comment by asbiin** [comment]
@pqhf5kd what is your config? It's working well on some users, so might it be on your side?

**Comment by pqhf5kd** [comment]
The contacts app on macOS doesn’t provide any diagnostics (as far as I can see). Off the top my head, I can add the account with any combination of server address and path and I can choose the address book but no contacts appear.

**Comment by bbrendon** [comment]
Yes. It’s the right combo of tricks to get it working. The trick is unknown :)

**Comment by pqhf5kd** [comment]
Closed?

**Comment by asbiin** [comment]
@pqhf5kd Well, Carddav is working.
At minimum there is a problem of documentation for your specific configuration, but I don't see how we can provide help ...

**Comment by pqhf5kd** [comment]
Three (well 2.5 if you count @bbrendon random success) users are unable to get it to work. macOS Contacts isn't exactly an obscure app.

**Comment by pqhf5kd** [comment]
I've tried disabling 2FA, still no contacts appearing

**Comment by asbiin** [comment]
Library have been updated

**Comment by pqhf5kd** [comment]
That appears to have fixed the problem

**Comment by tborychowski** [comment]
Sorry, I'm still experiencing this issue. Is there a guide or any information on what the settings for macos should be?
It works straight away on iOS, but not on mac.
I enter details as follows:
login: user@email.tld
password: <monicahq generated API token>
server URL: https://crm.domain.tld/dav/addressbooks/user@email.tld/contacts

I also tried a number of different paths, like: 
- /
- /dav/
- /dav/principals/
- /dav/principals/user@email.tld
etc.

But nothing works...
