### ISSUE TITLE
Can't Save Activity Details

### ISSUE THREAD

**Issue by davidbhayes** [monicahq/monica#3552]
**Describe the bug**
When I go to a contact and log an activity, the "Activity Details" (regardless of what I enter, any other changes I make in the box) doesn't save.

**Screenshots**
<img width="1002" alt="Screen Shot 2020-02-03 at 10 43 14 AM" src="https://user-images.githubusercontent.com/2613891/73676673-06a64f00-4672-11ea-925e-8dcc9ad1e1da.png">
Pressed "Save". See this:
<img width="999" alt="Screen Shot 2020-02-03 at 10 43 23 AM" src="https://user-images.githubusercontent.com/2613891/73676704-11f97a80-4672-11ea-8fa8-e4ae0b97b4e5.png">
 
**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Additional context**
This seems to have accompanied me getting the feature (hurrah!) the lets me know edit those events. I'm using Firefox 72.0.2

**Comment by asbiin** [comment]
Thanks for the report. This has already been fixed in #3542 and will be delivered soon.
