### ISSUE TITLE
Unable to edit the date of a conversation.  The content can be edited, but not the date.   Self-hosted with the latest code from the master branch as of today.

### ISSUE THREAD

**Issue by daryljones** [monicahq/monica#3553]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
A clear and concise description of what the bug is. If your comment is `it doesn't work`, we won't know what to do with it.

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.
**Which version are you using:**
 - Hosting version on https://app.monicahq.com
 - Mobile version
 - A server you maintain yourself (if so, please indicate your current version of Monica)

**Additional context**

**Comment by djaiss** [comment]
#3560 should fix this issue.

**Comment by daryljones** [comment]
Fix confirmed.  Thank you!
