### ISSUE TITLE
Adding a Gift gives SQL error

### ISSUE THREAD

**Issue by benwallace88** [monicahq/monica#3557]
When adding a Gift Idea, Offered or Received in the app.monicahq.com page, the page shows a SQL error about the 'monica.gift_photo' table not existing.

> Whoops! Something went wrong.
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'monica.gift_photo' doesn't exist (SQL: select `photos`.*, `gift_photo`.`gift_id` as `pivot_gift_id`, `gift_photo`.`photo_id` as `pivot_photo_id`, `gift_photo`.`created_at` as `pivot_created_at`, `gift_photo`.`updated_at` as `pivot_updated_at` from `photos` inner join `gift_photo` on `photos`.`id` = `gift_photo`.`photo_id` where `gift_photo`.`gift_id` = 2510)

![Screen Shot 2020-02-05 at 11 25 20 AM](https://user-images.githubusercontent.com/13092287/73860878-3b4d0e80-480a-11ea-977e-1eee273495e8.png)

**Comment by igbanam** [comment]
![Screenshot 2020-02-06 at 00 29 01](https://user-images.githubusercontent.com/390059/73895571-f495fd80-4877-11ea-9b2d-22fad4926a87.png)

This is the error I got. I have my instance installed locally on my laptop.

**Comment by djaiss** [comment]
We have found the bug and have worked on a fix. It should be live and ready for a next release soon.
