### ISSUE TITLE
compact with undefined variable breaks on PHP 7.3 while editing contacts

### ISSUE THREAD

**Issue by 4khi1** [monicahq/monica#3596]
![image](https://user-images.githubusercontent.com/21128035/74719405-f7222b00-5259-11ea-9030-4fe687348bd1.png)

**Comment by 4khi1** [comment]
Duplicate of https://github.com/laravel/framework/issues/26936

**Comment by 4khi1** [comment]
Fixed by downgrading PHP version to 7.1

**Comment by 4khi1** [comment]
Documentation needs to be updated #Requirements  -  PHP Version

**Comment by asbiin** [comment]
Thank you for this feedback.

> Documentation needs to be updated #Requirements - PHP Version

Well, no, we support php 7.3.
If there is a problem with Laravel, it should be fixed in Laravel.

What page/action did you do to have this error?

**Comment by 4khi1** [comment]
![image](https://user-images.githubusercontent.com/21128035/74808670-5ee77d00-5311-11ea-8084-fd89bdc7b983.png)


After submit... it's giving the error

**Comment by asbiin** [comment]
I cannot reproduce this bug.
I'm sure you don't have the last version of Monica. Please upgrade first.
