### ISSUE TITLE
Don't restrict gender to male or female

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#36]

**Comment by djaiss** [comment]
Sorry @ocdtrekkie , trying to keep with the incredible amount of feedback I'm getting.

**Comment by ocdtrekkie** [comment]
Haha, I didn't even notice, you're the dev. :D

**Comment by TheActualWalko** [comment]
https://github.com/monicahq/monica/issues/25 Is not inherently related to gender restriction. I'd be inclined to keep this issue open so we can separately discuss person-adding UI and gender identity concerns.
