### ISSUE TITLE
Allow entering just month/day for birthdate, if year is not known

### ISSUE THREAD

**Issue by ghewgill** [monicahq/monica#361]
Often you will know a contact's birthdate, but not the exact year. Even not knowing the year, you can still schedule a reminder to wish them a happy birthday.

This would be much better than guessing a year, forgetting that you guessed, and getting it wrong so that you wish them a happy 40th a year early!

**Comment by underyx** [comment]
Seems like a duplicate of https://github.com/monicahq/monica/issues/361

**Comment by Nebucatnetzer** [comment]
I think you mean #75

**Comment by ghewgill** [comment]
Thanks, that makes more sense as a duplicate.

**Comment by underyx** [comment]
Right, sorry :D
