### ISSUE TITLE
Weird date display of activities on Journal

### ISSUE THREAD

**Issue by davidbhayes** [monicahq/monica#3612]
**Describe the bug**
I've put an activity on a contact, and the date seems to correctly be Thursday. But I go the "Journal" view, and the date is displaying as Wednesday. Don't have the foggiest idea what would be causing this, but it seems like it's happening to most activities right now. (Maybe because of the leap-month?)

**Screenshots**
<img width="877" alt="Screen Shot 2020-02-21 at 7 31 20 AM" src="https://user-images.githubusercontent.com/2613891/75043113-be15d080-547c-11ea-9a01-fd7eab2ef8db.png">
How the activity is showing on the "Journal" view
<img width="867" alt="Screen Shot 2020-02-21 at 7 31 43 AM" src="https://user-images.githubusercontent.com/2613891/75043131-c837cf00-547c-11ea-8a8a-ade247ff1c6e.png">
The date the event is marked as occurring.

**Which version are you using:**
 - Hosting version on https://app.monicahq.com

**Additional context**
It's a little extra puzzling to me that ah *older* activity that I'd put in two days ago--"Dinner @ Little [7:30-9:30pm]"--is correctly showing as Tuesday. But all the other ones I'd entered this morning and a few days ago aren't showing correctly.

**Comment by davidbhayes** [comment]
<img width="223" alt="Screen Shot 2020-02-24 at 1 04 34 PM" src="https://user-images.githubusercontent.com/2613891/75186956-39d67e00-5706-11ea-9bee-7ef6256d7b36.png">
Just to add some extra color/context, best I can tell the issue that whatever is making the "Journal Entries" view display say "Sat" for Feb 23 is at issue. The event is recorded correctly as happening on Sunday Feb 23, but this view (specifically) seems to have a bug where it's getting days wrong for most of the most-recent week (for me).

**Comment by davidbhayes** [comment]
Oh, and other thing to clarify. I was wrong in saying earlier that

> It's a little extra puzzling to me that ah older activity that I'd put in two days ago--"Dinner @ Little [7:30-9:30pm]"--is correctly showing as Tuesday.

I'd put the date on that event in mistakenly as Wednesday when it happened Tuesday. So the (wrong) Wednesday was showing as Tuesday (which was just coincidentally correct). Best I can tell the days for all of my events in February and even into January are incorrect right now for me on "automatically added Journal entries" view. Maybe the day-of-the-week displayed there is a simple iterator that's off by one?

**Comment by asbiin** [comment]
Can you give us your current timezone please?

**Comment by davidbhayes** [comment]
@asbiin Sure thing! It's set as "America/Denver" I'm fairly sure:

<img width="1142" alt="Screen Shot 2020-02-25 at 2 48 34 PM" src="https://user-images.githubusercontent.com/2613891/75290633-f6e7d980-57dd-11ea-8ebf-9e393026294f.png">

**Comment by asbiin** [comment]
I think this has been fixed by #3672
