### ISSUE TITLE
Add a field for "nickname"

### ISSUE THREAD

**Issue by ghewgill** [monicahq/monica#362]
Sometimes people are best known by their nicknames. While it's easy to use this as "First name" if the person's real name is not known, there's nowhere to put it if you know real name and nickname. The idea here is to be able to search for a person by nickname.

**Comment by Nebucatnetzer** [comment]
This would be a nice feature I would use as well.

**Comment by djaiss** [comment]
I understand the need for the feature. However, if a nickname is defined, where/how would we display it? For John Doe with the nickname `Bono`, when mentioning the name, what should we display? John Bono Doe? Bono? John Doe (Bono)?

**Comment by BranTurner** [comment]
@djaiss I think you generally show the nickname, unless it's on the contact page where it would be John Doe (Bono). This is how both Android and iPhone contacts seem to do things.

**Comment by chrisma** [comment]
An alternative display could be `John "Bono" Doe`.
Maybe a custom format string couild be supplied in the config (with a sane default)?

**Comment by tylerrobb** [comment]
I just started using Monica and a 'nickname' field would be very helpful!

Upon adding the very first nickname, the UI could prompt you on how you would like to see nicknames rendered in your contact list. Following both @BranTurner and @chrisma's formats, it could show you an example of John Doe (Bono) and John "Bono" Doe with the option to pick your preference.

**Comment by colinfrei** [comment]
I just started playing around with Monica as well, and this was the first thing I noticed - I call my friends by nicknames, but would love to save that along with the firstname.

@tylerrobb's suggestion regarding display seems like a good choice.

**Comment by djaiss** [comment]
Alright let's do this.

**Comment by fiosmiles** [comment]
Yes please!

**Comment by djaiss** [comment]
It's coming in the next release!
