### ISSUE TITLE
All profile avatars (images) are lost after updating to v2.16.0

### ISSUE THREAD

**Issue by rasulkireev** [monicahq/monica#3626]
**The bug**
Once I updated the Monica version to 2.16.0 all the profile images got lost.

**Version**
 - Self-hosting on a DigitalOcean droplet

**Questions** 
Would people here have some suggestions as to why that could have happened?
What are some of the reasons this could have happened?
How can I debug?

I wasn't able to find similar issues filed here on GitHub. 
Thanks for taking the time to read this.

**Comment by asbiin** [comment]
I'm sorry for that.
I hope you had a chance to restore them from some backup.

I didn't saw any other issue about this.
Are you using docker image?

**Comment by rasulkireev** [comment]
I am not sure what the issue was. Since I have submitted this Issue, I moved my Monica instance to Heroku and have set up S3 to store all the images.

Thank you for your response. Hopefully, it was something I did, and no one else ran into this issue.
