### ISSUE TITLE
Attempting to edit an activity causes error

### ISSUE THREAD

**Issue by lhenze** [monicahq/monica#3640]
On a person page, under activities, I click "edit" under one of the activities and make an edit to the title field ("What did you do...") and click save.  I see an error and the change is not saved. 

![Screen Shot 2020-03-01 at 9 47 29 AM](https://user-images.githubusercontent.com/86330/75627946-ab00b000-5ba2-11ea-9886-29a2254c8c84.png)

This on on the hosted version on https://app.monicahq.com, using Mac Firefox 73.0.1 desktop.

**Comment by lhenze** [comment]
This is also the case when I try to edit the activity by adding a participant.

**Comment by asbiin** [comment]
See #3816
Running setup:production or monica:update now creates required the encryption keys and personal access client.

**Comment by lhenze** [comment]
This problem has returned. I can't edit the title of the event or add participants.  Haven't tried other modifications.

 
The error is now:

Whoops! Something went wrong.

The resource has not been found
