### ISSUE TITLE
Add a function to "promote" a kid or significant other to their own contact

### ISSUE THREAD

**Issue by ghewgill** [monicahq/monica#367]
Sometimes it is appropriate to create a new contact based on what was previously a "kid" record. For example, one may have an uncle whose kids are entering adulthood and should be treated as their own independent contacts. Of course this is possible to do manually, but having a function to copy the details would be handy.

**Comment by Phrohdoh** [comment]
Once everyone is a proper contact with relationship graphs this would be rendered unnecessary.

In-between that time and now, 👍

**Comment by djaiss** [comment]
This was done and is now in production!
