### ISSUE TITLE
Tag is not being created.

### ISSUE THREAD

**Issue by cedewey** [monicahq/monica#3686]
When I try and create a new tag on a contact, it is not created. I'm using the hosted version.

![monica-tag-bug](https://user-images.githubusercontent.com/1270531/76642205-6a952080-6518-11ea-8d36-7a03a536611d.gif)

**Comment by jeremies** [comment]
After entering the tag name you have to press enter to create a new tag for that person, then click **Save and close**

**Comment by asbiin** [comment]
Duplicated of #2025
