### ISSUE TITLE
Birthday reminder not updated when changing name

### ISSUE THREAD

**Issue by GenaBitu** [monicahq/monica#371]
When you change the name of a contact, the birthday reminder is not updated, instead a second one is added resulting in two duplicate reminders.

**Comment by djaiss** [comment]
@GenaBitu I just checked and this is not the behaviour for me.

Are you using `.com` or do you self host? If so, are you on the latest version?

**Comment by GenaBitu** [comment]
I am using the `.com`

**Comment by GenaBitu** [comment]
I don't see this issue happening right now, weird. Maybe was fixed along the way. Will report if happens again

**Comment by djaiss** [comment]
Thanks!
