### ISSUE TITLE
Allow to display name by Familyname Firstname

### ISSUE THREAD

**Issue by revi** [monicahq/monica#372]
Hi,

Korean name displays name by $familyname$firstname (with no space) ([Reference](https://en.wikipedia.org/wiki/Korean_name)), so it's awkward to see Firstname Familyname in the entry. While I can sort it via "Sort by First name A>Z", it doesn't make the Family name come first. So, can it be configured to behave so?

**Comment by djaiss** [comment]
In this case, I think the best way is to have a settings for this use case.

**Comment by djaiss** [comment]
@revi is it alright if there is a space between Family name and Firstname? That way we can accommodate both languages like Korean and western languages at the same time?

**Comment by revi** [comment]
That's not ideal but yes, I think it can be acceptable.

**Comment by djaiss** [comment]
The feature is now in production. Hope it helps!
