### ISSUE TITLE
Database migration from 2.16 to 2.17 fails

### ISSUE THREAD

**Issue by justsomebody42** [monicahq/monica#3730]
**Describe the bug**
I updated from 2.16 to 2.17 following the documentation. When I migrate the database I get the following error:
![2020-03-23 14_30_02-Window](https://user-images.githubusercontent.com/2913127/77321923-350be680-6d13-11ea-94c2-78ee349086b2.png)
The table "gift_photo" has been created and the WebUI seems to be working. I can add photos to gifts and remove them.
Unfortunately syncing from my mobile does not work any more:
`[2020-03-23 13:35:29] local.DEBUG: App\Http\Controllers\DAV\Backend\CardDAV\CardDAVBackend prepareCard: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'monica.contact_field_labels' doesn't exist in /var/www/monica/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61`
It seems that there are migrations missing or not being executed due to the one above failing.

**Comment by asbiin** [comment]
It seems you have a problem with your instance.
Table `contact_field_labels` was added years ago, and `gift_photo` was just added, so it cannot already exist.

**Comment by justsomebody42** [comment]
Hi asbiin,
Thanks for your reply.
I've been using monica since 2018 and never had a problem with the updates.
I have only been updating releases, so I assume that it is not related to intermediate updates or incomplete migrations.
Do you have any suggestion on how I might be able to fix this?
Could you provide an SQL statement to create the table `contact_field_labels`?
I'm surprised that I fared well so long without it :)

I have quite a few contacts in there, lots of activities and I would be quite sad, if I would need to setup a new instance :/

**Comment by justsomebody42** [comment]
Hi,
I tried to export my data, do a fresh installation of 2.16, import my data again and update with no luck so far.

After doing a fresh installation of 2.16, I don't see the table `contact_field_labels` in the database.
`contact_fields` and `contact_field_types` exist.

I currently reverted back to 2.16.0, which is working perfectly fine.

**Comment by asbiin** [comment]
I'm sorry, I made a mistake, `contact_field_labels` has just been added in fact. The error on the migration explains the absence of the table.
So you still need to fix the error on the gift_photo migration, and it should work.

**Comment by asbiin** [comment]
@justsomebody42 I can't see why this should be a bug, it's more a local problem on your instance.

**Comment by justsomebody42** [comment]
Hi @asbiin, after multiple tries back and forth, I now managed to update to 2.17.
I double checked a clean update from 2.16 to 2.17 and of course it went through without an issue.
Sorry for the troubles!
Thanks for all the efforts going into this, I really love monica :D
