### ISSUE TITLE
Cannot view the settings.storage.index page on 2.17 docker image

### ISSUE THREAD

**Issue by nwalke** [monicahq/monica#3743]
**Describe the bug**
I upgraded from 2.16 to 2.17 and can no longer view the storage page under my user's settings.  I've run through all the migration steps, cleared cache, etc.  

**Screenshots**
I'm just getting the "Whoops! Something went wrong" screen.

**Which version are you using:**
 - A server you maintain yourself: 2.17 (docker image)

**Additional context**
Log output:
```
[2020-03-25 19:44:12] production.ERROR: View [settings.storage.index] not found. {"userId":4,"exception":"[object] (InvalidArgumentException(code: 0): View [settings.storage.index] not found. at /var/www/monica/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137)
[stacktrace]
#0 /var/www/monica/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('settings.storag...', Array)
#1 /var/www/monica/vendor/laravel/framework/src/Illuminate/View/Factory.php(131): Illuminate\\View\\FileViewFinder->find('settings.storag...')
#2 /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(968): Illuminate\\View\\Factory->make('settings.storag...', Array, Array)
#3 /var/www/monica/app/Http/Controllers/Settings/StorageController.php(38): view('settings.storag...')
#4 [internal function]: App\\Http\\Controllers\\Settings\\StorageController->index()
```

I can include the entire stack trace if need be, but that seems to be the relevant bit.

**Comment by nwalke** [comment]
I wonder if the 2.17 docker image is broken?  Here's what I see:
```
$ dc exec monica ls -1 resources/views/settings/
_sidebar.blade.php
api
auditlog
dav
export.blade.php
imports
index.blade.php
personalization
security
subscriptions
tags.blade.php
users
```

Which does not match this: https://github.com/monicahq/monica/tree/v2.17.0/resources/views/settings

**Comment by nwalke** [comment]
After more digging, relaunching of the container, and playing with the image...   

The `resources/views/settings/storage` folder exists in the image under `/usr/src/monica` but for some reason doesn't seem to be getting copied to `/var/www/monica` as part of the `Syncing sources...` section.

**Comment by nwalke** [comment]
#3487 introduced the `upgrade.exclude` list.  It must be excluding any folders named "storage".

**Comment by asbiin** [comment]
@nwalke Thank you for the feedback! I'll fix it ASAP
