### ISSUE TITLE
Admin credentials when setting up in production

### ISSUE THREAD

**Issue by tylerdiaz** [monicahq/monica#3744]
My setup: Production configured Monica 2.6 inside Docker

When running the installation configured as a production environment, I couldn't find the default admin credentials in the documentation. 

I decided to run the app in test mode, found the output included test credentials, and tried those in production mode which seems to have worked.

Is this the recommended way to set up the default user for production?

**Comment by asbiin** [comment]
As mention on the documentation, you may use `setup:production` on production application.
You can run `php artisan setup:production -v`, then go to the register page to create the first account.
Or you can run `php artisan setup:production --email=x@x.com --password=xxxx` to set the first account directly.

**Comment by tylerdiaz** [comment]
@asbiin I didn't see a registration page when starting up on a production config. Should that command `php artisan setup:production --email=x@x.com --password=xxxx` be included as part of the install docs? Currently it just shows that first command `php artisan setup:production -v` (from https://github.com/monicahq/monica/blob/97fcae70039e2de6bda35b2858271880112b10ca/docs/installation/docker.md) which leaves the installation without a user and no direction for how to bootstrap one.

**Comment by mdeuerlein** [comment]
@tylerdiaz see: https://github.com/monicahq/monica/issues/3762#issuecomment-605700450
