### ISSUE TITLE
Error on update user Settings Account::hasLimitations()

### ISSUE THREAD

**Issue by felipe-balloni** [monicahq/monica#3748]
When save user setting I'm getting the error about following error: Call to undefined method App\Models\Account\Account::hasLimitations()

I already checked and realized that function hasLimitations() has been moved to Helper "AccountHelper"

I made one fork and correct into my deploy. It's in line 118 of SettingsController.

I hope that would been usefull.

Regard. Nice project, I loved it.

**Comment by Nerothos** [comment]
Got the same error trying to update /settings after installation.

**Comment by asbiin** [comment]
This is fixed by #3792
