### ISSUE TITLE
Add Japanese language

### ISSUE THREAD

**Issue by antron** [monicahq/monica#3750]
Please open Japanese Language in crowdin.
I help to translate.
https://crowdin.com/project/monicahq

**Comment by asbiin** [comment]
@antron Hi, and thank you for your contribution!
Japanese is open on crowdin project.

**Comment by antron** [comment]
Thank You.

**Comment by asbiin** [comment]
You can start translating at https://crowdin.com/project/monicahq/ja#

**Comment by antron** [comment]
I am grateful for your support..(antron=hakaiya)

**Comment by asbiin** [comment]
@antron Hi! would you like to translate Monica for Japanese language? Thank you!
