### ISSUE TITLE
Default max upload size 

### ISSUE THREAD

**Issue by noharm1010** [monicahq/monica#3760]
Hi,

I'm running Monica 2.17.0 and and want to adjust default max upload size of files.

Now I have 
# Maximum allowed size for uploaded files, in kilobytes.
# Make sure this is an integer, without commas or spaces.
DEFAULT_MAX_UPLOAD_SIZE=10240      

But I get an error when uploading a file of 2MB: There was an error uploading the document. Please try again below.

Any suggestions?

**Comment by asbiin** [comment]
This is the limit for the validation of size inside monica.
You'll have to check the limit size of you web server/php too. It depends if you use apache/nginx, and/or if you use fpm.

**Comment by noharm1010** [comment]
Thanks, I edited /etc/php/7.3/fpm/php.ini and used a bigger value in upload_max_filesize

Working perfect now.
