### ISSUE TITLE
Images / Pictures / Photos added but don’t show

### ISSUE THREAD

**Issue by Cambera** [monicahq/monica#3777]
Installation: Heroku

Image uploading process Ok - 

It says the photo is there but don’t show.
Dosen't show Thumbnails, Image, Photo, Avatar.

Tried different file formats: jpg, png, bmp, etc.
Tried different web browsers: safari, firefox, chrome, etc. 

<img width="871" alt="Captura de Tela 2020-03-31 às 13 25 16" src="https://user-images.githubusercontent.com/491091/78017270-afacb580-7354-11ea-851c-b66c7ad165fb.png">

**Comment by thanhdatbkk** [comment]
Have you fixed that error yet? I also had that problem

**Comment by asbiin** [comment]
Do you have more context? What is you storage destination, are the files there on the storage folder? ...

**Comment by Cambera** [comment]
@asbiin and @thanhdatbkk 
> Do you have more context? What is you storage destination, are the files there on the storage folder? ...

Hello, thank you for the feedback!
Context: I’ve updated to the latest version 2.17.0, but still the same problem.
1. It upload the image and show success message but doesn't show the uploaded file.
2. The storage destination is the default on heroku server.
3. When I inspect the element (image uploaded) it shows the url: 
https://prm.herokuapp.com/storage/photos/UZ93Zgytuq1zkSk5ESbfhmXbvmzItgiXwInQikVi.jpeg
but when I try to open, received 404 Not Found.
4. I’ve cloned the heroku git repo, for my install of monica, but the folder storage is empty!
<img width="474" alt="Screen_Shot2020-04-12 at 08 35 01" src="https://user-images.githubusercontent.com/491091/79061434-eeb60180-7c98-11ea-8d18-91e018a1552f.png">

Thank you for the help!

**Comment by asbiin** [comment]
Oh it's heroku !
See https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md#limitations

> No upload of photos for your contacts. Heroku doesn't support storage.

Actually, this is not accurate: you'll have to define a specific storage (AWS S3 for instance), and it will work.
