### ISSUE TITLE
Missing text in success message after adding new note

### ISSUE THREAD

**Issue by rickpastoor** [monicahq/monica#379]
* Add a new note to a person
* You'll see this message:

<img width="273" alt="schermafbeelding 2017-06-23 om 09 12 31" src="https://user-images.githubusercontent.com/149958/27470462-466500c4-57f4-11e7-8124-40dea5e03fe5.png">

**Comment by ghewgill** [comment]
Duplicate of #338

**Comment by rickpastoor** [comment]
🎉
