### ISSUE TITLE
Activities not showing after update

### ISSUE THREAD

**Issue by mbcollins2** [monicahq/monica#3790]
**Describe the bug**
Recently upgraded personal server from v2.16.0 to v2.17.0, and noticed that some activity entries were missing.

The update process was seamless overall and appears to be successful otherwise.

**Screenshots**
Screenshots below are for the same contact, before and after the upgrade. Version can be ~~see~~ seen at the bottom of each screenshot. No changes were made between these updates. 

_v.2.16.0 before update:_

![image](https://user-images.githubusercontent.com/11760430/78374149-7e70f700-7599-11ea-926f-c68e93594271.png)

<br>

_v.2.17.0 after update:_
![image](https://user-images.githubusercontent.com/11760430/78374274-a2ccd380-7599-11ea-8005-fe6370f424ba.png)

**Which version are you using:**
 - A server I maintain myself, using v2.16.0 and migrating to v2.17.0

**Additional context**
This appears to be rather random. Some activities are still present. One that is missing was one of my last entries before updating. Another that is missing was one of my earliest entries overall.

**Comment by mbcollins2** [comment]
Additionally, it appears that the Activities still exist (i.e. the entries are still in the mysql db, they were not deleted). They just do not show on the Contact's page anymore.

**Comment by nosbig** [comment]
I saw the exact same symptoms with the same circumstances and found a workaround in #3780 .  If you try to create a new activity, see if you get an error about a missing oauth key file in the storage/ directory.  If so, then we have the exact same issue, and you can use my workaround.

This might be an addition to include in the upgrade notes or the artisan scripts.  If I have time, I might try to clone this repo and add my steps to the appropriate script(s).  It's a single command.

**Comment by mbcollins2** [comment]
Thanks @nosbig, that was my issue. I'll also note that I also had to reboot my entire server after following the steps defined in #3780.
