### ISSUE TITLE
2.17 Update in Heroku

### ISSUE THREAD

**Issue by biomcanic** [monicahq/monica#3801]
Hello, I have reployed my Heroku instance with the latest version of master branch. When I want to run the command "php artisan migrate" in Heroku console, it throws the error "Item could not be created: Cannot run more than 1 Free size dynos.".

Please, could you help me with it?
Thank you very much in advance.

**Comment by asbiin** [comment]
Hello. First of all, you don't have to run "php artisan migrate", it's already done on the deployment phase (see the Release log).
I don't see the error when I run the command, if you have more context it could be useful. Where did you run the console, how did you do it?

**Comment by biomcanic** [comment]
Hi! Thanks for the info, I won't run the command.

Kind regards.
________________________________
De: Alexis Saettler <notifications@github.com>
Enviado: miércoles, 8 de abril de 2020 8:31
Para: monicahq/monica <monica@noreply.github.com>
Cc: Mike Dawson Kovalsky <biomcanic@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [monicahq/monica] 2.17 Update in Heroku (#3801)


Hello. First of all, you don't have to run "php artisan migrate", it's already done on the deployment phase (see the Release log).
I don't see the error when I run the command, if you have more context it could be useful. Where did you run the console, how did you do it?
