### ISSUE TITLE
Replace Darksky weather lookup

### ISSUE THREAD

**Issue by lazzurs** [monicahq/monica#3810]
Darksky has been sold to Apple and is no longer accepting signups for API keys. It is likely given this they will shutdown the API access in the future and so should be replaced.

**Comment by bbrendon** [comment]
The API _is_ scheduled to be shutdown Jan 31 2021.

**Comment by callahad** [comment]
From a [Hacker News subthread](https://news.ycombinator.com/item?id=22742096) back when Dark Sky was acquired, it seems like a leading free weather API might be Norway's public one at https://api.met.no/

**Comment by userbradley** [comment]
Hi Guys, have we made and progress on this or know of any work around? I know @callahad was speaking about another API. Is there any way to swap out the endpoints?

**Comment by abinadi** [comment]
Weather API's with free pricing tiers:

* [weatherapi](https://www.weatherapi.com/pricing.aspx)
* [openweather app](https://openweathermap.org/price)
* [weatherbit](https://www.weatherbit.io/pricing)
* [AccuWeather](https://developer.accuweather.com/packages)

Should consider using an adapter pattern so the weather api of your choice can be swapped in/out according to what you need/want.

**Comment by ocdtrekkie** [comment]
OpenWeatherMap has a delightfully simple API to use, with fantastic documentation.
