### ISSUE TITLE
Cannot register new user when using Postgres

### ISSUE THREAD

**Issue by David-LeBlanc-git** [monicahq/monica#384]
I tried to set up an instance of Monica with Postgres today and unfortunately ran into the following error any time I try to register a new user (including myself as the first user).

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "account_id" violates not-null constraint

I am able to register a user with a MySQL (MariaDB) database without issue.

**Comment by githubber** [comment]
Hi,
Could you tell me how to register a user, the main admin user, with MySQL please? I tried changing the admin@admin.com user but now it isn't recognized. Changing the password without a hash (?) messed it up somehow.

**Comment by ferenzo** [comment]
With a fresh setup (v0.2.1) and PostgreSQL 9.6.3 as the database I get the following errors when I try to populate the contact database either manually or via FakeContentTableSeeder:

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "default_avatar_color" violates not-null constraint

**Comment by martimarkov** [comment]
I have made fixes around what the column definitions are in order to get the monicahq to work but they are not really backwards compatible. 

I’ll try to push them to the repository.

**Comment by simhnna** [comment]
I got a fix for that, that should work for all database types. I'm not sure why it's postgresql specific, but then again, I'm not that familiar with the used php stack..

I'll push it tomorrow...

**Comment by djaiss** [comment]
I've merged the proposed fix that will end up in the 1.4.0 release later that will be released in the next days. Hopefully it will solve your problems with Postgre!

**Comment by simhnna** [comment]
@djaiss there is a lot more to fix for PostgreSQL compatibility, starting with the migrations (two are not valid PostgreSQL Migrations)...

I have a merge request that enables ci for PostgreSQL. I assume there is something in the test setup that is MySQL only, but since I'm not that familiar with laravel and phone in general, I guess someone else with more knowledge should check that.
