### ISSUE TITLE
How to run cron container with Monica 2.17?

### ISSUE THREAD

**Issue by HansAdema** [monicahq/monica#3859]
I run Monica in Docker with Kubernetes, which works really well!

However, when upgrading from Monica 2.16 to 2.17, I ran into an issue with the cron jobs.

Previously, I had a Kubernetes Deployment running the web application with Apache, and a Kubernetes CronJob which started the same container every hour with the command `php /var/ww/monica/artisan schedule:run`.

With Monica 2.17, this cron container just returns an error like `Could not open input file`. I did some digging myself, and I think this issue is caused by the following commit:

https://github.com/monicahq/monica/commit/9f121817351695d1c66cdd4b7cbbd702d3770d93

Because of rsync setup in entrypoint.sh, running the container with an arbitrary command does not copy the Monica files to the var directory, which is why the artisan file cannot be found.

The entrypoint.sh file still says "use another container" as a good way to run cron jobs, but I can't see a way to do that.

So how to run a cron container with Monica 2.17?

**Comment by asbiin** [comment]
Hi @HansAdema 
Did you try the example configuration here: https://github.com/monicahq/monica/blob/master/scripts/docker/.examples/readme.md ?

**Comment by HansAdema** [comment]
I haven't tried those examples, no. But as I understand it, the recommended setup is to run a cron process through Supervisor? I would prefer to avoid running a process supervisor unless unavoidable.

And upon testing it, it seems like that example may suffer from the same issue:

```
Attaching to apache_app_1
app_1  | 2020-04-20 15:15:18,151 INFO Set uid to user 0 succeeded
app_1  | 2020-04-20 15:15:18,154 INFO supervisord started with pid 1
app_1  | 2020-04-20 15:15:19,158 INFO spawned: 'cron' with pid 8
app_1  | 2020-04-20 15:15:19,161 INFO spawned: 'httpd_00' with pid 9
app_1  | 2020-04-20 15:15:19,164 INFO spawned: 'queue_00' with pid 10
app_1  | Could not open input file: /var/www/monica/artisan
app_1  | 2020-04-20 15:15:19,195 INFO exited: queue_00 (exit status 1; not expected)
app_1  | AH00112: Warning: DocumentRoot [/var/www/monica/public] does not exist
app_1  | 2020-04-20 15:15:19,248 INFO gave up: queue_00 entered FATAL state, too many start retries too quickly
app_1  | 2020-04-20 15:15:20,249 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1  | 2020-04-20 15:15:20,249 INFO success: httpd_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

I got this while running the example from here: https://github.com/monicahq/monica/tree/master/scripts/docker/.examples/supervisor/apache

I'm quite sure the issue is the same: running the `supervisor` command also bypasses the file copy in the entrypoint.

**Comment by asbiin** [comment]
Oh yes I see the problem with supervisor !
I'll fix it

In the meantime, here is a solution that is working: https://github.com/monicahq/monica/blob/master/scripts/docker/.examples/nginx-proxy/docker-compose.yml
Using another container and mount '/var/www/monica' on this container and on the main (app) container: the app container will copy rsync the file in the mounted volume.

**Comment by asbiin** [comment]
Hi. The next version of the docker image will change a little bit. From now the files of monica are directly in /var/www/monica directory, so this will solve the issue with supervisor.
I recommend using another container, running the "cron.sh" command - no need to mount /var/www/monica anymore.
