### ISSUE TITLE
iOS app in Germany

### ISSUE THREAD

**Issue by B3RR10** [monicahq/monica#3866]
Hello, 

Thanks for such an amazing work. I find this app very usefull. 

I‘m trying to find the iOS app on the App store, but it appears that it is not available in Germany. Is there any way to change that?

**Comment by bbrendon** [comment]
From what I understand there _was_ and app and it was removed.

**Comment by asbiin** [comment]
Indeed, the previous app is no longer available, but keep in touch, we are working on a new app !

**Comment by B3RR10** [comment]
Alright. Thanks for the answer. Should I close this issue?
