### ISSUE TITLE
Reminders need to respect time zone

### ISSUE THREAD

**Issue by ghewgill** [monicahq/monica#389]
I'm in UTC+12 (NZST) and had a reminder set for the 24th. I did not receive the email until 2am on the next day. 

A better time might be 6am on the day, local time.

**Comment by ziming** [comment]
Should this be our timezone or the contact tine zone?

**Comment by revi** [comment]
>Should this be our timezone or the contact tine zone?

The Timezone in the Settings should be sufficient, imo. (TBH I have no idea what "our" means in "our timezone".)

**Comment by ghewgill** [comment]
That's a good question. A reminder shown to a person in PST about a friend's birthday in NZST, would almost certainly be a day late. Are birthday reminders special? Should they be shown in the time zone of the contact? How do we even know what that is? Manual entry? Guessing by country? So many questions.

**Comment by djaiss** [comment]
We don't have the concept of contact timezone (at the moment).

We could determine it by looking at the country, if defined, otherwise default to user's timezone.

**Comment by djaiss** [comment]
Hopefully this is now fixed. I'll keep a close eye to make sure the fix is actually working.

**Comment by ghewgill** [comment]
I received a birthday reminder at 00:00 local time on the day, so this is fixed for now.

**Comment by djaiss** [comment]
Next would be the ability to set a time, but this is another feature :-D
