### ISSUE TITLE
command to test emails

### ISSUE THREAD

**Issue by farconada** [monicahq/monica#3890]
as a sysadmin I need a command to test that monica can send emails. please add an artisan command to send a test email y debug possible problems

**Comment by bbrendon** [comment]
Funny you mention that because I'm trying to figure out why emails stopped working.
```
/etc/periodic # /usr/bin/php /var/www/monica/artisan schedule:run -vvv
No scheduled commands are ready to run.
/etc/periodic #

```

**Comment by mechanarchy** [comment]
I've made a pull request that you can use for this - it hasn't yet been merged though. PR #3212
