### ISSUE TITLE
create account with facebook login broken

### ISSUE THREAD

**Issue by pyeguy** [monicahq/monica#39]
getting a `The redirect_uri URL must be absolute` error when trying to use Facebook openauth on initial signup page

**Comment by djaiss** [comment]
This has been deactivated for now.

**Comment by degan6** [comment]
@djaiss 
Is this being worked on? I can fix this and I would like to add login with Google too.

**Comment by djaiss** [comment]
@degan6 If you feel like it, that'd be great.

However I have the feeling, for privacy sake, that we should make it configurable (via `.env` and `config('monica.XX')`) and deactivated by default. I think it should be a conscious choice from the instance owner to activate this functionality.

**Comment by degan6** [comment]
To be clear you are referring to creating a setting in .env that toggles signup with social profiles?
Something like (in .env) `APP_ALLOW_FACEBOOK_SIGNUP` and similar for Google?

No problem. Sounds like a good precaution.

**Comment by asbiin** [comment]
there is no more facebook login
