### ISSUE TITLE
I cant send reminders with Amazon SES, help wanted

### ISSUE THREAD

**Issue by farconada** [monicahq/monica#3934]
I cant send remineder with amazon SES so this converts monica in something useless for me, please help

I'm able to send emails with https://github.com/monicahq/monica/pull/3212
but everytime monica tries to send a new email I have this error

monica 2.17.0

`
Expected response code 250 but got code "451", with message "451 4.4.2 Timeout waiting for data from client.
  "
`

`
[2020-04-30 12:11:55] local.ERROR: Expected response code 250 but got code "451", with message "451 4.4.2 Timeout waiting for data from client.
" {"exception":"[object] (Swift_TransportException(code: 451): Expected response code 250 but got code \"451\", with message \"451 4.4.2 Timeout waiting for data from client.
\" at /usr/share/nginx/monica/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457)
[stacktrace]
#0 /usr/share/nginx/monica/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('451 4.4.2 Timeo...', Array)
\1 /usr/share/nginx/monica/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('\
\\
', Array, Array, false, NULL)
\2 /usr/share/nginx/monica/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(404): Swift_Transport_EsmtpTransport->executeCommand('\
\\
', Array)
#3 /usr/share/nginx/monica/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(500): Swift_Transport_AbstractSmtpTransport->streamMessage(Object(Swift_Message))
#4 /usr/share/nginx/monica/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'fernando.arcona...', Array, Array)
#5 /usr/share/nginx/monica/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'fernando.arcona...', Array, Array)
#6 /usr/share/nginx/monica/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(486): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(261): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(65): Illuminate\\Mail\\Mailer->send(Object(Illuminate\\Support\\HtmlString), Array, Object(Closure))
#10 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(146): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(App\\Models\\User\\User), Object(App\\Notifications\\UserReminded))
#11 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(105): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(App\\Models\\User\\User), 'a7494247-d94d-4...', Object(App\\Notifications\\UserReminded), 'mail')
#12 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(29): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#13 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(107): Illuminate\\Notifications\\NotificationSender->withLocale('es', Object(Closure))
#14 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(54): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\UserReminded), Array)
#15 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(74): Illuminate\\Notifications\\ChannelManager->sendNow(Object(App\\Models\\User\\User), Object(App\\Notifications\\UserReminded), Array)
#16 [internal function]: Illuminate\\Notifications\\SendQueuedNotifications->handle(Object(Illuminate\\Notifications\\ChannelManager))
#17 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#18 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#20 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#21 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#22 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#23 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#24 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#25 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#26 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Notifications\\SendQueuedNotifications), false)
#27 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#28 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#29 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(Illuminate\\Notifications\\SendQueuedNotifications))
#31 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#32 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(45): Illuminate\\Queue\\Jobs\\Job->fire()
#33 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(182): Illuminate\\Queue\\SyncQueue->push(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#34 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(158): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(Illuminate\\Notifications\\SendQueuedNotifications))
#35 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#36 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(201): Illuminate\\Bus\\Dispatcher->dispatch(Object(Illuminate\\Notifications\\SendQueuedNotifications))
#37 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(76): Illuminate\\Notifications\\NotificationSender->queueNotification(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\UserReminded))
#38 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\UserReminded))
#39 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Notifications\\ChannelManager->send(Object(App\\Models\\User\\User), Object(App\\Notifications\\UserReminded))
#40 /usr/share/nginx/monica/app/Jobs/Reminder/NotifyUserAboutReminder.php(51): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#41 [internal function]: App\\Jobs\\Reminder\\NotifyUserAboutReminder->handle()
#42 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#43 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#44 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#45 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#46 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#47 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#48 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#49 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#50 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#51 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder), false)
#52 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#53 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#54 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#56 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#57 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(45): Illuminate\\Queue\\Jobs\\Job->fire()
#58 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(182): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#59 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(158): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#60 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#61 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(112): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\Reminder\\NotifyUserAboutReminder))
#62 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(16): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#63 /usr/share/nginx/monica/app/Console/Commands/SendReminders.php(52): App\\Jobs\\Reminder\\NotifyUserAboutReminder::dispatch(Object(App\\Models\\Contact\\ReminderOutbox))
#64 /usr/share/nginx/monica/app/Console/Commands/SendReminders.php(39): App\\Console\\Commands\\SendReminders->send(Object(Illuminate\\Database\\Eloquent\\Collection))
#65 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): App\\Console\\Commands\\SendReminders->App\\Console\\Commands\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 1)
#66 /usr/share/nginx/monica/app/Console/Commands/SendReminders.php(40): Illuminate\\Database\\Eloquent\\Builder->chunk(500, Object(Closure))
#67 [internal function]: App\\Console\\Commands\\SendReminders->handle()
#68 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#69 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#70 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#71 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#72 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#73 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#74 /usr/share/nginx/monica/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#75 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#76 /usr/share/nginx/monica/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#77 /usr/share/nginx/monica/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\SendReminders), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#78 /usr/share/nginx/monica/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#79 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#80 /usr/share/nginx/monica/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#81 /usr/share/nginx/monica/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#82 {main}
"}
`

**Comment by farconada** [comment]
after a lot of debugging i realized that it's something related to mail size

this fails:


```
Mail::raw(
		"Hi ".$email.", you requested a test email from Monica Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet vestibulum accumsan. Nullam sit amet eleifend velit, nec consequat lacus. Fusce ultrices vitae leo sit amet suscipit. Duis accumsan quis magna a auctor. Donec ultricies nunc eu tortor ultricies volutpat. Nunc ut varius augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus placerat elit orci, a rhoncus mi tempor eget. Nam gravida molestie diam sit amet semper.
		Nunc eu luctus ligula. Quisque consequat aliquam sapien eget rhoncus. Vestibulum nec congue mi, eget faucibus orci. Etiam vel lacinia risus. Nullam sed risus sit amet magna condimentum egestas. Donec laoreet ut nibh et mollis. Nam tempor laoreet enim, egestas bibendum ante efficitur a.
		Maecenas rhoncus ex at augue gravida aliquet. Vivamus iaculis magna nec lectus egestas, et finibus dui pellentesque. Quisque suscipit risus at lacus cursus dictum. Integer sollicitudin dui id tortor lobortis elementum. Proin vestibulum dignissim metus. Phasellus quis interdum mi. Suspendisse feugiat, arcu eget vestibulum lobortis, dui justo sollicitudin tortor, nec sodales tortor felis eu magna. Nunc eget eleifend risus. Nam maximus fermentum sapien. Pellentesque pellentesque vel mauris a ornare. Ut ornare ligula leo, ac tristique nisi porta consectetur. Curabitur ut turpis eros.

	Nulla commodo dui in volutpat eleifend. Nulla non arcu ante. Aenean pulvinar elementum malesuada. Vivamus vitae leo vitae metus imperdiet maximus. Cras rhoncus nisi ut urna tempor sagittis. Proin consectetur nisl lacus, vel porttitor lorem semper eu. Duis porta euismod est et dignissim. Donec vel erat eu quam molestie efficitur sit amet et erat. Sed tristique arcu viverra aliquam efficitur. Morbi mattis et odio ac tincidunt. Pellentesque et nisl magna. Nam elementum consectetur imperdiet. Nam semper odio nec nibh vulputate consequat. Ut in euismod arcu.	.",
            function($message) use($email) {
                $message->to($email)
                    ->subject('Monica email delivery test');
            }
	);
```

**Comment by asbiin** [comment]
Monica should be able to send through SES
