### ISSUE TITLE
Editing an activity fails with "The resource has not been found"

### ISSUE THREAD

**Issue by jyc** [monicahq/monica#3944]
Steps to reproduce:

1. Create an activity.
2. Save it.
3. Click edit, edit the list of participants, then click Save.

Expected: edits are saved.
Actual: edit fails with error in screenshot.

I'm using the hosted version on https://app.monicahq.com.

<img width="823" alt="Screen Shot 2020-05-03 at 12 01 54 AM" src="https://user-images.githubusercontent.com/360412/80908053-722fa500-8cd1-11ea-9934-7834168f7bd5.png">

**Comment by asbiin** [comment]
I can't reproduce it.
If you've installed Monica on your own, you have to generate the keys with `php artisan key:generate`

**Comment by jyc** [comment]
I haven’t installed it on my own. This is on monicahq.com, as I stated in the issue. 

Do you have ideas for me to help debug this?

**Comment by asbiin** [comment]
OK I found how to display the error better, but that does not solves it.
Can you send me by mail (alexis@saettler.org) the email you use for login?

**Comment by jyc** [comment]
For sure! Thank you!

**Comment by Keho** [comment]
This issue happens to me as well when using some emotions such as emotion_bliss (béatitude) emotion_exasperation (exaspération), emotion_annoyance (gêne).  
Self installation of Monica v 2.17 language set to french.

**Comment by PNRxA** [comment]
![image](https://user-images.githubusercontent.com/16978632/84901906-6d8f4680-b0ef-11ea-92c3-c9b59025a81d.png)

Same happening on self-hosted docker. Happy to help with any extra information I can provide.

Currently reproducible simply by doing the following:
* Create activity (I used all optional fields)
* Save
* Come back later to edit (e.g refresh)
* The error (pictured above) comes up

**Comment by jzoy** [comment]
I have same issue self-hosted on Ubuntu by docker-compse

same with the following steps
    Create activity (I used all optional fields)
    Save
    Come back later to edit (e.g refresh)
    The error (pictured above) comes up even if nothing is changed when clicking 'save'

**Comment by asbiin** [comment]
This is fixed, or not reproductible

**Comment by rodriguezarmando445** [comment]
Email me if you would like to attend  AT&T business summit Monica?

**Comment by HmnSDR** [comment]
Yes I need a lot of help and unfortunately I do not know English, I bought
a lot of digital currency but I can not find it in my wallet     :(.  man.
4. okt. 2021 kl. 08:04 skrev rodriguezarmando445 ***@***.***>:
