### ISSUE TITLE
Import Friends From Facebook

### ISSUE THREAD

**Issue by degan6** [monicahq/monica#395]
Not sure if possible or allowed but we should look into it. 

Let this serve as the record for its progress.
I'll up this issue when I start working on code. 

Ideas and input welcome.

**Comment by djaiss** [comment]
I tried to do this last January. I quickly realized after many attempts and reading the documentation from Facebook that it wasn't possible, because their API prevents it.

**Comment by degan6** [comment]
Well it seems your are right. Facebook has prevented it when using the api.

https://stackoverflow.com/questions/23417356/facebook-graph-api-v2-0-me-friends-returns-empty-or-only-friends-who-also-u

**Comment by Phrohdoh** [comment]
Should this ticket be closed?

**Comment by degan6** [comment]
Yes, not possible.
