### ISSUE TITLE
E-Mail Invalid (support@monicahq.com)

### ISSUE THREAD

**Issue by CorneliousJD** [monicahq/monica#3970]
The app itself has a "Send me an email" link in the bottom left corner that does not work. 

Address not found
--
Your message wasn't delivered to support@monicahq.com because the address couldn't be found, or is unable to receive mail.

**Comment by asbiin** [comment]
@djaiss can you check on this?

**Comment by asbiin** [comment]
This is now fixed, sorry for the inconvenience.
