### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by ssx** [monicahq/monica#399]
Will you be able to start tagging versions so that people can upgrade to stable release points vs instead of git pull'ing to update. Even 0.0.1 etc would be better than non.

**Comment by djaiss** [comment]
A bit linked to #30 

I understand that this will become a huge issue if I don't tackle this quickly. I'll put that on my priority list.

**Comment by Phrohdoh** [comment]
Also related to #349.

**Comment by djaiss** [comment]
I'm doing this **TONIGHT**.
