### ISSUE TITLE
Docker APP_URL

### ISSUE THREAD

**Issue by newhinton** [monicahq/monica#3992]
**Describe the bug**
APP_URL is not applied when using docker-compose. 

I want to run monica in docker behind apache in a subdirectory. I have read multiple times that APP_URL needs to be set to the url the application will have in the end. However, if APP_URL is set in the .env it is not changed. Editing it in the container does not help.

**Comment by asbiin** [comment]
What makes you say it is not working?
APP_URL is **only** used to set url of your application in the mail sent.

**Comment by asbiin** [comment]
Maybe your issue is you tried using apache (so a proxy), and a subdirectory? In this case this a duplicate of #3361
