### ISSUE TITLE
Fresh Heroku Deployment, MANY buttons simply DO NOT WORK.

### ISSUE THREAD

**Issue by the4ndy** [monicahq/monica#3995]
**Describe the bug**
I deployed a fresh Monica instance on Heroku, on a fresh Heroku account (already verified). However, many buttons / features just simply do NOTHING. Here are the ones I have found:

 - Delete a tag in Tag Management, does nothing
 - Change Default Gender, does nothing, as do the Edit and Delete buttons for Genders
 - Pretty much ALL buttons in the Personalization page
 - Click here to select a contact (for choosing a contact to represent yourself)
 - Many of these buttons, when you click them, they do nothing, but also freeze the page until refresh.

For what its worth, im using Chrome. but the same thing happens in Firefox and on my mobile device. I have also checked the JS Console and found nothing :(

**Comment by asbiin** [comment]
Indeed. I actually had a fix in preparation for that, it will be fixed right now.
Thanks!
