### ISSUE TITLE
Adding an activity for multiple contacts

### ISSUE THREAD

**Issue by psteinweber** [monicahq/monica#400]
I'm a bit hesitant to log activities with multiple persons, because it's quite the hassle. For example: _barbecue with 5 friends_.

At the moment: I have to go to each contact and add the barbecue, select date, insert note. 

I think it would be better to: Enter an activity once and add ("tag"?) various people in there. (Maybe the journal could be used for this?)

Ideally it would be possible to make additional individual separate notes or edits, e.g. note the great conversation you had with Paul and where you recommended him a specific book.

This doesn't exactly feel like a small feature, but it would make using Monica much more streamlined IMO.

**Comment by djaiss** [comment]
Duplicate #118 

I agree, this would be a nice feature. Closing this one in favour of the older one.
