### ISSUE TITLE
BadMethodCallException when attempting to update preferences

### ISSUE THREAD

**Issue by twrightsman** [monicahq/monica#4007]
**Describe the bug**
I get a `BadMethodCallException: Call to undefined method App\Models\Account\Account::hasLimitations()` when clicking "Update Preferences" (even with no changes) on the settings page.

**Which version are you using:**
 - 2.17.0 (Self-hosted docker image tagged "latest" on 2020-05-12)

**Comment by GiganteX** [comment]
I got this too. Fresh install. Docker.

**Comment by hoclun-rigsep** [comment]
Me too. Version: 2.17.0

**Comment by micoots** [comment]
Yes, I've just performed a fresh install under yunohost, which installs the latest version, and got the same problem described when clicking Update Preferences.

**Comment by asbiin** [comment]
This is fixed now
