### ISSUE TITLE
When name order is last name first, add new person should show last name first

### ISSUE THREAD

**Issue by revi** [monicahq/monica#401]
I have set a configuration to Last name first([img_1336](https://user-images.githubusercontent.com/7630875/27549819-49e600b8-5ad8-11e7-8f97-feb8390ff19d.PNG)), but it seems [Add new person](https://user-images.githubusercontent.com/7630875/27549866-779aa720-5ad8-11e7-86d9-95ca5bcd9624.PNG) is still showing First name first. Can this be fixed? (Also other place with names)

**Comment by djaiss** [comment]
This is done and in production. Enjoy.
