### ISSUE TITLE
Uploading large image failed

### ISSUE THREAD

**Issue by GiganteX** [monicahq/monica#4014]
Fresh install. Docker.

There is a maxium size for photo uploads that prevents me from uploading 5 MB photos. I have a lot of those. Please allow uploads of large photos.

**Comment by asbiin** [comment]
@GiganteX your issue is very difficult to read. Please use the issue template to help us.

**Comment by GiganteX** [comment]
I don't do templates, but I rewrote the bug report (removed unnecessary commentary) to make it more clear.

**Comment by Luke-Larsen** [comment]
@GiganteX I know this is old but I thought it might help someone. I had something similar happen and had forgotten to increase the PHP max upload size. So the two things you can do are:
1:) make sure to increase DEFAULT_MAX_UPLOAD_SIZE in .env
2:) Change upload_max_filesize and post_max_size in your php.ini

**Comment by asbiin** [comment]
Thanks @Luke-Larsen for your solution
