### ISSUE TITLE
Apache docker image not working (Ubuntu 18.04)

### ISSUE THREAD

**Issue by arielaco** [monicahq/monica#4029]
**Describe the bug**
A clear and concise description of what the bug is. If your comment is `it doesn't work`, we won't know what to do with it.

[As per the docs](https://github.com/monicahq/monica/blob/master/docs/installation/providers/docker.md#use-monica-docker-image), I run ````docker run -d -p 8080:80 monicahq/monicahq```` (with sudo) and it does not work. When I remove the -d flag I see the following:

````
Status: Downloaded newer image for monicahq/monicahq:latest
Syncing sources...
...done!
Application key set successfully.
Connecting to mysql:3306
nc: getaddrinfo: Name does not resolve
Waiting for mysql:3306...
nc: getaddrinfo: Name does not resolve
Waiting for mysql:3306...

[repeats...]

nc: getaddrinfo: Name does not resolve
Waiting for mysql:3306...
Unable to contact your database at mysql:3306
````

Then the container stops. I've also tried other ports. Same thing.

Any ideas?

Thank you in advance

**Comment by asbiin** [comment]
Well, the application needs a database, mysql or mariadb.
See the rest of the documentation to see how to connect to a database: https://github.com/monicahq/monica/blob/master/docs/installation/providers/docker.md#apache-version
