### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by Sadikk** [monicahq/monica#4099]
**Describe the bug**

Fresh setup of Monica on my server, unable to register the first account. Crash after submit of the registration form.

**Screenshots**
With APP_DEBUG=true : 

![screenshot](https://i.imgur.com/iJIKLeO.png)

**Which version are you using:**
 - A server you maintain yourself : v2.18.0

**Comment by owldock** [comment]
having the exact same issue, getting the same error message --  

> Whoops! Something went wrong.
Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given, called in /var/www/monica/vendor/laravel/ui/auth-backend/RegistersUsers.php on line 36

![Screen Shot 2020-06-11 at 6 56 38 PM](https://user-images.githubusercontent.com/48806964/84447174-4fb87200-ac15-11ea-8c2d-0795a146ddbb.png)
 
Running Monica on NAS via docker, connected to a mariadb docker container. Any ideas for how to fix? Thanks!

**Comment by AlphaJack** [comment]
Same problem, but installed in a subdirectory. In my case the red hidden URL should be https://example.com/monica/register but instead it is https://example.com/register, even if I have set

```ini
APP_URL=https://example.com/monica/
```

**Comment by SirTerrific** [comment]
Hi, 

Same here !
