### ISSUE TITLE
Create kids as own contacts and let the contacts connect each other

### ISSUE THREAD

**Issue by bensbox** [monicahq/monica#41]
Currently i am only able to create kids inside of a contact.

I like to have the kids as own contacts and maybe even link contacts together, when i have the kids first and the parents later as my contacts.

Thanks!

**Comment by xorgy** [comment]
Somewhat related to #35

**Comment by adrum** [comment]
Might be worth defining "relationships" between contacts and have a relationship type (spouse,child,step-parent, sibling, cousin, step-sibling, etc.) to knock out this issue and #35. 

It may be worth keeping in mind a future version having a future feature to calculate family trees or perhaps suggestions to ask about their siblings our cousins.

**Comment by djaiss** [comment]
This feature has been implemented some time ago already. Thanks for the suggestion!
