### ISSUE TITLE
Unable to install on Debian Buster

### ISSUE THREAD

**Issue by michalcwiok** [monicahq/monica#4112]
Hi, I am unable to install Monica on my laptop running Debian. I am following the instructions precisely and I do not think I missed anything. 

Everything is OK, untill I run the command `php artisan setup:production -v`

This is the error I get:

`You are about to setup and configure Monica. Do you wish to continue? (yes/no) [no]:
 > yes

In Connection.php line 664:
                                                                               
  [Illuminate\Database\QueryException (42000)]                                 
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val  
  ue for 'offered_at' (SQL: ALTER TABLE gifts CHANGE date_offered offered_at   
  DATETIME DEFAULT 'NULL')                                                     
                                                                               

Exception trace:
 Illuminate\Database\Connection->runQueryCallback() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
 Illuminate\Database\Connection->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:459
 Illuminate\Database\Connection->statement() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:86
 Illuminate\Database\Schema\Blueprint->build() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:252
 Illuminate\Database\Schema\Builder->build() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:149
 Illuminate\Database\Schema\Builder->table() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/monica/database/migrations/2018_01_16_212320_rename_gift_columns.php:19
 RenameGiftColumns->up() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:359
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:366
 Illuminate\Database\Migrations\Migrator->runMigration() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:177
 Illuminate\Database\Migrations\Migrator->runUp() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:146
 Illuminate\Database\Migrations\Migrator->runPending() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:95
 Illuminate\Database\Migrations\Migrator->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:69
 Illuminate\Database\Console\Migrations\MigrateCommand->handle() at n/a:n/a
 call_user_func_array() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
 Illuminate\Console\Command->execute() at /var/www/monica/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:214
 Illuminate\Console\Command->callSilent() at /var/www/monica/app/Console/Commands/SetupProduction.php:51
 App\Console\Commands\SetupProduction->handle() at n/a:n/a
 call_user_func_array() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
 Illuminate\Console\Command->execute() at /var/www/monica/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /var/www/monica/vendor/symfony/console/Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at /var/www/monica/vendor/symfony/console/Application.php:240
 Symfony\Component\Console\Application->doRun() at /var/www/monica/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Application.php:88
 Illuminate\Console\Application->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/monica/artisan:35

In PDOStatement.php line 107:
                                                                               
  [Doctrine\DBAL\Driver\PDOException (42000)]                                  
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val  
  ue for 'offered_at'                                                          
                                                                               

Exception trace:
 Doctrine\DBAL\Driver\PDOStatement->execute() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458
 Illuminate\Database\Connection->Illuminate\Database\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657
 Illuminate\Database\Connection->runQueryCallback() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
 Illuminate\Database\Connection->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:459
 Illuminate\Database\Connection->statement() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:86
 Illuminate\Database\Schema\Blueprint->build() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:252
 Illuminate\Database\Schema\Builder->build() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:149
 Illuminate\Database\Schema\Builder->table() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/monica/database/migrations/2018_01_16_212320_rename_gift_columns.php:19
 RenameGiftColumns->up() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:359
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:366
 Illuminate\Database\Migrations\Migrator->runMigration() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:177
 Illuminate\Database\Migrations\Migrator->runUp() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:146
 Illuminate\Database\Migrations\Migrator->runPending() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:95
 Illuminate\Database\Migrations\Migrator->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:69
 Illuminate\Database\Console\Migrations\MigrateCommand->handle() at n/a:n/a
 call_user_func_array() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
 Illuminate\Console\Command->execute() at /var/www/monica/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:214
 Illuminate\Console\Command->callSilent() at /var/www/monica/app/Console/Commands/SetupProduction.php:51
 App\Console\Commands\SetupProduction->handle() at n/a:n/a
 call_user_func_array() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
 Illuminate\Console\Command->execute() at /var/www/monica/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /var/www/monica/vendor/symfony/console/Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at /var/www/monica/vendor/symfony/console/Application.php:240
 Symfony\Component\Console\Application->doRun() at /var/www/monica/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Application.php:88
 Illuminate\Console\Application->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/monica/artisan:35

In PDOStatement.php line 105:
                                                                               
  [PDOException (42000)]                                                       
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default val  
  ue for 'offered_at'                                                          
                                                                               

Exception trace:
 PDOStatement->execute() at /var/www/monica/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
 Doctrine\DBAL\Driver\PDOStatement->execute() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458
 Illuminate\Database\Connection->Illuminate\Database\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657
 Illuminate\Database\Connection->runQueryCallback() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
 Illuminate\Database\Connection->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Connection.php:459
 Illuminate\Database\Connection->statement() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:86
 Illuminate\Database\Schema\Blueprint->build() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:252
 Illuminate\Database\Schema\Builder->build() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:149
 Illuminate\Database\Schema\Builder->table() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/monica/database/migrations/2018_01_16_212320_rename_gift_columns.php:19
 RenameGiftColumns->up() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:359
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:366
 Illuminate\Database\Migrations\Migrator->runMigration() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:177
 Illuminate\Database\Migrations\Migrator->runUp() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:146
 Illuminate\Database\Migrations\Migrator->runPending() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:95
 Illuminate\Database\Migrations\Migrator->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:69
 Illuminate\Database\Console\Migrations\MigrateCommand->handle() at n/a:n/a
 call_user_func_array() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
 Illuminate\Console\Command->execute() at /var/www/monica/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:214
 Illuminate\Console\Command->callSilent() at /var/www/monica/app/Console/Commands/SetupProduction.php:51
 App\Console\Commands\SetupProduction->handle() at n/a:n/a
 call_user_func_array() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
 Illuminate\Console\Command->execute() at /var/www/monica/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /var/www/monica/vendor/symfony/console/Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at /var/www/monica/vendor/symfony/console/Application.php:240
 Symfony\Component\Console\Application->doRun() at /var/www/monica/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Console/Application.php:88
 Illuminate\Console\Application->run() at /var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/monica/artisan:35
`
Any help appreciated. Please let me know what other details, I should provide. This is a fresh install of Debian.

**Comment by asbiin** [comment]
I've just tested it, there is no problem with the installation, following [these instruction](https://github.com/monicahq/monica/blob/master/docs/installation/providers/debian.md).
What is your database engine?

**Comment by michalcwiok** [comment]
Hey, I followed exactly same instructions. I gave up and installed on Ubuntu 18.04 after all. But if you want to analyze the problem further, I can set up a VM to dive deep into the problem. I had the same issues when installing Monica on RPI. Should I use instructions for Debian?
