### ISSUE TITLE
Unable to use docker with postgresql

### ISSUE THREAD

**Issue by duracell** [monicahq/monica#4117]
**Describe the bug**
I wanted to use the docker (latest and php-apache) and got error messages right at the first db migration attempt. I'm using postgresql and as far as I saw this should work today.
At the "latest" I get the following error:

> monicahq    | _ Performing migrations  
> monicahq    | '/usr/bin/php7' 'artisan' migrate --force  
> monicahq    | Migrating: 2017_06_07_173437_add_multiple_genders_choices  
> monicahq    |   
> monicahq    | In Connection.php line 671:  
> monicahq    |  
> monicahq    |   [Illuminate\Database\QueryException (42601)]  
> monicahq    |   SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "\`"  
> monicahq    |   LINE 1: ALTER TABLE \`contacts\` DROP CONSTRAINT \`contacts\`_gender_che...  
> monicahq    |                       ^ (SQL: ALTER TABLE \`contacts\` DROP CONSTRAINT \`contact  
> monicahq    |   s\`_gender_check;)  
> [...]
> monicahq    | In PDOStatement.php line 119:
> monicahq    |
> monicahq    |   [Doctrine\DBAL\Driver\PDOException (42601)]
> monicahq    |   SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "\`"
> monicahq    |   LINE 1: ALTER TABLE \`contacts\` DROP CONSTRAINT \`contacts\`_gender_che...
> monicahq    |                       ^
> monicahq    |
> monicahq    |
> monicahq    | Exception trace:
> [...]
> And more.

In the php-apache docker I just get the error that the driver could not be found:
> monicahq    | In Connection.php line 671:
> monicahq    |
> monicahq    |   [Illuminate\Database\QueryException]
> monicahq    |   could not find driver (SQL: select * from information_schema.tables where t
> monicahq    |   able_schema = public and table_name = cache and table_type = 'BASE TABLE')
> monicahq    |
> monicahq    |
> monicahq    | Exception trace:

Do you have any idea how to fix this? I have no idea how there could be a configuration error.
(And to get the latest running is my main point, the missing driver is only to show that a switch to the other docker doesn't help)

**Comment by asbiin** [comment]
Well I'm not sure what the error is exactly, but Monica is not compatible with postgresql yet. You can use mysql or mariadb

**Comment by duracell** [comment]
Oh, okay, the isues #137, #687 and the linked PR #140 sounds like it would be compatible now.
Thats sad, because my docker machine it not that powerful and running 2 DB server seems not that great. But I just hope that this will be fixed someday.
Thanks for the fast reply!
