### ISSUE TITLE
would a Norwegian translation be welcomed?

### ISSUE THREAD

**Issue by divinity76** [monicahq/monica#4137]
it's not a "target language" on [Crowdin](https://crowdin.com/project/monicahq), hence asking

**Comment by asbiin** [comment]
Hi @divinity76 
Not sure if it's a request for opening Norwegian language or a simple question? ;) I'll open it.
Please read https://github.com/monicahq/monica/blob/master/docs/contribute/translate.md for some guidance about translation.

**Comment by divinity76** [comment]
>  a request for opening Norwegian language 

yeah pretty much that,

thanks

**Comment by asbiin** [comment]
We can leave this open as we have to add the language in the settings menu in addition to activate translation in crowdin.
Thanks for your help!

**Comment by asbiin** [comment]
@divinity76 would you help translate monica here https://crowdin.com/project/monicahq/no# ?

**Comment by djaiss** [comment]
Our upcoming version Chandler is fully translated in Norwegian.
