### ISSUE TITLE
impossible to add custom new tag

### ISSUE THREAD

**Issue by juansecaro** [monicahq/monica#4159]
**Describe the bug**
Add tag to a contact from under the name doesn't actually add anything. It leaves without effect.

**version**
2.18.0

**Comment by dawolf** [comment]
Just to cover all bases: Did you try pressing ENTER after you input the tag name? Then it appears below. You still have to click on "Save" to actually save the new tag.

**Comment by juansecaro** [comment]
I have checked again and it works. It was my failure understanding how it was used. Sorry.
