### ISSUE TITLE
"1 kid" where there is no kids

### ISSUE THREAD

**Issue by revi** [monicahq/monica#416]
When I browse `/people`, it says everybody has 1 kid, but when I access anyone's profile, there is no kids registered.

# Screenshots

![untitled](https://user-images.githubusercontent.com/7630875/27723635-00306be2-5da9-11e7-9028-8a64fb0871e9.png)
![untitled](https://user-images.githubusercontent.com/7630875/27723685-4139135a-5da9-11e7-9445-d38d1879121e.png)

**Comment by revi** [comment]
Originally found after deploying current HEAD to heroku, but reproducible on app.monicahq.com.

**Comment by djaiss** [comment]
Ohh I see. Let me check.
