### ISSUE TITLE
Support for armhf in docker images

### ISSUE THREAD

**Issue by madbear2000** [monicahq/monica#4177]
Hi,

Thanks for a very useful application. Was looking for something like this for a while.
I am using docker to install my own version locally but noticed that you are only building the arm64 version.

Would it be possible to update the build process to build for multiple architectures. I was trying to run this on a armhf (32 bit) and could not pull any image.

Thanks

**Comment by OlegSmelov** [comment]
For what it's worth, `docker build . -t monicahq/monicahq` can build a working image for `armhf`. The only thing that's not compatible is Sentry (which isn't required). Comment out these lines:

https://github.com/monicahq/monica/blob/cf06f0101dac20aa5112958888ff214aa44a6576/scripts/docker/apache/Dockerfile#L105-L111

**Comment by asbiin** [comment]
This might be a duplicate of https://github.com/monicahq/monica/issues/1528 ... confirm ?

I have worked on a new docker image, to add monica in the official docker library, and sentry will not be part of this new image:
https://github.com/docker-library/official-images/pull/7233

**Comment by OlegSmelov** [comment]
I needed `armhf` for my Raspberry Pi 3, I think this is indeed a duplicate.

**Comment by madbear2000** [comment]
Thanks @OlegSmelov I will give that a try.


@asbiin, You might be right. I did a search at the time and found no armf reference. I will close this as its already been working on as part pf #1528 
Any idea when an armf version will be available
