### ISSUE TITLE
Feature request: CalDAV and CardDAV support

### ISSUE THREAD

**Issue by williamtheaker** [monicahq/monica#42]
Even if it's only read only, it would be an easy way to synchronize contact data and events from Monica with mobile devices.

**Comment by fergbrain** [comment]
Also good because I think many people already use CalDav to store this kind of information.

**Comment by djaiss** [comment]
I agree. Although this would have been better to split this issue in two because these are two way different things.

**Comment by enko** [comment]
This can be done via [sabredev](http://sabre.io/). Its a PHP-API for caldav & carddav.

**Comment by pnorton** [comment]
Don't forget that some already have carddav servers setup. So having Monica updating those remote servers would be a good feature.  That way we'd have a single source of truth for contact information.

**Comment by djaiss** [comment]
@cweagans not yet. This is a huge beast, therefore it'll take some time, but CardDav and CalDav support is something that I'm very passionate about. I would even say that it's absolutely essential. I need to see how we can achieve it.

**Comment by djaiss** [comment]
For future reference: https://metricloop.com/blog/building-a-calendar-for-a-web-app-without-reinventing-the-wheel

**Comment by cweagans** [comment]
You'll notice I've been commenting in #1284 ;)

#582 should be closed as a dupe. This one was in place first.

**Comment by djaiss** [comment]
Yep, Carddav now works. We have to document it now but it still has to be considered "alpha" and it's kinda slow at the moment. We'll make it better over time. We've also started to support Caldav.

**Comment by pqhf5kd** [comment]
Is there alpha support on the hosted version?

**Comment by djaiss** [comment]
Yes.

It works on iOS with Contacts. On Android you have to use a dedicated plugin or something to support Carddav officially.

You have to use the address `https://app.monicahq.com/carddav` then use your email/password.

Warning: it removes your existing contacts! And it's a bit slow (like really slow) for the first pull of data.

**Comment by pqhf5kd** [comment]
I get 'Cannot Connect Using SSL. Do you want to try setting up the account without SSL?'
If I try without SSL, I get 'CardDAV account verification failed'

I have 2FA switched on if that makes a difference?

iOS 12.1.2

**Comment by asbiin** [comment]
> Warning: it removes your existing contacts!

I did not notice this behavior! @djaiss you mean it removes the contacts on the phone?

You can use "email/password", or "email/token", with a token created on the Settings>Api page.
https://app.monicahq.com/carddav is *not* working right now, but you can activate carddav on your hosted version by setting `CARDDAV_ENABLED=true` in you .env file. Then use `/carddav` url.

**Comment by pqhf5kd** [comment]
> https://app.monicahq.com/carddav is _not_ working right now

Any particular reason why? I'm interested in testing it out.

**Comment by asbiin** [comment]
> > https://app.monicahq.com/carddav is _not_ working right now
> 
> Any particular reason why? I'm interested in testing it out.

It's not a stable feature right now, we wan't take a risk at delete some datas.

**Comment by pqhf5kd** [comment]
CardDav support is now ticked on the roadmap. Can we being testing on the hosted platform?

**Comment by Wulfheart** [comment]
What's the current status?

**Comment by asbiin** [comment]
@Wulfheart We are currently testing it. Would you like to help us? Please contact me on [slack](
https://monicahq-group.slack.com/team/UB00UTRSS) if so.

**Comment by Wulfheart** [comment]
@asbiin I'd need an invitation.

**Comment by searoso** [comment]
I would definitely try Monica as my primary contacts provider.

**Comment by asbiin** [comment]
This is now fixed

**Comment by pqhf5kd** [comment]
I get 'Unable to verify account name or password' on macOS:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/20027419/63647332-c7b5ba00-c71f-11e9-95de-576b156f46b8.png">
Same with Advanced settings:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/20027419/63647343-f2a00e00-c71f-11e9-9b4e-8bfbbc579ec2.png">

**Comment by asbiin** [comment]
Hi folks! Carddav is now activated on all account on app.monicahq.com!
Let me now if it's working ... or not.

**Comment by pqhf5kd** [comment]
I can now add my account and my contacts have synced but I'm having trouble with a few things and I'm trying to work out if they're related

Addresses are syncing both ways but the 'Label (optional)' from Monica is appearing on iOS. If I add an address on iOS with a custom label, the address appears in Monica with no label and the label is removed from iOS within a minute.

Contact Information labels appear to be broken in Monica, I can select one when adding the details but I can't edit or see it after. I'm only seeing (presumably) Landline labeled numbers and email addresses on iOS. 

If I add an email address to a contact on iOS, it's deleted within a minute.

**Comment by asbiin** [comment]
Thanks @pqhf5kd , can you open a new issue please? This is kind of tricky problem!
