### ISSUE TITLE
When using Docker Composer, one's unable to create their first user account.

### ISSUE THREAD

**Issue by lunaray** [monicahq/monica#4212]
When installing on Docker via Docker Composer, it skips directly to production environment without the option of creating an user account.

Easy fix, just run:
`docker-compose exec app php artisan setup:test`

Afterwards the first account is created, then run:
`docker-compose exec app php artisan setup:production`

**Comment by asbiin** [comment]
Hello @lunaray 
This is by design. When creating a new instance of monica, just run ```docker-compose exec app php artisan setup:production``` then open your application url to create the first account.

`docker-compose exec app php artisan setup:test` should not be used on a production level instance.
