### ISSUE TITLE
Missing installation steps in the documentation

### ISSUE THREAD

**Issue by MounirDrioua** [monicahq/monica#426]
In order to create an account you need to set this variable **APP_DISABLE_SIGNUP** in .env to false
`APP_DISABLE_SIGNUP=false`

**Comment by djaiss** [comment]
@MounirDrioua no this is not necessary. Check [this line](https://github.com/monicahq/monica/blob/cf2d31f3655b81d79adee52bb9b2f4352f6e00d5/config/monica.php#L29). 
```php
'disable_signup' => env('APP_DISABLE_SIGNUP', false),
```

It defaults to false if the variable is not present in the `.env` file.
