### ISSUE TITLE
Reminder is not sent on the right timezone

### ISSUE THREAD

**Issue by voryzen** [monicahq/monica#428]
I'm` not sure how the date is produced but I've noticed that the date when adding journals and the 'last consulted' date is incorrect, for my timezone, the timezone that I have selected in the settings.

I'm using the MonicaHQ hosted service and I'm guessing that Monica gets the date from the server time..

This doesn't work for the users that are in a different timezone to the timezone that the server is on. It will work for self hosted instances, but not for users that use the MonicaHQ service.

BTW: the journalling is a great addition and I feel it's something that I would use, especially in my line of work, as I would be including contacts that are involved with my work, as well as my personal life

**Comment by djaiss** [comment]
I'll fix this in the coming days.

**Comment by djaiss** [comment]
This is fixed (I hope).
