### ISSUE TITLE
Self-Host Help: Setting up FPM with Caddy

### ISSUE THREAD

**Issue by steakscience** [monicahq/monica#4281]
Hi,

I was wondering whether anyone could help with setting up the FPM version on Docker and then using Caddy?

I can't seem to find a guide on this anywhere, but hopefully it shouldn't be too hard.

Thank you for the help!

**Comment by Mohammed90** [comment]
Here's minimal config that works:
```
{
	debug
}
localhost # replace with domain
@htaccess {
	path *.htaccess
}
respond @htaccess 403 {
	close
}
@security {
	path /.well-known/security.txt
}
redir @security /security.txt
@dav {
	path_regexp dav	/\.well-known/(carddav|caldav)(.*)
}
redir @dav /dav{http.regexp.dav.2}
root * /var/www/monica/public
php_fastcgi app:9000
file_server
```

To be completely honest, I haven't verified all the edge-cases and tested it end-to-end. You can get to a starting point by using Caddy's nginx config adapter to convert the [example config](https://github.com/monicahq/monica/blob/master/scripts/docker/.examples/supervisor/fpm/web/nginx.conf) to Caddy's JSON and tweak it some more yourself. If you want to stick to the Caddyfile, you can map some more of the nginx conf to the Caddyfile I've provided or customize it some more however you like.

**Comment by asbiin** [comment]
Thank you @Mohammed90 for your answer. I hope this helps.
