### ISSUE TITLE
Send a reminder to call/visit specific people when you haven't seen them for a while

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#429]
Feedback from user:

> I use a tool called Tinyblu that works really well to remind you to stay in touch with people.

To achieve this:
- configurable alert to send an email X days/weeks after you've last seen them.

**Comment by edwardyu** [comment]
Related: be able to sort people not only alphabetically but by date of last activity.

**Comment by djaiss** [comment]
Done in 2.1.0.
