### ISSUE TITLE
dav auth is failing with 401 when using email/password instead of email/apitoken

### ISSUE THREAD

**Issue by nebulade** [monicahq/monica#4295]
This is on version 2.18.0 installed via Cloudron

When trying to connect to the dav endpoints using email + password all tested clients including a curl -X PROPFIND would result in 401 
However generating an api token and using that as the password in basic auth, works just fine.

The redirects to the actual dav resources do work as expected.

Unfortunately setting `APP_DEBUG=true` does not reveal more information (If it should, maybe I am looking in the wrong place). What is the best way to debug this further?

Thanks a lot,
Johannes

**Comment by asbiin** [comment]
Hi @nebulade. There is nothing to debug, the behiavor works perfectly as designed.
the dav endpoint only works with email + api token. That is the way we have designed it so it is secure enough.

**Comment by nebulade** [comment]
Ah, good to know, then I guess the text should be changed to not mention the password login option: https://github.com/monicahq/monica/blob/27d4bf58a8969bb097a4fdc317f818be778e500a/resources/lang/en/settings.php#L489

**Comment by nebulade** [comment]
I've created a PR for that https://github.com/monicahq/monica/pull/4310
