### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by seantronathon** [monicahq/monica#4313]
I'm trying to follow some backup and restore tips from [#2355](https://github.com/monicahq/monica/issues/2355), and like the user further down in that issue, chepec, I seem to have a successful dump with the
`$ docker-compose exec mysql /usr/bin/mysqldump -u root --password=sekret_root_password monica > monica.sql`
command. One thing to note is that the backup from this dump seems completely differently formatted from the Settings > Export data > Export to SQL option within the dashboard.

I have tried chepec's suggestion of 
`docker exec -i $(docker-compose ps -q mysql) mysql -u root --password=sekret_root_password monica < monica.sql`
which for some reason gives me `Error: No such container: $(docker-compose`

chepec also lings to [an SO answer](https://stackoverflow.com/questions/50528521/docker-compose-mysql-import-failed-the-input-device-is-not-a-tty/52854233#52854233), all of the options of which fail me for various reasons.

The top answer is 
`docker-compose exec -T MYSQL_CONTAINERNAME mysql databasename < data.sql`
 which yields the error : `ERROR: No such service: MYSQL_CONTAINERNAME`

If I replace "MYSQL_CONTAINERNAME" with "mysql," the name of my sql service, and add the appropriate login, i.e. trying:
`docker-compose exec -T mysql mysql -u root --password=sekret_root_password databasename < data.sql`
then I get 
> ERROR 1064 (42000) at line 211: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

The Settings > Export data > Export SQL version of the monica.sql file fails with the above error message, and the 
`$ docker-compose exec mysql /usr/bin/mysqldump -u root --password=sekret_root_password monica > monica.sql` version of monica.sql starts with "ERROR 1064 (42000) at line 1: ..." but is otherwise the identical error message.

Last things to note: I'm *not* very savvy with any of these tools, so this very well could be something stupid simple. I'm also trying to run this on my Windows desktop, with the intent to have backups on a Google Drive just as ROODAY wants to from [#2355](https://github.com/monicahq/monica/issues/2355). I just haven't been able to get any restore code to work.

**Comment by wipash** [comment]
Not sure why command substitution isn't working for you, but try running this to see (from the directory with docker-compose.yml in it) to see if it returns an ID:
`docker-compose ps -q mysql`

If so, just drop the ID in here in place of `YOUR_ID`:
`docker exec -i YOUR_ID mysql -u root --password=sekret_root_password monica < monica.sql`

**Comment by seantronathon** [comment]
Okay, as it turns out, your suggestion works! the $( ) substitution doesn't work for some reason, but doing it in stages does. Thanks for the tip!
