### ISSUE TITLE
Able to login without entering credentials after recently (< 10 minutes) logging out

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#439]
By clicking the 'create account or sign in' button on the marketing page.

**Comment by djaiss** [comment]
Hum. This sounds like a serious bug to me.

**Comment by djaiss** [comment]
I've tested it out and I can't reproduce.

**Comment by Phrohdoh** [comment]
I've only managed to do this 3 times in total but it is a pretty serious issue.

**Comment by djaiss** [comment]
Yeah but how did you do it? I can't reproduce, on all my browsers. I can't see how it can happen, I'm using the default Laravel controller and there is no custom code that messes up with it.

**Comment by erdmenchen** [comment]
How can you login on the login page without entering your credentials?

**Comment by Phrohdoh** [comment]
> By clicking the 'create account or sign in' button on the marketing page.

**Comment by erdmenchen** [comment]
Are you sure you logged out properly?

**Comment by Phrohdoh** [comment]
I think I've uncovered what is happening.

- Login as usual
- Logout
- Use your browser's "back" functionality
- See the dashboard of the last logged-in user

Notes:
- Clicking "Add people" takes you to the login view
- Toggling between "Latest actions" and "What's coming" will show the relevant data
- Clicking a link to a contact will show the error view ("Whoops, looks like something went wrong.")

So all-in-all you can only view the data on the dashboard.
Routes should send the client to the login view if they are not authenticated.

**Comment by erdmenchen** [comment]
When navigating back after logout, then this is the browsers cache and not a real page load, right?

**Comment by djaiss** [comment]
I don't know how I can catch the fact that we used the back button of the browser without using JS or a framework to detect it.

**Comment by Phrohdoh** [comment]
If this is the cache then this won't be 'fix'-able on Monica's side.

I'm still pretty sure I've been able to repro this by clicking the noted button (not using 'back') but can't seem to do that again now.

@djaiss Feel free to close.

**Comment by Phrohdoh** [comment]
I was just able to reproduce this *not* using the back button navigation.

I went to `monicahq.com`, clicked `log in` and was immediately logged in.
My browser *does not* have my monicahq credentials stored.

**Comment by djaiss** [comment]
I don't see how this is possible. I'm using standard Laravel auth.

Just to make sure, once you logged in, you were in your account, right?

**Comment by Phrohdoh** [comment]
Yes, I could navigate to individual contacts.
