### ISSUE TITLE
Seeding: FakeUserTableSeeder error'ing

### ISSUE THREAD

**Issue by alex-barylski** [monicahq/monica#4407]
I have everything setup (I believe) I can see the login screen but when I try and login using the default accounts:

u: admin@admin.com
p: admin

I am getting an error about invalid credentials. So I re-run:

`php artisan setup:production`

And it's error'ing with the following:

```
Monica v2.19.0 is set up, enjoy.
✓ Filling database
Seeding: FakeUserTableSeeder

In Validator.php line 445:
                               
  The given data was invalid.  
```

Any ideas?

**Comment by asbiin** [comment]
Hi.

The default credential password is: "admin0"
If you have setup a production instance, re-read https://github.com/monicahq/monica/blob/master/docs/installation/providers/generic.md : you should have set the `APP_ENV` variable to `production`.
