### ISSUE TITLE
contact dash/page inconsistancies

### ISSUE THREAD

**Issue by voryzen** [monicahq/monica#441]
![remindersdisplaydifferent](https://user-images.githubusercontent.com/1438921/27810214-00ec6eba-609b-11e7-9386-ee72956abc98.png)
So I've taken a screenshot to show what I'm talking about.

I've noticed that the reminders (and the notes, though it's not shown) are displayed differently to all the others.
My suggestion:
1. why not display everything like the reminders and the notes are displayed, no borders like the borders that surround the tasks, gifts, debts, activities entries

2. use the small delete and edit icons that are appear in tasks, gifts, debts, activities etc and use them with the others, instead of using the word 'delete', like it's used in reminders

hopefully that makes sense, and will help create a little more uniform UI

**Comment by djaiss** [comment]
This is now solved and in production. Thanks for sharing this issue.
