### ISSUE TITLE
Option to add a contact's parents & siblings

### ISSUE THREAD

**Issue by engstrom** [monicahq/monica#443]
It would be nice to be able to add a contact's parents and/or siblings in the same way children and significant others are currently handled.

It probably doesn't make sense to extend this functionality much deeper (e.g. cousins, nieces/nephews, etc.) but I think it would be helpful to be able to reference a contact's close family ties.

**Comment by degan6** [comment]
I agree, but we need to make a stureral change first. We need to make it so people can be linked to people in arbitrary ways. 

Talked about in #41, #117 and more that I don't to find right now.
