### ISSUE TITLE
Uploading a .vcf file gives me a 413 error

### ISSUE THREAD

**Issue by AndrewGable** [monicahq/monica#445]
I attempted to upload a .vcf file that is 3.2mb and I am getting a 413 error as seen below:

### File Info
<img width="377" alt="screen shot 2017-07-04 at 11 14 20 am" src="https://user-images.githubusercontent.com/2838819/27839948-00a81fc6-60aa-11e7-9c4e-9f67536c7af9.png">

### Error message from Monica
![screen shot 2017-07-04 at 11 10 22 am](https://user-images.githubusercontent.com/2838819/27839961-0f77a1e8-60aa-11e7-8911-fe12464d5652.png)

**Comment by djaiss** [comment]
I've tried with 10Mb file with no issues. I'll check. Sorry about this.

**Comment by djaiss** [comment]
Hum or did I?

https://laracasts.com/discuss/channels/forge/413-request-entity-too-large-nginx162

**Comment by djaiss** [comment]
This is fixed. However the account will be slow with thousands of users until we make sure it's fast (meaning, soon).

**Comment by AndrewGable** [comment]
It worked 🎉 thanks!

**Comment by djaiss** [comment]
@AndrewGable for such a file size, I'd be interested to know how many contacts you had? Also, is the UI still fast? I bet the contact list became slow?

**Comment by AndrewGable** [comment]
I had 18 contacts for this 3.2MB file, my full contact list is 375 contacts and comes in at 68MB. I sync with Facebook to get my contact's photos on my iPhone so that might cause them to be larger than the average. 

The site seemed fine, didn't notice any slows but really wasn't looking for it.

**Comment by djaiss** [comment]
@AndrewGable ohhh I thought this would have resulted in thousands of contacts. Yeah with 375 contacts, Monica will run really smoothly.

**Comment by dosch** [comment]
I have 733 contacts in a 2.6Mb vcard file.
![screen shot 2018-06-13 at 21 33 33](https://user-images.githubusercontent.com/5372610/41373737-7758899c-6f51-11e8-88ef-a316aef4f56e.png)

Uploading gives me the same error... 
![screen shot 2018-06-13 at 21 34 51](https://user-images.githubusercontent.com/5372610/41373797-a2f8b2e8-6f51-11e8-9996-5bf8c0a930b5.png)

I have Monica version 2.1.1

**Comment by jgillman** [comment]
[There is already a fix in this thread](
https://github.com/monicahq/monica/issues/445#issuecomment-312950042) but just to maintain a record here, that error is a configuration issue with Nginx, not Monica.

At the time of this writing the default limit is 1 MB for uploads in Nginx. This can be changed with the `client_max_body_size` directive. ([Nginx docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size))

After adding it your `nginx.conf` file will have something like this in it:

```nginx
html {
  client_max_body_size 50m;
}
```

> <sub>**Note:** Make sure you're using `m` for megabytes and _not_ `mb`</sub>

As with any config change in Nginx, don't forget to restart it after making the change: `sudo service nginx restart`

**Comment by alexriabtsev** [comment]
hey! I'm getting the same error for my Heroku install with 2.6 Mb file. How can I fix this?

**Comment by MatyiFKBT** [comment]
@alexriabtsev have you found any solution? I'm facing the same

**Comment by alexriabtsev** [comment]
> @alexriabtsev have you found any solution? I'm facing the same

unfortunetly no
