### ISSUE TITLE
Add ability to mark a note as important

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#446]
So you can filter by things that are important.

**Comment by Phrohdoh** [comment]
Do we need to explicitly build this functionality or can we offload that onto the user via tags (and tag filtering)?

**Comment by hupili** [comment]
Going further could be a full-text search function. I now manage contacts and notes via evernote. I "invent" some text snippets to help me filter information..

**Comment by djaiss** [comment]
This is now in production.
