### ISSUE TITLE
Feature Request: Add section for school/geography

### ISSUE THREAD

**Issue by xasos** [monicahq/monica#448]
A section for school/geography would be great, especially when you're visiting a specific city.

**Comment by degan6** [comment]
Could you expand on the second part?
I guessing you mean add education information for a contact. (Good Idea)
But what do you mean by geography info in regards to visiting a city?

**Comment by djaiss** [comment]
Education will be covered by custom fields.

**Comment by xasos** [comment]
^ @djaiss covered it. I'll close this, as I realized there's addresses that cover my use case.
