### ISSUE TITLE
Abandoned mobile app ?

### ISSUE THREAD

**Issue by Gaibhne** [monicahq/monica#4483]
I originally checked out this project because it seemed so promising, but without a mobile client to push data, it doesn't really seem all that useful to the average person. But because a mobile client was teased, I bookmarked the project and returned later in hopes of there being a finished client. Imagine my surprise when it seems that after long and hard development, a mobile client was released and apparently abandoned only a few months later, with no word other than the app disappearing from the store and the repo being marked archived/read only.

Aside from the general disappointment over losing what seems like a good 80% of this apps worth, I'm baffled that there seems to be no information as to what exactly is going on with the client. A few clarifying words on the repo at the very least would be nice, as well as some information on whether the app is on ice because the workload was too much, because a newer version is in development or where that whole aspect is headed.

**Comment by GitJamz** [comment]
This entire project seems abandoned.. 23 days and no information to the above question..  Wtf...

**Comment by asbiin** [comment]
Hi! The mobile app is not abandoned, we just need support from the community to do it.
If you have the skills, it would be welcome if you can improve it! Thank you
