### ISSUE TITLE
Feature Request: Autofill tags

### ISSUE THREAD

**Issue by xasos** [monicahq/monica#449]
When I'm adding a tag for a person, a list of previously used tags (by popularity) should be added as a card latching from the textbox.

**Comment by chrisspiegl** [comment]
The tag system could use a whole lot of improvements but this one is probably the most pressing. Having to actually remember all the tags and how they were typed isn't that great at the moment.

A tag cloud would be one option to make it easy to select tags by clicking as well as having autocomplete on the tag entry text box.

**Comment by djaiss** [comment]
Will be addressed here https://github.com/monicahq/monica/pull/1995
