### ISSUE TITLE
time in journal

### ISSUE THREAD

**Issue by SkyL0ver** [monicahq/monica#4508]
is there a way to show time when posting a journal?

**Comment by sktlmarat** [comment]
Hi @djaiss,
 
I worked with this issue and this required UI change. My solution is to simply display created at the date under the title.
It looks like this: 
![Снимок экрана 2021-03-11 в 14 55 40](https://user-images.githubusercontent.com/40805789/110761870-6b22dd00-827a-11eb-8d13-830dc1c07f20.png)

Thanks!
