### ISSUE TITLE
me profile

### ISSUE THREAD

**Issue by FuMagnet** [monicahq/monica#4510]
I cannot add my own profile.
(No profile)

2.19.1

![mh](https://user-images.githubusercontent.com/55971452/94876685-b11c7f00-0458-11eb-91f5-fa3fc519fbd8.PNG)

**Comment by GideonWolfe** [comment]
Can confirm I am also experiencing this.

**Comment by Niracus** [comment]
Had the same issue (?). I just search for my own name and found the contact. Seems like you have to type something before it actualy searches

**Comment by FuMagnet** [comment]
@Niracus It worked, thanks!
