### ISSUE TITLE
Feature Request: Work website

### ISSUE THREAD

**Issue by blindly** [monicahq/monica#452]
For work information, there are 3 listed fields:
1. Job title
2. Company
3. LinkedIn

I'd like to see a 4th: website
This would allow adding a website. This could be a personal or professional website, or maybe even the company website.

![capture](https://user-images.githubusercontent.com/1953656/27942919-fb2d0ace-62a8-11e7-8912-3f9af232dd69.PNG)

**Comment by djaiss** [comment]
To me this is out of scope for the project. Perhaps custom fields will allow this, but I don't think adding website about the job should be part of a personal relationship management system. It's not a CRM.
