### ISSUE TITLE
Invalid Validation Messages

### ISSUE THREAD

**Issue by kavanpancholi** [monicahq/monica#4541]
On any validation message, it shows something like the following message "validation.vue.required" instead of proper validation message.

Screenshot:
![image](https://user-images.githubusercontent.com/5137072/95723031-4fe37f80-0c92-11eb-88cc-23c4d6e5cc52.png)

Root Cause:
In the code, validation message uses vue-i18n plugin to show all the locale messages.
And there is no "vue" key defined in the json file (`public/js/langs/en.json`) and because of that it shows plain text instead of message from locale file.

**Comment by Daibushi** [comment]
Can i fix It?

**Comment by kavanpancholi** [comment]
@Daibushi I have already tried to fix it. I've created this PR https://github.com/monicahq/monica/pull/4542.
Waiting for the maintainer to approve it.

**Comment by Daibushi** [comment]
Ok.

**Comment by asbiin** [comment]
fixed
