### ISSUE TITLE
ERROR: for mysql  Cannot start service mysql:

### ISSUE THREAD

**Issue by jogjayr** [monicahq/monica#455]
Note: I mostly followed the steps on this guide https://github.com/monicahq/monica/blob/master/docs/installation/docker.md

Steps to reproduce:

1. Create a container-optimized VM (free tier) on Google Cloud Platform
2. Clone the monica git repo. `cd` into it
3. Rename `.env.example` to `.env`
3. Change `MAIL_` props to newly created Gmail account
3. Change `DB_HOST` to 'mysql`
4. Install docker-compose using this guide https://cloud.google.com/community/tutorials/docker-compose-on-container-optimized-os
5. Run `docker-compose pull`
6. Run `docker-compose up`

Expected:

`docker-compose up` runs successfully, without errors

Actual:

Got the following error:

    jogjayr@instance-1 ~/monica $ docker-compose up
    Starting monica_mysql_1 ...
    Starting monica_mysql_1 ... error

    ERROR: for monica_mysql_1  Cannot start service mysql: mkdir /rootfs: read-only file system

    ERROR: for mysql  Cannot start service mysql: mkdir /rootfs: read-only file system
    Encountered errors while bringing up the project.

**Comment by djaiss** [comment]
Sorry you've encountered this error. Unfortunately I do not master GCP and do not know how I can help you with this. Hopes someone from the community will help.

**Comment by Phrohdoh** [comment]
I don't think this is an issue with GCP.

@jogjayr Have you tried running a Monica instance in a local Docker environment?

Also, try setting `read_only: false` in `docker-compose.yml` for the mysql volume.

You'll have to change from short-form to [long-form](https://docs.docker.com/compose/compose-file/#long-syntax-3).

Let us know if this resolves your issue.

This isn't a great fix but it might get you up and running temporarily.

Ideally you'd mount to a persistent drive that isn't your rootfs.

**Comment by djaiss** [comment]
It's been some time now since this issue occurred. Is this fixed by now? I'll close the issue but feel free to let me know if I should open it again.
