### ISSUE TITLE
Edit button is not obvious

### ISSUE THREAD

**Issue by campbecf** [monicahq/monica#46]
![edit](https://user-images.githubusercontent.com/1759842/26849147-091116b6-4ad1-11e7-9129-746d306f73c1.png)

The edit button blends into the person page a bit too well. It was difficult to find. I suggest add a way to edit in the header perhaps with an icon ?

**Comment by ppanthony** [comment]
![screen shot 2017-06-06 at 21 48 44](https://user-images.githubusercontent.com/7252072/26850925-34e6c698-4b01-11e7-8d5d-4582e76dc1a3.png)

What's the thoughts on this as a potential fix? Or preferred to move the functionality to the header.

**Comment by campbecf** [comment]
@ppanthony That is a lot more obvious, I think that would be fine for now.
