### ISSUE TITLE
CardDAV Sync: Unable to connect in iOS

### ISSUE THREAD

**Issue by Antoine-lb** [monicahq/monica#4607]
Hello 👋

I found this comment in a feature request thread.

I don't really know how to connect to CardDAV and I can't find information about it.

---
I get 'Unable to verify account name or password' on macOS:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/20027419/63647332-c7b5ba00-c71f-11e9-95de-576b156f46b8.png">
Same with Advanced settings:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/20027419/63647343-f2a00e00-c71f-11e9-9b4e-8bfbbc579ec2.png">

_Originally posted by @pqhf5kd in https://github.com/monicahq/monica/issues/42#issuecomment-524610163_

---

I'm having this exact issue, but that comment was more than a year ego, I don't even know if I'm doing it right but I can't find documentation.

Thanks for the help!

**Comment by lpdyck** [comment]
When you input the password, are you using your login password or an API key?
