### ISSUE TITLE
Multi-tenant for self-hosting?

### ISSUE THREAD

**Issue by ford-prefect** [monicahq/monica#4617]
Thank you for this project!

This is more a question than a issue per-se -- does Monica allow multiple independent tenants while selfhosting? The impression I get is no, but thought I'd double-check since the README suggests that app.monicahq.com and the released code are the same.

**Comment by lpdyck** [comment]
If you host your own it allows multiple registered accounts. Is that what you mean or are you referring to something else?

**Comment by ford-prefect** [comment]
I guess I'm wondering how I register the second account after the first one -- can't seem to find it (I'm on 2.19.0, deployed with homelabOS).

**Comment by ford-prefect** [comment]
Sorry about the noise -- just realised that the default on HomelabOS is `APP_DISABLE_SIGNUP` is false.

**Comment by ford-prefect** [comment]
(though if there's a way to create users without having to enable registration, that would be nice to know too)

**Comment by lpdyck** [comment]
There isn't, but I was running into the same problem when I set up my instance the other day. I submitted an MR to add an artisan command, we'll see what becomes of it.
