### ISSUE TITLE
Change storage folder path in environment variables

### ISSUE THREAD

**Issue by AlexKnowsIt** [monicahq/monica#4641]
**Is your feature request related to a problem? Please describe.**
I tried today to run Monica on a server I control but my hosting provider (netcup) doesn't give the user full SU priviliges. That said after I made a database and connected it to Monica i run into the issue, that my folder paths are beginning not in the real root folder, but in the root root folder I give to the project itself (so in this case monica/public is my / directory). Therefore I can't give the correct rights that monica caan access the storage folder. I then tried to expose the monica folder as root folder (I am not sure if this is a smart idea), but then I get an error, because the folder exists in /storage instead of monica/storage, where it's looking for the file.

**Describe the solution you'd like**
An environment variable in the .env file where you could set the path for the storage folder manually. This way I could enter /storage as the folder and hide the mydomain.com site and just expose mydomain.com/public

**Describe alternatives you've considered (optional)**
If there is an alternate solution I would be really happy to know. So far Google an Stackoverflow did not show me what I need.

**Additional context**
I'm quite new into serverside applications and especially php. If I missed something fundamentally I am glad to learn :)

**Comment by asbiin** [comment]
Monica is based on Laravel, which does not allow to do that.
You can however store files in an external service like S3.
See installation docs.

**Comment by kpfleming** [comment]
Setting up a new installation and I'd really like to keep the 'storage' area out of the cloned repository as well; there are various ways that I can do that without Monica's knowledge, but I'd prefer to do it using a supported set of configuration variables.

It appears based on the contents of https://github.com/monicahq/monica/blob/master/config/filesystems.php that some work has been done in this area; can we help test this out?
