### ISSUE TITLE
Installation script doesn't check for ImageMagick extension

### ISSUE THREAD

**Issue by smaffulli** [monicahq/monica#4644]
The Installation process went smoothly following the instructions but at first login I got a `Whoops` message

```You need to install the imagick extension to use this back end```

A simple check at install time for imagick extension would make the experience a lot more pleasant. Or at the very list make it an explicit [requirement](https://github.com/smaffulli/monica/tree/master/docs/installation#requirements).

**Comment by arisAlexis** [comment]
I just submitted a pull request #4646 to solve this
