### ISSUE TITLE
Default .htaccess is missing RewriteBase URL

### ISSUE THREAD

**Issue by smaffulli** [monicahq/monica#4645]
After a clean installation on my hosting provider the app seemed to be able to only serve the home page. The Register and Reset Password URL were giving a 500 error. 
Upon investigation with the hosting provider, the fix was adding `RewriteBase /` to .htaccess. Not sure if this is necessary for every host but throwing out here in case someone else finds this 500 error after the first install.

```diff --git a/public/.htaccess b/public/.htaccess
index 631d10e8..32183839 100644
--- a/public/.htaccess
+++ b/public/.htaccess
@@ -4,7 +4,7 @@
     </IfModule>
 
     RewriteEngine On
-
+    RewriteBase /
     # Handle Authorization Header
     RewriteCond %{HTTP:Authorization} .
     RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

**Comment by asbiin** [comment]
Thank you for this tips.

However, I'm pretty sure we do not want this.
Everything is working fine now, you can verify that on the docker `monica` image, and adding a `RewriteBase` instruction in the `.htaccess` will prevent monica to work on subdir-installations.

**Comment by ford-prefect** [comment]
Was something fixed for this to work?
