### ISSUE TITLE
Account is not displayed correctly

### ISSUE THREAD

**Issue by montagsmodell** [monicahq/monica#4675]
Hi guys, love your product!
I am hosting Monica on a Docker environment on my Raspberry.

Specific to (one known) account I encounter the following issue:

* Cannot create any notes for an account

* Cannot add any activity to an account (but can do it via adding him/her to an activity event on another user, so the accounts are listed within the look-up field)

* I can only add "discussion", "reminders", and "debt" to the accounts (as well as all information in the left column and in the personal information like age, gender etc).

* It is not possible to delete the contact. I have the text "Delete contact" text on the down left side of the page, but cannot select it.

I tried:
- Restarting Raspberry
- sudo apt-get update/upgrade 

This seems to be specific to some (not all and not the most recent) accounts that I created within the last few days
Thank you for helping me figuring it out.

**Comment by montagsmodell** [comment]
ok I found out that this only happens if I connect via https. If I connect with http in the local net, everything looks as it should be.
Any ideas how to solve it?

**Comment by asbiin** [comment]
Please find the resources that are not loaded (404 errors), and fix these access

**Comment by montagsmodell** [comment]
where can I find these 404 errors? To clarify, _some_ account pages look like this:
![monica](https://user-images.githubusercontent.com/57067272/102691395-872f5900-420c-11eb-9019-d6c00d0120c7.PNG)

- There is no link for deletion of a contact
- There is no notes field
- There is no "add activity" but I can add the account to an activity that I created on another account that has the fields.
- There is no "add documents"
- There is no "add tasks"

I only have "talks", "debt" and "gifts", and "reminders".

I use Monica v2.19.1 on a raspian via docker image.

**Comment by asbiin** [comment]
Closing this due to lack of details
