### ISSUE TITLE
Password Recovery Emails Always Link to localhost on Self-Hosted Install

### ISSUE THREAD

**Issue by mgrhm** [monicahq/monica#4676]
On a working install, using a custom subdomain, password recovery emails do not generate a correct URL.  They always point to http://localhost rather than the correct URL.

They _do_ work, however, if you copy and paste the URL and replace 'localhost' with the correct subdomain.

**Comment by asbiin** [comment]
Did you set the `APP_URL` environment variable?

**Comment by mgrhm** [comment]
The `APP_URL` variable is set in `.env` like so:

    APP_URL=https://monica.instance.com

Is the `https://` part causing the issue?

**Comment by mgrhm** [comment]
Turns out that Monica’s reminders also link to localhost.

When I created the database, I followed the install instructions and used this command:

    CREATE USER 'monica'@'localhost' IDENTIFIED BY 'strongpassword';

Should that have been `'monica'@'monica.myserver.com'` instead?

**Comment by asbiin** [comment]
This has nothing to do with database installation.
Email send use the APP_URL to create the url that is included in the email.
You have to set the variable, and be sure to restart you apache/nginx/php-fpm service.

**Comment by mgrhm** [comment]
I can’t seem to fix this.  The `APP_URL` is set correctly, I’ve reloaded all the configs several times, and rebooted the server a couple of times too.  I can live with it for now, but sooner or later, I’ll reinstall Monica to see if that fixes it.

Thanks for the help.  I’ll close this now.
