### ISSUE TITLE
Translation for persian language farsi

### ISSUE THREAD

**Issue by wikiccu** [monicahq/monica#4682]
Hello
I would ask you is there any plan for translation to the Persian/farsi language ?

**Comment by asbiin** [comment]
Hi @wikiccu 
I've open the translation for Persian in crowdin: https://crowdin.com/project/monicahq/fa#
Please read our document about translations: https://github.com/monicahq/monica/blob/master/docs/contribute/translate.md

Thank you for your help!

**Comment by wikiccu** [comment]
Thank you I'll work on it.
