### ISSUE TITLE
Docker image 'latest' tag

### ISSUE THREAD

**Issue by coonce** [monicahq/monica#470]
Monica looks very nice! I tried pulling from Docker Hub using `docker-compose pull` which pulls the `monicahq/monicahq` image with the `latest` tag, but I got an older version from a month ago. Maybe the build just needs an additional tag when doing the release?
`$ docker tag <id> monicahq/monicahq:v0.5.0`
`$ docker tag <id> monicahq/monicahq:latest`
That should keep the `latest` tag in sync with the last release.

**Comment by djaiss** [comment]
@coonce Thanks a lot for this.

I think I can do something like `git tag --force latest` to always have the `latest` tag up to date.

(source: https://stackoverflow.com/questions/8044583/how-can-i-move-a-tag-on-a-git-branch-to-a-different-commit)

**Comment by djaiss** [comment]
Flow would be:

1. Delete the tag on any remote before you push `git push origin :refs/tags/<tagname>`
2. Replace the tag to reference the most recent commit `git tag -fa <tagname>`
3. Push the tag to the remote origin `git push origin master --tags`

**Comment by coonce** [comment]
Does Docker Hub use the git tag for tagging images? I haven't used their automated build process, but it might be easier to just use the `docker tag` command as part of the release process to just tag the image before `docker push`ing to the docker repository (Docker Hub). 
Here's a script that might work: https://medium.com/travis-on-docker/how-to-version-your-docker-images-1d5c577ebf54

**Comment by asbiin** [comment]
@coonce is right, docker tags is not linked to git tags, you don't need it.
I think this issue could be closed..

**Comment by djaiss** [comment]
@asbiin thansks!
