### ISSUE TITLE
Send a birthday reminder email on the day

### ISSUE THREAD

**Issue by mgrhm** [monicahq/monica#4705]
A reminder a month and a week before a birthday are really useful for getting presents organised, but it’s easy to let the actual date slip your mind when it comes around a week later.

It would be really useful to get one final reminder to wish someone happy birthday on the day itself.  This could either be a default, or a slider in the ‘Reminder Rules’ section of Personalisation.

**Comment by asbiin** [comment]
Actually, this feature is already implemented.
