### ISSUE TITLE
Access denied for user 'forge'@'localhost' to database 'forge'

### ISSUE THREAD

**Issue by RMPR** [monicahq/monica#4706]
**Describe the bug**
While installing monica on Raspbian (thus following the Debian instructions). I ran into an issue where I will just get the error message in the title of the issue.

**Screenshots**
![Error Message](https://i.imgur.com/V0nwQfE.png)

**Which version are you using:**
 - Self-hosted: v2.19.1

**Additional context**
I was actually able to solve the problem by creating the database and the user `forge`, then granting all the privileges. I think it should be added to the install instructions

```
MariaDB [(none)]> CREATE USER 'forge'@'localhost' IDENTIFIED BY '';
Query OK, 0 rows affected (0.002 sec)

MariaDB [(none)]> CREATE DATABASE forge;
Query OK, 1 row affected (0.001 sec)

MariaDB [(none)]> GRANT ALL ON forge.* TO 'forge'@'localhost';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.002 sec)

MariaDB [(none)]> exit;
```
If you're okay with that, I can make a PR.

**Comment by asbiin** [comment]
I think this is already explain in the install documentation. Where do you want to add this?
Create a PR if you want.

**Comment by asbiin** [comment]
See my comment in the PR #4734
