### ISSUE TITLE
This person is probably... age generates jan 1 bday calendar events

### ISSUE THREAD

**Issue by arisAlexis** [monicahq/monica#4707]
If you indicate that you know someone is probably X years old, you get Jan 1 calendar reminders.

**Comment by mgrhm** [comment]
Did this happen when you added an estimated age for an existing contact, or when you did it while adding a new contact?

I just tested this on my own instance and it doesn’t seem to happen for me when I edit existing contacts.  I tried two separate contacts without getting a January 1st reminder for either.

**Comment by arisAlexis** [comment]
it happens when adding a new contact

**Comment by mgrhm** [comment]
I’m struggling to reproduce this.  When I create a new contact, it doesn’t give me the option of adding the birthday.  I can only do this later via ‘Edit Contact Information’.  When I add it there, it doesn’t generate the January 1st reminder.

I’m using the current version self-hosted.

**Comment by lpdyck** [comment]
You can enter birthday when adding a new contact as a relationship, though I wasn't able to reproduce it that way either. There isn't even a way to enable a reminder for a person with an approximate age.
 @arisAlexis Can you give detailed steps to reproduce? Tell me like I'm dumb and you won't be far off 😅
