### ISSUE TITLE
Blank page on addig contacts

### ISSUE THREAD

**Issue by alexriabtsev** [monicahq/monica#4708]
**Describe the bug**
I have self-hosted Monica CRM (v.2.19.1) on Heroku. When I'm trying to manually add contact I'm getting blank screen with footer at the top.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8425396/102473245-e9972680-405f-11eb-910c-2f5d85de0f18.png">

**Comment by alexriabtsev** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8425396/102473351-07fd2200-4060-11eb-973c-7377bb1a926b.png">
Looks like everything inside the body tag is absent

**Comment by asbiin** [comment]
Please check all migration have ran, that might explain the problem.
Anyway, this is not reproducible.
