### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by tfont** [monicahq/monica#4711]
However, the error log is completely empty.

response:
```
Request URL: http://example.com/people/h:VRMjGqy2adpKZoOva0/contactfield
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 139.59.139.188:80
Referrer Policy: strict-origin-when-cross-origin
```

request:
```
{
    "message": "Server Error"
}
```

On **Zend OPcache v7.3.24-3+ubuntu20.04.1+deb.sury.org+1**
I've followed the latest installation instructions from your readme.

**Comment by asbiin** [comment]
Thank for your submission.
However, there is not enough information to analyse or reproduce this.
Please submit other information so we can investigate.
