### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by tfont** [monicahq/monica#4712]
Some features that I notice are on app.monicahq.com (v2.19.1)
and not on the self-hosted - downloaded from GitHub (v2.2.1)

- Archive contact
- Profile Star (favorite)
- Documents

What's the deal with that?

**Comment by asbiin** [comment]
To what "GitHub (v2.2.1)" do you refer? Last version is 2.19.1.

**Comment by tfont** [comment]
Following the instructions from here:
https://github.com/monicahq/monica/blob/master/docs/installation/providers/ubuntu.md

It is stated to use "git checkout tags/v2.2.1"
Is this incorrect?

Also considering a reasonable approach to proper semantic or standard software versioning "2.2" is after "2.19" which would state that it is a newer version. However, it is lacking features? Which is correct and incorrect?

**Comment by asbiin** [comment]
@tfont There are 2 ways to find the latest version:
- The version, as you mentioned, follow semantic version standard: here the minor version is either "2" (in "2.2.1"), and "19" (in "2.19.1"), which must be compared as numeric value (yes, 19 is higher than 2 (!))
- The date of the release, you can find here https://github.com/monicahq/monica/releases : 2.19.1 has been released on 2020-09-12, 2.2.1 has been released on 2018-05-31

the "git checkout" instruction is only an example, which has to be adapted to your needs.

**Comment by tfont** [comment]
In this case, please try to keep the docs update or state clearly that the comment version is ONLY an example.
It is after all instructions ;-)

I presume if I update with 2.19 and run migrations everything should be okay...
Thank you for your time.
