### ISSUE TITLE
Heroku Should Be More Descriptive when Throwing Exception for a 33-length key

### ISSUE THREAD

**Issue by yoonsikp** [monicahq/monica#474]
Pretty much the error I got after turning on debug, was saying that the only ciphers available were AES-128... 

Took me a while to figure out that I had a space at the end of my 32-length key.

**Comment by djaiss** [comment]
Sorry you encountered this. I'll change the documentation about it.

**Comment by asbiin** [comment]
Doc is pretty clear now ?

**Comment by djaiss** [comment]
Yes, let's close it.
