### ISSUE TITLE
Setup erroring: php artisan setup:production --email=your@email.com --password=yourpassword -v

### ISSUE THREAD

**Issue by thepra** [monicahq/monica#4740]
Here's what I see:
![immagine](https://user-images.githubusercontent.com/7032509/103156264-4654b880-47a7-11eb-8a44-9439421f01da.png)
and the mysql version:
![immagine](https://user-images.githubusercontent.com/7032509/103156315-bbc08900-47a7-11eb-9eef-ae268571f854.png)

Is there anything wrong with the mysql version?(I did follow all the instructions as [documented](https://github.com/monicahq/monica/blob/master/docs/installation/providers/ubuntu.md))

**Comment by lpdyck** [comment]
This has something to do with the version of mysql packaged in Ubuntu 20.04. If you use Ubuntu 18.04 (the officially supported version), it should work just fine.

**Comment by thepra** [comment]
ok then, I close the issue for lack of support of the Ubuntu OS version, hope one day it will make it.
