### ISSUE TITLE
Create User command for artisan

### ISSUE THREAD

**Issue by lpdyck** [monicahq/monica#4744]
**Is your feature request related to a problem? Please describe.**
I installed an instance of Monica and want to add additional accounts for other family members, but I don't want to open my instance to any person. While the SetupProduction command allows you to create an initial account, there is no easy way to create additional accounts. (See https://github.com/monicahq/monica/issues/4617 for another example of this)

**Describe the solution you'd like**
I would like an artisan command to create a new account easily from the command line.

**Describe alternatives you've considered (optional)**
https://github.com/monicahq/monica/issues/1876 talks about an admin portal, but that's a ways off. We could use the API, but that is rather complicated for an occasional new user.

**Comment by userbradley** [comment]
Hey @lpdyck, you can actually enable signup in the .env file:
```
# Ability to disable signups on your instance.
# Can be true or false. Default to false.
APP_DISABLE_SIGNUP=false

# Enable user email verification.
APP_SIGNUP_DOUBLE_OPTIN=true
```

Simply add their email in to the login page under sign up and you should be good to go.

**Comment by ford-prefect** [comment]
@userbradley the idea I believe is to allow the administrator to add new users without having to open sign up to anybody on the Internet. At least this is what I would like this feature for. :)
