### ISSUE TITLE
Change the license file to add NC clause.

### ISSUE THREAD

**Issue by roidelapluie** [monicahq/monica#477]
Hi,

Github recognizes this project as AGPL-3. It is not the case because the README adds the following:

```
You have the liberty to clone the repository and set it up yourself on any hosting provider, for free. I'm just asking that you don't try to make money out of it yourself.
```

It means that the project is `de facto` not AGPL-3.0. That clause should be added to the LICENSE file for clarification.

**Comment by Phrohdoh** [comment]
Related: #38 and #234

**Comment by djaiss** [comment]
This clause will be removed from the README entirely. It'll be pure AGPL-3.0.
