### ISSUE TITLE
Broken link to Apple Touch icons

### ISSUE THREAD

**Issue by callingmedic911** [monicahq/monica#4799]
**Describe the bug**
Commit: https://github.com/monicahq/monica/commit/755cbfa8dc60cb5817862a2a5e8e90b4861a8c6b added meta for apple touch icons (which looks great on the phone) but the href contains partial path like `touch-icon-iphone.png` instead of `img/icons/touch-icon-iphone.png`, which result in broken functionality.

**Comment by callingmedic911** [comment]
Being worked in https://github.com/monicahq/monica/pull/4798

**Comment by asbiin** [comment]
Fixed in #4798
