### ISSUE TITLE
Change "localhost" domain in links of email notifications

### ISSUE THREAD

**Issue by biomcanic** [monicahq/monica#4816]
Hi! I'd like to know how to change the links in the email notifications. 

Currently they are "localhost" based:

> If you’re having trouble clicking the "See X’s profile" button, copy and paste the URL below into your web browser: https://**localhost**/people/h:KQ93DaXrLNObP7l6EV 

The way I'd need will be:

> If you’re having trouble clicking the "See X’s profile" button, copy and paste the URL below into your web browser: https://**monica.mydomain.com**/people/h:KQ93DaXrLNObP7l6EV

Could it be done via Config Vars in my settings?
I have Monica v2.19.1 installed in Heroku.

Thank you very much in advance!!

**Comment by asbiin** [comment]
You can fix that setting the `APP_URL` environment variable/property
