### ISSUE TITLE
What value to use for HASH_SALT?

### ISSUE THREAD

**Issue by minorsecond** [monicahq/monica#4817]
I'm completing the .env file and am trying to understand what to enter for `HASH_SALT`. The default value is `ChangeMeBy20+KeyLength`. By "key", is it referring to the APP_KEY? Does that mean the default hash_salt length would be 52 characters, and I would simply use the value returned by pwgen -s 52 1? How does the `HASH_LENGTH` variable come into play?

Sorry if this is a simple question. I've searched the web but haven't found an answer for this one.

**Comment by djmattyg007** [comment]
Why did you close this? Did you find the answer?

**Comment by coatmaker618** [comment]
I would also like to know the answer to this!
