### ISSUE TITLE
Adding multiple notes at once

### ISSUE THREAD

**Issue by dancyfits** [monicahq/monica#486]
UX for adding notes, at least for initial comments on a new contact, is weird in that what in the current system should be multiple notes are entered (by people like me) as one note with line breaks.

**Comment by djaiss** [comment]
The UX for adding notes on a contact has changed in 1.3.0. I think it's much better now and kinda solves this issue. Do you agree?

**Comment by dancyfits** [comment]
Oh man, I can't even remember what the old way was like; you've been pushing out updates like crazy!  I think what I had in mind before was when you hit return, it would save the note and start a new one, as opposed to going to the next line in the same note.  But now that I'm looking at it again, I think the vast majority of people would prefer the way it functions now.

Either way, it looks great!  I love the favorite note feature.  Keep up the awesome work!

And I missed the chance to congratulate you on releasing v1.0... Congratulations on 1.4!

**Comment by djaiss** [comment]
> And I missed the chance to congratulate you on releasing v1.0... Congratulations on 1.4!

Thanks :-D v1.5 will be insane.
