### ISSUE TITLE
open_basedir restriction in Vesta CP for File(/tmp/__pragmarx-countries-cache__)

### ISSUE THREAD

**Issue by pankajjha** [monicahq/monica#4860]
**Describe the bug**
I am using self hosted version of monica in a centos vps with vestaCP. When I am trying to upload vCard contacts file it gives me following error
`file_exists(): open_basedir restriction in effect. File(/tmp/__pragmarx-countries-cache__) is not within the allowed path(s): (/home/admin/web/monica.domain.com/public_html:/home/admin/tmp)
`
It is a simple vcf file that I downloaded from google contacts. To fix this issue either I have to change the pragmarx package to change the tmp directory or I have to change vestaCP configuration, Neither of them is a good solution.

**Screenshots**
[Screenshot 1](https://share.getcloudapp.com/llu9J9l0)

**Which version are you using:**
`Release - v2.19.1`

 - Hosting version on https://app.monicahq.com - `Self Hosted`
 - Mobile version - `N/A - Using only web version as of now`
 - A server you maintain yourself (if so, please indicate your current version of Monica) - `Release - v2.19.1`

**Comment by SimonVanacco** [comment]
One of monica's dependancies (Pragmarx Countries) is trying to create a cache directory in the /tmp directory, which seems to be forbidden by your VPS / vestaCP configuration. 

Here's how you can fix it : 
Edit config/countries.php and change line 12 by this:
`
        'directory' => '/home/admin/tmp/__PRAGMARX_COUNTRIES__/cache',
`
If that doesn't work, then you'll need to disable the cache all together :
`
        'enabled' => false, // same file, line 6 :)
`

This is not a "permanent" fix as it will probably break on some future update, but it should keep you up and running while some more permanent solution can be found :)

**Comment by pankajjha** [comment]
Hi, I tried changing directory in the config, cleared the cache as well but that didn't worked. I even set `enabled => false` but that also didn't work.

Do I have to follow any additional steps after changing config and clearing the config cache>

**Comment by SimonVanacco** [comment]
@pankajjha Hi ! I forgot to mention that you should propably clear monica's config cache after your changes by running 
`
php artisan config:clear
php artisan cache:clear
` 
If that still doesn't solve your problem you may have to consider changing your host to something that allows you access to the /tmp folder :)
