### ISSUE TITLE
Unable to create 'gift' when hosted on Heroku, using interface

### ISSUE THREAD

**Issue by njelich** [monicahq/monica#4862]
Opening a new issue since the other one was regarding the problem on api usage.

When attempting to make a new gift using the form, it fails with the error:

Key path "file:///app/storage/oauth-public.key" does not exist or is not readable 

Running php artisan monica:update or setup:production doesn't fix the issue.

**Describe the bug**
A clear and concise description of what the bug is. If your comment is `it doesn't work`, we won't know what to do with it.

**Screenshots**
![Screenshot 2021-02-10 at 14 37 36](https://user-images.githubusercontent.com/12912633/107517060-8df3a000-6bad-11eb-9d1f-551b325eb58c.png)

**Which version are you using:**
 - Hosted on heroku with default settings, latest version. (for some reason it isnt shown in the footer, it just says "Version:" )

**Comment by cmdruid** [comment]
I'm also having this same exact issue on Heroku. Version in footer is also blank for me, but I'm running the latest version (2.19.1 as of posting).

**Comment by danmorin** [comment]
Have you tried the solution outlined here: https://laracasts.com/discuss/channels/laravel/heroku-error-oauth-publickey-doest-not-exist-or-is-not-readable

You need to run php artisan passport:keys on your server. You need to have a private and public key for passport on your server in the storage directory!

It's actually in the documentation: https://laravel.com/docs/6.x/passport#deploying-passport

**Comment by endorama** [comment]
Hello, I'm having the same issue.

Using the console I run the suggested command and I can confirm the files are there with correct permissions:L

```
~ $ ls -alh storage
total 32K
drwx------  6 u46378 dyno 4.0K Apr 27 16:55 .
drwx------ 19 u***** dyno 4.0K Apr 27 16:55 ..
drwx------  3 u***** dyno 4.0K Apr 26 21:55 app
drwx------  2 u***** dyno 4.0K Apr 26 21:55 debugbar
drwx------  6 u***** dyno 4.0K Apr 26 21:55 framework
drwx------  2 u***** dyno 4.0K Apr 27 17:00 logs
-rw-------  1 u***** dyno 3.3K Apr 27 17:01 oauth-private.key
-rw-r--r--  1 u***** dyno  812 Apr 27 17:01 oauth-public.key
~ $ pwd
/app
```

Still I get the same error. I also run `chmod 644 storage/oauth-public.key` for the key to be world readable (as is a public key) but without any positive effect.

Tried logout/login but without luck.
