### ISSUE TITLE
TrueNAS Monica Plugin failing install

### ISSUE THREAD

**Issue by jim9835** [monicahq/monica#4866]
If this isn't the place for this, please direct me to where I can find a solution. Thanks.

Hoping to take a look at Monica I've tried to install it on my NAS Box running TrueNAS-12.0-U1 using one of the community plugins. Unfortunately it's failing. Here is a screenshot of the errors:

![Screenshot_20210214_140344](https://user-images.githubusercontent.com/52280787/107879031-5bf47d80-6ece-11eb-9e1d-2aecb89f5b72.png)

Is there any documentation as to how to get this plugin working?

Thanks.

**Comment by asbiin** [comment]
Hello

I'm not aware of this plugin that we don't maintain.
You will find documentation [here](https://github.com/monicahq/monica/tree/master/docs/installation) about how to install Monica, especially regarding the dependencies and php module that must be installed - it seams that a few are missing.

Thanks!

**Comment by jim9835** [comment]
OK, many thanks for taking the time to respond.
