### ISSUE TITLE
A way to transatively add brother sister relations

### ISSUE THREAD

**Issue by RMHogervorst** [monicahq/monica#4887]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex.
* I'm sometimed frustrated when I add brothers and sisters because I have to add all relationships to all siblings.
* for instance I have 3 brothers, all of them have me as brother, but not each other automatically. I appreciate that there are more complex family structures. I also don't want to make the app more complex. 

**Describe the solution you'd like**
What if you can add a family, where in relationships are all propagated? 
**Describe alternatives you've considered (optional)**
Manual, which is fine.

**Additional context**
Add any other context or screenshots about the feature request here. The more context, the better.

**Comment by asbiin** [comment]
Hello
Thanks for the idea.
I think this has already been issued in some other feature requests:
#1810
#1479
#1327
#1255

**Comment by RMHogervorst** [comment]
You are absolutely right, I must have searched with the wrong terms. I'll close this one
