### ISSUE TITLE
Can't Disable 2FA if Lost Phone

### ISSUE THREAD

**Issue by al3x-huang** [monicahq/monica#4912]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
Currently, if a user has 2FA enabled and loses the security device, they can still log in with a recovery code. However they cannot disable or reset 2FA without an existing 2FA code. In this particular case, if a user no longer possesses the associated security device they will not be able to log into Monica without regenerating new recovery codes.

**Additional context**
I believe a 2FA code should *not* be required to disable 2FA for this use case since to log into the dashboard in the first place, the user already needed to present either a 2FA code or recovery code. Therefore, the disable 2FA button should just work. 

P.S. Are there any workarounds for this currently?

**Comment by al3x-huang** [comment]
Anyone?

**Comment by hrshadhin** [comment]
facing same issue.

**Comment by SimonVanacco** [comment]
Working on it : I'll submit a PR later in the day that should address this :)
