### ISSUE TITLE
What default account to login when install success?

### ISSUE THREAD

**Issue by vanloc0301** [monicahq/monica#493]
When installing Monica success, I can't log in. I found on the database, table `users` and `accounts` don't have any rows.

**Comment by Phrohdoh** [comment]
You have to register an account; there is no default user account.

**Comment by djaiss** [comment]
We could have one. It's the second time the question comes this week.

**Comment by fmcpherson** [comment]
The default .env file has APP_DISABLE_SIGNUP set to true, so a new installation via Docker does not provide a way to register a new user account when you first start up. The comment suggests this should be set to false, so I suspect this is a simple mistake. Changing to false enables the registration link so that one can create an account for themself.

**Comment by OrangeTux** [comment]
The lack of a default account and the default setting to disable sign up was very confusing for me.

**Comment by wagex** [comment]
i changed the line in .env to enable signup and it will not show up on the home page. so i have no way to use this.

**Comment by turbopixel** [comment]
Set `APP_DISABLE_SIGNUP = false` and run `php artisan migrate` in your console.
Now it is possible to register an account. After that, the value can be set to true again.

Install doc: https://github.com/monicahq/monica/blob/master/docs/installation/generic.md

**Comment by yoginth** [comment]
Displaying `Nothing to migrate.`

**Comment by dp87** [comment]
@yoginth No need to run `php artisan migrate` after you have set `APP_DISABLE_SIGNUP = false`, the signup link will appear in the home page as soon as you refresh the page. At least that's what happened in my installation.

**Comment by djaiss** [comment]
#694 will address this issue.

**Comment by asbiin** [comment]
I propose another solution with #902

**Comment by djaiss** [comment]
We've addressed this with #694 as mentioned, so this issue in itself can be closed.
