### ISSUE TITLE
Add gift view does not display

### ISSUE THREAD

**Issue by larsyencken** [monicahq/monica#494]
Within the last week, a release on https://app.monicahq.com/ seemed to break the "Add gift" view.

In particular, the `div` with class `main-content gifts modal` gets style `display: none`. Sometimes it flashes up but it disappears as the page loads.

If I manually edit the CSS and force display of it, then I can add gifts as usual, so nothing else is broken, just the form display for some reason.

**Comment by djaiss** [comment]
@larsyencken damn. Sorry. I'll fix it right away.

**Comment by djaiss** [comment]
This should now be fixed.

**Comment by larsyencken** [comment]
That was super fast, nice work! It works again now for me.
