### ISSUE TITLE
Subscription page seems broken

### ISSUE THREAD

**Issue by RyanKadri** [monicahq/monica#4951]
**Describe the bug**
I have a paid account on Monica. I like the idea of the project and wanted to support it. Unfortunately, my aspirations of being more organized have not totally happened and I'm not using the project enough to justify $90 a year. Unfortunately, when I go to try to cancel, I get an error rendering the page. Also, the contact us link on the homepage doesn't seem to work perfectly if there is not a default mail handling app set up. If I try to copy the address, it looks like there's some JavaScript and encoded characters. Would a normal `mailto:` link work?

**Screenshots**
![monica-subscriptions](https://user-images.githubusercontent.com/5432445/111039528-89b0e180-83fc-11eb-892d-6266a151a3d7.png)

**Server Version**
2.19.1

**Comment by asbiin** [comment]
Hi @RyanKadri that's unfortunate. Can you send us more details to support@monicahq.com ? Thanks
