### ISSUE TITLE
Allow multiple entries for relationship

### ISSUE THREAD

**Issue by lathomas64** [monicahq/monica#497]
Some folks have multiple significant others it would be useful to be able to list them instead of having to just choose one person.

**Comment by djaiss** [comment]
I agree.

**Comment by djaiss** [comment]
Also, the ability to record previous significant others.

**Comment by fabianhjr** [comment]
Hey, I just recently checked the web service and it seems this feature request has hit production. Just wanted to comment it so that you may close the issue and wanted to thank you for working on this awesome FOSS software. C:

**Comment by djaiss** [comment]
@fabianhjr good! I'll close it then!
