### ISSUE TITLE
Files stored in /storage are available without login

### ISSUE THREAD

**Issue by hftl-kalle** [monicahq/monica#498]
As of right now files stored in /storage on .com and self-hosted are available from the outside without login if their names can be guessed.
File names appear to be randomized but this is more a security through obscurity approach which I don't think is a good one.
Try this for example: [link to .com avatar](https://app.monicahq.com/storage/avatars/dLQ0GqAieB0aGrSkkPtEW8QnfbeeRq5etZI29w1Y_110.jpeg)

Is this by design? I am not feeling well with any file or information exposed to the general internet.

**Comment by djaiss** [comment]
Of course it is :-D But it's not what you think.

Storage, in the URL, is not the same as "storage" (the folder). `/storage` is a symlink to the public folder. This is a Laravel thing. Your data is not exposed to the general internet.

**Comment by hftl-kalle** [comment]
Okay, but this still means that any Avatar that is uploaded will be semi public. I consider this bad design and  I do not wish those to be accessible from outside. Of course you would have to know the filename. But still.
Maybe I am too paranoid.

**Comment by djaiss** [comment]
This is the case for Facebook as well, if you know the URLs.

**Comment by djaiss** [comment]
If you deeply care about that, host Monica yourself on a private server outside of the internet, and you are good to go 😄
