### ISSUE TITLE
remove call to https://fonts.googleapis.com

### ISSUE THREAD

**Issue by krswin** [monicahq/monica#5025]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is.
* For privacy reasons its important not to connect internet for any type of requests.
* Monica gets CSS from internet API to get CSS
* https://fonts.googleapis.com/css?family=Open Sans:400,600

**Describe the solution you'd like**
* Please include CSS in the code so no need to connect to internet for any type of requests. 

Thank you for your help.

**Comment by mgrhm** [comment]
I've opened pull #5027 to remove two instances where Google Fonts are called.  These are the only two 'Monica native' occurrences of Google Fonts.

I can see several instances of Google Fonts being called in Laravel and other vendor packages, but I haven't removed those.  I think that they'd need to be removed upstream on the package's master branch then merged into Monica from there.

**Comment by krswin** [comment]
@mgrhm Thanks.

**Comment by asbiin** [comment]
Fixed by #5027
