### ISSUE TITLE
Automatically sending Birthday wishes with a defined template 

### ISSUE THREAD

**Issue by anmol26s** [monicahq/monica#505]
Hi
An option for automatically sending Birthday wishes thorough mail would be a great feature to have.

Thanks

**Comment by djaiss** [comment]
I'm not sure about this feature. The software would risk to become a spamming machine if we allow this to happen - which I don't want to do.

**Comment by anmol26s** [comment]
Ok, I am closing the issue. If this feature is needed in future then it can be reopened.
