### ISSUE TITLE
[app.monikahq.com version] can't create access token?

### ISSUE THREAD

**Issue by DanielDornhardt** [monicahq/monica#5061]
Hi, i tried to create an access token with the paid / monikahq.com - version to access my calendars, but I get errors each time I try to create a token.

I tried in two different browsers, Safari & Brave, both on Mac OS:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/3845924/114521821-1096eb00-9c43-11eb-94c0-ecc66a250c61.png">

**Comment by Turochamp** [comment]
Hi,
Experienced the same this morning. Using Chrome latest version.

![image](https://user-images.githubusercontent.com/24321087/115954895-c0960f00-a4f3-11eb-950c-3b9ab5bdc278.png)

Does anyone know how to find details of the server error?

**Comment by asbiin** [comment]
I have the same error, I'm debugging it, I'll keep you informed.

**Comment by asbiin** [comment]
This is now fixed.
If anyone has the same issue: you have to create a [Personal Access Client](https://laravel.com/docs/8.x/passport#creating-a-personal-access-client)
`php artisan passport:client --personal`
the save the values in `PASSPORT_PERSONAL_ACCESS_CLIENT_ID` and `PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET` in the `.env` file.

The previous values suddenly disappear from our database, which may have cause the issue. It may be related to a Passport update?
Anyway, this is now fixed.
