### ISSUE TITLE
Move to fortrabbit infrastructure

### ISSUE THREAD

**Issue by asbiin** [monicahq/monica#5086]
Some times ago we tried to move to fortrabbit (see #1735).
At the time, fortrabbit database backend was mysql 5.6, and we needed mysql 5.7 at least. Now fortrabbit works with mysql 8.0 👍🏽 

The migration itself will take appr. 1h downtime.
We plan to do that on 1st-2nd of may 2021. More details soon!

----

## Changes in code TBD
- [x] Change config handle for passport
- [x] Adapt cache config for memcache
- [x] Remove unused tables: reminder_sent
- [x] Setup deployment workflow in GitHub

## Preparation
- [x] Add a new app in Fortrabbit
- [x] Setup PHP env
    - activate: redis, igbinary
- [x] Setup ENV variables, secrets variables
- [x] Update configuration scaling
    - PHP s 2
    - Mysql 8.0 m + enable backup
    - Memcache xs
    - Worker m (4 jobs)
- [x] Setup the cron `php artisan schedule:run` this should run every minute
    - After creation, put the cron in pause
- [x] Setup the queue `php artisan queue:work --sleep=10 --timeout=0 --tries=3 --queue=default,migration`
    - After creation, put the cron in pause

## Migration
- [x] Put application on Linode in maintenance
- [x] Backup the current DB
- [x] Restore DB in fortrabbit. See [doc](https://help.fortrabbit.com/mysql)
    - Get mysql password with `ssh app@deploy.us1.frbit.com secrets MYSQL.PASSWORD`
    - Run `ssh -N -L 13306:app.mysql.us1.frbit.com:3306 app@tunnel.us1.frbit.com` on a separate terminal
    - Run `mysql -h127.0.0.1 -P13306 -uapp -p app < dump.sql`
- [x] Update ENV variables
- [x] Deploy the application from GitHub workflow
- [x] Update DNS in Cloudflare
    * See [fortrabbit page about cloudflare](https://help.fortrabbit.com/cloudflare)
- [x] Activate crons
- [x] Enjoy

# Post-migration

- [x] Deactivate papertrail in forge
- [ ] Update privacy policy with new server information

(+30 days later)
- [x] Deprovision Linode
- [x] Cancel [Forge](https://forge.laravel.com)
- [x] Deprovision Ottomatik

**Comment by djaiss** [comment]
The line ` Clean unused table (reminder_sent, ...)`.

I would say `Remove unused tables: reminder_sent`. I don't think there are other tables that we need to clean?

**Comment by djaiss** [comment]
Also, we need to keep backups of the database for 30 days after the migration (according to our privacy policy). THEN we can delete Ottomatik.

**Comment by djaiss** [comment]
Also, there should not be any impact on S3 right?

**Comment by asbiin** [comment]
> Also, there should not be any impact on S3 right?

Exact, there is no impact on S3.

**Comment by asbiin** [comment]
This migration is now complete
