### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by chugamug** [monicahq/monica#5092]
Running: "composer install --no-interaction --no-dev --ignore-platform-reqs" command on ubuntu 18.04/20.10 results with 
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In PackageManifest.php line 120:

  Undefined index: name

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Running composer update results with:
monica@monica:/var/www/monica$ composer update
Cannot create cache directory /home/monica/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/monica/.cache/composer/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pragmarx/google2fa-laravel v0.2.1 requires pragmarx/google2fa ~4.0 -> found pragmarx/google2fa[v4.0.0, v4.0.1, v4.0.2] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - pragmarx/google2fa-laravel v0.2.0 requires laravel/framework >=5.2 -> satisfiable by laravel/framework[v5.6.0, ..., v5.6.40].
    - laravel/framework[v5.6.0, ..., v5.6.40] conflict with roave/security-advisories dev-master.
    - Root composer.json requires pragmarx/google2fa-laravel ^0.2 -> satisfiable by pragmarx/google2fa-laravel[v0.2.0, v0.2.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by TabTwo** [comment]
This also happens during upgrades of course

**Comment by chugamug** [comment]
Resolved the issue by using the latest version. By following the ubuntu guide I was using version 2.2.1 by accident. Also need to add php7.4-redis to the list of module installs.
