### ISSUE TITLE
Feature Request: Add search bar in navigation

### ISSUE THREAD

**Issue by tylerbmcsilva** [monicahq/monica#51]
It would be nice to have the "search" function that is able to pull from all data on Monica

**Comment by djaiss** [comment]
I agree. I'll do that in the future for sure.

**Comment by HHErebus** [comment]
I'd like to have a stab at this if possible. @djaiss are you working on this already?

I think there's a few things open for debate:

1.  **Placement in the UI:** my personal experience with using Monica would put this in the top navigation as @tylerbmcsilva suggested, visible on _all_ pages. I think it's important enough as a quick way to retrieve the information stored in the db to warrant that spot.

2. **Style:** I think the only sensible way to integrate it in the top nav, if we end up deciding that, is to do so like [Laravel's documentation](https://laravel.com/docs/5.4), e.g. an "invisible" input.

3. **Where to search:** I feel like searching on all data by default would be overkill, but I do see how searching tables other than contacts would be useful. I don't have a strong opinion either way so I'm open to guidance on the matter.

This seems like a fairly straightforward feature, so I chose it for my first contribution to Monica. Differing opinions are welcome.

**Comment by djaiss** [comment]
Thanks @HHErebus for your contribution.

I think it'd be a great feature. In terms of design I don't think it should be an invisible field. Check the design idea below.

![artboard 3](https://user-images.githubusercontent.com/61099/28192910-2f0bf842-6807-11e7-8297-3bcc5f80a31a.png)

![artboard 3](https://user-images.githubusercontent.com/61099/28192917-3a4e94b2-6807-11e7-9c30-1edee3b992e0.png)

About searching data themselves, I'd say let's search for contacts first. It'd be like a "quick jump" feature. I think that's the simplest first iteration we can do.

**Comment by HHErebus** [comment]
That's great, many thanks for the quick turnaround :D On mobile, I think I can just put it below the list of nav actions (i.e. it would be the last item in the nav), wdyt?

**Comment by djaiss** [comment]
This is done and in production.
