### ISSUE TITLE
Unable to edit contact's middle name

### ISSUE THREAD

**Issue by pc-zookeeper** [monicahq/monica#511]
I imported data into the Monica application via vCard.  Middle names that were imported are visible in the contact's name, but cannot be edited via the contact editor as there is no field to do so.  Manual editing of the database is currently the only way to modify a contact's middle name.

**Comment by dosch** [comment]
Agree, same behavior here. I now have someone called John John Doe Doe

**Comment by allo-** [comment]
+1 for including a middle name field.
In addition some custom information fields could be added, which could be used for similar cases. An example I could think of would be name,middlename,nickname and in the additional field the name used in religious contexts (which can be quite different).

**Comment by djaiss** [comment]
Alright, let's fix this.

**Comment by jeremies** [comment]
@asbiin, shall we close this issue? or is it not completed?
