### ISSUE TITLE
Error on Import - (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0)

### ISSUE THREAD

**Issue by baldfox** [monicahq/monica#5115]
Exported google contacts (1142) to vcf and imported into Monica, after a minute, I get the following:
![image](https://user-images.githubusercontent.com/32448665/116062131-748acc00-a6a5-11eb-933c-31c89c54ae26.png)

I opened the log file, here's the complete list...
[2021-04-26 04:43:19] local.ERROR: The "--message" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--message\" option does not exist. at /var/www/html/vendor/symfony/console/Input/ArgvInput.php:212)
[stacktrace]
#0 /var/www/html/vendor/symfony/console/Input/ArgvInput.php(140): Symfony\\Component\\Console\\Input\\ArgvInput->addLongOption('message', 'Upgrading Monic...')
#1 /var/www/html/vendor/symfony/console/Input/ArgvInput.php(76): Symfony\\Component\\Console\\Input\\ArgvInput->parseLongOption('--message=Upgra...')
#2 /var/www/html/vendor/symfony/console/Input/Input.php(55): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
#3 /var/www/html/vendor/symfony/console/Command/Command.php(215): Symfony\\Component\\Console\\Input\\Input->bind(Object(Symfony\\Component\\Console\\Input\\InputDefinition))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#5 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\DownCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 {main}
"} 

It shows I have 977 contacts imported.
Any suggestions?

**Comment by asbiin** [comment]
I think it's fixed now
