### ISSUE TITLE
Docker install of Monica can't create Journal entries

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#512]
I have installed a copy of Monica using the Docker instructions and Journal is not working with my installation. After saving a new Journal entry what I am seeing are long strings of jibberish. It is acting as though the Journal entries are being encrypted but not being decrypted for display. However, I do not have an option to edit, just delete.

Related, when I click delete, the message box that displays says "Are you sure you want to delete this gift?"

**Comment by djaiss** [comment]
The current version of Monica that ships in Docker by default is not up to date. You have to update it manually.

**Comment by fmcpherson** [comment]
Thanks, I've built my own image.
