### ISSUE TITLE
Using --no-interaction on setup:production doesn't install anything

### ISSUE THREAD

**Issue by nikolaos-spyratos** [monicahq/monica#5121]
Firstly, thanks for the project! Been keen to try it for quite a while.

**Describe the bug**
I'm making an Ansible role in my project to install Monica. If I run `php artisan setup:production`, it shows a `--no-interaction` flag. Using this however seems to make the command not continue with setup at all.

This is needed for automated setup so that Ansible doesn't hang on the task because of waiting for user input.

**Screenshots**
![image](https://user-images.githubusercontent.com/17888779/116287541-d4aa6c80-a790-11eb-9ba0-f4f1bd852dce.png)
As you can see, it proceeds if just doing `setup:production` but not with `--no-interaction`.
**Which version are you using:**
 - 2.21.0 in a Vagrant VM of an Ubuntu 20 box

**Additional context**
As a workaround, I'm currently doing `yes | php artisan setup:production`

**Comment by asbiin** [comment]
Try adding `--force` so it does skip asking the question "Do you wish to continue".

**Comment by nikolaos-spyratos** [comment]
`--force` does the trick as well, yep.

Is there any way to detect `--no-interaction` as well to behave the same as `--force`? All other artisan commands seem to have it, so could be some quick cleanup.

**Comment by asbiin** [comment]
I think `--no-interaction` do what it's expected: even if an interaction is required (here "Do you wish to continue" question), there is no interaction ever.
The option is by default in Laravel commands.

I will now close this issue, because everything is working as expected.
Don't hesitate to reopen it if you have more information to share.
