### ISSUE TITLE
Option to display date for next "Stay in touch" reminder

### ISSUE THREAD

**Issue by mgrhm** [monicahq/monica#5158]
It would be useful if there was an option to display the date of next reminder.  This could be done one of two ways:

1. Text in brackets next to the reminder:  _"Stay in touch every 40 days (next due 05/05/2021)"_
2. Using the `<abbr>` tag so that you can see it by hovering over the frequency

The first approach is simpler, and works everywhere, but at the expense of a little clutter.  The second approach is neater, but not easily discoverable and useless on mobile.

**Comment by MarkusDick** [comment]
Hi I'll make a PR for this issue. I took the first approach.

@djaiss This includes a little frontend change.
Instead of `Stay in touch every 40 days` it looks like `Stay in touch every 40 days (next due Oct 18, 2021)`.

If there are other ideas - I'm open to other suggestions. 👍
