### ISSUE TITLE
Reminder Emails Not Sent After Clean Install of 3.0.1 on Untouched Ubuntu 18.04

### ISSUE THREAD

**Issue by dgsharpe** [monicahq/monica#5159]
After a clean install, fastidiously following the documentation of the install process, reminder emails are not being sent. However, invite emails do work, and so do test emails sent with `php artisan monica:test-email`

**Reproduction steps**
1. Start with a brand-new installation of Ubuntu Server 18.04 (I'm using an LXC container on Proxmox)
2. Install Monica 3.0.1, f[ollowing the current documentation](https://github.com/monicahq/monica/blob/master/docs/installation/providers/ubuntu.md) exactly. 
3. No changes to the default .env file except for the sections necessary to connect to a Gmail account via SMTP.

**Symptoms**
1. Invite emails do work.
2. Reminder emails are never sent, which I can confirm by logging into the Gmail account configured as the sender.

**Attempted resolution / investigation**

1. I've run the `php artisan setup:production -v` command to make sure that the latest .env parameters are picked up.
2. I've tried to find relevant logs, but have been unsuccessful so far. 
3. I have redirected the cronjob output to a file, and I can see that they are running as expected, with entries like this:

```
No scheduled commands are ready to run.
No scheduled commands are ready to run.
Running scheduled command: '/usr/bin/php7.4' 'artisan' send:reminders >> '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7.4' 'artisan' send:stay_in_touch >> '/dev/null' 2>&1
```

Please let me know what I can look into to help investigate this. Thanks!

**Comment by maik-s** [comment]
@dgsharpe hey why did you close this issue? Did you find a solution and if so can you please share it?

**Comment by dgsharpe** [comment]
> @dgsharpe hey why did you close this issue? Did you find a solution and if so can you please share it?

@maik-s I wish I could give you a more satisfying answer, but here's the truth: I initially experienced this issue using an LXC image of Ubuntu 20.04, not 18.04. I had no problems with the installation process so I thought it should work, but I had the problem described above. Before posting this, I tried again with an 18.04 container, just to rule out the obvious. I expected the emails to be sent at midnight, so when they weren't, I figured I was having the same problem and created this issue. However, later that afternoon, I did receive a reminder email, at which point I closed this ticket.

All I can suggest from my experience is, make sure you're using a clean image of 18.04, make sure your crontab for the www-data user has the cronjob in it, and make sure to run `php artisan setup:production -v` after updating your .env file. Following the documentation exactly, and paying particular attention to those things, worked for me.

**Comment by maik-s** [comment]
@dgsharpe thanks for your quick reply. I was finally able to get reminders working, by including the `supervisord` configuration into the docker-instance [by following this provided example](https://github.com/monicahq/docker/blob/master/.examples/supervisor/fpm/docker-compose.yml)
