### ISSUE TITLE
2 password reset emails are sent - the latter one having an invalid token

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#521]
~I can provide a screenshot later in the day.~
Let me know if the title isn't clear enough, please.

**Comment by djaiss** [comment]
Again, that is weird :-D I will verify it locally because last time I checked, only one email was sent.

**Comment by Phrohdoh** [comment]
![monica_doublepasswordreset_email](https://user-images.githubusercontent.com/4861023/29366488-ca21ef2c-825f-11e7-9eb2-f3bed260bbdb.PNG)

**Comment by Dagolin** [comment]
Hi @Phrohdoh 

Does it still happen? I was not able to reproduce this, I think maybe this has something to do with the old version of Laravel, see https://github.com/laravel/framework/issues/21822,

**Comment by pqhf5kd** [comment]
I'm also unable to reproduce this issue (using the hosted version).

**Comment by djaiss** [comment]
Yep I think it's working fine by now (otherwise I would be bombarded in the support).
