### ISSUE TITLE
Please make the API rate limits configurable

### ISSUE THREAD

**Issue by sid3windr** [monicahq/monica#5213]
I have updated Monica to the latest version and my script using CardDAV no longer works (it retrieves contact data sequentially) because it runs into a 60/minute rate limit.

I understand this is a fair limit for the hosted app, and I can add a sleep command to my own script - however it would be good if the limits were configurable instead of hardcoded in `app/Providers/RouteServiceProvider.php` for my self hosted version.

**Comment by MarkusDick** [comment]
I'm going to work at this problem. I'll make both - the rate limit for the api and for the oauth configurable through the .env file.
