### ISSUE TITLE
Support time for call logs

### ISSUE THREAD

**Issue by waldyrious** [monicahq/monica#523]
I just tried logging a call and looked at the records from my phone to add the precise date and time, but inputting `2017-08-08 12:33` produced an empty page with a red banner on top, saying "Whoops, looks like something went wrong." This led to me to lose the note I had written for the log entry, which I had to retype.

I can see three ways to address this issue:
1) implement validation for the "exact call date" field, to avoid data loss in case the content is in a non-supported format. This should be possible to do on the client-side using [`<input type="date">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date), plus a [validation pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#wikiArticle) for the browsers that [don't implement `type="date"` yet](http://caniuse.com/#feat=input-datetime).
2) Gracefully handle the case when a malformed value is placed in the input (e.g. for clients with JavaScript disabled). One way to do this is to show the same page, with the previously filled information still there, and an informative error message.
3) Actually support exact date and time information for the logs, which obviously would be my preferred option :smile:

**Comment by djaiss** [comment]
@waldyrious thanks. Definitely I need to fix this.

**Comment by djaiss** [comment]
The problem here is that on Chrome, the date HTML5 component is supported, but not on Safari (and I wonder about Firefox). That means on this browser, the user doesn't see the Date component but simply a input field, resulting in error.

What I think we should do
* put 3 dropdowns (month, day, year) instead of the Date component
* do not put a calendar - if we do, it'll take a lot of clicks to browse from 2017 to 1978 for instance)
* in some cases, add two other dropdowns for the hour and minute (calls being a good candidate).

**Comment by waldyrious** [comment]
> on Chrome, the date HTML5 component is supported, but not on Safari (and I wonder about Firefox).

Ah sorry, I used the wrong URL in the third link of my previous comment. I meant to link to http://caniuse.com/#feat=input-datetime, which shows that at the moment both Chrome and Edge support it, and Firefox will support it in upcoming version 57.

In any case, your solution of 3 dropdowns would work well as far as I'm concerned. I'm not sure about a dropdown for the minutes -- 60 entries can be a bit much to scroll through, not to mention it might be desirable to also add seconds data, if available. In that case I would propose a text field with a pattern attribute, which is [well-suported by the evergreen browsers](http://caniuse.com/#feat=input-pattern).

In fact, perhaps also the date field could be more ergonomic (and more consistent) as a text-field with a pattern also. A placeholder text should be enough to make the expected format evident, I think.

**Comment by djaiss** [comment]
This is fixed for a long time now.
