### ISSUE TITLE
The MAC is invalid for 2fa enabled logins

### ISSUE THREAD

**Issue by NoJster** [monicahq/monica#5235]
Dear monicahq team,

I've recently enabled 2fa on a v3.0.1 instance running in docker (Laravel 8.40.0, PHP 8.0.6) and yesterday was, out of the blue, presented with a "The MAC is invalid" error after logging in.

APP_KEY has not been changed in my .env (at least not to the best of my knowledge).

I've recently switched from a v2.19.1 container and, just to make sure, used the APP_KEY from this one as well, but to no avail.

When trying to deactivate 2fa via laravel, it also fails with "The MAC is invalid". 

Any idea on how to remedy this is appreciated!

EDIT: Error log on flare: https://flareapp.io/share/Lm8p4Wjm#F67

**Comment by NoJster** [comment]
Resetting (deleting the google2fa_secret) did the trick for me

`UPDATE users SET `google2fa_secret`=NULL WHERE id=`

**Comment by asbiin** [comment]
This problem is not reproductible

**Comment by venn-xx** [comment]
Hi MonicaHQ team,

This problem is still reproducible. I am running Monica 3.1.3 in Docker, using MariaDB. 

I was also presented with the "Whoops! Something went wrong.\n The MAC is invalid." error message after enabling 2FA. I think this is quite a serious issue as I was completely unable to use Monica and there were no workarounds. 

I was able to use Monica again after following @NoJster's suggested fix of `UPDATE users SET google2fa_secret=NULL WHERE id=x`, thank you.

Could you please consider re-opening this issue @asbiin? It is not obvious that the enablement of 2FA is the cause of this issue, and the fix is rather obscure.

**Comment by 24788329** [comment]
I'm running into "The MAC is invalid" errors as well with Monica in docker-compose.

@vin-cf @NoJster how do I run the `UPDATE users SET google2fa_secret=NULL WHERE id=x` fix and where do I find the user IDs? New to all of this so specific directions are much appreciated. Thanks for your time and patience.

**Comment by NoJster** [comment]
@24788329 my apologies for the late reply!

In my case, I am using a dockerized setup with separate containers for the monica app and the mysql database, thus some of the steps might be different for you.

Once you connect to your database

`mysql -u homestead -p secret`

by default, you need to connect to the right database

`use monica`

and get the ID of the affected user

`SELECT id,first_name,last_name, email,google2fa_secret FROM users`

once you have the id (first column) you can use that with the query I mentioned in https://github.com/monicahq/monica/issues/5235#issuecomment-851333945

HTH!

**Comment by kyleaffolder** [comment]
I can also confirm that this is an issue when self-hosting Monica CRM via Docker Compose. Can get it working with 2FA until I stop the Monica container and restart it. After restart, I receive the same 'MAC is invalid' error.

**Comment by dUc0N** [comment]
Confirming this _incredibly annoying_ issue is still present. Even just a workaround to enable TOTP would be very much appreciated!

**Comment by AdamGaffney96** [comment]
Also confirming this is still an issue as I'm getting the same problem. Also personally struggling to find how to connect to the database at all hosted in a docker container on my Synology NAS so don't know if I can even execute the fix.

**Comment by NoJster** [comment]
@AdamGaffney96 there are different options for connecting to the DB in the docker case. 

1. Connect to the docker container and connect to db from there 
2. Connect to the db from your host

The first doesn't require that you have software packages like mysql installed, hence I chose to describe this one.

1. Start a console/terminal on your Synology
2. execute "docker ps -a" yielding something like this:
![image](https://user-images.githubusercontent.com/91568/216819057-0c1edfc6-2e96-4de3-bab0-e6ec09f2c0ea.png)
3. Look up the container ID (leftmost column) of the mysql container
4. execute "docker exec -it <id of container> /bin/bash", which will open a terminal in the docker container
5. execute "mysql -u monica monica -p" and enter the password that was defined during setup (likely "homestead" or "secret" 
6. then execute the UPDATE command described above

Hope this helps!

**Comment by AdamGaffney96** [comment]
@NoJster That did help a lot thank you! I managed to get in and run the update command, and was even able to import some journal entries I exported from one of my other journal apps I used to use which is nice. It's unfortunate this MAC invalid thing is an issue but it's no big loss to not have 2FA I suppose, I'll just not expose it to the internet.

**Comment by davisdre** [comment]
I'm running into this issue as of this morning after doing a restart of the containers. I'll be giving the suggested query call a go when I get back home. 

My current setup is:
Hardware: Synology NAS
App: Docker (Container Management)
Database: Mariadb (locally hosted, out side of Docker environment)
