### ISSUE TITLE
Seeding currencies should be performed in a seeder.

### ISSUE THREAD

**Issue by aejnsn** [monicahq/monica#526]
I see that currencies are introduced via a JSON file as a migration. This should be refactored into a seeder. Migrations are for controlling the schema, not the data within said schema.

I realize this change would impact the update path, however supporting multiple currencies is something that would likely involve change to any underlying data as well. The update path could be sustained by constructing a console command ran upon updating or having users updating their installation by manually running an ideally separate seeder class (`php artisan db:seed --class=SeedCurrencies`). Moving forward in later versions, that seeder class would be included in the top-level `DatabaseSeeder` class, just like the production block consisting of `ActivityTypesTableSeeder` and `CountriesSeederTable`. This would allow it would be seamless for new installations just as the migrations presently exist.

See merged PR changes here: https://github.com/monicahq/monica/pull/509

**Comment by djaiss** [comment]
I agree that it should be moved to a seeder instead, definitely.
