### ISSUE TITLE
New Docker Instance problem : Whoops! Something went wrong.

### ISSUE THREAD

**Issue by jagadeesh-s2104** [monicahq/monica#5268]
Hello,

I tried using [this](https://pastebin.com/SCPGdyu3) docker compose(copied from the example).

After few minutes when I try to access, I get the below error . I tried it in couple of different machines, same error. 

> "Whoops! Something went wrong. The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths."

This is the [log](https://pastebin.com/x09UgCqE) from the docker.

**Comment by TVqQAAMA** [comment]
Same problem, heroku instance.

**Comment by tresni** [comment]
@jagadeesh-s2104 that key looks like it's base64 encoded.  In that case I believe you need to prepend it with `base64:`

@TVqQAAMA That error generally means that `yarn run production` was not run.  I ran into this myself setting it up on Debian and kicked myself when I realized I'd missed the second half of the instructions for "4" under [Configure Monica](https://github.com/monicahq/monica/blob/master/docs/installation/providers/generic.md#3-configure-monica)

**Comment by jagadeesh-s2104** [comment]
> @jagadeesh-s2104 that key looks like it's base64 encoded. In that case I believe you need to prepend it with `base64:`
 
Thank you!! It's working

**Comment by asbiin** [comment]
Thank you @tresni for the solutions.
