### ISSUE TITLE
Reported a Security Issue in huntr

### ISSUE THREAD

**Issue by B3EF** [monicahq/monica#5270]
https://huntr.dev/bounties/11-other-monicahq/monica/

**Comment by cstrat** [comment]
I just tried this on my hosted instance and opening a private browsing window does not keep the session open unless I login again.

**Comment by B3EF** [comment]
i was reporting the session related issue occurring during change password functionality, its comes under a session fixation bug and its a type of business logic error , usually an application is build to logout all its other instances when the password of a corresponding user at a an open instance is changed. 
;i was testing it on the live [hosted one](app.monicahq.com) 
A video explaining the issue is being updated in my [report](https://huntr.dev/bounties/11-other-monicahq/monica/)
please review and verify the report, this one is  a low hanging common issue ,but chained with some other issues can make it stronger.

**Comment by cstrat** [comment]
I don't think the issue documented is session fixation?
The detail in the CWE write up is much more complex than demonstrated?

Unless I am wrong, you're just saying that changing password doesn't log out all other sessions?

https://security.stackexchange.com/questions/63256/on-password-change-in-a-web-application-should-it-log-out-all-other-sessions
