### ISSUE TITLE
403 when accessing a contact when unlogged

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#532]
Catch the error and display the login form instead.

**Comment by funcoding** [comment]
I am unable to re-produce the error. It is redirecting to login page for me.

**Comment by djaiss** [comment]
@funcoding thanks for helping!

**Comment by grrnikos** [comment]
500 error for me. No redirect.

**Comment by djaiss** [comment]
Same for me. I need to fix this.

**Comment by sylvainmetayer** [comment]
I can't reproduce this bug, I'm redirected to the login page. Maybe it has already been fixed and can be closed ?

**Comment by djaiss** [comment]
@sylvainmetayer thanks. Indeed 😀
