### ISSUE TITLE
Request Portuguese-BR Language

### ISSUE THREAD

**Issue by pedromvf** [monicahq/monica#5331]
Hello!

I want to request a new language in https://www.monicahq.com, Portuguese Brazillian.
Recently I did the translating job in Crowdin:

![image](https://user-images.githubusercontent.com/57451957/124363048-5397a780-dc0f-11eb-8cf4-73b79636557b.png)

Now, how can I set the Portuguese (Brazil) language in my Monica account?

![image](https://user-images.githubusercontent.com/57451957/124363070-73c76680-dc0f-11eb-834d-45384551655a.png)

Thanks!

**Comment by asbiin** [comment]
Hi. It requires some changes.
See https://github.com/monicahq/monica/blob/master/docs/contribute/translate.md#support-a-new-language

**Comment by pedromvf** [comment]
Hi asbiin.
Thank you for your attention.

I'm new on Github (sorry If I didn't the things the right way).
I recently translated Monica to pt-BR (Crowdin) and, today, I've created a new PR.

Thanks

**Comment by pedromvf** [comment]
Alexis, I think it is ok now.
I don't know how to create 1 PR and add 3 files, so I've createdd 1 PR for each file.

The last step (run PHP artisan lang:generate to generate the new JSON file, and run yarn run production to compile the JS with those new strings) I didn't understand. I'm a user of monicahq.com and don't know how to run this code.

Thank you for your patience and attention, Alexis.

**Comment by asbiin** [comment]
@pedromvf ok I've made the required changes in #5333, thank you!

**Comment by asbiin** [comment]
@pedromvf do you agree taht maybe the right english translation for your language should be "Brazilian Portuguese", like in this wikipedia page: https://en.wikipedia.org/wiki/Brazilian_Portuguese ?

**Comment by pedromvf** [comment]
Hi @asbiin! It is ok for me. Brazilian Portuguese is a good one. Thank you very much Alexis
