### ISSUE TITLE
When setting up Monica, sets a default user account

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#534]
... so users can get in right away.

**Comment by skrajewski** [comment]
I think the better option is to provide installation mechanism. It ensures not only a default account but also could setup a database connection, perform migrations and so on.

**Comment by hupili** [comment]
Some projects offer a "sample database" dump so that users not only get in directly but also can play around the features with existing data.

**Comment by djaiss** [comment]
#694 will address this issue.
