### ISSUE TITLE
Add "Got a vaccine" to Health & wellness life events

### ISSUE THREAD

**Issue by jorgeegomez** [monicahq/monica#5347]
Maybe this has been proposed already, or maybe it's been considered and rejected (I couldn't find any discussion or feature request on the subject).

I think Monica should include a "Got a vaccine" in its life events, clearly to celebrate a Covid-19 vaccine application.
(There's a "Went to the dentist" event, which I'm pretty sure is less important in the scale of things).

**Comment by TechRabb1t** [comment]
If there is an implementation of this, I think a much broader approach would be better - like a general health event which you then can edit with the actual details. This would provide more usability and could even help tracking general health of for example older/vulnerable people.

**Comment by djaiss** [comment]
@jorgeegomez you can already add a new kind of life event in https://app.monicahq.com/settings/personalization

What prevents you to achieve what you want here?
