### ISSUE TITLE
Repeated task in home screen

### ISSUE THREAD

**Issue by thanhpd56** [monicahq/monica#5381]
Version 3.1.3
I created a reminder, then in home screen, I see events are repeated.
Please fix, thanks.
![image](https://user-images.githubusercontent.com/3794898/126865038-7c172082-05b5-4731-8020-9d131e286f92.png)

**Comment by thanhpd56** [comment]
Anyone please help.

**Comment by Meuschke23** [comment]
@thanhpd56 Do you have 5 users in your instance? Then it could be the same problem as #1496. 
I have this problem too. **Any help would be appreciated**.

**Comment by thanhpd56** [comment]
@Meuschke23 yes, that's right. @djaiss please help. Thanks.

**Comment by Meuschke23** [comment]
Maybe @asbiin can help too. 
Is there anyone with the same problems? Could it be a configuration issue?

**Comment by Meuschke23** [comment]
We could use a little help here. Is there no one here who is also experiencing this problem? @asbiin  @djaiss  could you help us please?
