### ISSUE TITLE
[Help] Docker compose update

### ISSUE THREAD

**Issue by jagadeesh-s2104** [monicahq/monica#5493]
Hello! 

I mistakenly updated the docker containers. Is there a way to retrieve the data? 

I executed "docker-compose pull && docker-compose up -d" on 3.0.1 version of monica/docker instance. 
I was using [the basic docker compose](https://github.com/monicahq/docker#apache-version).

When I access the Url it is going to register page. 
Is there a way to retrieve the data?

**Comment by asbiin** [comment]
This has been fixed by #5524
