### ISSUE TITLE
Translate to persian language

### ISSUE THREAD

**Issue by amintado** [monicahq/monica#5494]
Hi everyone
I did a lot of searching to find a CMS where we could manage the information of people in need for a charity.
And finally, I think Monica is a good place to start.
I just need to translate this script into Persian.
I try to do this and promote it among Persian speakers.
If any of the Iranian programmers are here, I would be happy to do it together.
Finally, special thanks for making this script.

**Comment by asbiin** [comment]
We already had a request to open Persian language to our translation system (see #4682).
I will just give the same answer:
- Go to Persian in crowdin: https://crowdin.com/project/monicahq/fa#
- Please read first our documentation about translations: https://github.com/monicahq/monica/blob/master/docs/contribute/translate.md
