### ISSUE TITLE
Relax requirement that birth date be after 6/6/1967

### ISSUE THREAD

**Issue by rosstex** [monicahq/monica#55]
Would like to use this for my parents/grandparents, but they're too old for this date. Thanks!

**Comment by ocdtrekkie** [comment]
Duplicate of #16 and should be fixed by https://github.com/monicahq/monica/commit/e9a776ca285f78dadd28e1c2a73a250fc61f03af

**Comment by djaiss** [comment]
This is now fixed and in production. Sorry for the troubles.
