### ISSUE TITLE
Sentry error

### ISSUE THREAD

**Issue by anmol26s** [monicahq/monica#553]
I am unable to update monica. I am getting composer Sentry error.
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'Sentry\SentryLaravel\SentryLaravelServiceProvider' not found
```

**Comment by djaiss** [comment]
Have you run `composer update`?

**Comment by anmol26s** [comment]
Yes and I even tired fresh install.

**Comment by djaiss** [comment]
I think this is solved now with the current version in production.
