### ISSUE TITLE
Multiple readonly birthday reminders after relationship changes

### ISSUE THREAD

**Issue by sid3windr** [monicahq/monica#556]
Somehow one of my contacts ended up as "this person is probably x old" which meant the birthday reminder had a random date for some reason (11-Oct).

I've corrected this by selecting the "I know the exact age of this person" radio button - the correct date was still filled in.

Saved the contact, now there are 2 reminders, both called "Birthday of X", one for 11-Oct, one for the correct date. The old one should be deleted when changing the birthdate.

Related Q: how do I manually delete the wrong one?

**Comment by sid3windr** [comment]
Looks like the issue description is wrong; this problem occurs when you remove a Significant Other from someone, the reminder stays and becomes a birthday reminder for that person. Somehow the description in the UI is "Birthday of X" instead of "Wish happy birthday to Y, X's significant other" as it is shown in the database though.

**Comment by djaiss** [comment]
Oh, that's bad. Let me take a look, sorry for the inconvenience.

**Comment by Dagolin** [comment]
Hi @djaiss @sid3windr 

Thanks for the explanation, I have tried the steps but failed to reproduce the bug, maybe it has been fixed?

**Comment by sid3windr** [comment]
Probably fixed as there were a lot of changes in the meanwhile. Should it resurface I'll reopen.
