### ISSUE TITLE
I’ve written a Debian update script

### ISSUE THREAD

**Issue by mgrhm** [monicahq/monica#5567]
Hi @asbiin.

I’ve written a simple shell script to update my Monica instance on a Debian system.  It’s not sophisticated – it just runs the commands sequentially to bring Monica up to latest.

Is this something you’d be interested in adding to Monica?  It’s *not* anything sophisticated, and isn’t a [DPKG or anything like that](https://github.com/monicahq/monica/issues/5526), but I’m happy to raise a pull and maintain it if it’s useful to have it included.

**Comment by TuringZauber** [comment]
this would be very cool IMO
