### ISSUE TITLE
Provide ability for contacts to be grouped

### ISSUE THREAD

**Issue by ssx** [monicahq/monica#559]
I think this is a key feature for Monica.

I'd like to be able to specify groups of people, such as "Friends", "Colleagues", "Soccer" and "Business".

Is this something that is on the roadmap?

**Comment by djaiss** [comment]
What about tags, a feature that already exists? Isn't it enough?

**Comment by ssx** [comment]
Hi!

I don't seem to have tagging within the version I have, (I'm only a couple of releases out of date) - where does that appear?

**Comment by ssx** [comment]
Ignore that, I'm clearly blind!

That will solve my need, thanks!
