### ISSUE TITLE
Tags not saving...

### ISSUE THREAD

**Issue by souhailmerroun** [monicahq/monica#5611]
Hello,

![image](https://user-images.githubusercontent.com/8895242/137413742-14d2af14-3af6-44bd-992a-c9e5c592b2d1.png)

I'm unable to save tags.

I can pick one and then select it. If i refresh or click close then refresh it doesn't save.

![image](https://user-images.githubusercontent.com/8895242/137413810-08bccc79-786f-4319-9f65-8301bc1198ea.png)

**Comment by asbiin** [comment]
It's working well. You have to hit `Enter` key to save the tag.
Do you have logs (network traces) when you save the tag, or when you select an existing tag?

**Comment by souhailmerroun** [comment]
I think it is because i reached the max size using jawsdb... They don't alert or anything, they simply revoke your rights.

https://stackoverflow.com/questions/40415035/jawsdb-on-heroku-new-database-post-migration-mysql2error-insert-command-de

I'll close the issue.

Thank you @asbiin
