### ISSUE TITLE
Self-hosted site on heroku returns 'Unsupported cipher or incorrect key length' error

### ISSUE THREAD

**Issue by kaust-technovert** [monicahq/monica#5651]
I am a beginner with programming and I have tried to setup monica-hq as a self-hosted site on heroku, following each and every step as listed in your guide.
However, after deploy, I am trying to visit the site but I am getting this error - 

![image](https://user-images.githubusercontent.com/86673833/138749744-5709a261-ea10-4f69-a32c-cb0afa2ca0fa.png)

I am not sure what is causing it and I have tried to debug it with whatever my knowledge. It feels bad that I have come this far with this but stuck here.

Please help me with this issue.
Thanks in advance!

**Comment by ovizii** [comment]
> Okaay nvm, figured it out.
> 
> Turns out running `openssl rand -base64 32` returns a string of length 44
> 
> ![image](https://user-images.githubusercontent.com/86673833/138751337-8399d443-d9e6-4fe3-a8de-dacabef18083.png)
> 
> ![image](https://user-images.githubusercontent.com/86673833/138751399-92008ef2-b0b6-4228-9793-a5cd9f0c75ce.png)
> 
> Changed the APP_KEY to a string of length 32 and it worked! :D

Just wanted to let you know that I wasted hours trying to figure this one out - thank god I found your solution or this would have driven me nuts :-)
