### ISSUE TITLE
Can't update the new settings for .env

### ISSUE THREAD

**Issue by e-edgren** [monicahq/monica#5653]
Hi.

I started my own instance with registration disabled. Now I have enabled registration in the `.env` file, but I don't know how to refresh them so the registration indeed become enabled on my instance.

How can I do this? The installation guide doesn't say anything about this.

**Comment by Mik13** [comment]
Taken from https://github.com/monicahq/monica/blob/master/docs/installation/update.md


> Note: if you have just change some setting in your .env file, as the configuration of the application is cached, any update on the .env file will not be detected after that. You may have to run php artisan config:cache manually after every update of .env file.


Did you do that?

**Comment by e-edgren** [comment]
I thought I did, but I ran it again and it worked! Thanks 🙂
