### ISSUE TITLE
Consider replacing Facebook with generic "social network profile"

### ISSUE THREAD

**Issue by nbaksalyar** [monicahq/monica#566]
Facebook is not that popular in some countries (e.g. [China and Russia](http://vincos.it/wp-content/uploads/2016/02/WMSN0116_1029.png)) and it's possible to set this field to random URLs anyway.

So please consider replacing it with "Social network profile", unless you plan for further integration with FB specifically.

**Comment by djaiss** [comment]
I'm not a fan of Facebook personally. You are right that this could be expanded to reflect the other countries as well.

**Comment by hupili** [comment]
How about allowing a list of "URL" to be associated with one profile. We can infer which social network it is by looking at the domains. Besides social network links, I also keep notes of personal homepage. The unified schema works.

**Comment by sid3windr** [comment]
+1 for list of URLs, maybe with "type" dropdown (like in your contacts for phone you can add "work", "mobile", ...) - would fix a separate question I had about adding someone 's "blog" url.

**Comment by djaiss** [comment]
This has been done in 1.2.0 with the new Contact fields and contact field types 😀
