### ISSUE TITLE
Cannot log in with admin@admin.com

### ISSUE THREAD

**Issue by rimu** [monicahq/monica#5663]
On a fresh install of v3.3.1 I cannot log in with admin@admin.com using password 'admin'.

Please advise the correct password.

**Comment by asbiin** [comment]
On a fresh installation on a **production** environment, there is no default login, just create your first account.

On a **test** environment, you can run `php artisan setup:test` to create an `admin@admin.com` with `admin0` password, see [this doc](https://github.com/monicahq/monica/blob/master/docs/contribute/readme.md).

**Comment by rimu** [comment]
Thanks. I was following the instructions at https://github.com/monicahq/monica/blob/master/docs/installation/providers/generic.md which is for production environments.
