### ISSUE TITLE
New release isn't on Docker Hub

### ISSUE THREAD

**Issue by JonTheNiceGuy** [monicahq/monica#5671]
I have an issue with Monica in 3.3.1, but I saw this morning that 3.4.0 has been released that (apparently) fixes my issue.

I performed `docker-compose pull ; docker-compose up -d` but I'm still running 3.3.1.

Checking Docker Hub shows that the latest is 3.3.1.

![image](https://user-images.githubusercontent.com/228671/139662053-ad90dd95-0933-4fdf-a2db-7415cfa4f986.png)

Is there somewhere else I should be looking for this? I did wonder (given the github actions) if the Github Packages were enabled for the account, but the latest one there is from 2019

![image](https://user-images.githubusercontent.com/228671/139662989-600bffc2-366e-45a5-a262-b8484e9bdbf2.png)

**Comment by asbiin** [comment]
official docker images follows another workflow. The new version will be there soon ...
