### ISSUE TITLE
Contacts not appearing after CardDAV sync (AddressBookSubscription)

### ISSUE THREAD

**Issue by Zegorax** [monicahq/monica#5675]
**Describe the bug**
When adding an AddressBookSubscription, the subscription is added successfully and the contacts are synced. (In the audit log, they appear, and it is possible to click on it and see the contact details)
However, the system considers that there is no contacts at all. (Onboarding screen asking to add a first contact, impossible to search for a contact, impossible to select myself as a contact)

**Screenshots**
![image](https://user-images.githubusercontent.com/20574959/139815852-7516e0e1-0568-4635-b28b-b4050beae829.png)
![image](https://user-images.githubusercontent.com/20574959/139815966-498328ce-1e34-496f-bb62-543ae1ab8323.png)

**Which version are you using:**
 - A server you maintain yourself, Docker image (v3.4.0)

**Comment by oliverjhyde** [comment]
I think this is probably related to #5521

**Comment by Zegorax** [comment]
@oliverjhyde I don't think so. The current address book is synced correctly, however, the frontend doesn't display it (or the backend doesn't send the contact data)

**Comment by Zegorax** [comment]
Looping in @ribounette

**Comment by oliverjhyde** [comment]
Exactly the frontend doesn't yet display the new addressbook, listed as the first limitation in #3851 and #5521 will be the fix

**Comment by Zegorax** [comment]
@oliverjhyde Okay got it, I didn't think that "second adressbook" meant the subscription.

**Comment by asbiin** [comment]
The implementation isn't finished yet.
Thank you for testing the synchronization!

**Comment by Zegorax** [comment]
@asbiin I'm looking forward of this task so much. It's the only thing preventing me from using Monica 😄
