### ISSUE TITLE
Non-binary Gender

### ISSUE THREAD

**Issue by finsqm** [monicahq/monica#5725]
Currently, you only have `no gender`, `rather not say`, `man` and `woman` as your gender options. Could you add `non-binary` to this list? I personally would be more likely to use Monica if this was a feature.

There's a great blog post from Ruth Ng on the subject here, although more focused asking for personal data: https://www.ruth-ng.co.uk/how-to-ask-about-gender-in-forms-respectfully

**Comment by jacobm001** [comment]
You can add additional gender types by going to _Settings_ > _Personalization_. _Gender types_ is the top option.

**Comment by finsqm** [comment]
Amazing, thanks
