### ISSUE TITLE
I often know the exact birthdate, but not the year

### ISSUE THREAD

**Issue by rickpastoor** [monicahq/monica#573]
The title says it all. I don't want to enter an approx number of years or guess the year, because I'll forget that and I then will proceed to congratulate the person with the wrong number of years :)

**Comment by djaiss** [comment]
Good one 😀 We'll do it.

**Comment by Silveress** [comment]
I just came here to say the same thing, started using a selfhosted  version yesterday and it already came up (a lot of birthdays around me lately)

**Comment by sid3windr** [comment]
Heh, also had this one on my "list of things to request". So +1.

**Comment by ghewgill** [comment]
Duplicate of #75.

**Comment by djaiss** [comment]
You have a good eye @ghewgill  😀
