### ISSUE TITLE
api key seems to expire randomly

### ISSUE THREAD

**Issue by kavemang** [monicahq/monica#5740]
Hi folks, I have monica in a docker container that syncs to my phone via DAVx5, for the most part it all works fine, but I find that every week or so the API key seems to expire or just stop functioning and DAVx5 reports inability to connect 

I end up going and making a new API key, setting that as the password on the DAVx5 side and it kicks back in and works fine for a week or two, any idea what is causing this?

**Comment by dotcs** [comment]
You can see the expiry date of an API key when hovering the entry on the page `/settings/api`. Does the date that is mentioned there align with the expiry date? If not this is probably a bug.

In my instance those keys are valid for a year which I guess is the default setting.

![screenshot_2021-12-30_00-45-12_021901201](https://user-images.githubusercontent.com/3976183/147711519-a7f40097-9c9e-4b9e-9695-ceb6b5af0a50.png)

**Comment by kavemang** [comment]
I confirmed theyre always 1 year into the future, they still fail somewhat randomly

**Comment by asbiin** [comment]
We currently rely on Laravel Passport to create tokens. They have a 1-year expiration date. Nothing random here.
See https://laravel.com/docs/8.x/passport#token-lifetimes

**Comment by kavemang** [comment]
> We currently rely on Laravel Passport to create tokens. They have a 1-year expiration date. Nothing random here. See https://laravel.com/docs/8.x/passport#token-lifetimes

@asbiin  I opened this issue because despite the token saying it expires in ~1 year it stops working after a somewhat random interval of a few hours to a few days. When I create a new API and put it into DAVx5 it begins working again for a while. What kind of logs can I dig up to help with this?

**Comment by FranPregernik** [comment]
I have a similar issue. Not random but on ever docker-compose up

Steps to reproduce:
* start docker image
* generate api key
* setup davx with said key and verify successfully synced
* docker-compose stop monica
* docker-compose up - d
* login to monica, check key is present
* go to davx and do sync - error authentication failed (check login credentials)
* generate new api key, enter into davx - syncs successfully

**Comment by kavemang** [comment]
> I have a similar issue. Not random but on every docker-compose up
> 
> Steps to reproduce:
> 
> * start docker image
> * generate api key
> * setup davx with said key and verify successfully synced
> * `docker-compose stop monica`
> * `docker-compose up -d`
> * login to monica, check key is present
> * go to davx and sync - error authentication failed (check login credentials)
> * generate new api key, enter into davx - syncs successfully

in my case now monica has also lost formatting and all the page content is showing up as text with no GUI, I have archived my sql db until there is a more stable docker solution :(

**Comment by kavemang** [comment]
@asbiin can this be reopened since we have another user? ^ or is it expected to need to replace API key on container rebuilds? in that case we should probably adjust watchtower settings

**Comment by kavemang** [comment]
@FranPregernik In the meantime I've set the label "com.centurylinklabs.watchtower.enable" as false on the monica container to avoid api cutting out due to replacement, no more phone notices from davx5 that way, just going to manually update monica once a year or so unless this gets patched somehow
