### ISSUE TITLE
Photos uploaded with wrong permissions

### ISSUE THREAD

**Issue by basteyy** [monicahq/monica#5752]
## Environments:
* Ubuntu 20,04.3
* PHP8
* Monica 3.5.0 (fresh installation)
* web server runs as user (instead of www-data as sysusr)

## Problem:
When I upload a photo to a contact, the file is stored with wrong file permissions. I already changed everything regarding uploading to public.

### Expected Behaviour
Upload the photo with correct filepermissions and make it available for the group r-r-

### Observed behaviour
Upload the photo to the correct location but with only file permissions r--

## Quick fix:
I modified the upload-service https://github.com/monicahq/monica/blob/223fbed0a8826206f45a33f200d9a4894c4af3ac/app/Services/Account/Photo/UploadPhoto.php#L151

```php
    private function storeImage(string $disk, $image, string $filename): ?string
    {
        $result = Storage::disk($disk)
            ->put($path = $filename, (string) $image->stream(), config('filesystems.default_visibility'));

        if($result) {
            chmod($path, 0644);
        }

        return $result ? $path : null;
    }
```

Now it works.

**Comment by asbiin** [comment]
File upload is a Laravel feature, and there is no permission setting. In fact, we need to keep write permissions to eventually delete the files.
