### ISSUE TITLE
WebDAV into Nextcloud

### ISSUE THREAD

**Issue by endo34** [monicahq/monica#5753]
I am trying to pull Monica calendars into Nextcloud and can't seem to make it work. Nextcloud's format to import WebDAV calendars is: 

> username@password:service-url

Because Monica's login ID is an email address, I have two ampersand (@), one in the log-in ID (email address) and the separator to the password, which is causing Nextcloud confusion.

Anyone making this work?

**Comment by asbiin** [comment]
This is not possible.
It's either on Nextcloud side, which does not accept authentication for calendar imports, or Monica which should provide public ics calendar, see #2891
