### ISSUE TITLE
Notes can not be deleted on mobile

### ISSUE THREAD

**Issue by Brice187** [monicahq/monica#5754]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
Notes can not be deleted on mobile devices.
There is no button

**Screenshots**
If you can, add screenshots to help explain your problem. An image is always helpful.

**Which version are you using:**
 - A server you maintain yourself (if so, please indicate your current version of Monica)
 Current latest version

**Additional context**

**Comment by asbiin** [comment]
Please add more details in the content of the issue.
