### ISSUE TITLE
Issues Updating from v2.20.0 to v3.5.0 on Windows 10

### ISSUE THREAD

**Issue by zeezhao** [monicahq/monica#5767]
I have been running a local version of v2.20.0 on a Windows 10 machine for a while.

After checking out the latest version from git and then run: composer install --no-interaction --no-dev

I get the error:

```
> App\Helpers\ComposerScripts::preInstall
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.


  [ErrorException]
  Illegal offset type


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...


```

I have updated composer and it says on 2.1.14.

Please has anyone got any idea on how to fix? Thanks for you help

edit:
I should add that I have been able to upgrade numerous times in the past on versions 2.* without any issues.
So it may be related to 3.*....

**Comment by asbiin** [comment]
try remove `vendor` folder, and reinstall dependencies.

**Comment by zeezhao** [comment]
Thanks for the suggestion. Now works!
