### ISSUE TITLE
Bug: When a phone is set, if I update the profile the phone is lost

### ISSUE THREAD

**Issue by yeltsinseal** [monicahq/monica#579]
I have imported a few contacts and I just found a bug. I'm using monicahq.com not the self-hosted version.

If the contact has a phone number associated if I edit the profile, the phone is auto-removed.

**Comment by sid3windr** [comment]
I had the same problem (it's been there since at least mid August!) but was still investigating - due to holidays I didn't get around to it. It does look like I've lost (from Monica, luckily not completely) a few phone numbers due to this...

**Comment by sManWorks** [comment]
not sure why this was closed. The issue still exists on the hosted version

**Comment by djaiss** [comment]
This was closed automatically when the PR was merged.
This PR is now part of the released version 0.7.1 which can be downloaded.
