### ISSUE TITLE
Readme: "Create 2 databases: monica and monica_test" is vague

### ISSUE THREAD

**Issue by jappareti** [monicahq/monica#58]
"Create 2 databases: monica and monica_test" in the Readme is vague. Which commands do you run? `php artisan make:migration monica` and `php artisan make:migration monica_test` ?

**Comment by BranTurner** [comment]
If you create two databases in the engine of your choosing (Postgres, MySQL) and add the details of both to the .env file created in step 2, when you run `php artisan migrate` both databases will be populated with the correct tables. Hope this helps!

**Comment by djaiss** [comment]
@jappareti as @BranTurner said, unless you need to actually contribute to the project (which would require you to actually test your code after), you don't need to even setup the test database.

When you run `php artisan migrate`, only the main DB will be migrated, not the test database. You need to explicitely use `php artisan migrate --database testing` to run the migrations on the test DB.

I've updated the README to make this a bit better (https://github.com/monicahq/monica/commit/ecdc5f92dc908ed6f863f2d62605433ae9c351ad).

**Comment by tetov** [comment]
@djaiss Maybe add some quick notes like
```mysql
$ mysql
> CREATE DATABASE monica
```

?

**Comment by Nebucatnetzer** [comment]
It should probably be more generic because the command mysql needs to get executed with root rights on most Linux distributions.
