### ISSUE TITLE
[Heroku] Difficulty setting up Mailgun

### ISSUE THREAD

**Issue by vjFaLk** [monicahq/monica#580]
I created a new domain at mailgun, set up the DNS and made it active, changed the config in Heroku settings for the app, and I still can't get the emails to work. Am I missing anything? 

Sorry if this isn't the right place for troubleshooting.

**Comment by djaiss** [comment]
I suggest you take a look at https://laravel.com/docs/5.4/mail#driver-prerequisites

Maybe that might help?

**Comment by djaiss** [comment]
Is that solved now? I'll close the issue, let me know if there is other problems.
