### ISSUE TITLE
after following guide to deploy to Heroku, app load just shows "Whoops! Something went wrong. Version string '' does not follow SemVer semantics"

### ISSUE THREAD

**Issue by acgourley** [monicahq/monica#5816]
When I deploy, the resulting page will show: 

```
Whoops! Something went wrong.
Version string '' does not follow SemVer semantics
```

The deploy logs have an error which seems relevant: 

```
Error calling "https://version.monicahq.com/ping": HTTP request returned status code 422:
{"error":{"message":["The version field is required."],"error_code":32}}
```

Let me know if build logs or deploy logs would help. I've tried deploying three times.

**Comment by breakzplatform** [comment]
just got the same error here. Monica was working fine before te update

<img width="1320" alt="Screen Shot 2022-01-02 at 23 09 40" src="https://user-images.githubusercontent.com/597126/147895565-6b37cb18-1002-496e-9172-38d3d4f53399.png">

**Comment by jcat59** [comment]
same
