### ISSUE TITLE
Modals text is blurry

### ISSUE THREAD

**Issue by jtagcat** [monicahq/monica#5817]
![image](https://user-images.githubusercontent.com/38327267/147783397-03d70703-8664-4f1f-8b9c-ceb2dcee9382.png)

lmk if I can provide anything

**Comment by asbiin** [comment]
I don't understand the problem here?

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/148872801-00f64595-e16c-4fae-9fa4-b2474755ddc7.png)

Added another screenshot to compare. The text 'We can remind you...' is literally like out of focus, blurry, while the 'Product Changes' (dashboard) and 'First name' (settings) is not.

**Comment by jtagcat** [comment]
At 300% zoom, it is no longer significantly blurry:
![image](https://user-images.githubusercontent.com/38327267/148872926-5946a514-7267-4d6b-ac02-30810cf64626.png)

At 80% zoom, it seems it is intensified:
![image](https://user-images.githubusercontent.com/38327267/148873017-87be47c2-3380-416e-a4ae-e23c3ce05913.png)
