### ISSUE TITLE
How to use Personal Access Token?

### ISSUE THREAD

**Issue by k3davis** [monicahq/monica#5818]
I created a free hosted account for testing purposes (after Heroku deployment failed in the same way as #5816). I created an access token, but don't know how to use it, eg. from Postman. What's it for or how does it work? It's not listed under the section for authentication options in the API documentation > Overview, nor could I find any other reference to it.

I tried sending it as the value of a Basic Authorization token header but that didn't seem to have any effect.

I assume OAuth2 tokens are preferred for prod, perhaps they are required all the time, but it makes me wonder what the personal access token is for, if so. Thanks.

**Comment by asbiin** [comment]
You have to use it as a Bearer header authentication.
See https://www.monicahq.com/api#oauth-2-token-sent-in-a-header
