### ISSUE TITLE
Sync with CardDAV

### ISSUE THREAD

**Issue by andreasjacobsen93** [monicahq/monica#582]
It would be a nice feature if it was possible to sync the contacts with a CardDAV,
so contacts are imported automatically from the server and updated on changes.

**Comment by djaiss** [comment]
I can't agree more. After the API, this is what's coming next. But the work is gigantic to make it work :-D

**Comment by tlwt** [comment]
Same here, but I would be worried about clients messing up my data. I used to keep the birthdays in my contacts and they got screwed up probably by time zone changes etc. and I ended up calling people on wrong dates (never really chased down where this came from). 

So it would be great to either track changes, keep versions or make (some) data read only.

**Comment by jkbecker** [comment]
This would be an absolute killer feature :+1: 

I agree with @tlwt, being able to make data read only would be neat.

**Comment by kidk** [comment]
@asbiin Are you working on this at the moment? I'm looking at http://sabre.io to use as a library, but don't want to do double work.

My goals would be to allow read/only access to the Monica Contacts through CardDAV and to have calendar setup with CalDAV for reminders and tasks.

**Comment by djaiss** [comment]
Indeed. We do have a basic support which has to be considered alpha at this point, but it's working. We'll document how it works soon.
