### ISSUE TITLE
Dazed and Confused on Dockerized DB connection

### ISSUE THREAD

**Issue by mfabache** [monicahq/monica#5841]
Hello!

1. Im attempting to install/run monicaHQ in a Docker container.
2. I'm attempting to have that monicaHQ docker container use ANOTHER docker container that houses the database (mariadb) as its (monicahq) db.

My question is, can someone help me understand the plumbing between the two?

I read the examples and when starting the install, my monicahq docker fails to install due to a bunch of monicahq install errors as this:

<snip>
_Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 34 | stdout
Waiting for database to settle...
MySQL Connection Error: (2002) Connection refused_
</snip>

OBVIOUSLY, something is wrong with my .env or docker_compose.

Here are the naughty bits in the .env:
DB_CONNECTION=mysql
#DB_HOST=127.0.0.1
DB_HOST=0.0.0.0 # I tried both 127.0.0.1 and 0.0.0.0.  Netstat reports my mariadb port (6666) listening on 0.0.0.0
#DB_PORT=3306 # I tried 3306 as well for giggles
DB_PORT=6666 
#You can use mysql unix socket if available, it overrides DB_HOST and DB_PORT values.
#DB_UNIX_SOCKET=/var/run/mysqld/mysqld.sock
DB_DATABASE=monicahq
DB_USERNAME=monica
DB_PASSWORD=monica

I'm not sure how to implement the docker-compose,  The example seems to use a host mysql (not container) - would it make a difference?  Perhaps I don't understand how to get the naughty bit of what the connection needs for the mariadb container?

I know the mariadb container works (see below)

<snip>
_# sudo docker exec -it mariadb.Docker bash
Password: 
root@7ab6d7480fea:/# mysql -u monica -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 11
Server version: 10.6.5-MariaDB-1:10.6.5+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| monicahq           |
+--------------------+
2 rows in set (0.001 sec)

MariaDB [(none)]> use monicahq
Database changed
MariaDB [monicahq]> show tables;
Empty set (0.000 sec)_
</snip>

Thanks for reading and trying!

**Comment by kurumushi** [comment]
Your db host needs to be the name of the container, and both containers need to be on the same network within docker. So if your mariadb container is called "mariadb" your DB_HOST should be "mariadb" And the port should be whatever port the database is running on inside the container, not the exposed port. So most likely this is 3306.

**Comment by asbiin** [comment]
Please have a look at https://github.com/monicahq/docker/blob/master/.examples/simple/apache/docker-compose.yml

**Comment by mfabache** [comment]
Thanks for the assist and we got further, just not complete.

Quick rant.  I was using the help guide [here](https://registry.hub.docker.com/_/monica/).  I would be cautious to others cutting and pasting.  I was struggling with compose formatting errors.

Thanks to @asbiin who pointed me to the proper example with proper formating.

Ok, where we are is that I followed the link from @asbiin.  I configured the yml to have my container info, but it does not seem to be taking.

After the 'docker-compose up -d' is completed, I see two new docker containers:
monica_app_1 (monica)
monica_db_1 (mariadb:latest)

Am I supposed to have two (new) monica containers?  Why wouldn't my already pre-setup existing docker (mariadb) be used as I setup the ?correct? 'environment:' and 'db:'?

Here is the setup, why are they not being used?
_Note: I'm using DB_HOST as recommended by @kurumushi (mariadb.Docker) is my container name for the mariadb datase container I want to use.
All containers are on the same network_

`   depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - APP_KEY=<hide>
      - DB_HOST=mariadb.Docker
      - DB_USERNAME=monica
      - DB_PASSWORD=monica
...
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=monica
`
Something squirrely about my lack of understanding of all the misdirection (images, db_host, etc?)

**Comment by mfabache** [comment]
This is still not resolved.  Not sure why it was 'CLOSED' so early.  

Contemplating starting a new thread or giving up.

**Comment by kurumushi** [comment]
>After the 'docker-compose up -d' is completed, I see two new docker containers:
>monica_app_1 (monica)
>monica_db_1 (mariadb:latest)

Most likely you changed the name of the container (or didn't specify one to begin with) in your docker-compose, but did not tell docker-compose to remove old containers. try running docker-compose up -d --remove-orphans. and also set a container name for each of your containers.

And I'm assuming the reason the issue was closed as it's not really a monica issue, but more of an issue with understanding how docker and docker-compose work.

**Comment by mfabache** [comment]
Thanks for the tip.  You are correct, I am not a docker pro (and less of a compose newbie)

And you raise a fair point, a docker issue.  Yet, I have looked at much Monica documentation.  Either I’ve missed the correct ‘how-to’ or my setup is too complicated.

In summary: I’m just trying to run a Monica instance with the db portion in an already established mariadb container.

I did what you said and now get the following error(s):

——

~/scripts/monicahq$ sudo docker-compose up -d --remove-orphans
Password: 
Creating monicahq_db_1 ... done
Recreating monicahq_app_1 ... error

ERROR: for monicahq_app_1  Cannot create container for service app: Conflict. The container name "/mariadb.Docker" is already in use by container "7ab6d7480fea881e78186a69ab65a35d802dc0518c17a7e958011ad0a420ecfd". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for app  Cannot create container for service app: Conflict. The container name "/mariadb.Docker" is already in use by container "7ab6d7480fea881e78186a69ab65a35d802dc0518c17a7e958011ad0a420ecfd". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

——

Shouldn’t the container I specified be used?
Why is the message about ‘… remove (or rename)’, when I am trying to do just that, use a pre-existing container?  Surely, I cannot be the only one to attempt this, or screw up the config…?

Here is my yml:

version: "3.4"

services:
  app:
    image: monica:latest
    depends_on:
      - db
    container_name: mariadb.Docker
    ports:
      - 8087:80
    environment:
      - APP_KEY=<secret>
      - APP_DEBUG=true
      - DB_HOST=mariadb.Docker
      - DB_USERNAME=monica
      - DB_PASSWORD=<secret>
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monicahq
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=<secret>
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mariadb

Michael
P.S. likely an issue with ports, but can troubleshoot once I get past the critical errors.

**Comment by kurumushi** [comment]
That error would seem to  mean that you create the other servers either not using compose, or using compose in a different location... I'm not really sure how docker-compose decides if a container belongs to the current stack, or another. Either way, just stop all the other containers and remove them. "docker stop <id>; docker rm <id>" You can see the list of containers by running "docker ps"

Here is my docker compose file for monica, since I'm set up using an existing DB as well. Hope this helps:

```
version: '3.7'

services:

  monica:
    image: monica
    container_name: monica
    depends_on:
      - mariadb
    environment:
      - APP_URL=https://monica.(REDACTED).com
      - DB_USE_UTF8MB4=true
      - APP_ENV=production
      - DB_HOST=mariadb
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=(REDACTED)
      - APP_DISABLE_SIGNUP=true
    volumes:
      - /var/docker_data/monica:/var/www/html/storage
    restart: unless-stopped

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      - PUID=99
      - PGID=100
    volumes:
      - /var/docker_data/mariadb:/config

```

**Comment by mfabache** [comment]
Hi @kurumushi - its been a while.

I gave up on getting Monica working.  Its seems you either have to be a semi expert on docker compose or run the vanilla setup.

I'm not either.

But, after a break, I thought I would try again.
I took your yml and changed to my environment.
I now get the below error message:

> sudo docker-compose up -d
Password: 
Creating network "monicahq_default" with the default driver
Creating mariadb.Docker ... error

> ERROR: for mariadb.Docker  Cannot create container for service mariadb.Docker: Conflict. The container name "/mariadb.Docker" is already in use by container "7ab6d7480fea881e78186a69ab65a35d802dc0518c17a7e958011ad0a420affe". You have to remove (or rename) that container to be able to reuse that name.

I hear what you say about:
>That error would seem to mean that you create the other servers either not using compose

Yes, that is true.  My Docker setup is on my NAS, it has docker and I use it to run/manage my databases (plus other Docker containers)

Your advice is if I move those containers from my NAS Docker managment to my linux/server Docker management for docker-compose, all *should* work?

This has become an effort of ramping up my docker-compose limited knowledge to offset the lack of monica documentation to support such a configuration for Monica.

I may look to port out all my NAS Docker containers to the server level and just use docker-compose to run all.  I just need to contemplate if monica is worth it or not.

Thanks for the help.

**Comment by mfabache** [comment]
Final? update:

I wanted to thank @kurumushi for insight into docker-composer.  It got me on the right track to complete this monica install.

I finally got it working.

In the end, it was an excerise in docker-composer, although it seems the monicahq docker install is pretty lite.  Anything behind a vanilla install, one will have to know docker-composer at a mid level.  Again, for non-vanilla installs of monicahq or pretty much everything.  I now  know docker compose from starting a db with init scripts, to setting up networking, etc. 

It was a while, but only could work on in short time allotments.  Again, thanks to @kurumushi 

Best,
MIchael
