### ISSUE TITLE
Amazon AWS S3 storage - exposed to public?? Anyone can access our Monica data?

### ISSUE THREAD

**Issue by jcat59** [monicahq/monica#5846]
### Discussed in https://github.com/monicahq/monica/discussions/5845

The instructions to link Monica to Amazon AWS storage, indicate that you should leave the settings to 'allow public access', which from what I understand literally means that anyone (in the world) can access it. Am I missing something, why would anyone want their Monica data to be publicly accessible?

Unless I'm missing something, can you please advise how to revert back to no longer use this storage? Would it just be changing the 'DEFAULT_FILESYSTEM' variable from S3 to ???

For now I shut down access on AWS so it wasn't public anymore. As background - I followed the below instructions to set up external storage with Amazon AWS.
https://github.com/monicahq/monica/blob/master/docs/installation/storage.md

@asbiin  can you please offer any advice or help?

**Comment by asbiin** [comment]
Thank you for your concern.
Some month ago I made a PR to fix that, so the public access to S3 is not needed anymore.
So to reassure you: **data on app.monicahq.com s3 bucket are not public anymore**

You can now set the privacy of the bucket to `private`, and it will work.
However, if for any reason you still want to use a public bucket, you can set `FILESYSTEM_DEFAULT_VISIBILITY` environment variable to `public` (default value is `private`).

The documentation is not up to date, I'll update it.

**Comment by jcat59** [comment]
Thanks for your reply. Unfortunately it does not work when I block all public access on the S3 bucket. See attached photo, there are 4 options around this. Is there one I should uncheck so that it still works? What is missing in the instructions?


![56F5A605-3541-47B8-89BE-EB7BA22F1830](https://user-images.githubusercontent.com/34663690/148650091-1b8b4f90-0ead-44ae-b573-3363b84e6956.jpeg)

**Comment by asbiin** [comment]
This is odd. There is nothing more todo, we have the exact same config on app.monicahq.com bucket.
Did you set `FILESYSTEM_DEFAULT_VISIBILITY` environment variable?
What a tipical avater url looks like?
It should be something like `https://app.monicahq.com/store/photos/[randomid].jpeg`

**Comment by jcat59** [comment]
URL looks like this https://monicaxxx.herokuapp.com/store/avatars/random.jpg?1641567654

I did not have the FILESYSTEM_DEFAULT_VISIBILITY variable set, didn’t see it in the instructions. I just added the variable though, and no difference after a restart. I tried a value of private and then blank.  I still get an access error denied for AWS. 

Any ideas? Any other variables missing in instructions. I would really like to get this going.  If nothing else, can you tell me how to revert the storage changes? Would it be setting this variable as blank instead of S3? DEFAULT_FILESYSTEM

**Comment by asbiin** [comment]
@jcat59 exactly, you need to setup S3, by setting `DEFAULT_FILESYSTEM` to `s3`, and other variables.
See https://github.com/monicahq/monica/blob/master/docs/installation/storage.md

**Comment by jcat59** [comment]
> @jcat59 exactly, you need to setup S3, by setting `DEFAULT_FILESYSTEM` to `s3`, and other variables. See https://github.com/monicahq/monica/blob/master/docs/installation/storage.md#3-set-environment-variables

@asbiin Perhaps I'm not explaining myself well. The instructions DO NOT work unless you expose the s3 bucket to Public access (which the instructions tell you to do). I already set all the variables mentioned including DEFAULT_FILESYSTEM to s3.  It does not work unless you set the bucket to public access.

My 2st question, is what needs to change to make this work? Do you know? You said you were going to update the instructions.

My 2nd question is, if you don't know how to fix this, how do I revert back to using the default filesystem instead of S3?

**Comment by asbiin** [comment]
@jcat59 the documentation is now up to date.

> Seems like all data on the app.monicahq.com s3 bucket must be public

Again, that's not true. Our bucket is in private mode, you cannot get files directly.

**Comment by asbiin** [comment]
@jcat59 is your heroku instance up to date with the latest monica sources?

**Comment by jcat59** [comment]
> @jcat59 is your heroku instance up to date with the latest monica sources?

Hi @asbiin -- I'm currently running v3.5.0 - I just tried an update** to v3.6.0 and am unfortunately getting the below error. When I run git pull, it says already updated. Any suggestions?

hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**update instructions -- https://github.com/monicahq/monica/blob/master/docs/installation/update.md#updating-heroku-instance

**Comment by jcat59** [comment]
Disregard - I'm just going to try and reinstall

**Comment by jcat59** [comment]
Confirmed working after reinstall - thanks again @asbiin
