### ISSUE TITLE
After docker install getting "fatal: Not a git repository" in logs

### ISSUE THREAD

**Issue by timjrobinson** [monicahq/monica#589]
I went through the monica docker setup guide building the docker image myself with `docker-compose build` then `docker-compose up`. After setup I saw the following error message appear whenever I visited the `/dashboard` page. 

```
fatal: Not a git repository (or any of the parent directories): .git
```

This error also appears in /var/log/apache2/error.log inside the monica docker container. 

I fixed it by ssh'ing into the monica container and setting up git in /var/www/monica with:

```
/var/www/monica # git init
/var/www/monica # git remote add origin https://github.com/monicahq/monica.git
/var/www/monica # git reset --hard origin/master
```

This stopped the error from appearing, but I'm not sure where it was coming from in the first place. Is Monica inside the docker container supposed to be a git repository? Or is this some bug where the code assumes it's a git clone but that's not true when doing the docker setup so it freaks out?

**Comment by kofiav** [comment]
Encountering the same issue, tried doing what @timjrobinson did, but now my dashboard does not work.

**Comment by timjrobinson** [comment]
My dashboard isn't working at the moment either :/

**Comment by RogerSik** [comment]
Removing .git from .dockerignore and then rebuilding the image fixed this error for me.

**Comment by djaiss** [comment]
Was this solved?

**Comment by mgolisch** [comment]
works for me without that error.
probably due to #650 
the artisan commands seem to expect a git reposiroty there

**Comment by asbiin** [comment]
Linked to #872, but it's just a warning message, app is running well.
