### ISSUE TITLE
Feature request: Ability to select Contact categories using a dropdown menu or auto-completion

### ISSUE THREAD

**Issue by msaharia** [monicahq/monica#590]
Current implementation makes it difficult to attach categories.

**Comment by djaiss** [comment]
I agree. Thanks for this idea.

**Comment by djaiss** [comment]
I actually don't understand the issue.

**Comment by msaharia** [comment]
@djaiss I mean I want to be able to select a certain category(ies) for a user using a dropdown menu of all previously used categories. Right now, I have type in the category.

**Comment by Aeolun** [comment]
You are talking about the tags I think. And yeah, that's indeed an issue. It would be nice if the tag box showed a dropdown of the existing ones when you focus it.

**Comment by asbiin** [comment]
See #449

**Comment by djaiss** [comment]
@asbiin selectize.js is jQuery based. Can we find a Vue alternative? Here is a list of [awesome Vue components](https://github.com/vuejs/awesome-vue).

**Comment by djaiss** [comment]
Tags are now autocomplete.
