### ISSUE TITLE
Person detail page cannot be opened: getShortDateWithTime(): Argument #1 ($date) must be of type Carbon\Carbon

### ISSUE THREAD

**Issue by justsomebody42** [monicahq/monica#5931]
**Describe the bug**
When I try to open a person detail page, I get the following error:
`App\Helpers\DateHelper::getShortDateWithTime(): Argument #1 ($date) must be of type Carbon\Carbon, null given, called in /var/www/html/storage/framework/views/21e290f401118f0566ba0c35c78250149146efdd.php on line 53 (View: /var/www/html/resources/views/people/profile.blade.php)`

This only happens for some persons.
I have tried to open quite a few and it seems to affect persons that have not been created recently, but are present in the DB for a while already.
So it may be related to the recent update to 3.6.1?

**Which version are you using:**
Version 3.6.1, running in a Docker container

**Comment by justsomebody42** [comment]
It seems to be caused by
`title="{{ $weather->location }} &mdash; {{ \App\Helpers\DateHelper::getShortDateWithTime($weather->date) }}">`

Disabling the weather functionality or removing `&mdash; {{ \App\Helpers\DateHelper::getShortDateWithTime($weather->date) }}` from `profile.blade.php` did not help, though.

**Comment by JDetmar** [comment]
I have this same issue. Also running Docker container.
I was able to restore the ability to view my records again after doing the following.
1) Disabled weather
2) Deleted all entries from the monica.weather table.

I'm unsure if this is a okay solution long term but I'm okay with it for now.

**Comment by justsomebody42** [comment]
I just tried after truncating the weather table, but unfortunately still have the same issue.
To disable the weather functionality, I set `ENABLE_WEATHER=false` and removed the `DARKSKY_API_KEY` variable from the docker-compose file.
Is there anything else you did?

**Comment by JDetmar** [comment]
I set
```
ENABLE_WEATHER=false
ENABLE_GEOLOCATION=false
```
I later re-enabled geolocation.
That's it, I am using docker and running v3.6.1

**Comment by justsomebody42** [comment]
Great. I truncated the weather table in the wrong database...
Now it's working again. (weather disabled).

**Comment by asbiin** [comment]
Actually it's already fixed by #5914
I'll create a new release ASAP.

**Comment by justsomebody42** [comment]
Thanks a lot!!

**Comment by asbiin** [comment]
Actually ... it's not fixed :( I'm on it

**Comment by asbiin** [comment]
OK after some checks, it *was* fixed by #5901 (but the fix was not deployed...)
