### ISSUE TITLE
snyk protect : Could not load policy.

### ISSUE THREAD

**Issue by secnum** [monicahq/monica#5934]
**Describe the bug**
After `yarn install` :

yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.17
$ snyk protect
**Could not load policy. Try running snyk wizard to define a Snyk protect policy**
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Which version are you using:**
 - A server you maintain yourself : v3.6.1

**Additional context**
Fresh installation

**Comment by asbiin** [comment]
I can't reproduce it.
