### ISSUE TITLE
Contacts number translation

### ISSUE THREAD

**Issue by davidoskky** [monicahq/monica#5935]
**Describe the bug**
Setting the UI language to some languages, the number of contacts in the contacts page stops being displayed and other strings are displayed.

e.g. 
Italian: :conta contatti
Swedish: kontakter

**Screenshots**
![immagine](https://user-images.githubusercontent.com/13107368/151217071-ef39ad66-62c2-4383-a7d5-c52dd061a308.png)

**Which version are you using:**
 - A server you maintain yourself 3.6.1

**Comment by asbiin** [comment]
It has been fixed
