### ISSUE TITLE
Unable to add life event without specifying a day and month

### ISSUE THREAD

**Issue by filcuk** [monicahq/monica#5936]
**Describe the bug**
When adding life event without specified month and day of the event, the confirmation `Life event was added` pops ups, but the event is in fact not added.
No error shows up in either Monica or database logs.
No 'POST' event in Monica logs, which would normally show up upon successful creation.

**Screenshots**
This does not work:
![image](https://user-images.githubusercontent.com/1339532/151347982-1e7f1ef0-6b48-4765-bcbf-d4d1f21263e5.png)

This doesn't work either:
![image](https://user-images.githubusercontent.com/1339532/151347885-5b990b34-43e1-4262-b0c1-c651a43c5239.png)

This works perfectly fine:
![image](https://user-images.githubusercontent.com/1339532/151348038-c655afd5-a32d-4c13-b2ae-64c005607514.png)

**Which version are you using:**
 - Self-hosted Docker Monica v3.6.1

**Comment by filcuk** [comment]
I've just also noticed upon failing to add the event, URL adds fragment `#lifeEventundefined`, thought I don't suppose that's unexpected.

**Comment by ChristophQu** [comment]
Error also in the Hosting version on https://app.monicahq.com
