### ISSUE TITLE
Problem with migration

### ISSUE THREAD

**Issue by LongDuongBIT** [monicahq/monica#594]
Congratulations for your great work!
I'm very impressed with this repo, but I just found out a bug with one of migration files.
In class `ChangeStringToBooleanForReminders.php`, it should be:

```
Schema::table('reminders', function ($table) {
            $table->boolean('is_a_birthday')->after('is_birthday');
        });
```
Not like this: 
```
Schema::table('reminders', function ($table) {
            $table->boolean('is_a_birthday')->after('is_birthday')->nullable();
        });
```

Because when I run "php artisan migrate", there was an error with default value of "is_a_birthday", I have to change it like above.
I hope you'll review and fix it soon :)

**Comment by djaiss** [comment]
I don't understand why this boolean should be set to null. Have you been able to install Monica? I'll close the issue, let me know if i should reopen it.
