### ISSUE TITLE
[Feature request] Suggestion and autofilling of premade tags.

### ISSUE THREAD

**Issue by Halkx** [monicahq/monica#598]
Suggestion and autofilling of premade tags.

This would save a lot of time.  What I mean is that when you start typing a tag, you get a suggestion from the tags you have already saved.  This would reduce mistyped duplicates and so on and shorten the time when contacts have multiple tags.

**Comment by djaiss** [comment]
Will be addressed here https://github.com/monicahq/monica/pull/1995
