### ISSUE TITLE
Swiftmailer is EOL, look into replacing it

### ISSUE THREAD

**Issue by samip5** [monicahq/monica#5983]
**Describe the bug**

Your app seems to be using Swiftmailer which is EOL, it's development stopped last year.

**Additional context**

More information: https://symfony.com/blog/the-end-of-swiftmailer & https://github.com/swiftmailer/swiftmailer

**Comment by asbiin** [comment]
`swiftmailer/swiftmailer` is a dependency of Laravel 8.x, there nothing we can do until we can upgrade to Laravel 9.
