### ISSUE TITLE
Can not add  Life events with only Year and Month

### ISSUE THREAD

**Issue by ChristophQu** [monicahq/monica#6001]
**Describe the bug**
I try to add the " Life event" "Expects a baby" without a day (---), Monica sasy in green it is added but it is not there. A event with year, month and day works fine.

**Screenshots**
I  think no Screenshot is nedded.

**Which version are you using:**
 - Version: 3.7.0 hosted on uberspace.de

**Comment by filcuk** [comment]
See #5936, this issue was already on v3.6.1 (not sure if any earlier too).

**Comment by ChristophQu** [comment]
Duplicate of #5936
