### ISSUE TITLE
Date entry for birthday should be easier and error should tell the user what went wrong

### ISSUE THREAD

**Issue by jonnycyr** [monicahq/monica#601]
I just started using the application, so I'm not sure if this issue is present in all date entries or just for birthdays. 

When entering in a date for <Person_Name> => Edit Contact Information, under the heading "I know the exact birthdate of this person, which is" if you enter in a date in the wrong format - i.e. instead of YEAR-MONTH-DAY with YEAR-DAY-MONTH then the error page:

**Whoops, looks like something went wrong.**

appears. I think that this error should tell the user that they are entering in the date wrong.

In addition, I think it should be easier to enter in a date. It might be worth it to switch over to a date picker, like here: https://jqueryui.com/datepicker/

I also might take this on myself, I program in PHP all the time but I've never used Laravel. I've created a Rails app before, so I imagine the learning curve might not be too high for me.

**Comment by djaiss** [comment]
This is because we are using the default HTML5 datepicker. Since v1.4.0 we've started to get rid off this datepicker in some places, and we'll get rid of it entirely in the future. Thanks for reporting this!

**Comment by djaiss** [comment]
This has been solved as now we are using another component to select a date.
