### ISSUE TITLE
Feature request: settings to make Monday the first day of the week.

### ISSUE THREAD

**Issue by martinpospech** [monicahq/monica#602]
First day of the week should be configurable, right now, it's hardcoded that weeks begin with a Sunday.
This makes the date selection weird for users from cultures where weeks start with a Monday (or another day).

**Comment by TheGP** [comment]
That will be great! And dates format is weird too.

**Comment by degan6** [comment]
Do you know where the start of the week is hard coded?

**Comment by djaiss** [comment]
@degan6 I think it's on the input date selector (the HTML5 component) (for instance when you add a reminder). As far as I know it's not possible to indicate the start of the week when we use the native HTML5 date picker.

**Comment by asbiin** [comment]
Currently, the first day of the week depends on the locale, and it's automatically handle by vuejs-datepicker component.
