### ISSUE TITLE
Adding Task on contact disappears on page refresh.

### ISSUE THREAD

**Issue by reraxe** [monicahq/monica#6023]
**Describe the bug**
I have created Tasks on various contacts. When I click on Tasks on Dashboard and click on a contact name for the tasks, the list of tasks does not show. When you add a task and refresh page on a contact, the task disappears.

**Which version are you using:**
 - v3.7.0
 - Docker Image

**Comment by SimonVanacco** [comment]
Hi ! 
I've reproduced your issue and submitted a PR to fix the issue in the upcoming release.
