### ISSUE TITLE
monica-docker "Whoops, looks like something went wrong."

### ISSUE THREAD

**Issue by pixelyo** [monicahq/monica#603]
i tried installing monica, following the [instructions](https://github.com/monicahq/monica/blob/master/docs/installation/docker.md). when registering an account I get [this message](https://i.imgur.com/MiNxY14.png) in my web browser. The registration seemed to work since i could login into my monica instance. when navigation to the dashboard after the creation of a contact, i get the same error as above.

If it helps: here are my [docker logs](https://pastebin.com/raw/VQ9r7KEt)

**Comment by chuckbutler** [comment]
Duplicated by #596
