### ISSUE TITLE
Phone field does not persist through edits

### ISSUE THREAD

**Issue by chuckbutler** [monicahq/monica#604]
Monica version: 0.6.5

Add a user, fill out their contact detail.  The phone # will be displayed on the overview and things appear fine.

Re-enter the edit screen and notice that the phone field did not populate.

If the user saves the entry without re-entering the phone# its wiped off of the contact record.

**Comment by sid3windr** [comment]
Looks like dupe of #579 :)

**Comment by chuckbutler** [comment]
Nice find :+1:
