### ISSUE TITLE
Do I need to find APP_KEY if I want to reuse the data?

### ISSUE THREAD

**Issue by puppylpg** [monicahq/monica#6050]
Hello, I deploy monica the first time using https://github.com/monicahq/monica/blob/main/docs/installation/providers/docker.md，without docker volume, and didn't set `APP_KEY` environment cause this doc doesn't mention it.

Today I want to redeploy monica with docker volume to persist mysql data, so I copy all the data from the first mysql container to a newly created volume, which goes as what I expected. However, when running new mysql container using the volume with the old data, the container fails and restarts again and again(using docker-compose.yml restart policy).

So is the data encrypted with `APP_KEY`? 'cause the second time i set a new `APP_KEY` manually in docker-compose.yml as said in https://github.com/monicahq/docker, and it fails to use old mysql data.

In my opinion, I think the reason is that `APP_KEY` differs between this two deployment so the mysql data can not be resused. Is that true? And how can I find back `APP_KEY` in the first deployment since I never set it... Does it have a default value? I don't find any clue in the code.

Any advice would be appreciated! Thanks~

**Comment by djaiss** [comment]
`APP_KEY` is only used by Laravel itself to generate the CRSF token used on form submission and sessions. `APP_KEY` does not have a default value. It is set once the docker image is set up. It's sorted in the .env file.

**Comment by puppylpg** [comment]
Gotcha. Thanks.

Any suggestions to export or migrate the mysql data from my docker container first deployed to the second docker? I tried the 'export' function in monica but failed as said in #5917 , so a I wonder whether there is a raw data migration process.

Thanks for your dedicated work and suggestions again~

**Comment by djaiss** [comment]
The best would be to log into your primary database in Docker, dump the database, and feed the other one.
