### ISSUE TITLE
Does the node-ipc malware affect Monica?

### ISSUE THREAD

**Issue by mgrhm** [monicahq/monica#6062]
The author of `node-ipc` has added [region-specific malware](https://arstechnica.com/information-technology/2022/03/sabotage-code-added-to-popular-npm-package-wiped-files-in-russia-and-belarus/) to ‘his’ code that attacks the machines of users in Russia and Belarus.

It appears that `vuejs`, which Monica uses, may be compromised by this malware:

> As a dependency, node-ipc is automatically downloaded and incorporated into other libraries, **including ones like Vue.js CLI**, which has more than 1 million weekly downloads.

(Emphasis mine.)

Is Monica affected by this malware attack?

**Comment by particleflux** [comment]
There is no package `node-ipc` in _yarn.lock_, and `yarn audit` does not show an issue with this lib either - so I'd say no, at least not on current HEAD.

**Comment by djaiss** [comment]
I don't think it's affected.
