### ISSUE TITLE
Create and update activities API don't work

### ISSUE THREAD

**Issue by arantespp** [monicahq/monica#6064]
**Describe the bug**

I'm working on activities API, and I can't create and update them. I follow the [documentation on the website](https://www.monicahq.com/api/activities), but I always get the error below, even though I send `summary,` `happened_at,` and `contacts` fields.

```js
{
  error: {
    message: [
      'The summary field is required.',
      'The happened at field is required.',
      'The contacts field is required.'
    ],
    error_code: 32
  }
}
```

The code, in Node.js I use to create is:

```js
fetch(`${process.env.MONICA_ENDPOINT}/api/activities`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.MONICA_API_KEY}`,
      ContentType: 'application/json',
    },
    body: JSON.stringify({
        activity_type_id: 1,
        summary: '2022-03-19',
        description: 'some description',
        happened_at: '2022-03-19',
        contacts: [ 2 ],
    }),
})
```

Am I missing something?

Request to GET all activities or contact activities works.

Thank you.

**Comment by arantespp** [comment]
It is related to #2398.

It worked when I changed `ContentType` to `Content-Type` on headers.

**Comment by particleflux** [comment]
`Content-Type` is the correct, standardized, header - `ContentType` does not exist.

Does the documentation use that somewhere?

**Comment by arantespp** [comment]
No, it was my mistake. The documentation is correct.
