### ISSUE TITLE
First update : Monica:update artisan command doesn't exist

### ISSUE THREAD

**Issue by MounirDrioua** [monicahq/monica#607]
This is the first time i try to update my monica instance since i first installed it Localy july/02, the first prefered step according to the doc is to run **php artisan monica:update** but when i do i get this 
 
```
[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "monica:update" is not defined.
  Did you mean one of these?
      monica:calculatestatistics
      monica:resetdb
      monica:sendnotifications
```

I fetched into the Repo and haven't found this Command in the consol, what should i do ?

**Comment by djaiss** [comment]
@MounirDrioua sorry about that.

It appears the doc is not exact. I have to change it.

You can do `php artisan migrate` to run all the migrations, but **make sure you backup your database first**, because version 0.6.0 changes a lot of things in the DB.

That's all you should do in theory.

**Comment by djaiss** [comment]
https://github.com/monicahq/monica/pull/694 fixes this. Sorry about it.
