### ISSUE TITLE
no encryption key after install

### ISSUE THREAD

**Issue by FN-Florian** [monicahq/monica#6088]
Hi
I did the installation and then when I call it I get this error during the installation there was no error message.

No application encryption key has been specified.

Best regards
Florian

**Comment by helloworld0123** [comment]
Hi @FN-Florian,

you have to run` php artisan key:generate` command

See #3: [https://github.com/monicahq/monica/blob/main/docs/installation/providers/generic.md#3-configure-monica](https://github.com/monicahq/monica/blob/main/docs/installation/providers/generic.md#3-configure-monica)

**Comment by FN-Florian** [comment]
I have run the command but still get the same error message.

` php artisan key:generate
Application key set successfully.`

**Comment by asbiin** [comment]
See this chapter: https://github.com/monicahq/monica/blob/main/docs/installation/providers/generic.md#7-optional-setup-the-access-tokens-to-use-the-api

```
php artisan passport:keys
php artisan passport:client --personal --no-interaction
```
