### ISSUE TITLE
Change phone number format to support E.164

### ISSUE THREAD

**Issue by andy47** [monicahq/monica#61]
At the moment you can only enter numeric digits for a phone number. I like to be able to store phone numbers in E.164 format - https://en.wikipedia.org/wiki/E.164 - as they are more interchangeable.

This allows us to specify phone numbers like:

* +1 555 274 3212
* +44 207 427 0010
* +61 412 072460

**Comment by djaiss** [comment]
Thanks for raising this issue.

I think https://github.com/monicahq/monica/pull/65 pretty much covers it at the moment.
