### ISSUE TITLE
Add note button vanishes when clicking escape key

### ISSUE THREAD

**Issue by ChargingBulle** [monicahq/monica#6173]
**Describe the bug**
When looking at a contact (`/people/`) there's a window to add remarks and notes about the person:
![image](https://user-images.githubusercontent.com/6533815/171221926-da28d5af-e82e-47dd-8751-879db936d900.png) (german screenshot)

The button "Hinzufügen" (add) and "Abbrechen" (cancel) appear once having browsed to the textbox.

**Bug** pressing escape (ESC) key both buttons disappear, resulting in the inability to save the note.
Return and Ctrl+Return don't allow saving.
Reloading the page and entering the note again (while avoiding the escape key) works.

**Screenshots**
![image](https://user-images.githubusercontent.com/6533815/171222708-322a895b-8fc9-4fbc-b36c-cd9c69921443.png) -> ESC ->  ![image](https://user-images.githubusercontent.com/6533815/171222987-af038b7c-e678-4c20-9e68-9d71ccf05d31.png)

I've searched the bug tracker for the bug but I was unable to find a duplicate. Perhaps the wording of the other bug is different in a way in which I was unable to find the issue.

**Which version are you using:**
 - version `3.7.0` @ A server you maintain yourself
 - `Firefox 91.9.0esr (64-bit)`
 - `Linux [...] 5.17.0-1-amd64 #1 SMP PREEMPT Debian 5.17.3-1 (2022-04-18) x86_64 GNU/Linux`

**Comment by particleflux** [comment]
Clicking somewhere else and re-focusing the input also helps.
