### ISSUE TITLE
Code quality needs to be improved

### ISSUE THREAD

**Issue by cloud-arrow** [monicahq/monica#6176]
Code quality needs to be improved

Please raise the level of phpstan.neon to max

thank you.
<img width="1806" alt="截屏2022-06-02 14 35 50" src="https://user-images.githubusercontent.com/52516729/171568088-6b0dbe29-79a1-4c21-bb22-ab2c5f65a8f1.png">

**Comment by boehs** [comment]
Could you do this and submit a PR if it is bothering you?

**Comment by djaiss** [comment]
Lol.

I concur with @boehs . If it's bothering you so much, please submit a PR and have fun dealing with the max level of phpstan. A nightmare, really, to make tests pass.

**Comment by boehs** [comment]
![image](https://user-images.githubusercontent.com/51836263/172913494-1d269c22-7030-409e-aea5-fddfec898ccb.png)
