### ISSUE TITLE
Feedback from user

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#62]
Timezone: it shouldn't default to UTC -05:00. Maybe guess based on
user location?

Gender: it shouldn't default to man. I don't want my contacts to be
men by default (it should probably be an option field).

In a contact page, in "PERSONAL INFORMATION": I can see that
"Birthdate is not set." However, the edit button is easy to miss.

"Edit personal information": Why does the country default to US?

* Is there a way to enter the birthdate without the year. I sometimes
know when someone's birthday is, but remembering the year is more
difficult.

* Apparently, the format for birthdate is MM/DD/YYYY. This is very
confusing for me and there's no indication in the UI. Ideally, there
should be an option in the settings + the format description in the
page.

* In the main page, "Latest actions" shows the date as: YYYY-MM-DD. This
is not consistent with the birthdate.

* FOOD PREFERENCIES: I instinctively entered one information per line.
Line returns are not shown in the profile page.

* Debts: Why is it in dollars? I don't use dollars.

* Journal: it's not clear why I'd want to use it. It doesn't seem
related to contact management. Maybe there should be a way to link a
story with people. Then, show the story on the person's page?

* The Kid/Significant other feature doesn't seem useful, because they
are not treated as real people. Treat them as real people, and add
link information (I think it's
https://github.com/monicahq/monica/issues/19).

* I've checked the French version, it looks like half of the text is
still in English.

**Comment by Nebucatnetzer** [comment]
The gender issue is probably this one:
- https://github.com/monicahq/monica/issues/25

The birthday problem has an issue here:
- https://github.com/monicahq/monica/issues/75

The date format issue:
- https://github.com/monicahq/monica/issues/102

The journal issue:
- https://github.com/monicahq/monica/issues/27
However this one is probably a bit of a bigger topic

I'll create issues for the topics which currently don't have one.

**Comment by Nebucatnetzer** [comment]
I don't understand this two points:

> In a contact page, in "PERSONAL INFORMATION": I can see that
"Birthdate is not set." However, the edit button is easy to miss.

> "Edit personal information": Why does the country default to US?

wrong timezone:
#271

inconsisten date format:
#272

currency issue:
#259 

food preferences:
#273

translation here:
#274

**Comment by djaiss** [comment]
Thanks @Nebucatnetzer that helps!
