### ISSUE TITLE
Connection for seeding testing db fails if DB PORT is not 3306

### ISSUE THREAD

**Issue by aleksasaric** [monicahq/monica#6200]
For developers forking and installing projects locally, if database connection port is not 3306, there is an Illuminate\Database\QueryException thrown on command php artisan migrate --database testing.

<img width="882" alt="Screenshot 2022-06-26 at 21 04 11" src="https://user-images.githubusercontent.com/42605072/175830015-e4042a85-e09c-4d29-82a4-ee9ba161d951.png">

**Comment by particleflux** [comment]
Indeed, the `testing` db config seems to be missing a functionality to set the port via `.env`.

https://github.com/monicahq/monica/blob/7c8105c338e4c1f9a3111c2e22b5974cd13e0736/config/database.php#L99-L111

https://github.com/monicahq/monica/blob/7c8105c338e4c1f9a3111c2e22b5974cd13e0736/.env.example#L43-L46

Probably a rather easy fix
