### ISSUE TITLE
Creating activity with multiple contacts returns to last person added to activity upon save

### ISSUE THREAD

**Issue by hftl-kalle** [monicahq/monica#622]
As the title states upon saving an activity you are returned to the contact page of the person that was last added to that activity. I think it would be more appropriate to return to the contact page from which the add activity was initiated.

**Comment by djaiss** [comment]
Yep @hftl-kalle this is definitely a small issue that we need to solve.

**Comment by acharron** [comment]
Looking for issues to participate with what I can in the project, so I ended up here. It seems like the issue has been fixed, but not closed yet.

@djaiss Could you confirm the status? 
(Very new here, but so far an awesome job, and a very useful project! Thanks)

**Comment by erdmenchen** [comment]
@djaiss  this can be closed.
