### ISSUE TITLE
Conflicting paid plan features.

### ISSUE THREAD

**Issue by aericson** [monicahq/monica#623]
The README lists Email reminders as in the free plan. The website lists it in the paid plan https://monicahq.com/pricing.

**Comment by djaiss** [comment]
@aericson you are right. I'm going to update the README to change this - it's going to be modified very soon.

I want this project to become successful in terms of revenues so I can work on it full time. Therefore I'm trying different business models to see what's working. Obviously, while I'd love to have everything free, how would I be able to live from it if that'd be the case, unless I resell data or puts ads (both options are unacceptable to me)? Therefore, while downloading the project on your own server is free of charge, I have to have some kind of ways to make money.

Thanks for noticing this issue in the README though.

**Comment by aericson** [comment]
You are completely right! I hope you find a model that works. Just wanted to point out the difference to avoid confusion.

@djaiss 
Since you mentioned the subscription consider offering a way to pay for longer time upfront ie: 6 months or 1 year with a discount, like many services do. Might help you with some security and revenue to focus on the project.

**Comment by aericson** [comment]
Interesting answers about value of annual subscriptions: https://www.quora.com/Why-do-subscription-services-offer-discounts-if-you-pay-annually-instead-of-monthly-What-do-they-gain-from-that
