### ISSUE TITLE
Edit address link from google maps to OpenStreetMaps

### ISSUE THREAD

**Issue by trvrcr** [monicahq/monica#6269]
As you are creating an Open source project.
It might be interesting to link to another project instead of google services.

**Comment by djaiss** [comment]
I fully agree.
This is why in v2 that we are currently building, we give users the choice. It'd be too much of work to implement this in the current version of Monica.

**Comment by trvrcr** [comment]
When will version 2 be available? I thought we were already past v2:
(on your blog, you talk about v2.16 already)
Thank you to continue making the product better

**Comment by djaiss** [comment]
@trvrcr https://www.monicahq.com/blog/a-new-version-is-coming 😄
