### ISSUE TITLE
Activities are not shown

### ISSUE THREAD

**Issue by biomcanic** [monicahq/monica#6270]
Hi! The activities are not shown in the contact page. I have just installed the app with the Heroku button, and also updated it following the three steps of https://github.com/monicahq/monica/blob/main/docs/installation/update.md#updating-heroku-instance

<img width="1280" alt="imagen" src="https://user-images.githubusercontent.com/3276352/185753098-4925ea2d-608b-40ce-a910-a234c3cf048e.png">

The data is in the tables:

<img width="835" alt="imagen" src="https://user-images.githubusercontent.com/3276352/185753150-0869242d-2d92-4cad-bce5-79f094a8e5cd.png">

<img width="602" alt="imagen" src="https://user-images.githubusercontent.com/3276352/185753177-085299e1-3be2-4e35-b22a-bb91fe6a9abe.png">

<img width="714" alt="imagen" src="https://user-images.githubusercontent.com/3276352/185753200-f0184628-0ad0-489d-b21a-72394ee56b3d.png">

Please, could you help me with it? Thanks in advance!

**Comment by biomcanic** [comment]
Duplicates https://github.com/monicahq/monica/issues/3482

**Comment by thmsjkn** [comment]
With APP_DEBUG=true in .env, the following message showed in the logs:
`[2022-08-25 17:05:57] production.ERROR: Argument 1 passed to App\Helpers\DateHelper::getShortDate() must be an instance of Carbon\Carbon, null given, called in /var/www/monica/app/Http/Controllers/Contacts/TasksController.php on line 24 {"userId":1,"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Helpers\\DateHelper::getShortDate() must be an instance of Carbon\\Carbon, null given, called in /var/www/monica/app/Http/Controllers/Contacts/TasksController.php on line 24 at /var/www/monica/app/Helpers/DateHelper.php:136)
`

Therefore with:
```
--- a/app/Http/Controllers/Contacts/TasksController.php
+++ b/app/Http/Controllers/Contacts/TasksController.php
@@ -21,7 +21,7 @@ class TasksController extends Controller
                 'title' => $task->title,
                 'description' => $task->description,
                 'completed' => $task->completed,
-                'completed_at' => DateHelper::getShortDate($task->completed_at),
+                'completed_at' => $task->completed ? DateHelper::getShortDate($task->completed_at) : null,
                 'edit' => false,
             ];
             $tasks->push($data);

```
tasks are showing again. The patch is not perfect, but hey, it works.

**Comment by thmsjkn** [comment]
@biomcanic  please reopen
