### ISSUE TITLE
Static Mail To

### ISSUE THREAD

**Issue by zikeji** [monicahq/monica#63]
I noticed here: https://github.com/monicahq/monica/blob/2e6760e7dbcccd5375707ce1b7ce9c099f40f4b7/app/Jobs/SendNewUserAlert.php

You have the new user alert static, and not using an environment variable. Not only does this result in you being sent notifications for everyone's instances with functional outgoing email, it exposes potentially private information.

As an aside:
https://github.com/monicahq/monica/blob/2e6760e7dbcccd5375707ce1b7ce9c099f40f4b7/config/mail.php#L58

Should probably use environment variables here.

**Comment by anatolinicolae** [comment]
@lancepioch why don't you create a PR? Your fix is great IMHO.

**Comment by djaiss** [comment]
Thanks a lot for caring. The fix has been pushed and is now in production.
