### ISSUE TITLE
[API] phone call is not added, and returns unexpected response

### ISSUE THREAD

**Issue by mrderiuzz** [monicahq/monica#6304]
**Describe the bug**
When adding a new call through API, I get a response containing ALL phone calls instead of this newly created one. The said phone call is not created.

please help, I'm desperate for this api to work :( currently migrating over from heroku.

**Which version are you using:**
selfhosted heroku version on hostinger

**Comment by particleflux** [comment]
Seems to work fine for me.

How exactly did you do the request? Seems like you accidentally did a GET instead of a POST.

This works fine for me on `3.7.0` and current `main` branch:

```
POST http://127.0.0.1:8000/api/calls
Authorization: Bearer xxx
Content-Type: application/json

{
  "content": "He called, we had fun.",
  "contact_id": 41,
  "called_at": "2018-02-02"
}

```


or as curl:

```
curl -X POST --location "http://127.0.0.1:8000/api/calls" \
    -H "Authorization: Bearer xxx" \
    -H "Content-Type: application/json" \
    -d "{
          \"content\": \"He called, we had fun.\",
          \"contact_id\": 41,
          \"called_at\": \"2018-02-02\"
        }"
```

**Comment by mrderiuzz** [comment]
here's how I do the request:

`let token = `HERE_GOES_MY_TOKEN`
  let apiURL = `https://app.monicahq.com/api/calls/`;
  let fetchHeaders = {
    "Authorization": "Bearer " + tokk
  }
  let date = new Date();
  date = Utilities.formatDate(date, "GMT", "yyyy-MM-dd");
  let payload = {
      'contact_id': String(1), //i only have one contact in this account
      'content': "test call",
      'called_at': String(date),
  }

  let fetchParams = {
    "method": 'post',
    "muteHttpExceptions": true,
    "headers": fetchHeaders,
    "payload": payload,
  }
  
  let response = UrlFetchApp.fetch(apiURL,fetchParams);
  var responseBody = response.getContentText();
  return JSON.parse(responseBody);`

in return I get:

`{ data: [],
  links: 
   { first: 'https://app.monicahq.com/api/calls?page=1',
     last: 'https://app.monicahq.com/api/calls?page=1',
     prev: null,
     next: null },
  meta: 
   { current_page: 1,
     from: null,
     last_page: 1,
     links: [ [Object], [Object], [Object] ],
     path: 'https://app.monicahq.com/api/calls',
     per_page: 15,
     to: null,
     total: 0,
     statistics: [] } }`
     
 and nothing is created in the contact page. I know this method should (in theory) work because it does on my Heroku version of monica. Is there something wrong with my request?

**Comment by particleflux** [comment]
I guess this is google "app scripts" code?


You probably need to explicitly define the content type of the request, as shown in documentation of UrlFetchApp - it seems it does a multipart/formdata instead of a application/json request otherwise.


From documentation:

```js
// Because payload is a JavaScript object, it is interpreted as
// as form data. (No need to specify contentType; it automatically
// defaults to either 'application/x-www-form-urlencoded'
// or 'multipart/form-data')
var options = {
  'method' : 'post',
  'payload' : formData
};
UrlFetchApp.fetch('https://httpbin.org/post', options);


// Make a POST request with a JSON payload.
var data = {
  'name': 'Bob Smith',
  'age': 35,
  'pets': ['fido', 'fluffy']
};
var options = {
  'method' : 'post',
  'contentType': 'application/json',
  // Convert the JavaScript object to a JSON string.
  'payload' : JSON.stringify(data)
};
UrlFetchApp.fetch('https://httpbin.org/post', options);

```

 (taken from here: https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app)

**Comment by mrderiuzz** [comment]
unforunately adding, explicitly defining content as `application/json` does not seem to help. My code currently:

```javascript
let apiURL = `https://app.monicahq.com/api/calls/`;
  let fetchHeaders = {
    "Authorization": "Bearer " + token_monicahq
  }
  let payload = {
      'contact_id': "1",
      'content': "He called, we had fun.",
      'called_at': "2018-02-02",
  }
  let fetchParams = {
    'contentType': 'application/json',
    "method": 'post',
    "headers": fetchHeaders,
    "payload": payload
  }
  let response = UrlFetchApp.fetch(apiURL,fetchParams);
```

still get are generic response (returns ALL calls, although it's supposed to return just the created one). Also no call entry is created in the contact's profile page.

After your request, do you get this call item as a reponse, and is the call created in that profile's contact? If so, that's probably an issue with google apps script but I'd be surprised as I have no problems with other services (todoist, inoreader, etc) but could be the case.

Also, thanks for picking this up! Appreciate your help a lot

**Comment by particleflux** [comment]
Yes, my _curl_ request above returns a `201 created` status code, actually creates the call entry, and alsoreturns call data + contact data intermingled like this:

```json
{
  "data": {
    "id": 27,
    "uuid": "55239f7b-7775-477e-ac66-12a800b71fb5",
    "object": "call",
    "called_at": "2018-02-02T00:00:00Z",
    "content": "He called, we had fun.",
    "contact_called": null,
    "emotions": [],
    "url": "http:\/\/127.0.0.1:8000\/api\/calls\/27",
    "account": {
      "id": 1
    },
    "contact": {
      "id": 41,
     // ... shortened for readability
    },
    "created_at": "2022-09-04T17:19:19Z",
    "updated_at": "2022-09-04T17:19:19Z"
  }
}
```

That curl line I pasted should also be adaptable to test with your host (or app.monicahq.com) - just change the host & data and insert the token.



I never worked with app script, and also don't have an account set up, so I can't directly test that. However, you could try one more thing, by changing your latest snippet to also set the content type via header, since you have custom headers, and the google documentation didn't have those.

Apart from that, are you also executing against version 3.7.0? Or something older? (if you login to monica UI it should show the version in the footer)

**Comment by HmnSDR** [comment]
![image](https://user-images.githubusercontent.com/88235271/188335879-b3f0b1b3-764c-45a2-b1a7-8dbfaf83f3b3.jpeg)

**Comment by mrderiuzz** [comment]
Unfortunately haven't managed to get it to work neither through updated apps script nor through curl run via VSC. Anyways, I managed to resuscitate my heroku instance so its not a problem for now, especially since you say it does work on your local copy of 3.7.0. Thanks for looking into this again!
