### ISSUE TITLE
[Possible miss] Automatic bi-directional relationships

### ISSUE THREAD

**Issue by Akshay-Thakare** [monicahq/monica#6446]
Feature request: Say we add a child for a contact, then the parent should automatically be added to the child's contact. (Also applicable for other relation types)

Update
On further analysis it seems like this does partially work, say if you add more children then a sibling relation between children's is not automatically established especially if there is more than 1 sibling

**Comment by expionage** [comment]
+1

**Comment by Akshay-Thakare** [comment]
On further analysis it seems like this does partially work, say if you add more children then a sibling relation between children's is not automatically established especially if there is more than 1 sibling
