### ISSUE TITLE
The link to how to set up the test suit is broken

### ISSUE THREAD

**Issue by Trentr9** [monicahq/monica#646]
On the main Contributing page of the project there is a link that is supposed to take you to how to set up the test suit.

What is happening: It is taking you to the main page of the repository

What is expected to happen: Take you to this page: https://github.com/monicahq/monica/blob/master/docs/contribute/contribute.md#setup-the-testing-environment

**Comment by djaiss** [comment]
Thanks a lot for caring. The fix has been pushed and is now in production. Sorry that you had to go through this error.
