### ISSUE TITLE
The "Me as a contact" option displays "Sorry, no matching options." when selected

### ISSUE THREAD

**Issue by moonmusicstone** [monicahq/monica#6479]
**Describe the bug**
Monica is a project I like very much, I discovered her not long ago, and then I deployed it on my server, everything is perfect, Monica is running normally. I did some testing and most of the features work fine. But the "Me as a contact" option displays "Sorry, no matching options." when selected. I'm sure I've added the contact, but the option doesn't work. My browser gives me the warning "Manifest: one of 'url' or 'id' is required, related application ignored." I assume this is why the "Me as a contact" option isn't working, but I don't know how to fix it. I have tried to download the source code of V3.7.0 version directly and pull the source code according to the tutorial, but the problem has not been solved. I don't know much about this and hope you can help me.

**Screenshots**
["Me as a contact" option displays "Sorry, no matching options."](https://images.moonmusicstone.com/picshow/2022/12/14/6399c1eea3c9a.png)
[My browser warning](https://images.moonmusicstone.com/picshow/2022/12/14/6399c1eedc172.png)

**Which version are you using:**
 - A server maintained by myself (The lastest version V3.7.0)

**Comment by YacineSahli** [comment]
I'm having the same problem using docker-apache image  version 3.7

**Comment by Kenishi99** [comment]
Same issue here on the online hosted (not self-hosted) version.

**Comment by ecshreve** [comment]
Just ran into this on self-hosted version 4.0.0. As a workaround I manually set the `users.me_contact_id` field in the database for my user.

**Comment by rockbenben** [comment]
> Just ran into this on self-hosted version 4.0.0. As a workaround I manually set the `users.me_contact_id` field in the database for my user.

Thanks! This method is great and has finally solved a problem that has been troubling me for months.

If you have the same issue, you my execute the SQL command:
> UPDATE `monica`.`users` SET `me_contact_id` = 1 WHERE `id` = 1

**Comment by TurboKyle** [comment]
Try entering the contact's name into the text input box and see.

**Comment by moonmusicstone** [comment]
Thanks for your help. After testing with the self-hosted version V4.0.0, there are currently two solutions to this problem. 
1. One is to manually set the `users.me_contact_id` field in the database for your user. This is the method proposed by @ecshreve .
2. The second method is to enter the first name, last name or nickname of the contact in the search box. After testing, it seems that the first and last name are input at the same time and it seems unrecognizable. Please use one of the above three methods. After input, the corresponding contact will be matched automatically. This is the method proposed by @TurboKyle .
