### ISSUE TITLE
Docker image does not work because it is missing the .env file

### ISSUE THREAD

**Issue by jamrizzi** [monicahq/monica#648]
It is a terrible user experience to have to manually copy the `.env.example` file with Docker. It threw me off really bad.

**Comment by DracoMilesX** [comment]
Why is it a terrible user experience? Now you add an .env file with default settings and not even completely configured for a workable container this means you need to add a bunch of '-e' tags to get it configured? Don't even know if it is supported like that

**Comment by irufus** [comment]
If you want a better user experience you can just sign up for a Monica account without having to deploy this yourself.

**Comment by jamrizzi** [comment]
Gee, it's a terrible docker user experience is what I'm referring to. In my experience, Docker containers should work out of the box without having to configure them. Configuration should be reserved for overriding default settings, not a requirement to spin up a container. Also, containers should be able to be configured with just environment variables.

**Comment by irufus** [comment]
So basically you just need the docker make files to copy the .env.example to .env. I'm also assuming some reminder or warning to let the user know they will need to make configuration changes.

**Comment by jamrizzi** [comment]
Yeah, that's exactly what I was thinking

**Comment by jamrizzi** [comment]
I made a pull request for it

**Comment by jamrizzi** [comment]
https://github.com/monicahq/monica/pull/651
