### ISSUE TITLE
[Feature Request] Add SQLite support

### ISSUE THREAD

**Issue by Draxter** [monicahq/monica#6518]
**Issue**
As a Monica user, I don't want to have to run/maintain/backup a SQL database instance for Monica to use.

**Proposed Solution**
Instead, a built-in SQLite database option could be added, which in vast majority of cases would provide a good enough performance.

**Justification**
This would make running Monica simpler as well as lower the setup/maintenance/backup burden.

**Comment by strootje** [comment]
This would make my instance with 2 users a lot simpler. Having the option would be nice

**Comment by virtadpt** [comment]
Same here.  I'm the only person using my instance, and my hosting provider's overworked database server is both overkill and not helping.

**Comment by Draxter** [comment]
SQLite DB option is available in the new Chandler beta version of Monica.
