### ISSUE TITLE
Missing dependency to php-tokenizer

### ISSUE THREAD

**Issue by allo-** [monicahq/monica#6524]
**Describe the bug**
Monica fails with a blank page when and
`Call to undefined function Illuminate\View\Compilers\token_get_all` in the laravel log, when the tokenizer php extension is not installed. There should probably a check for it and a useful error message.

**Comment by SimonVanacco** [comment]
Hi ! I've submitted a PR to document the dependency better and to make it so that a better error message will be shown to the user, preventing confusion from the token_get_all error :)

**Comment by asbiin** [comment]
Fixed by #6577
