### ISSUE TITLE
Non-integer currency values are not possible.

### ISSUE THREAD

**Issue by trwnh** [monicahq/monica#653]
For example, trying to add a $3.50 "debt" as a test will instead prompt you to use the nearest values 3 or 4. Expected behavior would be to allow including a fractional currency amount. 

As best as I can tell, this is because of the following line:

> [monica/database/migrations/2017_05_30_023116_create_money_table.php](https://github.com/monicahq/monica/blob/a2172f08518cb27bb2c3dd3855e5abc2a26e8501/database/migrations/2017_05_30_023116_create_money_table.php)
>Line 21
`$table->integer('amount');`

**Comment by djaiss** [comment]
This is now done and in production! Thanks for reporting this issue!
