### ISSUE TITLE
Please add the ability to rename tags

### ISSUE THREAD

**Issue by sean808080** [monicahq/monica#6544]
In the UI it's possible to delete tags and see which contacts fall under a particular tag.

Please add the option to rename a tag.

**Comment by djaiss** [comment]
This is coming in Chandler (aka Monica v2).

<img width="745" alt="image" src="https://user-images.githubusercontent.com/61099/227719124-47a86947-d1b7-4896-899f-e7c699f13703.png">

The code is currently here: https://github.com/monicahq/chandler

You can test it here: https://staging.monicahq.com/ (but data is reset very often).
