### ISSUE TITLE
First run up, cant login, getting odd log in page.

### ISSUE THREAD

**Issue by nzhooch** [monicahq/monica#6568]
Sorry Newbie to most things here, I got unraid and found this program which is EXACTLY what i was looking for, followed a bunch of videos and wrestled it to the point where it starts fine, two things though, seems to always want https, but im happy with http, as it will not be exposed at any point, and its just for me. secondly, I cannot create a user, my first page is as follows.
![image](https://user-images.githubusercontent.com/57616145/217957205-79cc0805-6cd6-4397-b3af-33ba9e765eef.png)

What have i done wrong, also if this isnt where i should go for help, can someone poke me in the right direction. 
Have a great day :)

**Comment by mariushosting** [comment]
90% of users have the same issue as you. Version 4 looks bugged. 
![bugged](https://user-images.githubusercontent.com/37554361/218000894-953bd2de-1ffa-4986-82c8-07239afef688.png)

**Comment by mariushosting** [comment]
@djaiss @asbiin

**Comment by mariushosting** [comment]
Ok solved @nzhooch add new environment variable - APP_ENV=production
to make it to work over https.

**Comment by nzhooch** [comment]
> Ok solved @nzhooch add new environment variable - APP_ENV=production to make it to work over https.

You Sir are a legend.
Thankyou so much !!!!
