### ISSUE TITLE
Stay in touch should be able to automatically adjust after last contact

### ISSUE THREAD

**Issue by Scronkfinkle** [monicahq/monica#6571]
One of my favorite features of monica is the "stay in touch" option which will email every N days so I remember to stay in touch with folks. However, it doesn't feel intuitive that it will ignore recent conversations.  

For example, I have stay in touch configured for every 14 days with a friend. I called them 2 days ago, and logged the call. What I expected to happen is monica would register we were just in touch, and then update the reminder to be 14 days after that call. However, it instead sent me an email yesterday, as the feature seems to only email me every N days regardless of past interaction. It would be nice if there was a way to have monica register that conversation as being in touch, and then wait 14 days from that point in time to remind me it's been 2 weeks since I last got in touch with that person.

**Comment by syeo66** [comment]
#1814 is open since 2018...

**Comment by Scronkfinkle** [comment]
closing due to duplicate of #1814
