### ISSUE TITLE
Add API methods for adding and removing Tags from Contacts

### ISSUE THREAD

**Issue by mattdp** [monicahq/monica#658]
I was able to import 2,000+ contacts from my old system using the API, so am very happy with the API overall so far. The big stumbling block for me is a lack of an easy helper method to add a Tag to a Contact, even if I have the Tag.id already. Though I might be incorrect, right now it looks like I'd have to GET the Contact, add the exact right JSON for the Tag(s), and PUT it back.

Thanks for considering!

**Comment by djaiss** [comment]
@mattdp thanks for trying out the API :-D Fortunately it works.

It makes sense to add this to the API of course. I'll do it very soon.

**Comment by mattdp** [comment]
@djaiss any chance of including this in a near future release? Are there other active developers helping who I should ping instead? Let me know what would be best!

**Comment by djaiss** [comment]
@mattdp I've started to implement this feature https://github.com/monicahq/monica/pull/924 so you can follow the progress.

**Comment by djaiss** [comment]
@mattdp the API calls are now in production (but not yet in the Docker image).

Documentation is here: https://www.monicahq.com/api/tags#associate-a-tag-to-a-contact

Let me know if it suits your needs.
