### ISSUE TITLE
Is possible install monica on windows in xampp? 

### ISSUE THREAD

**Issue by raulgh0201** [monicahq/monica#6619]
One question, is it compatible for windows? since when using the composer install using php 8.2.0 I get a lot of dependencies type xml ext-intl, ext-redis, php_dom and I have all those already activated in the php.ini, and even so the error appears when installing and using the command composer install --ignore-platform-req=ext-intl --ignore-platform-req=ext-redis --ignore-platform-req=ext-zip which is to ignore if dependencies are missing, it doesn't work for me I keep getting errors and i want to collaborate, thanks in advance for any help you can offer me. I am using xamp in windows

```
`PHP warning: PHP startup: unable to load dynamic library 'dom' (tested: C:\xampp\php\ext\dom (Cannot find specified module), C:\xampp\php \ext\php_dom .dll (Cannot find the specified module)) to Unknown on line 0

Warning: PHP startup: unable to load dynamic library 'dom' (tested: C:\xampp\php\ext\dom (Cannot find specified module), C:\xampp\php\ext \php_dom.dll (Cannot find the specified module)) to Unknown on line 0
PHP warning: PHP startup: unable to load dynamic library 'xml' (tested: C:\xampp\php\ext\xml (Cannot find specified module), C:\xampp\php \ext\php_xml .dll (Cannot find the specified module)) to Unknown on line 0

Warning: PHP startup: unable to load dynamic library 'xml' (tested: C:\xampp\php\ext\xml (Cannot find specified module), C:\xampp\php\ext \php_xml.dll (Cannot find the specified module)) to Unknown on line 0
PHP warning: PHP startup: unable to load dynamic library 'json' (tested: C:\xampp\php\ext\json (Cannot find specified module), C:\xampp\php \ext\php_json .dll (Cannot find the specified module)) to Unknown on line 0`
```

**Comment by zeezhao** [comment]
Yes, I run it on xampp. See my comment here:
https://github.com/monicahq/monica/issues/4351#issuecomment-801286911

Make sure server stopped and restarted after chaning php.ini

**Comment by djaiss** [comment]
Yes of course. It's available on any OS that can run PHP, MySQL etc...
