### ISSUE TITLE
SMTP / Connection to "..." timed out

### ISSUE THREAD

**Issue by turbopixel** [monicahq/monica#6624]
I have installed and set up MonicaCRM at a Linux server. I am getting nowhere with the email configuration setup.

Server hostname: *vm8.domain.tld* / Monicas domain: *monica.example.tld*

**.env settings**

```
# Mail credentials used to send emails from the application.
MAIL_MAILER=smtp
MAIL_HOST=vm8.domain.tld
MAIL_PORT=465
MAIL_USERNAME=monica@monica.example.tld
MAIL_PASSWORD=<secret>
MAIL_ENCRYPTION=SSL
```

Using the console I want to send a test email. I do this with the command: `php artisan monica:test-email`

After a few seconds I get the following error message:

```
[11:40:15] turbopixel@vm8$ ~/web/monica.example.tld/public_html: php artisan monica:test-email
Preparing and sending email to ....

In AbstractStream.php line 81:
                                              
  Connection to "vm8.domain.tld:995" timed out.                                          

```

I have already tried STARTTSL and SSL with different port variations. I have also tested * sendmail* as MAILER. Without success.

So what's wrong in my configuration?

### System

* Monica Version: 4.0.0
* Linux Debian
* Webhosting Control Panel: HestiaCP
* PHP 8.2

**Comment by Szeraax** [comment]
have you proved that you are able to send emails with those credentials/host/port manually?

**Comment by turbopixel** [comment]
How can I rebuild the cache/config.php file? I found out that the smtp credentials are wrong in this caching file.
