### ISSUE TITLE
Allow setting of db_prefix via env

### ISSUE THREAD

**Issue by jangalinski** [monicahq/monica#664]
I want to save limited mysql databases on my hosting account and use monica together with other apps in on db.
I could use the db-prefix setting, but looking at database.php, it is not possible to configure the default '' string.

**Comment by turtles2** [comment]
#720 Adds this

**Comment by djaiss** [comment]
Thanks to @turtles2 it's now merged in the codebase. This change will appear in version 1.5 which will be released in a couple of days.
