### ISSUE TITLE
Naming of the new version? v1?

### ISSUE THREAD

**Issue by duracell** [monicahq/monica#6647]
Hey, I just wanted to ask why the new version is called 1.0.0-beta.1?
Giving a new version a lower number than the old seems very odd to me, is there any reason for this?

**Comment by wrharding** [comment]
Looks like it was just a misnamed release and has been adjusted:

https://github.com/monicahq/chandler

https://github.com/monicahq/monica/releases/tag/v5.0.0-beta.1

**Comment by duracell** [comment]
Closed because it was fixed.
