### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#668]
Hey everyone,

Just wanted to say all of you a quick thank you.
While I haven't been very active here I still from time to time check in and I must say the current release 1.2.0
looks very great.
I don't know when exactly you added all the options but there has been happening very much and it's great to use it.
Great work 👍 !

**Comment by djaiss** [comment]
@Nebucatnetzer that is very nice of you to say 😀
I'm trying to work on it when I can and I'm still extremely motivated by the project. I'm also super grateful for all the people who submit pull requests, it's awesome.
