### ISSUE TITLE
Links in CONTRIBUTING.md are broken

### ISSUE THREAD

**Issue by ravi-sensify** [monicahq/monica#67]
Most links in `CONTRIBUTING.md` point to

https://github.com/djaiss/monica...
instead of
https://github.com/monicahq/monica...

and need to be updated to the right ones.

**Comment by djaiss** [comment]
Thanks so much. It's merged.

**Comment by ravi-sensify** [comment]
@djaiss - quick note, BTW. I noticed that your commits are using this alias: `Régis Freyd <djaiss@users.noreply.github.com>`

If you _ever_ rename your github account to say `foo` and I rename _my_ account to `djaiss`, all your commit history will get attributed incorrectly to me.

To fix this, you simply need to set your `~/.gitconfig` appropriately with the `email` field. Here's what's in mine:

```
cat ~/.gitconfig
# This is Git's per-user configuration file.
[user]
# Please adapt and uncomment the following lines:
	name = Ravi Rao
	email = ravi@sensify-security.com
[credential]
	helper = osxkeychain
[filter "lfs"]
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
```

This way, even if you rename your github account, your commits are still associated with your email (which you hopefully own forever).

**Comment by djaiss** [comment]
It's actually done on purpose 😄  This is a feature from Github. https://help.github.com/articles/keeping-your-email-address-private/
