### ISSUE TITLE
[Chandler] Mobile features / questions

### ISSUE THREAD

**Issue by jxn** [monicahq/monica#6730]
I can't tell if this is a feature request, bug, or information request.

I noticed that the Chandler branch does not have any links or buttons on to create content in mobile browser layouts, and when I path-hack to get to a URL to create content, the touch targets are small and the layouts look weird.

Is it a deliberate decision to avoid mobile, assumed that once the API is available folks will use an app instead?  Is mobile work expected to be done, or is nobody interested in mobile for Monica?  I'm happy to make small contributions to help enable more of the features on mobile (if someone else is planning to work on that eventually), but I don't have the time or front-end chops to do the mobile work from the ground up.  Is mobile work planned, and if so is it more likely we'll see initial mobile functionality or an API?

Thanks for the project.  It looks nice and the chandler re-work looks promising.

**Comment by djaiss** [comment]
It is not a conscious decision. We'll improve it over time, that's for sure.
Thanks for your comment!
