### ISSUE TITLE
Monica won't start when changing from monica-next:main to monica-next:chandler

### ISSUE THREAD

**Issue by b3nd1k** [monicahq/monica#6750]
Hey. As the Main branch seems to no longer be updated, I wanted to move from `monica-next:main` to `monica-next:chandler,`. However, when I change the image and use the same files, Monica won't start and just crashes. How can I fix this?

In order to get the chandler-branch to start, I have to start with a clean database and app folder.

**Comment by b3nd1k** [comment]
Maybe one of you two would know how to fix this? @asbiin @djaiss

**Comment by b3nd1k** [comment]
That's a bummer. Since both versions are "Chandler", it awful that it should be so diffuckt.

**Comment by asbiin** [comment]
Hello. Sorry for that, there is no upgrade yet. Also the `monica-next` image should be used for development purpose only.
