### ISSUE TITLE
Docker version still at v0.7.1

### ISSUE THREAD

**Issue by alecgorge** [monicahq/monica#676]
The images available at [hub.docker.com](https://hub.docker.com/r/monicahq/monicahq/tags/) at over a month old and set at v0.7.1.

I would love to be able to use the 1.0 API features via my docker based deployment. Can someone with authority push updated images? There are easy workarounds of course but it would nice to get those updated.

Thanks for Monica!

**Comment by djaiss** [comment]
Right now, docker images are maintained by someone else (@kstrauser) I'll put in my todos to update the image myself on each new release.

**Comment by kstrauser** [comment]
Eek! The new version notifications still aren't coming through. @djaiss, in the mean time, I'll try to get new images up tonight.

**Comment by djaiss** [comment]
@kstrauser thanks so much! If you provide me with instructions on how to do it myself, I could do it when I release a new version 😀

**Comment by kstrauser** [comment]
@djaiss This is my very high tech Makefile for pushing images:

```make
GIT_TAG=$$(git describe --abbrev=0 --tags)

docker_build:
	docker-compose build

docker_tag:
	docker tag monicahq/monicahq monicahq/monicahq:$(GIT_TAG)

docker_push:
	docker push monicahq/monicahq:$(GIT_TAG)
	docker push monicahq/monicahq:latest
```

To build and push version 3.4.5, I run:

```shell
$ git reset --hard v3.4.5
$ make docker_build docker_tag docker_push
```

**Comment by djaiss** [comment]
Awesome @kstrauser 

As I'm not familiar with Docker (but I'll learn in the coming days), I assume I run this command either at the root of the project's folder, or inside the `docker` folder directly?

**Comment by kstrauser** [comment]
You'd run it in the root of the project's folder.

**Comment by djaiss** [comment]
@kstrauser Gotcha. I'll let you know if I run into some issues.

**Comment by alecgorge** [comment]
Thanks so much! Now I can deploy super easily on [dokku](https://github.com/dokku/dokku) and stay up to date without too much work.

**Comment by alecgorge** [comment]
@djaiss @kstrauser it looks like the new 1.5.0 release didn't make it to Docker either

**Comment by djaiss** [comment]
@alecgorge yep this is my roadmap for the week 😀

**Comment by djaiss** [comment]
1.5.0 and 1.6.0 have both been pushed to Docker Hub.
I now know how to build and push Docker images, so @kstrauser you don't have to do it anymore (unless I've fucked up something in the process 😀 ). Thanks a lot for all your help!
