### ISSUE TITLE
[chandler] feature: Ability to write multi-line notes

### ISSUE THREAD

**Issue by phorcys420** [monicahq/monica#6779]
![UX when creating a note](https://github.com/monicahq/monica/assets/57866459/2c229093-5931-4c8b-8d39-e00ed33df414)

---

I think it would be a nice thing if the notes were actually multiline.
I'm also thinking it would be a nice addition if they supported MD formatting.

**Comment by djaiss** [comment]
They actually support markdown formatting. It should be clearer.
