### ISSUE TITLE
Installation docs falsly state that PHP 7+ is required

### ISSUE THREAD

**Issue by simhnna** [monicahq/monica#678]
In fact 7.1 is required, the docs are lying...

It wouls also be helpful to have a release that still works under 7.0  
I read through the release notes and couldn't find anything regarding the dependency on 7.1

**Comment by djaiss** [comment]
Lying is a strong word 😀 

I reverted the minimum version to 7.0 as it's the version Laravel itself uses. Also, it caused problems on Heroku, so we'll stick to this until Laravel changes it too.
