### ISSUE TITLE
[chandler] bug: Character count overlaps in front of text

### ISSUE THREAD

**Issue by phorcys420** [monicahq/monica#6780]
![monica_charactercount](https://github.com/monicahq/monica/assets/57866459/23bf2b1b-0f0f-4392-9ef6-33ff0747a9a0)

---

5.0.0-beta.2 — commit dd27398

---

This also happens when [filling in a form field](https://github.com/monicahq/monica/assets/57866459/a43a4f93-7038-4fc4-8fa9-0df239da3268).

**Comment by Albertoroldanq** [comment]
<img width="443" alt="Screenshot 2023-10-25 at 11 59 57" src="https://github.com/monicahq/monica/assets/18287617/d0b6ca54-5417-4e4b-9b61-23e5f082bc59">

**Comment by djaiss** [comment]
@Albertoroldanq it's a great idea.

I'll check what I can do for this.

**Comment by djaiss** [comment]
Fixed :-)
