### ISSUE TITLE
PHP 7.2 Error: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by tristankerner** [monicahq/monica#681]
Just installed the other day (on a fresh VPS). I'm using PHP 7.2.0-2+ubuntu16.04.1+deb.sury.org+1. I'm able to add contacts, but when accessing them, or navigating to Contacts, I get the following errors:

`count(): Parameter must be an array or an object that implements Countable (View: /var/www/html/resources/views/people/_header.blade.php) (View: /var/www/html/resources/views/people/_header.blade.php)`

`count(): Parameter must be an array or an object that implements Countable (View: /var/www/html/resources/views/people/index.blade.php)`

Both realate to the line:

`<?php if(count($contact->getInitials()) == 1): ?>`

Overall, this appears to be caused by change in php 7.2: https://wiki.php.net/rfc/counting_non_countables .

**Comment by djaiss** [comment]
Ouch. I'll fix this. Thanks for reporting it!

**Comment by djaiss** [comment]
This is fixed now in production and in version 1.4.0. Sorry for the confusion.
