### ISSUE TITLE
Default template

### ISSUE THREAD

**Issue by ivocro** [monicahq/monica#6839]
**Describe the bug**
I somehow deleted the default template, and when I want to create it again, I can not. There are no "modules" to add to the pages available. Is it possible somehow to "reset" my account to have a fresh start, or to reset a default template? I created an account with some other email, and it is all correct, but on this one, I can not do it. Thank you!

I am talking about new, Chandler beta.

**Screenshots**
![nema_1](https://github.com/monicahq/monica/assets/15676517/bd16fb5f-cf28-404c-9075-f99f12c8782b)
![nema_2](https://github.com/monicahq/monica/assets/15676517/41a1d91c-1667-466e-b8c3-53c56bde75cf)
![version](https://github.com/monicahq/monica/assets/15676517/d4cf07f0-4a78-46ee-966a-b8f2f90699d7)

**Comment by djaiss** [comment]
Thanks for writing about this issue.

We can't recreate the default template in the DB in production. However you should be able to see the list of modules when you create a new template.

That being said, I've made it so we can't delete the default template anymore. This will make sure accounts are still usable no matter what happens.

**Comment by stephenwade** [comment]
I'm having a similar problem with no templates and no modules, but I didn't delete a template. I never had one. I also don't have any modules available to create my own template. Did I miss a step when setting up?

**Comment by workdojos** [comment]
> I'm having a similar problem with no templates and no modules, but I didn't delete a template. I never had one. I also don't have any modules available to create my own template. Did I miss a step when setting up?

Ever figure this out?  The whole templates section is just straight up missing.
