### ISSUE TITLE
installation issue: yarn production script missing

### ISSUE THREAD

**Issue by fawaffle** [monicahq/monica#6872]
I haven't worked with yarn before so I apologize if this question has an obvious answer. I am following the [Debian instructions](https://github.com/monicahq/monica/blob/4.x/docs/installation/providers/debian.md) to install Monica on my own server, and all went well until I got here: 

```
me@toolmaster:~/monica $ yarn run production
Usage Error: Couldn't find a script named "production".
```

I don't see a file named "production" anywhere in the main or 4.x branches. Where can I find it?

**Comment by djaiss** [comment]
This is because now you have to use `yarn build` to build the production scripts (as seen in the file called `package.json`). I'll update the debian instructions.
