### ISSUE TITLE
Translate the app through an external platform

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#695]
We should use one of the translation platforms out there (Transifex for instance).

At the moment, translating the applications is done through the edition of the `lang` files. Not user friendly and very discouraging for people who would want to contribute without knowing how to use Git.

**Comment by turtles2** [comment]
Take a look at the following laravel packages they require migrations but make translation much more approachable for the average user. I have no experience with either of these packages but they seem like they would do the trick.

1. [Laravel 5 Translation Manager](https://github.com/barryvdh/laravel-translation-manager)
2.[Laravel 5 Translation Manager with Yandex ](https://github.com/vsch/laravel-translation-manager)

**Comment by djaiss** [comment]
@turtles2 thanks for your help! It's super useful.

**Comment by djaiss** [comment]
https://crowdin.com/project/monicahq

We now use Crowdin to help us in that regard.
