### ISSUE TITLE
Enhance: The Buttons in the Header Section Lacks Transition

### ISSUE THREAD

**Issue by DeepRahangdale** [monicahq/monica#6956]
When hovering over an element, apply a smooth transition effect with a scale change from 95% to 105% to create a subtle zoom-in and out effect, enhancing the user interaction and visual feedback.
similar to this site.
https://drive.google.com/file/d/1Gm2KpWL_40dTaTYSwiTKyI3HPI0nPcQw/view?usp=sharing

**Comment by djaiss** [comment]
I assume you are talking about the new version (codename Chandler).

This is not something we want to support. Everything that is clickable in Chandler has some kind of visual feedback already.
