### ISSUE TITLE
Dav 500 currentAccessToken

### ISSUE THREAD

**Issue by tamaskan** [monicahq/monica#6964]
production.ERROR: Call to a member function currentAccessToken() on null {"exception":"[object] (Error(code: 0): Call to a member function currentAccessToken() on null at /var/www/html/app/Http/Middleware/AuthenticateWithTokenOnBasicAuth.php:67

**Comment by djaiss** [comment]
We don't have enough information for this.
Please open a new ticket with more information: OS, version of Monica, what did you try to achieve, etc..
