### ISSUE TITLE
Find a way to do functional tests

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#698]
We use unit tests and some sort of functional tests, but these are extremely limited.

I've done some tests with [Dusk](https://laravel.com/docs/5.5/dusk) but
* tests with Dusk are painfully slow
* they don't work with [Homestead](https://laravel.com/docs/homestead) (or the installation process is horribly painful)

**What can we use to do functional tests?** I'd love to use [Ghost Inspector](https://ghostinspector.com/) which is a company I've always admired, but 
* they are expensive and the project earns like nothing today
* adding tests could be done only by a few people (including me) and not people who submit PRs.

Functional testing is a necessity and not having them currently makes me super nervous.

**Comment by djaiss** [comment]
Perhaps Dusk is the answer after all. Even if I don't like its slowness. It doesn't work with Homestead, but it does work when your dev env is outside a VM (with Valet for instance).

An avenue to run Dusk on Travis https://laravel-news.com/laravel-dusk-continuous-integration

**Comment by erdmenchen** [comment]
What exactly are you missing from default [Laravel http testing](https://laravel.com/docs/5.5/http-tests) capabilities?

**Comment by asbiin** [comment]
I'm currently trying to run tests with an other test framework which uses selenium : [lmc/steward](https://github.com/lmc-eu/steward).

**Comment by djaiss** [comment]
@erdmenchen it won't let me test the views that contain VueJS.

**Comment by erdmenchen** [comment]
What about this approach: https://nick-basile.com/blog/post/testing-a-vuejs-and-laravel-todo-app

The author uses PHPunit tests for Laravel side by side with the official [vue-test-utils](https://vue-test-utils.vuejs.org/en/) for your vue stuff...

And a key motivation was speed, too.

**Comment by djaiss** [comment]
@erdmenchen Wasn't aware of this. It's worth trying so we can stick with Laravel's built-in capabilities. Will test and report.

**Comment by erdmenchen** [comment]
Why close? Is the discussion over?

**Comment by asbiin** [comment]
Well, this was closed automatically when I've merged the PR, but the discussion is not really over, yep !

**Comment by asbiin** [comment]
The (merged) PR #892 activated tests with Dusk.

**Comment by djaiss** [comment]
So yes, we've migrated to Dusk outside a VM, we run it on Sauce Labs and for now, things are working. We should see if we encounter cases where Dusk is not appropriate again.

**Comment by asbiin** [comment]
Browser tests are running well now.
