### ISSUE TITLE
[Chandler] Currencies are not alphabetically sorted

### ISSUE THREAD

**Issue by DunklerPhoenix** [monicahq/monica#6985]
## Bug description

The currencies under dept are not sorted in alphabetically order. So it's quite difficult to find the right one ;)

**Comment by SecurID** [comment]
<img width="841" alt="image" src="https://github.com/monicahq/monica/assets/7266850/20c830c6-a41f-4ee2-88bd-4faa5d33f6a1">
You mean here?

**Comment by DunklerPhoenix** [comment]
![Bildschirmfoto vom 2023-10-31 03-45-03](https://github.com/monicahq/monica/assets/1261305/b26b2aea-a0d1-4ab6-8857-eacc3c0b0a0c)


No here. Under a contact -> Information -> Credit

**Comment by djaiss** [comment]
Thanks for this report.
It'll be fixed in #7009
