### ISSUE TITLE
Troubleshooting: Upload of avatars fails

### ISSUE THREAD

**Issue by Reubo** [monicahq/monica#702]
Hi,

after uploading an avatar to a contact the image won't appear.

- Monica runs self hosted
- I cannot find any images under storage/app/public
- There is no folder 'avatars'. Should one be there?
- The folder is writable
- A Symlink from public is set
- The "FollowSymlinks" Setting is active

Is it possible to log the request? It seems like it cannot save the image, altough the browser is uploading it.

Thanks for your help!

**Comment by Reubo** [comment]
@djaiss 
Thank you for your help.
- I've run `php artisan storage:link` again, it says `The "public/storage" directory already exists.`so that should be fine
- php-gd is installed and running
- `APP_DEBUG=true` is active since yesterday
- `APP_LOG=daily` is set

Even tough the last log file created was `laravel-2017-12-09.log`

I do not know the default behaviour, but shouldn't there be logfiles from yesterday or today?

Thanks!

**Comment by djaiss** [comment]
It depends if this problem generates an exception or not, which apparently does not.
Can you check in your database if the table `contacts` has data for the field `avatar_location` with data in it?

The generation of avatars goes through the queue mechanism. What value do you have in your `.env` file for `QUEUE_DRIVER`?

Also, can you check in the `storage/app/public/avatars` folder if it's empty or is there the file you've uploaded?

**Comment by Reubo** [comment]
Thanks again for helping me out!

This is how my Select on the contacts table looks like:

mysql> SELECT id, has_avatar, avatar_external_url, avatar_file_name, avatar_location, has_avatar_bool from contacts;
+----+------------+---------------------+------------------+-----------------+-----------------+
| id | has_avatar | avatar_external_url | avatar_file_name | avatar_location | has_avatar_bool |
+----+------------+---------------------+------------------+-----------------+-----------------+
...
| 31 |          0 | NULL                | NULL             | local           |               0 |
| 32 |          0 | NULL                | NULL             | local           |               0 |
| 33 |          0 | NULL                | NULL             | local           |               0 |
| 34 |          0 | NULL                | NULL             | local           |               0 |
| 35 |          0 | NULL                | NULL             | local           |               0 |
| 36 |          0 | NULL                | NULL             | local           |               0 |
| 37 |          0 | NULL                | NULL             | local           |               0 |
+----+------------+---------------------+------------------+-----------------+-----------------+

I have shortened the table, but every column looks like the ones above. I tried to upload an avatar to 36 and 37 many times.

- `QUEUE_DRIVER=sync`
- `DEFAULT_FILESYSTEM=public`
- Monica runs on apache with an subdomain like https://monica.XYZ.domain with Apache Rewrite-Rules like `Rewrite Base /` - maybe there is some problem?
- Unfortunately the `storage/app/public/avatars` is empty (except .gitignore)

Would it be possible to set some breakpoint or `dd` for further troubleshooting?

**Comment by djaiss** [comment]
Looks like the avatars are not even uploaded in your case.

Just to be sure, are you using the latest release or at best the `master` branch?

The avatars are uploaded here: https://github.com/monicahq/monica/blob/master/app/Http/Controllers/ContactsController.php#L175

You can `dd($request->avatar);` right after this line to see what you have in return.

**Comment by Reubo** [comment]
Yes, the latest release is installed.

It seems like the whole If-Clause starting at 172 does not get triggered, even when i upload an avatar.


Putting `dd($request->avatar);` right before the If-Clause on Line 171 returns the following:

UploadedFile {#581 ▼
  -test: false
  -originalName: "avatar_image.jpg"
  -mimeType: "application/octet-stream"
  -size: 0
  -error: 6
  #hashName: null
  path: ""
  filename: ""
  basename: ""
  pathname: ""
  extension: ""
  realPath: "/var/www/virtual/capybara/Projekte/laravel/monica/public"
  aTime: 1970-01-01 01:00:00
  mTime: 1970-01-01 01:00:00
  cTime: 1970-01-01 01:00:00
  inode: false
  size: false
  perms: 00
  owner: false
  group: false
  type: false
  writable: false
  readable: false
  executable: false
  file: false
  dir: false
  link: false
}

**Comment by djaiss** [comment]
Ok.
1. What's the size of the file you want to upload?
1. I've taken a look at the UploadedFile object from Guzzle. It seems that the error (`6`) is either `        UPLOAD_ERR_NO_TMP_DIR` or `UPLOAD_ERR_CANT_WRITE`

**Comment by Reubo** [comment]
1. I've tried with 2 different files, a JPG with 172kb and one with 41kb

2. The DocBlock in Symfonys `UploadedFile.php` says 

`@param int|null    $error        The error constant of the upload (one of PHP's UPLOAD_ERR_XXX constants); null defaults to UPLOAD_ERR_OK`

whichs seems to be

```
UPLOAD_ERR_NO_TMP_DIR
Value: 6; Missing a temporary folder. Introduced in PHP 5.0.3.
```

according to [php.net](http://php.net/manual/en/features.file-upload.errors.php) as you stated.

Checking the location of the temporary folder with
`php -r 'echo sys_get_temp_dir() . "\n";'`
returns (of course) `/tmp`. Permissions `drwxrwxrwt.` as it should be.

Sorry for any headaches :-(
