### ISSUE TITLE
Troubleshooting: Displaying of Avatars

### ISSUE THREAD

**Issue by Khaoz-Topsy** [monicahq/monica#703]
I am hosting Monica in IIS, I finally got the security settings right so that PHP could write the uploaded avatars to disk. When I upload an avatar it writes the image (plus the 110 and 174 resolutions) to Monica\storage\app\public\avatars. From the front end the image was broken with a 404. In one of the other issues I saw this command `php artisan storage:link` I noticed it was talking about a storage folder in public. After copying and pasting the avatars to Monica\public\storage\avatars the images were displayed.

I assume that `php artisan schedule:run` is meant to copy these images to the write folder? I havent seen this command actually do anything yet (other that return "No scheduled commands are ready to run.")

**Comment by djaiss** [comment]
@Khaoz-Topsy this issue https://github.com/monicahq/monica/issues/702 sounds exactly the same actually.

**Comment by djaiss** [comment]
Can you follow those instructions too? https://github.com/monicahq/monica/issues/702#issuecomment-352005354 and report it here?

**Comment by Khaoz-Topsy** [comment]
Thank you for responding 👍 

avatar_file_name = 'avatars/1c1ado7fpd8FFrRXc6FYJLUdRPhimGu1HFOu3gkN.jpeg' 
avatar_location = 'public'

In the .env I have
QUEUE_DRIVER=sync

And my `\storage\app\public\avatars` has 3 images (original, 110 and 174)

When I copy the files to `\public\storage\avatars` then the avatars display

**Comment by djaiss** [comment]
It's as if the path of the file is not found.

1. Can you upload an avatar and right click on the avatar (that doesn't load after upload) to take a look at the URL that you have?
1. Also, what is the value of `APP_URL` in your `.env` file?

**Comment by Khaoz-Topsy** [comment]
Sorry for the delay 😬 
1. <img src="/storage/avatars/4ZDDGhDAKE3ja38hwD97rc0lD71OL8e5mfipkcr8_110.gif" width="87">
2. APP_URL=http://monica.mydomain.com
