### ISSUE TITLE
Journal redesign

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#704]
I think the current version of the journal sucks. It is basically a big text area and it doesn't add value. Frankly I'm a bit ashamed by it. We can do much better.

At its heart, Monica is about logging everything you know about the persons you care about, so you can remember everything - it's not like Evernote (the Note app) in the sense that Monica structures all those data in a much better way than a note app could do.

But a lot of things about your contacts is actually linked to you, as well. For instance, all the activities that you can log, are about you AND the contacts you've done the activity with.

Me, as a person, could also be considered as a contact in Monica, and have a special status, with some features only available to this contact, like how you felt at a certain day.

The journal should be smart enough to display a lot of data in an intelligent manner: a mix of notes, activities, even you how felt at a specific date. An even farther vision would be to provide a lot of reports about all those data, letting you know at which restaurant you go the most, or with whom you go the theater the most on which day, etc...

I would like to ship a first iteration of this new Journal in the next version of Monica. This could look like this:

![image](https://user-images.githubusercontent.com/61099/34052069-ce69cbde-e18e-11e7-9f95-3ea341436c60.png)

It's a work in progress and it's not really MVP, but we'll start with this, and iterate on it.

It's a mix of:
* your activities,
* the journal entries you could have written,
* the notion of how you felt on a certain day.

The only things we don't have at the moment to achieve this vision:
* the concept of "rich activities": special entries like a restaurant or a movie at the theater, could have specific fields associated with this activity.
* the concept of you felt.

I'll start with the "feeling" concept first.

**Comment by fmcpherson** [comment]
What would be cool is if the journal could automatically link to contact records Wiki style. I am thinking of something like VoodooPad in which when you create a page with a title, any subsequent references to that title name are automatically linked. Linking = relationships.

**Comment by djaiss** [comment]
@fmcpherson exactly what I want to achieve next. First step, this :-D

**Comment by djaiss** [comment]
First step is in production and soon in v1.5.
