### ISSUE TITLE
Postdeploy execution timed out when deploying to Heroku

### ISSUE THREAD

**Issue by stralsi** [monicahq/monica#705]
When trying to deploy to heroku all the steps pass successfully until the "Run scripts & scale dynos" step which fails with the error `Postdeploy execution timed out`

Unfortunately that's all I see displayed in the heroku UI. 
Please tell me if you know how I can give you more details or help fix this in any other way.

**Comment by djaiss** [comment]
Sorry you encounter this error. I'm going to check this and see why Heroku's deployment has problems (again).

**Comment by Vici37** [comment]
Also getting `Postdeploy execution timed out` error, also provides the tail of the output:

```fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

 [32mYou are about to setup and configure Monica. Do you wish to continue? (yes/no)[39m [[33mno[39m]:
 >
```

It looks like it's timing out at the terminal setup prompt?

**Comment by djaiss** [comment]
@Vici37 ohhh it's true I haven't tested this with the new way of setting up Monica on Heroku. We should take a look at this and probably do a special command line for Heroku to prevent asking questions during setup.

**Comment by asbiin** [comment]
I have found a workaround to create a default user (admin@admin.com / admin) with setup:production.

But another error is happening:
[heroku.log](https://github.com/monicahq/monica/files/1729637/heroku.log)
This is linked to #781
