### ISSUE TITLE
Exporting data in local install does not work

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#710]
I've created a personal instance of Monica running on a Debian server with Docker. Before I get too committed to using it, I want to be certain that I can export and backup my data. I found the Export data section under settings, but when I try it I get an error saying "Whoops, looks like something went wrong."

If memory serves from the last time I tried Monica, I think this is being caused because the function is intended for getting data out of the hosted version of Monica for import to a personal version. I think export need to work no matter where Monica is installed. 

Ultimately, I am concerned about backing up data at this point. If there is a CLI way I can do this outside of Monica, I am interested.

**Comment by mgolisch** [comment]
maybe set APP_DEBUG=true in the containers environment to see the error messages or poke around in the logfiles it creates inside the container.
The export feature seems to work fine for me on version v1.4.1 of the docker image.

**Comment by fmcpherson** [comment]
Flipped APP_DEBUG=true, clicked the Export and got the error in the screenshot. Suggests a permissions error to me. I
![exportsqlerror](https://user-images.githubusercontent.com/7051925/34121617-ac35516c-e3f7-11e7-93aa-f0d2dd6ae20a.png)

**Comment by fmcpherson** [comment]
Well, I have fiddled with the permissions and have had no luck. If it helps, I am not building my own image, I just pull the image using docker-compose pull and then docker-compose up.

**Comment by fmcpherson** [comment]
I've resolved this by giving other permission to ./persist/storage/app and child directories.

**Comment by mgolisch** [comment]
nice, it worked fine for me as i was using datavolumes instead of the host mounts.
The image should probably correct the permissions on startup.

**Comment by djaiss** [comment]
Sorry you've encountered this error. So far the Docker image is maintained by the community. If someone wants to submit a PR for this, it'd be awesome.
