### ISSUE TITLE
SSL not working, wrong schema detected

### ISSUE THREAD

**Issue by brucealdridge** [monicahq/monica#7120]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Laravel incorrectly assumes scheme to be http

### Steps to reproduce

1. Using cloudflare or traefik to proxy access to monica via SSL
2. Set url in `APP_URL` env var with `https://` scheme
3. Visit monica url
4. See all links as `http://` 
...
<img width="1397" alt="Screenshot 2024-01-15 at 3 33 37 PM" src="https://github.com/monicahq/monica/assets/57298/52fddd84-70b4-4fac-aed9-544fd5d79c58">

![Screenshot 2024-01-15 at 3 32 19 PM](https://github.com/monicahq/monica/assets/57298/12bdf2d0-19a6-478b-846e-4a0f052fc12d)

### Expected behavior

Expect the http/s scheme to be detected correctly, or have an option to define the scheme.

### Environment

Your own self-hosted instance (v5 a.k.a chandler version or main branch)

### Version of Monica

a6bf7814d43292b2b954998d66fb4814268e54ae

### Installation method

Docker image

### Web server

Apache

### Database engine version

SQlite

**Comment by MouettE-SC** [comment]
Did you try to set the variable ASSET_URL in .env with the https link ?

**Comment by MouettE-SC** [comment]
OK setting up APP_TRUSTED_PROXIES=* in .env should fix it (you can drop the ASSET_URL as it should not be needed anymore. Refer to https://laravel.com/docs/10.x/requests#configuring-trusted-proxies for more information

**Comment by brucealdridge** [comment]
That worked great, thank you!
