### ISSUE TITLE
Add Ukrainian language / Додати українську мову

### ISSUE THREAD

**Issue by zvlad** [monicahq/monica#7121]
Will the site be translated into Ukrainian? I can help with the translation if you are interested.

**Comment by GooRoo** [comment]
Hi @zvlad,

There is an older issue #4062 regarding Ukrainian. 

When I joined the translation project on Crowdin in August 2023, about 13% of translated text was available. I corrected some of the previous translations and finished the missing lines, but the result has never been approved by anyone. I wrote to the maintainers on Crowdin, I sent them emails, I tried to reach them here on GitHub—no response, completely ignored 😢 

Later on, some split of versions on Crowdin happenned. You can see the current status here: https://crowdin.com/project/monicahq/uk. Everything that was available before I came, is now visible in the `monica / 4.x` folder, and everything I translated (plus a few contributions after that) is available in `main`.

I also left some instructions to other contributors for Ukrainian here: https://crowdin.com/project/monicahq/discussions/3
