### ISSUE TITLE
Collator class not found - missing ext-intl dependency

### ISSUE THREAD

**Issue by MouettE-SC** [monicahq/monica#7129]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

After following the Setup local development wiki instruction and started the application, creation of the first user failed with "Collator class not found"

### Steps to reproduce

1. Setup empty local development version
2. Attempt to create the first user
3. Application show "Collator class not found"

### Expected behavior

Composer should have complained on dependency setup that ext-intl providing the Collator class was missing.

### Environment

Your own self-hosted instance (v5 a.k.a chandler version or main branch)

### Version of Monica

a6bf781

### Installation method

Manual installation with git

### Web server

artisan serve + yarn dev

### Database engine version

MariaDB

### Additional info

Adding ext-intl as a dependency in composer.json and adding the extension to php fixed the issue. I'm not very familiar with Laravel so maybe it's not the right way to fix this but if you wish I can provide a PR for this small change.

**Comment by DanteB918** [comment]
I've made a PR for this change, as I encountered this as well!

**Comment by djaiss** [comment]
Thanks a lot!
