### ISSUE TITLE
Simplify avatar handling

### ISSUE THREAD

**Issue by BranTurner** [monicahq/monica#715]
I think it's possible to simplify the way Monica handles avatars. Currently:
- There are two fields which handle external avatars: `avatar_external_url` and `gravatar_url`, it's possible that these can be merged.
- There are two fields which have the same function: `has_avatar` and `has_avatar_bool`, one of these can probably be removed. 

Although it's a minor change, it would simplify the database slightly which is never a bad thing!

**Comment by djaiss** [comment]
@BranTurner yes definitely.

`avatar_external_url` was added for the API very quickly so we could build a Chrome extension that would fetch info from Facebook. But the overall handling of avatars is a real mess at the moment.

`has_avatar_bool` can safely be removed. It's a past mistake where I forgot to delete the row after a migration.

**Comment by BranTurner** [comment]
I'm currently working on this and will submit a pull request sometime this weekend! Hopefully we can simplify things a bit.

**Comment by djaiss** [comment]
Super happy to read this. Do you think you could put that in the API as well?

**Comment by BranTurner** [comment]
@djaiss Have done - will finalise and submit a pull request sometime today!

**Comment by djaiss** [comment]
https://laravel-news.com/uploading-avatar-images

**Comment by djaiss** [comment]
I've started to change how avatars are handled. It will completely change how we do things currently and make it much better.

I'll introduce also a new photo uploader and a Photo object in the database.
