### ISSUE TITLE
https://beta.monicahq.com/ returns 500

### ISSUE THREAD

**Issue by sergeifilippov** [monicahq/monica#7157]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Project description link to https://beta.monicahq.com/ returns 500

### Steps to reproduce

1. Go to https://beta.monicahq.com/

### Expected behavior

Load a page with a 200 status code.

### Environment

beta.monicahq.com (v5 a.k.a chandler version or main branch)

### Installation method

None

### Web server

None

### Database engine version

None

**Comment by chris-est** [comment]
duplicate #7148
