### ISSUE TITLE
List of activities

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#716]
At home
* Ate
* Watched a movie
* Just hung out
* Made love
* Played

Outside
* Just hung out and talked
* Hiked
* Practiced sport together
* Went to a bar
* Went to a coffee shop
* Picknicked
* Ate at a restaurant
* Went to the theater
* Went to a concert
* Went to see a play
* Went to the museum

**Comment by damjanuzelac** [comment]
How about adding:
- went to the movies
- took a walk
- played boardgames
- went to a wedding

**Comment by samschooler** [comment]
Why not make this a text box in order to allow custom activities? I have a lot of obscure things I want to put down, but will never be used by anyone else.

**Comment by xJMV** [comment]
Anyway to add new activities ? that could be added in the "settings/personalization" just like genders or contact field types...

**Comment by djaiss** [comment]
You can now customize everything with the activities, starting with 2.5.0.
