### ISSUE TITLE
Leaving (optional) Company blank in Job Information gives error

### ISSUE THREAD

**Issue by SkepticMystic** [monicahq/monica#7162]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

The Company field under Job Information is described as optional. However, when adding only a Job Title and clicking save, it gives the error: "Oops! Something went wrong.  The selected company id is invalid.", and doesn't save

### Steps to reproduce

1. Go to an existing contact with no Job Information
2. Edit their Job Info, only add a Job Title, but no Company
3. Hit save

### Expected behavior

A missing company field should be allowed, as the field is described as optional

### Environment

beta.monicahq.com (v5 a.k.a chandler version or main branch)

### Version of Monica

12a6f08

### Installation method

None

### Web server

None

### Database engine version

None

**Comment by djaiss** [comment]
Fixed in #7299
