### ISSUE TITLE
Where has the API docs repository gone?

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#717]
Previously there was a separate repository for the API docs but now I do not see that repo.
This repo's README does not point to a live docs instance either.

**Comment by djaiss** [comment]
@Phrohdoh indeed, but I never used it actually.
The API is now hosted on the marketing site https://github.com/monicahq/marketing/tree/master/api

**Comment by Phrohdoh** [comment]
For anyone else who comes across this issue [this](https://monicahq.com/api/overview) is the link you want.
