### ISSUE TITLE
Wrong URL in Monica's Web

### ISSUE THREAD

**Issue by carmarbar9** [monicahq/monica#7173]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

When you click on "install it" in Monica's Web, the link takes you to an invalid direction in GitHub.

### Steps to reproduce

1. Open Monica's Web
2. Click on "install it"

### Expected behavior

The link should take you to the installation documents.

### Environment

app.monicahq.com (monica v4)

### Installation method

None

### Web server

None

### Database engine version

None

**Comment by millette** [comment]
This was fixed in the marketing site repo.
