### ISSUE TITLE
PHP noob guide

### ISSUE THREAD

**Issue by carmarbar9** [monicahq/monica#7174]
### How to use GitHub

- Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
- Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
- Subscribe to receive notifications on status change and new comments.

**Is your feature request related to a problem? Please describe.**
My feature request is not a problem at all, but it could be interesting to include a PHP guide for noobs to understand better the code.

**Describe the solution you'd like**
I would like to see included a document for a PHP noob guide.

**Describe alternatives you've considered (optional)**

**Additional context**
Add any other context or screenshots about the feature request here. The more context, the better.

**Comment by slifty** [comment]
I'm not a maintainer of this project, but just wanted to note that resources for learning PHP are already just an internet-search away.  The maintainers of any given project already have their hands full trying to build their own code base, and maintaining resources to train potential contributors is a project in itself that's already covered elsewhere.

**Comment by djaiss** [comment]
Also, https://laracasts.com/ is an amazing (although not free) resources to learn.

I'll close this issue since it's not related to the project itself.
