### ISSUE TITLE
Person exists in app, but isn't found #bug

### ISSUE THREAD

**Issue by damjanuzelac** [monicahq/monica#718]
I've added a person months ago and he shows up in many places in the app - but today after I did a few things _(added a few call logs and deleted an old duplicate entry for the person's spouse)_ whenever I click on the name I get a full page error _"Sorry, the page you are looking for could not be found."_ (on the _app.monicahq.com/people/xxxx_ page)

![image](https://user-images.githubusercontent.com/18301852/35722957-bf0da7b0-07f8-11e8-88ff-2e970f8c9e21.png)

**If the entry got deleted why does it show up in activities, reminders and debts? If it's in the db, why the error?**

**Comment by asbiin** [comment]
I think this is not an error anymore
