### ISSUE TITLE
Error when updating timezone

### ISSUE THREAD

**Issue by pedrosfdcarneiro** [monicahq/monica#719]
When I try to update the timezone in the account settings page in app.monicahq.com, I get the following error: 

> The email has already been taken.

I didn't edit the email field.

**Comment by virtadpt** [comment]
I'm running commit 08c37bbdc4bf39c0c1bdcc527efaf397242687e9 (installed today) and I'm still seeing that bug.  I've had to hand-hack the database to work around it.
