### ISSUE TITLE
Register page has broken link to privacy policy

### ISSUE THREAD

**Issue by rcsheets** [monicahq/monica#72]
The register page links to `/privacy`, which doesn't exist. It should probably link to http://monicahq.com/privacy.html instead, at least for the hosted version of Monica.

**Comment by lukefabish** [comment]
Since _privacy.html_ isn't in the repository, maybe the location of the privacy policy should be an env setting rather than a bare link to `/privacy`.

**Comment by djaiss** [comment]
Thanks a lot for caring. The fix has been pushed and is now in production. Sorry that you had to go through this error.
