### ISSUE TITLE
Twitter Login Provider Still Show on The Login Page

### ISSUE THREAD

**Issue by batinmustu** [monicahq/monica#7221]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Twitter Login Provider Still Show on The Login Page

### Steps to reproduce

Twitter login provider still show on the [login page](https://beta.monicahq.com/login). It was removed with this [PR](https://github.com/monicahq/monica/pull/7099). But still show on the login page.

<img width="912" alt="image" src="https://github.com/monicahq/monica/assets/74476363/dfee8042-1ba0-4791-a8c9-9ff0878a09f8">

### Expected behavior

When I checked, I saw that the providers here come from the ".env" file. This provider can be deleted from the ".env" file or the cache can be cleared if it has been deleted before.

### Environment

beta.monicahq.com (v5 a.k.a chandler version or main branch)

### Installation method

None

### Web server

None

### Database engine version

None

**Comment by asbiin** [comment]
Thank you, I've just removed it from beta.monicahq.com
