### ISSUE TITLE
Header search box contents when clicked on is not copied to search page's text box 

### ISSUE THREAD

**Issue by eoinobrien** [monicahq/monica#7229]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Header search box contents when clicked on is not copied to search page's text box 

### Steps to reproduce

1. In the network tab of a developer tools, change the throttling to "Regular 2G" or a slow speed. This is not required but showcases the issue more.
2. Open a vault
3. Click on the "Search something" bar in the header, and type "Micheal"
4. The page will refresh and the Search page will open, and the large search box on the search bar will be focused
5. The Search page's text box and the header's search box will both be empty. And "Micheal" will no longer show.

![monica-search-box](https://github.com/monicahq/monica/assets/6508687/d7635431-78a5-454a-ae04-7bb7862cc6c7)

### Expected behavior

For the contents of the header search box to appear in the search box on the Search page.

### Environment

beta.monicahq.com (v5 a.k.a chandler version or main branch)

### Version of Monica

Version v5.0.0-beta.3 — commit 2f5225b.

### Installation method

None

### Web server

None

### Database engine version

None

**Comment by DanteB918** [comment]
I've opened up a pull request for this issue. 😄

**Comment by djaiss** [comment]
This is very relevant. Thanks for this issue.
