### ISSUE TITLE
Error: Impossible to create the root directory "/var/www/monica/storage/app/public/imports"

### ISSUE THREAD

**Issue by jstevensen** [monicahq/monica#723]
New install of monicahq on self hosted docker. Added a user, logged in, created a contact successfully. Attempted to import a vcard and was show this error:

Impossible to create the root directory "/var/www/monica/storage/app/public/imports"

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

$ docker --version
Docker version 1.13.1, build 092cba3

I can attach additional debug info if needed.

**Comment by jstevensen** [comment]
I was able to fix this manually by running the following commands

$ docker exec -it monica_monicahq_1 sh
/var/www/monica # chown -R monica:apache /var/www/monica/storage/app/public/
/var/www/monica # chmod -R g+rw /var/www/monica/storage/app/public/

I am now able to upload a vcard file.

**Comment by hexnet** [comment]
This issue is fixed in (da859af) which was merged to master and will be available in the next release (we are currently at 1.4.1).
