### ISSUE TITLE
Can't delete AddressType | Importing Wrong Servcies Class

### ISSUE THREAD

**Issue by timothyoesch** [monicahq/monica#7365]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/monicahq/monica/issues?q=is%3Aopen+is%3Aissue+label%3Abug) _(I've searched it)_.
- [X] I agree to follow Monica's [Code of Conduct](https://github.com/monicahq/monica/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Can't delete AddressType because DestroyPronoun is imported

### Steps to reproduce

1. Open Settings -> Personalize Account -> Address types
2. Create new type
3. Try to delete the type
4. Error: «The pronoun id field is required.»

### Expected behavior

No error, deletion of address type

### Environment

Your own self-hosted instance (v5 a.k.a chandler version or main branch)

### Version of Monica

commit c900b4a

### Installation method

Other

### Web server

Nginx

### Database engine version

MySQL

### Additional info

Error can be fixed by changing lines 8 and 64 in the PersonalizeAddressTypeController:

```php
use App\Domains\Settings\ManageAddressTypes\Services\DestroyAddressType;
```

```php
(new DestroyAddressType())->execute($data);
```

I'd create a pull request myself but I am unsure of your contribution policy.

**Comment by IbrahimHammash1** [comment]
Hello
I'll check the problem
