### ISSUE TITLE
How to import google contact

### ISSUE THREAD

**Issue by weir1** [monicahq/monica#7380]
I used old monica from runtipi & I can easily import my google contacts but I lost & all the data then after research I installed on my own monica full version but it showed as chandler, when i visit chandler repo, it was read only.

Currently I am not seeing how to upload all my google contacts into monica / chandler the version I am using is
Monica. All rights reserved. 2017 — 2024. Made from all over the world. We ❤️ you.
This site is open source. Version 5.0.0-beta.4 — commit [c900b4a](https://github.com/monicahq/monica/commit/c900b4af726c40a907e2d2ca07d0530bfbcf872e).

**Comment by djaiss** [comment]
Currently you have to add contacts manually. We don't mass import contacts.
