### ISSUE TITLE
"Trying to get property of non-object" while vCard Import

### ISSUE THREAD

**Issue by Kovah** [monicahq/monica#739]
I tried to import a vCard with a lot of exports that I previously exported from the macOS Contacts app. Importing fails with the generic "Whoops, something went wrong" error. Looking at the log files I found the following error:
```
production.ERROR: Trying to get property of non-object {"userId":1,"email":"<my-email@here>","exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /var/www/vhosts/kovah.de/sites/pcrm/app/Jobs/AddContactFromVCard.php:129
```
So I inspected the code and found the following line ([Github link](https://github.com/monicahq/monica/blob/master/app/Jobs/AddContactFromVCard.php#L129))
```
$contactField->data = $this->formatValue($vcard->EMAIL);
$contactField->contact_field_type_id = $contactFieldType->id;
$contactField->save();
```
So I assumed that `$contactFieldType` is no object here so I added a dd() and got `null` for `$contactFieldType`.

Investigating the previous line `$contactFieldType = ContactFieldType::where('type', 'email')->first();` and noticed that something is a bit off here. Because the `contact_field_types` table is empty after the initial setup and while adding a custom field type I also can't modify the `type` field.

How is this supposed to work?

**Comment by barttenbrinke** [comment]
I have the same issue.

**Comment by Kovah** [comment]
Fixed the import by adding two Contact field types: `Email` and `Phone`, then edited the database manually and added `phone` and `email` as types respectively.
However, the user should not have to edit the database. At least add a proper check if the fields exist.

**Comment by djaiss** [comment]
Sorry about this and thanks @Kovah for your help in this matter!

**Comment by Kovah** [comment]
Thanks for the merge.
I would leave this issue open as I just added a hotfix to make it work. But I think someone should take a look at it because it seems that some things were changed in the meantime.

Additional hint: couldn't make the tests for this working because of an error in Laravel Dusk.
