### ISSUE TITLE
Feature: Allow addition of birth mm/dd without year

### ISSUE THREAD

**Issue by shockey** [monicahq/monica#75]
I have quite a few friends whose birthdays I know, but ages I do not know.

It'd be nice to be able to save those dates without having to define an age for them!

**Comment by djaiss** [comment]
Interesting use case. This would require some heavy changes though, but I welcome the idea.

**Comment by Nebucatnetzer** [comment]
You could just add the current year to it and threat it as a normal date.
This way the reminders should work and you cust leave the age empty.

However it might be more complex than I think.

**Comment by djaiss** [comment]
This is now in production.
