### ISSUE TITLE
Add a CLA

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#754]
Contribution License Agreements are a way to protect a project from potential lawsuits etc... We should consider adding one in Monica.

**Comment by ocdtrekkie** [comment]
I discussed why this was beneficial significantly in #38 as well.

**Comment by djaiss** [comment]
@ocdtrekkie indeed, I do remember this one. I feel more and more the importance of having a CLA. I just need to figure out the best system to do it.

**Comment by Phrohdoh** [comment]
FWIW I use [cla-assistant](https://cla-assistant.io) for my projects.

**Comment by asbiin** [comment]
It's a good idead.
@djaiss do you need help for this ?

**Comment by djaiss** [comment]
@asbiin a few days ago I created https://gist.github.com/djaiss/4a0f866952bdce1146335fbcd4537fbd

And yes if you want to move forward with this issue, be my guest 😀

**Comment by asbiin** [comment]
@djaiss I've updated the CLA here : https://gist.github.com/asbiin/a19e73d006343e79663770ed52d9f7a4

**Comment by asbiin** [comment]
OK, the CLA is here:
https://gist.github.com/djaiss/509567279c01359fa0f427c2578a1bb6
It's on place with https://cla-assistant.io/ thanks @Phrohdoh
