### ISSUE TITLE
Reminders: ErrorException: Trying to get property 'account' of non-object

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#771]
https://sentry.io/monica-lv/production-app/issues/428141987/

```
ErrorException: Trying to get property 'account' of non-object
  File "app/Console/Commands/SendNotifications.php", line 52, in handleError
    $account = $reminder->contact->account;
  File "app/Console/Commands/SendNotifications.php", line 52, in handle
    $account = $reminder->contact->account;
...
(12 additional frame(s) were not displayed)
```

**Comment by Jipooex** [comment]
I do not know if this related to that bug, but Monica won't send any notifications.

`[2018-01-07 00:00:02] production.ERROR: Trying to get property of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /var/www/virtual/monica/laravelmonica/app/Console/Commands/SendNotifications.php:52)
[stacktrace]
#0 /var/www/virtual/monica/laravelmonica/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/virtua...', 52, Array)
#1 /var/www/virtual/monica/laravelmonica/app/Console/Commands/SendNotifications.php(52): Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/virtua...', 52, Array)
#2 [internal function]: App\\Console\\Commands\\SendNotifications->handle()
#3 /var/www/virtual/monica/laravelmonica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /var/www/virtual/monica/laravelmonica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/virtual/monica/laravelmonica/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /var/www/virtual/monica/laravelmonica/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /var/www/virtual/monica/laravelmonica/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\\Container\\Container->call(Array)
#8 /var/www/virtual/monica/laravelmonica/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /var/www/virtual/monica/laravelmonica/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /var/www/virtual/monica/laravelmonica/vendor/symfony/console/Application.php(936): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /var/www/virtual/monica/laravelmonica/vendor/symfony/console/Application.php(240): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\SendNotifications), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/www/virtual/monica/laravelmonica/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/www/virtual/monica/laravelmonica/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/virtual/monica/laravelmonica/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/virtual/monica/laravelmonica/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"} 
)
`

**Comment by djaiss** [comment]
It probably is. Thanks for this report!
