### ISSUE TITLE
Bunch of files in the repo that shouldn't be there

### ISSUE THREAD

**Issue by simhnna** [monicahq/monica#782]
* [.DS_Store](https://github.com/monicahq/monica/blob/master/.DS_Store)
* [.travis.yml.sig](https://github.com/monicahq/monica/blob/master/.travis.yml.sig)
* [travis-sonar.sh.sig](https://github.com/monicahq/monica/blob/master/travis-sonar.sh.sig)

**Comment by asbiin** [comment]
The .sig files are used to launch the sonar analyser.
I will move them to a .ci directory

The .DS_Store is mac OSx specific, I think we could remove it @djaiss ?

**Comment by djaiss** [comment]
@asbiin @simhnna  ohhh. .DS_Store should definitely not be there. I wonder how I didn't realize it yet.

**Comment by djaiss** [comment]
Your turn @asbiin

**Comment by Phrohdoh** [comment]
*All* `.DS_Store` files should be:
 - ignored (by adding `**/.DS_Store` to the `.gitignore` file), then
 - removed from the index (`git rm --cached **/.DS_Store`)

Then if you really want to clean up you can run `git clean -dfx` (but read the manpage first! and check out `git clean -dfxn` where `-n` is short for `--dry-run`).

**Comment by asbiin** [comment]
The .sig files are mandatory, and must be behind the signed file.
That means the .travis.yml.sig is in the right place.
I could move the travis-sonar.sh, and its .sig file in another directory, but everything regarding CI is in the root directory for now. What subdirectory should we use ?

**Comment by simhnna** [comment]
When i created the issue, I searched for uses for the files and didn't find any. Now I know they are used in the sonarlauncher project.

Why are you doing it this complicated? It looks like you can just call a travis addon with an encrypted token.
https://docs.travis-ci.com/user/sonarcloud/
https://github.com/SonarSource/sq-com_example_standard-sqscanner-travis

**Comment by asbiin** [comment]
Of course, but this is not working with external Pull Requests.

**Comment by djaiss** [comment]
I've cleaned the remaining DS store files.
