### ISSUE TITLE
API settings view assumes user knowledge

### ISSUE THREAD

**Issue by Phrohdoh** [monicahq/monica#794]
3 things regarding `/settings/api`:

1) API access

> The API can...

As a user my immediate thoughts are:

*What* "API"?

Where do I go to read about this *thing*?

Do I need to know what this is as a user? I assume so since it is part of my settings.

2) Personal access tokens

> Make sure you give this token to a source you trust - as they allow you to access all your data.

Ok I need to give this to someone I trust... my SO? Does this allow them to login as me?

Why would I create a PAT?

3) OAuth

> This section lets you register your own OAuth clients.

As before, what is this?

Do typical users need to know?

---

Hopefully you can see the points I am trying to make above.

The API view does not tell the user what anything presented is or whether they even need to care about its existence.

Given that the API and OAuth2 access are developer-oriented my opinion is that they should be moved elsewhere (possibly somewhere like [a marketplace](https://github.com/monicahq/monica/issues/473) where developers can register OAuth2 applications and users can browse available integrations).

---

As a final note please see [this issue request documentation of integrating with Monica via OAuth2](https://github.com/monicahq/marketing/issues/18) because as a developer who has successfully used OAuth2 previously I do not know what to make of the information presented once I have registered a client.

**Comment by asbiin** [comment]
Fixed by #3268
