### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'monica_prod.'monica'instances' doesn't exist (SQL: select * from `'monica'instances` limit 1) when trying to start Docker

### ISSUE THREAD

**Issue by kofiav** [monicahq/monica#795]
I am unable to launch monicahq because of a SQL error (in title). I've also attached a screenshot (below):

![artisan](https://user-images.githubusercontent.com/4621203/34901668-60274fd0-f7db-11e7-81a9-dcd71440005b.png)

Here's the output when I tried to repopulate the database using laravel.  Is there an easy fix for this or should I just give up on MonicaHQ?

/var/www/monica # php artisan migrate:status
+------+-------------------------------------------------------------------+
| Ran? | Migration                                                         |
+------+-------------------------------------------------------------------+
| Y    | 2014_10_12_000000_create_users_table                              |
| Y    | 2014_10_12_100000_create_password_resets_table                    |
| Y    | 2016_06_01_000001_create_oauth_auth_codes_table                   |
| Y    | 2016_06_01_000002_create_oauth_access_tokens_table                |
| Y    | 2016_06_01_000003_create_oauth_refresh_tokens_table               |
| Y    | 2016_06_01_000004_create_oauth_clients_table                      |
| Y    | 2016_06_01_000005_create_oauth_personal_access_clients_table      |
| Y    | 2016_06_07_234741_create_account_table                            |
| Y    | 2016_06_08_003006_add_account_info_table                          |
| Y    | 2016_06_08_005413_create_contacts_table                           |
| Y    | 2016_06_25_224219_create_reminder_type_table                      |
| Y    | 2016_06_28_191025_create_tasks_table                              |
| Y    | 2016_06_30_185050_create_notes_table                              |
| Y    | 2016_07_25_133835_add_width_field                                 |
| Y    | 2016_08_28_122938_create_kids_table                               |
| Y    | 2016_08_28_215159_create_relations_table                          |
| Y    | 2016_09_03_202027_add_reminder_id_to_contacts                     |
| Y    | 2016_09_05_134937_add_last_talked_to_field                        |
| Y    | 2016_09_05_135927_add_people_id_to_contacts                       |
| Y    | 2016_09_05_145111_add_name_info_to_peoples                        |
| Y    | 2016_09_06_213550_create_activity_type_table                      |
| Y    | 2016_09_10_164406_create_jobs_table                               |
| Y    | 2016_09_10_170122_create_notifications_table                      |
| Y    | 2016_09_12_014120_create_failed_jobs_table                        |
| Y    | 2016_09_30_014720_add_kid_to_reminder                             |
| Y    | 2016_10_15_024156_add_deleted_at_to_users                         |
| Y    | 2016_10_19_155139_create_cache_table                              |
| Y    | 2016_10_19_155800_create_sessions_table                           |
| Y    | 2016_10_21_022941_add_statistics_table                            |
| Y    | 2016_10_24_013543_add_journal_setting_to_users                    |
| Y    | 2016_10_24_014257_create_journal_tables                           |
| Y    | 2016_10_28_002518_add_metric_to_settings                          |
| Y    | 2016_11_01_014353_create_activities_table                         |
| Y    | 2016_11_01_015957_add_icon_column                                 |
| Y    | 2016_11_03_150307_add_activity_location_to_activities             |
| Y    | 2016_11_09_013049_add_events_table                                |
| Y    | 2016_12_08_011555_remove_type_from_notes                          |
| Y    | 2016_12_13_133945_add_gifts_table                                 |
| N    | 2016_12_28_150831_change_title_column                             |
| N    | 2017_01_14_200815_add_facebook_columns_to_users_table             |
| N    | 2017_01_15_045025_add_colors_to_users                             |
| N    | 2017_01_22_142645_add_fields_to_contacts                          |
| N    | 2017_01_23_043831_change_people_to_contact_for_kids               |
| N    | 2017_01_26_013524_change_people_to_significantother               |
| N    | 2017_01_26_022852_change_notes_to_contact                         |
| N    | 2017_01_26_034553_add_notes_count_to_contact                      |
| N    | 2017_01_27_024356_change_people_in_events                         |
| N    | 2017_01_28_180156_remove_deleted_at_from_significant_others       |
| N    | 2017_01_28_184901_remove_deleted_at_from_kids                     |
| N    | 2017_01_28_193913_remove_deleted_at_from_notes                    |
| N    | 2017_01_28_222114_remove_viewed_at_from_contacts                  |
| N    | 2017_01_29_175146_remove_delete_at_from_activities                |
| N    | 2017_01_29_175629_add_number_activities_to_contacts               |
| N    | 2017_01_31_025849_add_activity_statistics_table                   |
| N    | 2017_02_04_225618_change_reminders_table                          |
| N    | 2017_02_05_035925_add_gifts_metrics_to_contacts                   |
| N    | 2017_02_05_041740_change_gifts_table                              |
| N    | 2017_02_05_042122_change_people_to_contact_for_gifts              |
| N    | 2017_02_07_041607_change_tasks_table                              |
| N    | 2017_02_07_051355_add_number_tasks_to_contact                     |
| N    | 2017_02_08_002251_change_number_tasks_contact                     |
| N    | 2017_02_08_025358_add_sort_preferences_to_users                   |
| N    | 2017_02_10_195613_remove_notifications_table                      |
| N    | 2017_02_10_214714_remove_people_table                             |
| N    | 2017_02_10_215405_remove_entities_table                           |
| N    | 2017_02_10_215705_remove_deleted_at_from_contact                  |
| N    | 2017_02_10_224355_calculate_statistics                            |
| N    | 2017_02_11_154900_add_avatars_to_contacts                         |
| N    | 2017_02_12_134220_create_entries_table                            |
| N    | 2017_05_03_155254_move_significant_other_data                     |
| N    | 2017_05_04_164723_remove_contact_encryption                       |
| N    | 2017_05_04_185921_add_title_to_activities                         |
| N    | 2017_05_04_193252_alter_activity_nullable                         |
| N    | 2017_05_08_164514_remove_encryption_tasks                         |
| N    | 2017_05_30_002239_remove_predefined_reminders                     |
| N    | 2017_05_30_023116_create_money_table                              |
| N    | 2017_06_07_173437_add_multiple_genders_choices                    |
| N    | 2017_06_10_152945_add_social_networks_to_contacts                 |
| N    | 2017_06_10_155349_create_currencies_data                          |
| N    | 2017_06_11_025227_remove_encryption_journal                       |
| N    | 2017_06_11_110735_change_unique_constraint_for_contacts           |
| N    | 2017_06_13_035059_remove_gifts_encryption                         |
| N    | 2017_06_13_195740_add_company_to_contacts                         |
| N    | 2017_06_14_131803_remove_bern_timezone                            |
| N    | 2017_06_14_132911_add_zar_currency_to_currencies_table            |
| N    | 2017_06_16_215256_add_about_who_to_reminders                      |
| N    | 2017_06_17_010900_fix_contacts_table                              |
| N    | 2017_06_17_153814_refactor_user_table                             |
| N    | 2017_06_19_105842_add_stripe_fields_to_users                      |
| N    | 2017_06_20_121345_add_invitations_statistics                      |
| N    | 2017_06_22_210813_add_name_order_to_users                         |
| N    | 2017_06_27_134704_create_import_table                             |
| N    | 2017_06_29_211725_add_import_job_to_statistics                    |
| N    | 2017_06_29_230523_add_gravatar_url_to_users                       |
| N    | 2017_07_02_155736_create_tags_table                               |
| N    | 2017_07_04_132743_add_tags_to_statistics                          |
| N    | 2017_07_09_164312_update_bad_translation_key                      |
| N    | 2017_07_12_014244_create_calls_table                              |
| N    | 2017_07_17_005012_drop_reminders_count_from_contacts              |
| N    | 2017_07_18_215312_add_danish_kroner_to_currencies_table           |
| N    | 2017_07_18_215758_add_indian_rupee_to_currencies_table            |
| N    | 2017_07_19_094503_add_brazilian_real_to_currencies                |
| N    | 2017_07_22_153209_create_instance_table                           |
| N    | 2017_07_26_220021_change_contacts_table                           |
| N    | 2017_08_02_124102_add_world_currencies                            |
| N    | 2017_08_02_152838_change_string_to_boolean_for_reminders          |
| N    | 2017_08_06_085629_change_events_data                              |
| N    | 2017_08_06_153253_move_kids_to_contacts                           |
| N    | 2017_08_16_041431_add_contact_avatar_location                     |
| N    | 2017_08_21_224835_remove_paid_limitations_for_current_users       |
| N    | 2017_09_10_125918_remove_unusued_counters                         |
| N    | 2017_09_13_095923_add_tracking_table                              |
| N    | 2017_09_13_191714_add_partial_notion                              |
| N    | 2017_10_14_083556_change_gift_column_structure                    |
| N    | 2017_10_17_170803_change_gift_structure                           |
| N    | 2017_10_19_134816_create_activity_contact_table                   |
| N    | 2017_10_19_135215_move_activities_to_pivot_table                  |
| N    | 2017_10_25_102923_remove_contact_id_activities_table              |
| N    | 2017_11_01_122541_add_met_through_to_contacts                     |
| N    | 2017_11_02_202601_add_is_dead_to_contacts                         |
| N    | 2017_11_10_174654_create_contact_fields_table                     |
| N    | 2017_11_10_181043_migrate_contacts_information                    |
| N    | 2017_11_10_202620_move_addresses_from_contact_to_addresses        |
| N    | 2017_11_10_204035_delete_contact_fields_from_contacts             |
| N    | 2017_11_20_115635_change-amount-to-double-on-debts                |
| N    | 2017_11_27_083043_add_more_statistics                             |
| N    | 2017_11_27_134403_add_new_avatar_to_contacts                      |
| N    | 2017_11_27_202857_change_tasks_table_structure                    |
| N    | 2017_12_01_113748_update_notes                                    |
| N    | 2017_12_04_164831_create_ages_table                               |
| N    | 2017_12_04_165421_move_ages_data                                  |
| N    | 2017_12_10_181535_remove_important_dates_table                    |
| N    | 2017_12_10_205328_add_account_id_to_activities                    |
| N    | 2017_12_10_214545_add_last_consulted_at_to_contacts               |
| N    | 2017_12_13_115857_create_day_table                                |
| N    | 2017_12_21_163616_update_journal_entries_with_existing_activities |
| N    | 2017_12_21_170327_add_google2fa_secret_to_users                   |
| N    | 2017_12_24_115641_create_pets_table                               |
| N    | 2017_12_31_114224_add_dashboard_tab_to_users                      |
+------+-------------------------------------------------------------------+

**Comment by djaiss** [comment]
It's super weird to see `'monica'instances'` with no quotes or dots between monica and instances. What values do you have in your .env for the database?

**Comment by kofiav** [comment]
Hi @djaiss, thanks for the quick response. 

My .env file contains the following DB information:

```
# Database information
# To keep this information secure, we urge you to change the default password
DB_CONNECTION=mysql
DB_HOST=monica_mysql_1
DB_PORT=3306
DB_DATABASE=monica_prod
DB_USERNAME=monicahq
DB_PASSWORD=pass
DB_PREFIX=''
DB_TEST_DATABASE=monica_devel
DB_TEST_USERNAME=monicahq
DB_TEST_PASSWORD=pass 
```
My docker-compose looks like this:

```
version: "3.1"
services:
  monicahq:
    build: .
    container_name: monicahq
    image: monicahq/monicahq
    ports:
      - 80:80
    env_file: .env
    volumes:
      - ./persist/storage/app/public:/var/www/monica/storage/app/public

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=monica_prod
      - MYSQL_USER=monicahq
      - MYSQL_PASSWORD=pass
    volumes:
      - ./persist/mysql:/var/lib/mysql

```

Finally I removed .env from the .gitignore file as suggested here (https://github.com/monicahq/monica/issues/596#issuecomment-348773514) as I assumed that was causing a problem as well.

**Comment by kofiav** [comment]
Hi @djaiss,

I got the error to go away. It seems like the migrations do not work when the database name is set to anything but `monica`. Also, I am currently running version `1.0.0 `right now. Even with the database set to `monica` the most up to date version `1.6.0` does not work at all using Docker. 

It seems to me that there's an issue with the default variable settings in the .env file. To get the Docker to work some of them need to be changed while others shouldn't be touched. It can be very confusing. I found this comment extremely valuable when debugging a multitude of issues I was encountering with the env variables (https://github.com/monicahq/monica/issues/596#issuecomment-348773514). 

I'd suggest reviewing it and doing an extensive update to the MonicaHQ Docker Readme.md (https://github.com/monicahq/monica/blob/master/docs/installation/docker.md) so that new users trying to deploy aren't left in the lurch.

**Comment by djaiss** [comment]
@kofiav ouch sorry about that.

That's weird though. We have many, many Docker instances out there and this is the first time we received this feedback. You are right we should fix the readme as well.

**Comment by kofiav** [comment]
@djaiss 

No worries. I'm looking forward to upgrading to version 1.6.0 and beyond once the bug with the migrations has been fixed. 

Even adding a FAQ section addressing some of the common points will help.

**Comment by asbiin** [comment]
This could be linked to issue #826.
Try to set `DB_PREFIX=` or `DB_PREFIX=monica` (whithout quotes)

**Comment by kofiav** [comment]
@asbiin thanks for the note. I will try your suggestion out to see if it will fix my problem.

**Comment by asbiin** [comment]
@kofiav perfect, thank you for the feedback.
