### ISSUE TITLE
Support editing phone call logs

### ISSUE THREAD

**Issue by tomzx** [monicahq/monica#799]
As of 85653415dd6927a18b66a6d4e943c4d647af3b6e, it is not possible to edit a phone call notes once the  call has been logged. The only option is to copy the note, create a new phone call log, paste the note, save the phone call log and then delete the previous phone call log.

I think it's reasonable to think that users may want to edit a phone call log if they think about anything afterward, or if they made any typo mistake while entering their note.

**Comment by lassiter** [comment]
I second this issue, @djaiss. I just created an account for Monica and tried to edit a log and ended up here to create this ticket. I also did exactly @tomzx did before getting here; I don't like doing that. 

I'm not familiar with your stack or codebase, mainly learning/working in a react/rails stacks; however, if you (@djaiss) can provide some direction I'd be willing to take a crack at it on my own time.

**Comment by anmol26s** [comment]
+1

**Comment by djaiss** [comment]
This will be solved by https://github.com/monicahq/monica/pull/1629, coming soon ™️ .

**Comment by djaiss** [comment]
The work has started here: #2134

**Comment by djaiss** [comment]
The feature is done. It'll be merged after the code review.
