### ISSUE TITLE
1.6.0 - Composer install fails

### ISSUE THREAD

**Issue by Kovah** [monicahq/monica#805]
Unfortunately the upgrade to 1.6.0 breaks the app completely, again.
Running `composer install` after pulling all changes leads to the following error:
```
In DuskServiceProvider.php line 43:
It is unsafe to run Dusk in production.
```
I don't know why Dusk is considered to be loaded in a production environment. This makes absolutely no sense.

Are there any tests that are running before a release?

----

**Update**
Removing `"laravel/dusk": "^2.0",` from the composer.json file and then running `composer update --no-dev --prefer-dist` solves the problem.

**Comment by djaiss** [comment]
@Kovah I'm going to remove it because it's not required at all. Sorry about this problem.
