### ISSUE TITLE
 SQLSTATE[42000]: Syntax error or access violation: 1064 on docker start up in rancherOS

### ISSUE THREAD

**Issue by kerbbles** [monicahq/monica#826]
made a fresh host on rancher, connected it to the controller, and then followed instructions via https://github.com/monicahq/monica/blob/master/docs/installation/docker.md
when I run: docker-compose up

mysql seems to load fine, but then monicahq errors as follows

monicahq_1  | Waiting for database to settle
monicahq_1  | docker/test-server.sh
monicahq_1  | Application key [removed] set successfully.
monicahq_1  |
monicahq_1  | In Connection.php line 664:
monicahq_1  |
monicahq_1  |   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
monicahq_1  |   n your SQL syntax; check the manual that corresponds to your MySQL server v
monicahq_1  |   ersion for the right syntax to use near '''reminders CHANGE title title VAR
monicahq_1  |   CHAR(60000) DEFAULT NULL COLLATE utf8_unicode_' at line 1 (SQL: ALTER TABLE
monicahq_1  |    ''reminders CHANGE title title VARCHAR(60000) DEFAULT NULL COLLATE utf8_un
monicahq_1  |   icode_ci)
monicahq_1  |
monicahq_1  |
monicahq_1  | In PDOConnection.php line 79:
monicahq_1  |
monicahq_1  |   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
monicahq_1  |   n your SQL syntax; check the manual that corresponds to your MySQL server v
monicahq_1  |   ersion for the right syntax to use near '''reminders CHANGE title title VAR
monicahq_1  |   CHAR(60000) DEFAULT NULL COLLATE utf8_unicode_' at line 1
monicahq_1  |
monicahq_1  |
monicahq_1  | In PDOConnection.php line 77:
monicahq_1  |
monicahq_1  |   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
monicahq_1  |   n your SQL syntax; check the manual that corresponds to your MySQL server v
monicahq_1  |   ersion for the right syntax to use near '''reminders CHANGE title title VAR
monicahq_1  |   CHAR(60000) DEFAULT NULL COLLATE utf8_unicode_' at line 1
monicahq_1  |
monicahq_1  |
monicahq_1  | The [public/storage] directory has been linked.

when I attempt login to the webui:
Whoops, looks like something went wrong.

have down and uped a few times always same error

**Comment by nathyong** [comment]
Can confirm that something identical is happening when I'm trying to interact with the Docker containers as well. Seems to be related to the migration at https://github.com/monicahq/monica/blob/master/database/migrations/2016_12_28_150831_change_title_column.php

I've experimented with different mysql versions but the issue seems to be happening between version 8 and version 5.7.

**Comment by asbiin** [comment]
Same here.
This is a mysql log when trying to run docker, with an external mysql base.
[mysql.log](https://github.com/monicahq/monica/files/1687110/mysql.log)

See the very first statements:
```
2018-02-01T19:34:32.144104Z	   30 Execute	select * from information_schema.tables where table_schema = 'monicadocker' and table_name = '\'\'migrations'
2018-02-01T19:34:32.147917Z	   30 Execute	create table `''migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(255) not null, `batch` int not null) default character set utf8 collate utf8_unicode_ci
```
=> All table are created whith two single quote preprend.
I'm investigating for this issue. If anyone has an idea ?

**Comment by asbiin** [comment]
Found it !
It because of `DB_PREFIX=''` in .env, for any reason, docker set the variable to "''", and not to an empty string.

**Comment by kerbbles** [comment]
setting DB_PREFIX to <nothing> did work for me!  Thank you!
