### ISSUE TITLE
Help: does someone know how to test a relationship?

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#834]
Like
```
return $this->hasMany(Activity::class);
```

I have problems finding resources about this and I wonder what are the best practices around it.

https://github.com/monicahq/monica/blob/master/app/Account.php#L54

**Comment by erdmenchen** [comment]
What are you missing here? Can you provide more details?

**Comment by turtles2** [comment]
I am just spit balling here but could we generate some some entries for it. Then test to see if the model has them?

**Comment by djaiss** [comment]
In all the models in Laravel, you define the relationships `belongsTo`, `hasMany`, etc… through methods.

The code coverage reports indicates (rightfully) that these methods are not tested.

@erdmenchen I was wondering if we should test those relationships and how we could test them.

I have the feeling we should test them, to make sure that if someone changes a relationship, we can see it immediately. However it’s also very possible that changing a relationship will break a lot of unit tests anyway.

So any advice here would be super helpful.

@turtles2 we probably could but I don't know what are the best practices.

**Comment by turtles2** [comment]
@djaiss How about this package it seems to make it super easy. [laravel-relationship-test](https://github.com/fs-ap/laravel-relationship-test)

**Comment by djaiss** [comment]
@turtles2 just tested it, it doesn't work. The package is a bit old and doesn't seem to have any activity.

**Comment by rydurham** [comment]
One way to test an eloquent relationship might look like this:

```php
$account = factory(Account::class)->create();
$activity = factory(Activity::class, 3)->create(['account_id' => $account->id]);

$this->assertEquals($account->id, $account->activity->first()->id);
$this->assertEquals($activity->pluck('id')->all(), $account->activity->pluck('id)->all());
```

You can also use the [`is()`](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Model.php#L1071) method like so:

```php
$this->assertTrue($account->activity->first()->is($activity->first());
```

Would that be feasible?

There are some better ways to make assertions against collections, but I can't remember them off the top of my head. 

It is also worth thinking about how valuable a test like this really is.   I understand the desire to get full code coverage, but since we know that the Laravel framework itself has tests for the `hasMany` method - would adding a test for that here just be adding a further maintenance burden down the road?   I am not suggesting this is a good or bad thing, just saying that it is worth thinking about.

**Comment by djaiss** [comment]
> It is also worth thinking about how valuable a test like this really is. I understand the desire to get full code coverage, but since we know that the Laravel framework itself has tests for the hasMany method - would adding a test for that here just be adding a further maintenance burden down the road? I am not suggesting this is a good or bad thing, just saying that it is worth thinking about.

I don't want to test if the `hasMany` method is working, but I want to make sure that if someone change a `belongsTo` relationship to `haMany`, there will be an alarm somewhere.

I believe that all the other tests should catch this problem, but would it 100% of the time? This is where I lack experience in unit testing specifically.

For now I've tried

```php
$account = factory(Account::class)->create([]);
$user = factory('App\User')->create(['account_id' => $account->id]);
$this->assertTrue($user->account()->exists());
```

and it seems to work fine. For `hasMany` I can add the notion of `count` so I know that the relationship retrieves a bunch of objects in a collection.
