### ISSUE TITLE
Error when doing a composer update

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#862]
This is because we are pulling from a private repository hosted on Github.

We should move this package to [Packagist](packagist.org), I think.

This affects all the installations that are out there.

```bash
Loading composer repositories with package information
Reading composer.json of pragmarx/google2fa-laravel (v0.1.2)
Could not fetch https://api.github.com/repos/asbiin/google2fa-laravel/contents/composer.json?ref=ebc24520bea1f1ef5659e39d4024a3275ce49a49, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+Bigdoudou.local+2018-01-27+1955
to retrieve a token. It will be stored in "/Users/regis/.composer/auth.json" for future use by Composer.
Token (hidden):
```

**Comment by erdmenchen** [comment]
This is a fork by @asbiin from the real project: pragmarx/google2fa-laravel

It is already availabe on packagist:
composer require pragmarx/google2fa-laravel

**Comment by tomzx** [comment]
This error only has to do with the fact that you fetched a large number of git repositories lately and so github is throttling you, asking you to provide an authentication token to bypass this limitation on your computer.

**Comment by asbiin** [comment]
I've already created a PR to the project: https://github.com/antonioribeiro/google2fa-laravel/pull/18
This is not a real problem : just add then github token as asked and it works.
