### ISSUE TITLE
'You owe' string used everytime

### ISSUE THREAD

**Issue by obstschale** [monicahq/monica#88]
I think I found a bug. I just set up monica and added some debt to a person and it looks like this:

![bildschirmfoto 2017-06-07 um 13 04 05](https://user-images.githubusercontent.com/1058710/26875380-d46a246e-4b81-11e7-8d60-3d15982ffaba.png)

However only one of these three entries is added as "I owe her ..." Take a look at the DB entries:

![bildschirmfoto 2017-06-07 um 13 04 54](https://user-images.githubusercontent.com/1058710/26875405-f2a824a8-4b81-11e7-97b8-a4d6392e329b.png)

I have the feeling there is not separate string for the other case.

**Comment by djaiss** [comment]
@obstschale this https://github.com/monicahq/monica/pull/86 should have fixed the problem. Can you verify and close the issue if that's the case? Thanks!

**Comment by obstschale** [comment]
Yes, #86 fixes the problem. I had only search for issues not for PR 👍
