### ISSUE TITLE
Docker Container Issue

### ISSUE THREAD

**Issue by TacoRocket** [monicahq/monica#886]
Following the instructions on the docker setup leads to an error with Monica not being able to find the mysql container. May not be code but the documentation might need to be fleshed out to help new users install the application. 

Maybe provide an option where Monica uses SQLite for those who want no frills getting up and started? Then provide advanced users the option to connect to an external mysql/mariadb container/server?

**Comment by abizer** [comment]
What error, exactly, are you getting?

**Comment by asbiin** [comment]
Unfortunatly sqlite is not supported yet. See #911.
What is your error ?

I've updated the docs (see #903). Don't hesitate to comment if it's not clear.
