### ISSUE TITLE
Bug with recording dates for activities, calls etc

### ISSUE THREAD

**Issue by vk3il** [monicahq/monica#887]
I've just started using Monica and came across what appears to be a bug. When I record a call or note, the date automatically assigned to it is yesterday, not today. I suspect this may be time zone related as I'm in Melbourne/Australia (UTC+11). Does the code use UTC or some other timezone for recording the date?

Also, it would be useful to be able to edit these dates so that I can record calls in the past.

**Comment by congqiao** [comment]
I have the exactly same issue but I'm at America/New_York, currently UTC-4. As a workaround you can set the date to plus one.

**Comment by scheidm** [comment]
Same timezone as Congquiao and I am also noting this issue.

**Comment by JonahAragon** [comment]
Same issue with America/Chicago.

**Comment by jcgruenhage** [comment]
I have the same problem in Europe/Berlin, very annoying. The things always show up as one day before.

**Comment by asbiin** [comment]
Is your timezone set in /settings url ?
