### ISSUE TITLE
Gravatar support

### ISSUE THREAD

**Issue by danielbachhuber** [monicahq/monica#897]
As a Monica user, it's helpful to see people's faces as a reminder of who they are. However, manually uploading avatar images for each contact can be pretty tedious.

Instead, it would be helpful if Monica supported [Gravatar](https://en.gravatar.com/). If I enter an email address for my contact, then Monica could use the Gravatar image until I upload some override.

Somewhat related #715

**Comment by djaiss** [comment]
@danielbachhuber as a matter of fact it used to support Gravatar.

But, hum, I just noticed I *cough* broke *cough* it a few weeks ago. We should bring it back.

**Comment by grand-lotus-iroh** [comment]
+1 for gravatar support
