### ISSUE TITLE
Add other ways to log communication with a contact

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#917]
Feature request from a user:

We should keep track of non-phone communications.
Right now I just put them under “Phone calls” with a little tag like

EMAIL: talked to him about event

But I’m thinking maybe “Phone Log” can be “Communication” and then you could select from

* Phone Call
* SMS
* Email
* Meeting

**Comment by wearpants** [comment]
+1 - mainly using monica for lightweight tracking of business leads, this would be really helpful

**Comment by lostfocus** [comment]
+1 Yepp!
