### ISSUE TITLE
Bug: Already offered gifts dont show the comment

### ISSUE THREAD

**Issue by erdmenchen** [monicahq/monica#94]
I went back in mind and added some gifts to a person I already offered them.
Since the form does not allow to set when that was (christmas / birthday / ...) I used the comment field.

Sadly there is no way to see the comment later again.

**Comment by Nebucatnetzer** [comment]
@djaiss which kind of help is required here? Do you need someone for validating the bug?

**Comment by djaiss** [comment]
Well it's not a bug per se. It's something that I've forgotten and should be really easy to fix. I'll submit a PR.

**Comment by djaiss** [comment]
This is fix in production.
