### ISSUE TITLE
Add LetsEncrypt SSL Support To Docker Image

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#946]
The Monica Docker image as it currently exists does not appear to support SSL. Recommend adding LetsEncrypt support to the Docker image, you will find several examples of adding SSL to Apache running in a container on Docker Hub.

**Comment by superbilk** [comment]
It's not a fix, but I use https://github.com/SteveLTN/https-portal
So I just have one container for securing all my other containers and don't have to wiggle with many configurations etc

**Comment by fmcpherson** [comment]
Are you using the Automatic Container discovery as described in the https-portal repo? Did you edit the docker-compose.yml that is in the monica repository? I am interested in testing the https-portal container out and thinking about how that works.

**Comment by asbiin** [comment]
Let'encrypt will not be added to the image.
See examples in https://github.com/monicahq/monica/tree/master/scripts/docker/.examples to how use a proxy image to do that.
