### ISSUE TITLE
What's the language zh representative？simplified Chinese？

### ISSUE THREAD

**Issue by bwboy** [monicahq/monica#953]
I found there is a zh folder in lang,and same as en now .Is this folder prepare for simplified Chinese？

**Comment by djaiss** [comment]
@bwboy yes, this stands for simplified chinese.

However if you want to translate, you have to use https://crowdin.com/project/monicahq 😀

**Comment by bwboy** [comment]
Ok，I will try to translate it   😀

**Comment by djaiss** [comment]
@bwboy thank you very much 😀

**Comment by asbiin** [comment]
See #652 also
