### ISSUE TITLE
Call logs hide list bullets

### ISSUE THREAD

**Issue by jonasvp** [monicahq/monica#959]
I'm on the hosted version and usually add markdown bullet lists to my call logs, such as:

    - item1
    - item2

However, the CSS style removes all list styling, so they appear without bullets - which makes the logs hard to read.

**Comment by jonasvp** [comment]
Thanks for the quick merge!

**Comment by djaiss** [comment]
Thanks for your help!

**Comment by jonasvp** [comment]
@djaiss Quick question: I noticed you reverted this change in https://github.com/monicahq/monica/commit/a4e051e61ca56af3e5762ecd35e86fc1fcf1fa85#diff-6376951539a07d7b8f0dedc26aa3473a - was there a reason for that? I'm missing my bullet points again. ;-)
