### ISSUE TITLE
Help: Please define an update guide

### ISSUE THREAD

**Issue by erdmenchen** [monicahq/monica#96]
When cloning the repository and hosting it private, how can I update to the current state / latest version?

Is it save to just checkout the latest commit?

Which version am I currently running on?

**Comment by djaiss** [comment]
Good point. At the moment there are no versioning per se, so it's basically a `git pull origin master` and you are good to go. But I'll update the README to reflect this.

**Comment by erdmenchen** [comment]
Thanks for adding a paragraph about updating a self hosted monica instance.
However the composer update statement should be run after the git pull statement, since new dependencies need to be installed after the git pull...

**Comment by Nebucatnetzer** [comment]
I think this is fixed now. At least the commands seem to be in the correct order.

**Comment by djaiss** [comment]
Yes this is fixed. Thanks a lot!
