### ISSUE TITLE
iCloud contact integration

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#976]
This is a feature request from one of our users.

**Comment by johnriley** [comment]
Should be able to accomplish this and Google Apps/GMail integration via CardDAV. They both use this underlying protocol.

**Comment by asbiin** [comment]
carddav feature already allow this

**Comment by johnriley** [comment]
@asbiin Not sure that's true. Can Monica sync two way with iCloud?

**Comment by asbiin** [comment]
I never tried iCloud, but in that case, maybe this will wait for  #2738
