### ISSUE TITLE
Bug: Wrong validation when you edit a child with less than 1 year old based on birthday

### ISSUE THREAD

**Issue by jaindsonvs** [monicahq/monica#98]
Steps to reproduce:

1. "Add a child" to one contact and use option "I know the exact birthdate of this child, which is", so that the child is less than 1 year old (ex: 05/01/2017).
2. Fill other informations and save.
3. Try to edit this child and hit save (you don't even need to change anything).
4. App will provide an error validation about "This child is probably", even though it is not used: "The value must be greater than 1"

Expected behaviour: No error validation about "This child is probably" field.

**Comment by Nebucatnetzer** [comment]
I can confirm this bug.
It doesn't let you save the form unless you increase the age to something >1.
Even when you select one of the other options.
