### ISSUE TITLE
Order journal by post date not edit date

### ISSUE THREAD

**Issue by johnriley** [monicahq/monica#982]
Currently, journal posts are ordered by edit date. Can it be ordered by post date? As I've put in back dated content on contacts, it has gummed up my journal.

**Comment by djaiss** [comment]
That sounds fair! When I wrote this feature, I hesitated. Looks like you make a good point and we could change that.

**Comment by Nebucatnetzer** [comment]
I agree that this would make a lot of sense.
I've added a few old activities and the appear now all the the top.

**Comment by TheGP** [comment]
Yes, it should has ability to add some posts to the past, in case you forget to add it before

**Comment by pqhf5kd** [comment]
Any update on this?

**Comment by djaiss** [comment]
I think this issue has been done in #1087
