### ISSUE TITLE
Can't finish installing Monica

### ISSUE THREAD

**Issue by xJMV** [monicahq/monica#989]
I'm following the Debian instructions to install Monica on my own debian system (https://github.com/monicahq/monica/wiki/Installing-Monica-on-Debian).

At step 7.7 : when running "php artisan setup:production" I get an error:
```
user@HQ:/var/www/monica$ php artisan setup:production

 You are about to setup and configure Monica. Do you wish to continue? (yes/no) [no]:
 > yes


In Connection.php line 664:

  could not find driver (SQL: select * from information_schema.tables where table_schema = monica and table_name = migrations)


In PDOConnection.php line 47:

  could not find driver


In PDOConnection.php line 43:

  could not find driver


```

I even tried to run "php artisan setup:test" but in both case, the database is not populated. Is there something I do not understand? all step above this one is successful...

**Comment by xJMV** [comment]
Fixed it with: sudo apt-get install php7.1-pdo-mysql
Seems that this package was missing when installed PHP 7.1

**Comment by djaiss** [comment]
Thanks for pointing that error.

@asbiin what do you think? Should we update the instructions?

**Comment by asbiin** [comment]
@djaiss Debian documentation is for php 7.0 which is default version for debian stable (stretch).
debian testing (buster) is currently set with php 7.2, but I didn't tested monica on it.

**Comment by djaiss** [comment]
Due to the lack of activity, I'll close this issue. Feel free to reopen it if you want to continue the discussion.
