### ISSUE TITLE
Tag or group contacts

### ISSUE THREAD

**Issue by supernaut** [monicahq/monica#99]
I'd love a system to tag and simply visualise my contacts to keep track of which circles they are part of. For instance if they are family, if I know them from school, work, a club, etc. This would need to be in the format of tags rather than categories as it needs to support overlap. This could of course cover other data and not just social circle.

**Comment by djaiss** [comment]
I agree that tags are very important for this application. We'll do it.

**Comment by djaiss** [comment]
> This could of course cover other data and not just social circle.

Can you expand?

**Comment by supernaut** [comment]
If tags are called just tags and not something more specific like for examle "Social Circles" they can be used for any kind of tagging. For instance people I like, people with the same taste in music, etc.

**Comment by Piste** [comment]
Agreeing with Supernaut, here: I could tag a bunch of folks with "surf" which would indicate that next time I'm planning an outing I can simply send it to all these folks, i.e. I'd use tags as indication of interest.

**Comment by djaiss** [comment]
We are on the same page.

**Comment by djaiss** [comment]
It's coming, sometimes this week: https://github.com/monicahq/monica/pull/424

**Comment by Piste** [comment]
Incredible iteration velocity. I love this.
