### ISSUE TITLE
Bug when editing contacts - V1.8.1

### ISSUE THREAD

**Issue by xJMV** [monicahq/monica#994]
I recently installed Monica and I notice two bugs when editing contacts.

1. The first name do not appear into the textbox. This requires to re-enter the first name on every edit...
2. When uploading picture, I get the "something went wrong" message. If I get back to the person's page, picture is available...

**Comment by djaiss** [comment]
For 1), we can easily change that.

2 is a bit more problematic. Could you enable `APP_DEBUG=true` and paste the error log you get when uploading a picture?

**Comment by xJMV** [comment]
Here is several scenario tested...

1.  If the filename starts with an underscore ("_"), there will be no changes at all but returns no error.
2. A file of 10mb exactly return an expiration notice. Refreshing the page gets me back to the edit page with an error about the birthday:
`/var/www/monica/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#70Illuminate\Session\TokenMismatchException

            return $this->addCookieToResponse($request, $next($request));
        }

        throw new TokenMismatchException;
    }

    /**
`
3. I just can't recreate the first error... Even with the same contact and same picture... I will keep debuging ON until I can recreate it..

**Comment by asbiin** [comment]
Not enough information right now
